InfiniSQL: /home/infinisql/build/infinisql/infinisqld/Schema.h File Reference
Schema.h File Reference
Schema class. Contains tables (fields (indices)). One schemata per domain. Corresponds to tablespace or database on other RDBMS platforms.
#include "gch.h"
#include "Table.h"
Classes
class Schema
Schema object.
Functions
template<typename T >
void createSchema (T servent)
creates Schema object, in lieu of constructor
Detailed Description
Schema class. Contains tables (fields (indices)). One schemata per domain. Corresponds to tablespace or database on other RDBMS platforms.
Author
Mark Travis mtrav.nosp@m.is15.nosp@m.432+s.nosp@m.rc@g.nosp@m.mail..nosp@m.com
Date
Tue Dec 17 13:46:55 2013
Definition in file Schema.h.
Function Documentation
template<typename T > void createSchema (T servent)
creates Schema object, in lieu of constructor
Parameters
servent
Definition at line 87 of file Schema.h.
References BUILTIN_STATUS_NOTOK, BUILTIN_STATUS_OK, Schema::domainid, MessageUserSchema::userschema_s::domainid, and MessageUserSchema::userschemaStruct.
Referenced by Engine::createschema(), UserSchemaMgr::createschema(), and TransactionAgent::TAcreateschema().
 {
     class MessageUserSchema &msgref =
         *(class MessageUserSchema *)servent->msgrcv;
     if (servent->domainidsToSchemata.count(msgref.userschemaStruct.domainid))
     {
         servent->status = BUILTIN_STATUS_NOTOK;
     }
     else
     {
         class Schema *sptr = new class Schema(msgref.userschemaStruct.domainid);
         servent->domainidsToSchemata[msgref.userschemaStruct.domainid] = sptr;
         servent->status = BUILTIN_STATUS_OK;
     }
 }