InfiniSQL: /home/infinisql/build/infinisql/infinisqld/TopologyMgr.cc File Reference
TopologyMgr.cc File Reference
Actor which receives configuration commands over 0mq and MessagePack from infinisqlmgr.py.
#include "TopologyMgr.h"
Functions
void * userSchemaMgr (void *)
void * listener (void *)
launch Listener actor
void * transactionAgent (void *)
void * engine (void *)
void * deadlockMgr (void *)
launch Engine actor
void * ibGateway (void *)
launch IbGateway actor
void * obGateway (void *)
launch ObGateway actor
void replyToManager (void *, msgpack::sbuffer &)
void * topologyMgr (void *identity)
launch Topology Manager actor
Variables
cfg_s cfgs
Detailed Description
Actor which receives configuration commands over 0mq and MessagePack from infinisqlmgr.py.
Author
Mark Travis mtrav.nosp@m.is15.nosp@m.432+s.nosp@m.rc@g.nosp@m.mail..nosp@m.com
Date
Tue Dec 17 13:58:20 2013
Launches all other actors, updates Topology, and distributes configuration changes to all other actors on each node. Facilitates dynamic reconfiguration.
Definition in file TopologyMgr.cc.
Function Documentation
void* deadlockMgr (void *)
launch Engine actor
Parameters
identity how to identify this
Returns
Definition at line 179 of file DeadlockMgr.cc.
Referenced by TopologyMgr::TopologyMgr().
 {
     new DeadlockMgr((Topology::partitionAddress *)identity);
     while (1)
     {
         sleep(10);
     }
     return NULL;
 }
void* engine (void *)
Definition at line 167 of file Engine.cc.
Referenced by TopologyMgr::TopologyMgr().
 {
     Engine((Topology::partitionAddress *)identity);
     return NULL;
 }
void* ibGateway (void *)
launch IbGateway actor
Parameters
identity how to identify actor instance
Returns
Definition at line 420 of file IbGateway.cc.
References IbGateway::IbGateway().
Referenced by TopologyMgr::TopologyMgr().
 {
     new IbGateway((Topology::partitionAddress *)identity);
     while (1)
     {
         sleep(500000);
     }
     return NULL;
 }
void* listener (void *)
launch Listener actor
Parameters
identity how to identify Listener instance
Returns
Definition at line 201 of file Listener.cc.
Referenced by TopologyMgr::TopologyMgr().
 {
     new Listener((Topology::partitionAddress *)identity);
     while (1)
     {
         sleep(250000);
     }
     return NULL;
 }
void* obGateway (void *)
launch ObGateway actor
Parameters
identity how to identify actor instance
Returns
Definition at line 274 of file ObGateway.cc.
Referenced by TopologyMgr::TopologyMgr().
 {
     new ObGateway((Topology::partitionAddress *)identity);
     while (1)
     {
         sleep(150000);
     }
     return NULL;
 }
void replyToManager (void * zmqsocket, msgpack::sbuffer & sbuf)
Definition at line 609 of file TopologyMgr.cc.
Referenced by TopologyMgr::TopologyMgr().
 {
     zmq_msg_t zmqmsg;
     zmq_msg_init_size(&zmqmsg, sbuf.size());
     memcpy(zmq_msg_data(&zmqmsg), sbuf.data(), sbuf.size());
     zmq_msg_send(&zmqmsg, zmqsocket, 0);
     zmq_msg_close(&zmqmsg);
 }
void* topologyMgr (void * identity)
launch Topology Manager actor
Launcher function for TopologyMgr actor
Definition at line 599 of file TopologyMgr.cc.
Referenced by main().
 {
     new TopologyMgr((Topology::partitionAddress *)identity);
     while (1)
     {
         sleep(1000000);
     }
     return NULL;
 }
void* transactionAgent (void *)
Definition at line 633 of file TransactionAgent.cc.
Referenced by TopologyMgr::TopologyMgr().
 {
     TransactionAgent((Topology::partitionAddress *)identity);
     return NULL;
 }
void* userSchemaMgr (void *)
Definition at line 191 of file UserSchemaMgr.cc.
Referenced by TopologyMgr::TopologyMgr().
 {
     UserSchemaMgr((Topology::partitionAddress *)identity);
     return NULL;
 }
Variable Documentation
cfg_s cfgs
Definition at line 37 of file main.cc.