InfiniSQL: MessageSocket Class Reference
MessageSocket Class Reference
Message variant for communicating socket events.
#include <Message.h>
Classes
struct socket_s
MessageSocket POD (serializable by memcpy) data members.
Public Member Functions
MessageSocket ()
MessageSocket (int socketarg, uint32_t eventsarg, listenertype_e listenertype, int64_t nodeidarg, topic_e topicarg)
Message variant for communicating socket events.
virtual ~MessageSocket ()
size_t size ()
get Message size
string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
size_t size ()
get Message size
std::string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
string * sermsg ()
return serialized Message variant string
void setEnvelope (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
put addresses in Message variant envelope
Public Attributes
socket_s socketStruct
Public Attributes inherited from Message
__int128 nextmsg
message_s messageStruct
Additional Inherited Members
Static Public Member Functions inherited from Message
static class Message * des (string *serstr)
deserialize entire message
Detailed Description
Message variant for communicating socket events.
Returns
Definition at line 166 of file Message.h.
Constructor & Destructor Documentation
MessageSocket::MessageSocket ()
Definition at line 205 of file Message.cc.
 {
 }
MessageSocket::MessageSocket (int socketarg, uint32_t eventsarg, listenertype_e listenertype, int64_t nodeidarg, topic_e topicarg)
Message variant for communicating socket events.
Parameters
socketarg socket discriptor
eventsarg epoll events
listenertype type of listener
nodeidarg nodeid
topicarg topic
Definition at line 209 of file Message.cc.
                                                :
     socketStruct({socketarg, eventsarg, listenertypearg})
MessageSocket::~MessageSocket () virtual
Definition at line 219 of file Message.cc.
 {
 }
Member Function Documentation
void MessageSocket::clear ()
clear contents of this
Definition at line 252 of file Message.cc.
References Message::clear(), and socketStruct.
 {
     Message::clear();
     socketStruct={};
 }
void MessageSocket::package (class SerializedMessage & serobj)
serialize this
Parameters
serobj SerializedMessage
Definition at line 240 of file Message.cc.
References Message::package(), SerializedMessage::ser(), and socketStruct.
Referenced by ser().
 {
     Message::package(serobj);
     serobj.ser(socketStruct);
 }
string * MessageSocket::ser ()
create string with serialized message
Returns
serialized message string
Definition at line 228 of file Message.cc.
References SerializedMessage::data, SerializedMessage::getpayloadtype(), logfile, package(), and SerializedMessage::pos.
 {
     class SerializedMessage serobj(size());
     package(serobj);
     if (serobj.data->size() != serobj.pos)
     {
         fprintf(logfile, "%s %i ser %i size %lu pos %lu\n", __FILE__, __LINE__,
                 serobj.getpayloadtype(), serobj.data->size(), serobj.pos);
     }
     return serobj.data;
 }
size_t MessageSocket::size ()
get Message size
Returns
size in bytes
Definition at line 223 of file Message.cc.
References SerializedMessage::sersize(), Message::size(), and socketStruct.
 {
     return Message::size() + SerializedMessage::sersize(socketStruct);
 }
void MessageSocket::unpack (SerializedMessage & serobj)
deserialize into this
Parameters
serobj SerializedMessage
Definition at line 246 of file Message.cc.
References SerializedMessage::des(), Message::messageStruct, and Message::unpack().
Referenced by Message::des().
 {
     Message::unpack(serobj);
     serobj.des(messageStruct);
 }
Member Data Documentation
socket_s MessageSocket::socketStruct
Definition at line 225 of file Message.h.
Referenced by clear(), Pg::cont(), package(), size(), and TransactionAgent::TransactionAgent().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc