InfiniSQL: MessageCommitRollback Class Reference
MessageCommitRollback Class Reference
Message variant for committing and rolling back transactions.
#include <Message.h>
Public Member Functions
MessageCommitRollback ()
virtual ~MessageCommitRollback ()
size_t size ()
get Message size
string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
Public Member Functions inherited from MessageTransaction
MessageTransaction ()
virtual ~MessageTransaction ()
size_t size ()
get Message size
string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
size_t size ()
get Message size
std::string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
string * sermsg ()
return serialized Message variant string
void setEnvelope (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
put addresses in Message variant envelope
Public Attributes
std::vector< rowOrField_s > rofs
Public Attributes inherited from MessageTransaction
transaction_s transactionStruct
Public Attributes inherited from Message
__int128 nextmsg
message_s messageStruct
Additional Inherited Members
Static Public Member Functions inherited from Message
static class Message * des (string *serstr)
deserialize entire message
Detailed Description
Message variant for committing and rolling back transactions.
Returns
Definition at line 507 of file Message.h.
Constructor & Destructor Documentation
MessageCommitRollback::MessageCommitRollback ()
Definition at line 501 of file Message.cc.
 {
 }
MessageCommitRollback::~MessageCommitRollback () virtual
Definition at line 505 of file Message.cc.
 {
 }
Member Function Documentation
void MessageCommitRollback::clear ()
clear contents of this
Definition at line 539 of file Message.cc.
References MessageTransaction::clear(), and rofs.
 {
     MessageTransaction::clear();
     rofs.clear();
 }
void MessageCommitRollback::package (class SerializedMessage & serobj)
serialize this
Parameters
serobj SerializedMessage
Definition at line 527 of file Message.cc.
References MessageTransaction::package(), rofs, and SerializedMessage::ser().
Referenced by ser().
 {
     MessageTransaction::package(serobj);
     serobj.ser(rofs);
 }
string * MessageCommitRollback::ser ()
create string with serialized message
Returns
serialized message string
Definition at line 515 of file Message.cc.
References SerializedMessage::data, SerializedMessage::getpayloadtype(), logfile, package(), and SerializedMessage::pos.
 {
     class SerializedMessage serobj(size());
     package(serobj);
     if (serobj.data->size() != serobj.pos)
     {
         fprintf(logfile, "%s %i ser %i size %lu pos %lu\n", __FILE__, __LINE__,
                 serobj.getpayloadtype(), serobj.data->size(), serobj.pos);
     }
     return serobj.data;
 }
size_t MessageCommitRollback::size ()
get Message size
Returns
size in bytes
Definition at line 509 of file Message.cc.
References rofs, SerializedMessage::sersize(), and MessageTransaction::size().
 {
     return MessageTransaction::size() +
         SerializedMessage::sersize(rofs);
 }
void MessageCommitRollback::unpack (SerializedMessage & serobj)
deserialize into this
Parameters
serobj SerializedMessage
Definition at line 533 of file Message.cc.
References SerializedMessage::des(), rofs, and MessageTransaction::unpack().
Referenced by Message::des().
 {
     MessageTransaction::unpack(serobj);
     serobj.des(rofs);
 }
Member Data Documentation
std::vector<rowOrField_s> MessageCommitRollback::rofs
Definition at line 543 of file Message.h.
Referenced by Transaction::addRof(), clear(), Transaction::continueReplaceRow(), Transaction::deadlockAbort(), Ast::evaluate(), package(), SubTransaction::processTransactionMessage(), Transaction::revertback(), Transaction::rollback(), size(), and unpack().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc