InfiniSQL: Mboxes Class Reference
Mboxes Class Reference
collection of producers
#include <Mbox.h>
Classes
struct location_s
address and MboxProducer for an actor
Public Member Functions
Mboxes ()
Mboxes (int64_t nodeidarg)
collection of producers
virtual ~Mboxes ()
void update (class Topology &top)
update Topology of producers
void update (class Topology &top, int64_t myActorid)
update Topology of producers
void toActor (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
produce Message for specific actor
void toUserSchemaMgr (const Topology::addressStruct &source, class Message &msg)
produce Message for replica's UserSchemaMgr
void toDeadlockMgr (const Topology::addressStruct &source, class Message &msg)
produce Message for replica's DeadlockMgr
void toPartition (const Topology::addressStruct &source, int64_t partitionid, class Message &msg)
produce Message for Engine associated with specific partition
int64_t toAllOfType (actortypes_e type, const Topology::addressStruct &source, class Message &msg)
int64_t toAllOfTypeThisReplica (actortypes_e type, const Topology::addressStruct &source, class Message &msg)
produce Message destined to all actors of type on current replica
void sendObBatch ()
send batched Message objects destined to remote nodes
Public Attributes
int64_t nodeid
class MboxProducer topologyMgr
class MboxProducer userSchemaMgr
class MboxProducer deadlockMgr
class MboxProducer listener
class MboxProducer obGateway
class MboxProducer ibGateway
std::vector< class MboxProducer > transactionAgents
std::vector< class MboxProducer > engines
std::vector< class MboxProducer * > actoridToProducers
std::vector< class MboxProducer * > transactionAgentPtrs
std::vector< class MboxProducer * > enginePtrs
class MboxProducer * topologyMgrPtr
location_s userSchemaMgrLocation
location_s deadlockMgrLocation
class MboxProducer * listenerPtr
class MboxProducer * obGatewayPtr
std::vector< location_s > partitionToProducers
std::vector< vector< int > > allActors
boost::unordered_map< int16_t,
std::vector< int > > allActorsThisReplica
Detailed Description
collection of producers
This class lets each actor keep track of destinations in a consistent way
Definition at line 139 of file Mbox.h.
Constructor & Destructor Documentation
Mboxes::Mboxes ()
Definition at line 193 of file Mbox.cc.
                : Mboxes(0)
 {
 }
Mboxes::Mboxes (int64_t nodeidarg)
collection of producers
Parameters
nodeidarg nodeid
Definition at line 197 of file Mbox.cc.
References deadlockMgr, ibGateway, listener, MboxProducer::mbox, obGateway, topologyMgr, and userSchemaMgr.
                                 : nodeid(nodeidarg),
                                     topologyMgrPtr(NULL),
                                     userSchemaMgrLocation (),
                                     deadlockMgrLocation (),
                                     listenerPtr(NULL),
                                     obGatewayPtr (NULL)
 {
     topologyMgr.mbox = NULL;
     userSchemaMgr.mbox = NULL;
     deadlockMgr.mbox = NULL;
     listener.mbox = NULL;
     ibGateway.mbox = NULL;
     obGateway.mbox = NULL;
 }
Mboxes::~Mboxes () virtual
Definition at line 212 of file Mbox.cc.
 {
 }
Member Function Documentation
void Mboxes::sendObBatch ()
send batched Message objects destined to remote nodes
Definition at line 551 of file Mbox.cc.
References MboxProducer::obBatchMsg, obGatewayPtr, and MboxProducer::sendMsg().
Referenced by DeadlockMgr::DeadlockMgr(), Engine::Engine(), MboxProducer::sendMsg(), TransactionAgent::TransactionAgent(), and UserSchemaMgr::UserSchemaMgr().
 {
     if (obGatewayPtr != NULL)
     {
         if (obGatewayPtr->obBatchMsg != NULL)
         {
             obGatewayPtr->sendMsg(*obGatewayPtr->obBatchMsg);
             obGatewayPtr->obBatchMsg=NULL;
         }
     }
 }
void Mboxes::toActor (const Topology::addressStruct & source, const Topology::addressStruct & dest, class Message & msg)
produce Message for specific actor
Parameters
source source address
dest destination address
msg Message
Sends message by global actor address
Definition at line 347 of file Mbox.cc.
References Topology::addressStruct::actorid, actoridToProducers, Topology::addressStruct::nodeid, nodeid, obGatewayPtr, MboxProducer::sendMsg(), and Message::setEnvelope().
Referenced by Engine::apply(), Transaction::commit(), DeadlockMgr::deadlock(), TransactionAgent::handledispatch(), IbGateway::inbufhandler(), TransactionAgent::newprocedure(), UserSchemaMgr::operationHandler(), SubTransaction::replyTransaction(), toAllOfType(), toAllOfTypeThisReplica(), toDeadlockMgr(), and toUserSchemaMgr().
 {
     msg.setEnvelope(source, dest, msg);
     if (nodeid==dest.nodeid)
     {
         actoridToProducers[dest.actorid]->sendMsg(msg);
     }
     else
     {
         obGatewayPtr->sendMsg(msg);
     }
 }
int64_t Mboxes::toAllOfType (actortypes_e type, const Topology::addressStruct & source, class Message & msg)
produce Message destined to all actors of type
Parameters
type destination actor type
source source address
msg Message
Returns
Definition at line 389 of file Mbox.cc.
References allActors, Message::messageStruct, PAYLOADCOMMITROLLBACK, PAYLOADDEADLOCK, PAYLOADMESSAGE, PAYLOADSOCKET, PAYLOADSUBTRANSACTION, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, and toActor().
Referenced by TransactionAgent::addcolumn(), TransactionAgent::compile(), TransactionAgent::createtable(), and TransactionAgent::schemaBoilerplate().
 {
     int64_t tally = 0;
     for (int16_t n=1; n < (int16_t)allActors.size(); n++)
     {
         for (int16_t m=FIRSTACTORID; m < (int16_t)allActors[n].size(); m++)
         {
             if (allActors[n][m] == (int)type)
             {
                 switch (msg.messageStruct.payloadtype)
                 {
                 case PAYLOADMESSAGE:
                 {
                     class Message *nmsg = new class Message;
                     *nmsg = *((class Message *)&msg);
                     toActor(source, {n, m}, *nmsg);
                 }
                 break;
                 case PAYLOADSOCKET:
                 {
                     class MessageSocket *nmsg = new class MessageSocket;
                     *nmsg = *((class MessageSocket *)&msg);
                     toActor(source, {n, m}, *nmsg);
                 }
                 break;
                 case PAYLOADUSERSCHEMA:
                 {
                     class MessageUserSchema *nmsg = new class MessageUserSchema;
                     *nmsg = *((class MessageUserSchema *)&msg);
                     toActor(source, {n, m}, *nmsg);
                 }
                 break;
                 case PAYLOADDEADLOCK:
                 {
                     class MessageDeadlock *nmsg = new class MessageDeadlock;
                     *nmsg = *((class MessageDeadlock *)&msg);
                     toActor(source, {n, m}, *nmsg);
                 }
                 break;
                 case PAYLOADSUBTRANSACTION:
                 {
                     class MessageSubtransactionCmd *nmsg =
                         new class MessageSubtransactionCmd;
                     *nmsg = *((class MessageSubtransactionCmd *)&msg);
                     toActor(source, {n, m}, *nmsg);
                 }
                 break;
                 case PAYLOADCOMMITROLLBACK:
                 {
                     class MessageCommitRollback *nmsg =
                         new class MessageCommitRollback;
                     *nmsg = *((class MessageCommitRollback *)&msg);
                     toActor(source, {n, m}, *nmsg);
                 }
                 break;
                 default:
                     printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                            msg.messageStruct.payloadtype);
                 }
                 tally++;
             }
         }
     }
     return tally;
 }
int64_t Mboxes::toAllOfTypeThisReplica (actortypes_e type, const Topology::addressStruct & source, class Message & msg)
produce Message destined to all actors of type on current replica
Parameters
type destination actor type
source source address
msg Mesage
Returns
Definition at line 466 of file Mbox.cc.
References allActors, allActorsThisReplica, Message::messageStruct, PAYLOADCOMMITROLLBACK, PAYLOADDEADLOCK, PAYLOADMESSAGE, PAYLOADSOCKET, PAYLOADSUBTRANSACTION, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, and toActor().
 {
     int64_t tally = 0;
     boost::unordered_map< int16_t, vector<int> >::iterator it;
     for (it = allActorsThisReplica.begin(); it != allActorsThisReplica.end();
          ++it)
     {
         for (int16_t m=FIRSTACTORID; m <
                  (int16_t)allActorsThisReplica[it->first].size(); m++)
         {
             if (allActorsThisReplica[it->first][m] == (int)type)
             {
                 printf("%s %i n m %i %i allActors %i allActorsThisReplica %i\n",
                        __FILE__, __LINE__, it->first, m, allActors[it->first][m],
                        allActorsThisReplica[it->first][m]);
                 switch (msg.messageStruct.payloadtype)
                 {
                 case PAYLOADMESSAGE:
                 {
                     class Message *nmsg = new class Message;
                     *nmsg = *((class Message *)&msg);
                     toActor(source, {it->first, m}, *nmsg);
                 }
                 break;
                 case PAYLOADSOCKET:
                 {
                     class MessageSocket *nmsg = new class MessageSocket;
                     *nmsg = *((class MessageSocket *)&msg);
                     toActor(source, {it->first, m}, *nmsg);
                 }
                 break;
                 case PAYLOADUSERSCHEMA:
                 {
                     class MessageUserSchema *nmsg = new class MessageUserSchema;
                     *nmsg = *((class MessageUserSchema *)&msg);
                     toActor(source, {it->first, m}, *nmsg);
                 }
                 break;
                 case PAYLOADDEADLOCK:
                 {
                     class MessageDeadlock *nmsg = new class MessageDeadlock;
                     *nmsg = *((class MessageDeadlock *)&msg);
                     toActor(source, {it->first, m}, *nmsg);
                 }
                 break;
                 case PAYLOADSUBTRANSACTION:
                 {
                     class MessageSubtransactionCmd *nmsg =
                         new class MessageSubtransactionCmd;
                     *nmsg = *((class MessageSubtransactionCmd *)&msg);
                     toActor(source, {it->first, m}, *nmsg);
                 }
                 break;
                 case PAYLOADCOMMITROLLBACK:
                 {
                     class MessageCommitRollback *nmsg =
                         new class MessageCommitRollback;
                     *nmsg = *((class MessageCommitRollback *)&msg);
                     toActor(source, {it->first, m}, *nmsg);
                 }
                 break;
                 default:
                     printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                            msg.messageStruct.payloadtype);
                 }
                 tally++;
             }
         }
     }
     return tally;
 }
void Mboxes::toDeadlockMgr (const Topology::addressStruct & source, class Message & msg)
produce Message for replica's DeadlockMgr
Parameters
source source address
msg Message
Definition at line 368 of file Mbox.cc.
References Mboxes::location_s::address, deadlockMgrLocation, and toActor().
Referenced by Transaction::abortCmd(), Transaction::checkLock(), and Transaction::checkSqlLock().
 {
     toActor(source, deadlockMgrLocation.address, msg);
 }
void Mboxes::toPartition (const Topology::addressStruct & source, int64_t partitionid, class Message & msg)
produce Message for Engine associated with specific partition
Parameters
source source address
partitionid destination partition
msg Message
Definition at line 374 of file Mbox.cc.
References Mboxes::location_s::address, Mboxes::location_s::destmbox, partitionToProducers, MboxProducer::sendMsg(), and Message::setEnvelope().
Referenced by Transaction::continueCommitTransaction(), TransactionAgent::handledispatch(), Transaction::rollback(), and Transaction::sendTransaction().
 {
     if (partitionid < 0 || (size_t)partitionid > partitionToProducers.size()-1)
     {
         printf("%s %i anomaly %li %lu\n", __FILE__, __LINE__, partitionid,
                (unsigned long)partitionToProducers.size());
         return;
     }
     location_s &destLocation = partitionToProducers[partitionid];
     msg.setEnvelope(source, destLocation.address, msg);
     destLocation.destmbox->sendMsg(msg);
 }
void Mboxes::toUserSchemaMgr (const Topology::addressStruct & source, class Message & msg)
produce Message for replica's UserSchemaMgr
Parameters
source source address
msg Message
Definition at line 362 of file Mbox.cc.
References Mboxes::location_s::address, toActor(), and userSchemaMgrLocation.
Referenced by TransactionAgent::changepassword(), TransactionAgent::createdomain(), TransactionAgent::createuser(), TransactionAgent::deletedomain(), TransactionAgent::deleteuser(), TransactionAgent::login(), and TransactionAgent::schemaBoilerplate().
 {
     toActor(source, userSchemaMgrLocation.address, msg);
 }
void Mboxes::update (class Topology & top)
update Topology of producers
Parameters
top node's authoritative Topology
Updates the set of MboxProducers based on updated Topology. Should be called by an actor after it receives a message from TopologyMgr that a change in nodeTopology has happened. Should be passed a Topology local to the actor.
Definition at line 220 of file Mbox.cc.
Referenced by TopologyMgr::broadcastConfig(), DeadlockMgr::DeadlockMgr(), Engine::Engine(), IbGateway::IbGateway(), Listener::Listener(), ObGateway::ObGateway(), TransactionAgent::TransactionAgent(), and UserSchemaMgr::UserSchemaMgr().
 {
     update(top, 0);
 }
void Mboxes::update (class Topology & top, int64_t myActorid)
update Topology of producers
Parameters
top node's authoritative Topology
myActorid actorid for owning actor
Definition at line 225 of file Mbox.cc.
References Topology::addressStruct::actorid, actoridToProducers, Topology::actorList, Mboxes::location_s::address, Topology::allActors, allActors, Topology::allActorsThisReplica, allActorsThisReplica, deadlockMgrLocation, Topology::deadlockMgrNode, Mboxes::location_s::destmbox, enginePtrs, listenerPtr, Topology::addressStruct::nodeid, Topology::nodeid, nodeTopology, nodeTopologyMutex, Topology::numengines, Topology::numobgateways, Topology::numpartitions, Topology::numtransactionagents, obGatewayPtr, Topology::partitionListThisReplica, partitionToProducers, topologyMgrPtr, transactionAgentPtrs, userSchemaMgrLocation, and Topology::userSchemaMgrNode.
 {
     class Topology *newTop = new class Topology();
     std::swap(*newTop, top);
     delete newTop;
     pthread_mutex_lock(&nodeTopologyMutex);
     top = nodeTopology;
     pthread_mutex_unlock(&nodeTopologyMutex);
     // new, so delete the previous logic when switched over
     // local
     actoridToProducers.resize(top.actorList.size(), NULL);
     transactionAgentPtrs.resize(top.numtransactionagents, NULL);
     enginePtrs.resize(top.numengines, NULL);
     for (size_t n=0; n < top.actorList.size(); n++)
     {
         if (actoridToProducers[n]==NULL)
         {
             if (top.actorList[n].type != ACTOR_NONE)
             {
                 actoridToProducers[n] =
                     new class MboxProducer(top.actorList[n].mbox,top.nodeid);
                 actoridToProducers[n]->mboxes=this;
             }
             switch (top.actorList[n].type)
             {
             case ACTOR_TRANSACTIONAGENT:
                 transactionAgentPtrs[top.actorList[n].instance] =
                     actoridToProducers[n];
                 break;
             case ACTOR_ENGINE:
                 enginePtrs[top.actorList[n].instance] = actoridToProducers[n];
                 break;
             case ACTOR_TOPOLOGYMGR:
                 topologyMgrPtr = actoridToProducers[n];
                 break;
             case ACTOR_LISTENER:
                 listenerPtr = actoridToProducers[n];
                 break;
             case ACTOR_USERSCHEMAMGR:
             {
                 userSchemaMgrLocation.address.nodeid = top.nodeid;
                 userSchemaMgrLocation.address.actorid = n;
                 userSchemaMgrLocation.destmbox = actoridToProducers[n];
             }
             break;
             case ACTOR_DEADLOCKMGR:
             {
                 deadlockMgrLocation.address.nodeid = top.nodeid;
                 deadlockMgrLocation.address.actorid = n;
                 deadlockMgrLocation.destmbox = actoridToProducers[n];
             }
             break;
             case ACTOR_IBGATEWAY:
                 break;
             case ACTOR_OBGATEWAY:
                 if ((int64_t)(myActorid % top.numobgateways) ==
                     top.actorList[n].instance)
                 {
                     obGatewayPtr = actoridToProducers[n];
                 }
                 break;
             case ACTOR_NONE:
                 break;
             default:
                 printf("%s %i unhandled actor type: %i\n", __FILE__, __LINE__,
                        top.actorList[n].type);
             }
         }
     }
     // global
     location_s emptyLocation = {};
     partitionToProducers.resize(top.numpartitions, emptyLocation);
     for (size_t n=0; n < top.partitionListThisReplica.size(); n++)
     {
         if (partitionToProducers[n].address.nodeid==0)
         {
             partitionToProducers[n].address =
                 top.partitionListThisReplica[n].address;
             if (top.nodeid==partitionToProducers[n].address.nodeid)
             {
                 partitionToProducers[n].destmbox =
                     actoridToProducers[partitionToProducers[n].address.actorid];
             }
             else
             {
                 partitionToProducers[n].destmbox = obGatewayPtr;
             }
         }
     }
     vector< vector<int> > aa = top.allActors;
     allActors.swap(aa);
     boost::unordered_map< int16_t, vector<int> > aatr = top.allActorsThisReplica;
     allActorsThisReplica.swap(aatr);
     if (top.userSchemaMgrNode && (top.userSchemaMgrNode != top.nodeid))
     {
         userSchemaMgrLocation.address = {top.userSchemaMgrNode, 3};
     }
     if (top.deadlockMgrNode && (top.deadlockMgrNode != top.nodeid))
     {
         deadlockMgrLocation.address = {top.deadlockMgrNode, 2};
     }
 }
Member Data Documentation
std::vector<class MboxProducer *> Mboxes::actoridToProducers
Definition at line 249 of file Mbox.h.
Referenced by TopologyMgr::broadcastConfig(), toActor(), and update().
std::vector< vector<int> > Mboxes::allActors
Definition at line 260 of file Mbox.h.
Referenced by toAllOfType(), toAllOfTypeThisReplica(), and update().
boost::unordered_map< int16_t, std::vector<int> > Mboxes::allActorsThisReplica
Definition at line 261 of file Mbox.h.
Referenced by toAllOfTypeThisReplica(), and update().
class MboxProducer Mboxes::deadlockMgr
Definition at line 241 of file Mbox.h.
Referenced by Mboxes().
location_s Mboxes::deadlockMgrLocation
Definition at line 254 of file Mbox.h.
Referenced by toDeadlockMgr(), and update().
std::vector<class MboxProducer *> Mboxes::enginePtrs
Definition at line 251 of file Mbox.h.
Referenced by update().
std::vector<class MboxProducer> Mboxes::engines
Definition at line 246 of file Mbox.h.
class MboxProducer Mboxes::ibGateway
Definition at line 244 of file Mbox.h.
Referenced by Mboxes().
class MboxProducer Mboxes::listener
Definition at line 242 of file Mbox.h.
Referenced by Mboxes().
class MboxProducer* Mboxes::listenerPtr
Definition at line 255 of file Mbox.h.
Referenced by update().
int64_t Mboxes::nodeid
Definition at line 237 of file Mbox.h.
Referenced by DeadlockMgr::DeadlockMgr(), Engine::Engine(), IbGateway::IbGateway(), Listener::Listener(), ObGateway::ObGateway(), toActor(), TransactionAgent::TransactionAgent(), and UserSchemaMgr::UserSchemaMgr().
class MboxProducer Mboxes::obGateway
Definition at line 243 of file Mbox.h.
Referenced by Mboxes().
class MboxProducer* Mboxes::obGatewayPtr
Definition at line 256 of file Mbox.h.
Referenced by sendObBatch(), toActor(), and update().
std::vector<location_s> Mboxes::partitionToProducers
Definition at line 258 of file Mbox.h.
Referenced by toPartition(), and update().
class MboxProducer Mboxes::topologyMgr
Definition at line 239 of file Mbox.h.
Referenced by Mboxes().
class MboxProducer* Mboxes::topologyMgrPtr
Definition at line 252 of file Mbox.h.
Referenced by update().
std::vector<class MboxProducer *> Mboxes::transactionAgentPtrs
Definition at line 250 of file Mbox.h.
Referenced by Listener::Listener(), and update().
std::vector<class MboxProducer> Mboxes::transactionAgents
Definition at line 245 of file Mbox.h.
class MboxProducer Mboxes::userSchemaMgr
Definition at line 240 of file Mbox.h.
Referenced by Mboxes().
location_s Mboxes::userSchemaMgrLocation
Definition at line 253 of file Mbox.h.
Referenced by toUserSchemaMgr(), and update().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Mbox.h
/home/infinisql/build/infinisql/infinisqld/Mbox.cc