InfiniSQL: SpookyHash Class Reference
SpookyHash Class Reference
#include <spooky.h>
Public Member Functions
void Init (uint64 seed1, uint64 seed2)
void Update (const void *message, size_t length)
void Final (uint64 *hash1, uint64 *hash2)
Static Public Member Functions
static void Hash128 (const void *message, size_t length, uint64 *hash1, uint64 *hash2)
static uint64 Hash64 (const void *message, size_t length, uint64 seed)
static uint32 Hash32 (const void *message, size_t length, uint32 seed)
static INLINE uint64 Rot64 (uint64 x, int k)
static INLINE void Mix (const uint64 *data, uint64 &s0, uint64 &s1, uint64 &s2, uint64 &s3, uint64 &s4, uint64 &s5, uint64 &s6, uint64 &s7, uint64 &s8, uint64 &s9, uint64 &s10, uint64 &s11)
static INLINE void EndPartial (uint64 &h0, uint64 &h1, uint64 &h2, uint64 &h3, uint64 &h4, uint64 &h5, uint64 &h6, uint64 &h7, uint64 &h8, uint64 &h9, uint64 &h10, uint64 &h11)
static INLINE void End (uint64 &h0, uint64 &h1, uint64 &h2, uint64 &h3, uint64 &h4, uint64 &h5, uint64 &h6, uint64 &h7, uint64 &h8, uint64 &h9, uint64 &h10, uint64 &h11)
static INLINE void ShortMix (uint64 &h0, uint64 &h1, uint64 &h2, uint64 &h3)
static INLINE void ShortEnd (uint64 &h0, uint64 &h1, uint64 &h2, uint64 &h3)
Static Private Member Functions
static void Short (const void *message, size_t length, uint64 *hash1, uint64 *hash2)
Private Attributes
uint64 m_data [2 *sc_numVars]
uint64 m_state [sc_numVars]
size_t m_length
uint8 m_remainder
Static Private Attributes
static const size_t sc_numVars = 12
static const size_t sc_blockSize = sc_numVars*8
static const size_t sc_bufSize = 2*sc_blockSize
static const uint64 sc_const = 0xdeadbeefdeadbeefLL
Detailed Description
Definition at line 57 of file spooky.h.
Member Function Documentation
static INLINE void SpookyHash::End (uint64 & h0, uint64 & h1, uint64 & h2, uint64 & h3, uint64 & h4, uint64 & h5, uint64 & h6, uint64 & h7, uint64 & h8, uint64 & h9, uint64 & h10, uint64 & h11) inline static
Definition at line 270 of file spooky.h.
References EndPartial().
Referenced by Final(), and Hash128().
   {
     EndPartial(h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
     EndPartial(h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
     EndPartial(h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
   }
static INLINE void SpookyHash::EndPartial (uint64 & h0, uint64 & h1, uint64 & h2, uint64 & h3, uint64 & h4, uint64 & h5, uint64 & h6, uint64 & h7, uint64 & h8, uint64 & h9, uint64 & h10, uint64 & h11) inline static
Definition at line 227 of file spooky.h.
References Rot64().
Referenced by End().
   {
     h11+= h1;
     h2 ^= h11;
     h1 = Rot64(h1,44);
     h0 += h2;
     h3 ^= h0;
     h2 = Rot64(h2,15);
     h1 += h3;
     h4 ^= h1;
     h3 = Rot64(h3,34);
     h2 += h4;
     h5 ^= h2;
     h4 = Rot64(h4,21);
     h3 += h5;
     h6 ^= h3;
     h5 = Rot64(h5,38);
     h4 += h6;
     h7 ^= h4;
     h6 = Rot64(h6,33);
     h5 += h7;
     h8 ^= h5;
     h7 = Rot64(h7,10);
     h6 += h8;
     h9 ^= h6;
     h8 = Rot64(h8,13);
     h7 += h9;
     h10^= h7;
     h9 = Rot64(h9,38);
     h8 += h10;
     h11^= h8;
     h10= Rot64(h10,53);
     h9 += h11;
     h0 ^= h9;
     h11= Rot64(h11,42);
     h10+= h0;
     h1 ^= h10;
     h0 = Rot64(h0,54);
   }
void SpookyHash::Final (uint64 * hash1, uint64 * hash2)
Definition at line 331 of file spooky.cc.
References End(), m_data, m_length, m_remainder, m_state, Mix(), sc_blockSize, sc_bufSize, sc_numVars, and Short().
 {
   // init the variables
   if (m_length < sc_bufSize)
   {
     Short(m_data, m_length, hash1, hash2);
     return;
   }
   const uint64 *data = (const uint64 *)m_data;
   uint8 remainder = m_remainder;
   uint64 h0 = m_state[0];
   uint64 h1 = m_state[1];
   uint64 h2 = m_state[2];
   uint64 h3 = m_state[3];
   uint64 h4 = m_state[4];
   uint64 h5 = m_state[5];
   uint64 h6 = m_state[6];
   uint64 h7 = m_state[7];
   uint64 h8 = m_state[8];
   uint64 h9 = m_state[9];
   uint64 h10 = m_state[10];
   uint64 h11 = m_state[11];
   if (remainder >= sc_blockSize)
   {
     // m_data can contain two blocks; handle any whole first block
     Mix(data, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
     data += sc_numVars;
     remainder -= sc_blockSize;
   }
   // mix in the last partial block, and the length mod sc_blockSize
   memset(&((uint8 *)data)[remainder], 0, (sc_blockSize-remainder));
   ((uint8 *)data)[sc_blockSize-1] = remainder;
   Mix(data, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
   // do some final mixing
   End(h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
   *hash1 = h0;
   *hash2 = h1;
 }
void SpookyHash::Hash128 (const void * message, size_t length, uint64 * hash1, uint64 * hash2) static
Definition at line 150 of file spooky.cc.
References ALLOW_UNALIGNED_READS, End(), Mix(), sc_blockSize, sc_bufSize, sc_const, sc_numVars, and Short().
Referenced by Hash32(), and Hash64().
 {
   if (length < sc_bufSize)
   {
     Short(message, length, hash1, hash2);
     return;
   }
   uint64 h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11;
   uint64 buf[sc_numVars];
   uint64 *end;
   union
   {
     const uint8 *p8;
     uint64 *p64;
     size_t i;
   } u;
   size_t remainder;
   h0=h3=h6=h9  = *hash1;
   h1=h4=h7=h10 = *hash2;
   h2=h5=h8=h11 = sc_const;
   u.p8 = (const uint8 *)message;
   end = u.p64 + (length/sc_blockSize)*sc_numVars;
   // handle all whole sc_blockSize blocks of bytes
   if (ALLOW_UNALIGNED_READS || ((u.i & 0x7) == 0))
   {
     while (u.p64 < end)
     {
       Mix(u.p64, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
       u.p64 += sc_numVars;
     }
   }
   else
   {
     while (u.p64 < end)
     {
       memcpy(buf, u.p64, sc_blockSize);
       Mix(buf, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
       u.p64 += sc_numVars;
     }
   }
   // handle the last partial block of sc_blockSize bytes
   remainder = (length - ((const uint8 *)end-(const uint8 *)message));
   memcpy(buf, end, remainder);
   memset(((uint8 *)buf)+remainder, 0, sc_blockSize-remainder);
   ((uint8 *)buf)[sc_blockSize-1] = remainder;
   Mix(buf, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
   // do some final mixing
   End(h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
   *hash1 = h0;
   *hash2 = h1;
 }
static uint32 SpookyHash::Hash32 (const void * message, size_t length, uint32 seed) inline static
Definition at line 85 of file spooky.h.
References Hash128().
   {
     uint64 hash1 = seed, hash2 = seed;
     Hash128(message, length, &hash1, &hash2);
     return (uint32)hash1;
   }
static uint64 SpookyHash::Hash64 (const void * message, size_t length, uint64 seed) inline static
Definition at line 72 of file spooky.h.
References Hash128().
Referenced by Transaction::getengine(), Transaction::getEngineid(), and getPartitionid().
   {
     uint64 hash1 = seed;
     Hash128(message, length, &hash1, &seed);
     return hash1;
   }
void SpookyHash::Init (uint64 seed1, uint64 seed2)
Definition at line 215 of file spooky.cc.
References m_length, m_remainder, and m_state.
 {
   m_length = 0;
   m_remainder = 0;
   m_state[0] = seed1;
   m_state[1] = seed2;
 }
static INLINE void SpookyHash::Mix (const uint64 * data, uint64 & s0, uint64 & s1, uint64 & s2, uint64 & s3, uint64 & s4, uint64 & s5, uint64 & s6, uint64 & s7, uint64 & s8, uint64 & s9, uint64 & s10, uint64 & s11) inline static
Definition at line 143 of file spooky.h.
References Rot64().
Referenced by Final(), Hash128(), and Update().
   {
     s0 += data[0];
     s2 ^= s10;
     s11 ^= s0;
     s0 = Rot64(s0,11);
     s11 += s1;
     s1 += data[1];
     s3 ^= s11;
     s0 ^= s1;
     s1 = Rot64(s1,32);
     s0 += s2;
     s2 += data[2];
     s4 ^= s0;
     s1 ^= s2;
     s2 = Rot64(s2,43);
     s1 += s3;
     s3 += data[3];
     s5 ^= s1;
     s2 ^= s3;
     s3 = Rot64(s3,31);
     s2 += s4;
     s4 += data[4];
     s6 ^= s2;
     s3 ^= s4;
     s4 = Rot64(s4,17);
     s3 += s5;
     s5 += data[5];
     s7 ^= s3;
     s4 ^= s5;
     s5 = Rot64(s5,28);
     s4 += s6;
     s6 += data[6];
     s8 ^= s4;
     s5 ^= s6;
     s6 = Rot64(s6,39);
     s5 += s7;
     s7 += data[7];
     s9 ^= s5;
     s6 ^= s7;
     s7 = Rot64(s7,57);
     s6 += s8;
     s8 += data[8];
     s10 ^= s6;
     s7 ^= s8;
     s8 = Rot64(s8,55);
     s7 += s9;
     s9 += data[9];
     s11 ^= s7;
     s8 ^= s9;
     s9 = Rot64(s9,54);
     s8 += s10;
     s10 += data[10];
     s0 ^= s8;
     s9 ^= s10;
     s10 = Rot64(s10,22);
     s9 += s11;
     s11 += data[11];
     s1 ^= s9;
     s10 ^= s11;
     s11 = Rot64(s11,46);
     s10 += s0;
   }
static INLINE uint64 SpookyHash::Rot64 (uint64 x, int k) inline static
Definition at line 125 of file spooky.h.
Referenced by EndPartial(), Mix(), ShortEnd(), and ShortMix().
   {
     return (x << k) | (x >> (64 - k));
   }
void SpookyHash::Short (const void * message, size_t length, uint64 * hash1, uint64 * hash2) static private
Definition at line 27 of file spooky.cc.
References ALLOW_UNALIGNED_READS, sc_const, sc_numVars, ShortEnd(), and ShortMix().
Referenced by Final(), and Hash128().
 {
   uint64 buf[2*sc_numVars];
   union
   {
     const uint8 *p8;
     uint32 *p32;
     uint64 *p64;
     size_t i;
   } u;
   u.p8 = (const uint8 *)message;
   if (!ALLOW_UNALIGNED_READS && (u.i & 0x7))
   {
     memcpy(buf, message, length);
     u.p64 = buf;
   }
   size_t remainder = length%32;
   uint64 a=*hash1;
   uint64 b=*hash2;
   uint64 c=sc_const;
   uint64 d=sc_const;
   if (length > 15)
   {
     const uint64 *end = u.p64 + (length/32)*4;
     // handle all complete sets of 32 bytes
     for (; u.p64 < end; u.p64 += 4)
     {
       c += u.p64[0];
       d += u.p64[1];
       ShortMix(a,b,c,d);
       a += u.p64[2];
       b += u.p64[3];
     }
     //Handle the case of 16+ remaining bytes.
     if (remainder >= 16)
     {
       c += u.p64[0];
       d += u.p64[1];
       ShortMix(a,b,c,d);
       u.p64 += 2;
       remainder -= 16;
     }
   }
   // Handle the last 0..15 bytes, and its length
   d = ((uint64)length) << 56;
   switch (remainder)
   {
     case 15:
       d += ((uint64)u.p8[14]) << 48;
     case 14:
       d += ((uint64)u.p8[13]) << 40;
     case 13:
       d += ((uint64)u.p8[12]) << 32;
     case 12:
       d += u.p32[2];
       c += u.p64[0];
       break;
     case 11:
       d += ((uint64)u.p8[10]) << 16;
     case 10:
       d += ((uint64)u.p8[9]) << 8;
     case 9:
       d += (uint64)u.p8[8];
     case 8:
       c += u.p64[0];
       break;
     case 7:
       c += ((uint64)u.p8[6]) << 48;
     case 6:
       c += ((uint64)u.p8[5]) << 40;
     case 5:
       c += ((uint64)u.p8[4]) << 32;
     case 4:
       c += u.p32[0];
       break;
     case 3:
       c += ((uint64)u.p8[2]) << 16;
     case 2:
       c += ((uint64)u.p8[1]) << 8;
     case 1:
       c += (uint64)u.p8[0];
       break;
     case 0:
       c += sc_const;
       d += sc_const;
   }
   ShortEnd(a,b,c,d);
   *hash1 = a;
   *hash2 = b;
 }
static INLINE void SpookyHash::ShortEnd (uint64 & h0, uint64 & h1, uint64 & h2, uint64 & h3) inline static
Definition at line 347 of file spooky.h.
References Rot64().
Referenced by Short().
   {
     h3 ^= h2;
     h2 = Rot64(h2,15);
     h3 += h2;
     h0 ^= h3;
     h3 = Rot64(h3,52);
     h0 += h3;
     h1 ^= h0;
     h0 = Rot64(h0,26);
     h1 += h0;
     h2 ^= h1;
     h1 = Rot64(h1,51);
     h2 += h1;
     h3 ^= h2;
     h2 = Rot64(h2,28);
     h3 += h2;
     h0 ^= h3;
     h3 = Rot64(h3,9);
     h0 += h3;
     h1 ^= h0;
     h0 = Rot64(h0,47);
     h1 += h0;
     h2 ^= h1;
     h1 = Rot64(h1,54);
     h2 += h1;
     h3 ^= h2;
     h2 = Rot64(h2,32);
     h3 += h2;
     h0 ^= h3;
     h3 = Rot64(h3,25);
     h0 += h3;
     h1 ^= h0;
     h0 = Rot64(h0,63);
     h1 += h0;
   }
static INLINE void SpookyHash::ShortMix (uint64 & h0, uint64 & h1, uint64 & h2, uint64 & h3) inline static
Definition at line 295 of file spooky.h.
References Rot64().
Referenced by Short().
   {
     h2 = Rot64(h2,50);
     h2 += h3;
     h0 ^= h2;
     h3 = Rot64(h3,52);
     h3 += h0;
     h1 ^= h3;
     h0 = Rot64(h0,30);
     h0 += h1;
     h2 ^= h0;
     h1 = Rot64(h1,41);
     h1 += h2;
     h3 ^= h1;
     h2 = Rot64(h2,54);
     h2 += h3;
     h0 ^= h2;
     h3 = Rot64(h3,48);
     h3 += h0;
     h1 ^= h3;
     h0 = Rot64(h0,38);
     h0 += h1;
     h2 ^= h0;
     h1 = Rot64(h1,37);
     h1 += h2;
     h3 ^= h1;
     h2 = Rot64(h2,62);
     h2 += h3;
     h0 ^= h2;
     h3 = Rot64(h3,34);
     h3 += h0;
     h1 ^= h3;
     h0 = Rot64(h0,5);
     h0 += h1;
     h2 ^= h0;
     h1 = Rot64(h1,36);
     h1 += h2;
     h3 ^= h1;
   }
void SpookyHash::Update (const void * message, size_t length)
Definition at line 225 of file spooky.cc.
References ALLOW_UNALIGNED_READS, m_data, m_length, m_remainder, m_state, Mix(), sc_blockSize, sc_bufSize, sc_const, and sc_numVars.
 {
   uint64 h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11;
   size_t newLength = length + m_remainder;
   uint8  remainder;
   union
   {
     const uint8 *p8;
     uint64 *p64;
     size_t i;
   } u;
   const uint64 *end;
   // Is this message fragment too short?  If it is, stuff it away.
   if (newLength < sc_bufSize)
   {
     memcpy(&((uint8 *)m_data)[m_remainder], message, length);
     m_length = length + m_length;
     m_remainder = (uint8)newLength;
     return;
   }
   // init the variables
   if (m_length < sc_bufSize)
   {
     h0=h3=h6=h9  = m_state[0];
     h1=h4=h7=h10 = m_state[1];
     h2=h5=h8=h11 = sc_const;
   }
   else
   {
     h0 = m_state[0];
     h1 = m_state[1];
     h2 = m_state[2];
     h3 = m_state[3];
     h4 = m_state[4];
     h5 = m_state[5];
     h6 = m_state[6];
     h7 = m_state[7];
     h8 = m_state[8];
     h9 = m_state[9];
     h10 = m_state[10];
     h11 = m_state[11];
   }
   m_length = length + m_length;
   // if we've got anything stuffed away, use it now
   if (m_remainder)
   {
     uint8 prefix = sc_bufSize-m_remainder;
     memcpy(&(((uint8 *)m_data)[m_remainder]), message, prefix);
     u.p64 = m_data;
     Mix(u.p64, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
     Mix(&u.p64[sc_numVars], h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
     u.p8 = ((const uint8 *)message) + prefix;
     length -= prefix;
   }
   else
   {
     u.p8 = (const uint8 *)message;
   }
   // handle all whole blocks of sc_blockSize bytes
   end = u.p64 + (length/sc_blockSize)*sc_numVars;
   remainder = (uint8)(length-((const uint8 *)end-u.p8));
   if (ALLOW_UNALIGNED_READS || (u.i & 0x7) == 0)
   {
     while (u.p64 < end)
     {
       Mix(u.p64, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
       u.p64 += sc_numVars;
     }
   }
   else
   {
     while (u.p64 < end)
     {
       memcpy(m_data, u.p8, sc_blockSize);
       Mix(m_data, h0,h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
       u.p64 += sc_numVars;
     }
   }
   // stuff away the last few bytes
   m_remainder = remainder;
   memcpy(m_data, end, remainder);
   // stuff away the variables
   m_state[0] = h0;
   m_state[1] = h1;
   m_state[2] = h2;
   m_state[3] = h3;
   m_state[4] = h4;
   m_state[5] = h5;
   m_state[6] = h6;
   m_state[7] = h7;
   m_state[8] = h8;
   m_state[9] = h9;
   m_state[10] = h10;
   m_state[11] = h11;
 }
Member Data Documentation
uint64 SpookyHash::m_data[2 *sc_numVars] private
Definition at line 416 of file spooky.h.
Referenced by Final(), and Update().
size_t SpookyHash::m_length private
Definition at line 418 of file spooky.h.
Referenced by Final(), Init(), and Update().
uint8 SpookyHash::m_remainder private
Definition at line 419 of file spooky.h.
Referenced by Final(), Init(), and Update().
uint64 SpookyHash::m_state[sc_numVars] private
Definition at line 417 of file spooky.h.
Referenced by Final(), Init(), and Update().
const size_t SpookyHash::sc_blockSize = sc_numVars*8 static private
Definition at line 402 of file spooky.h.
Referenced by Final(), Hash128(), and Update().
const size_t SpookyHash::sc_bufSize = 2*sc_blockSize static private
Definition at line 405 of file spooky.h.
Referenced by Final(), Hash128(), and Update().
const uint64 SpookyHash::sc_const = 0xdeadbeefdeadbeefLL static private
Definition at line 414 of file spooky.h.
Referenced by Hash128(), Short(), and Update().
const size_t SpookyHash::sc_numVars = 12 static private
Definition at line 399 of file spooky.h.
Referenced by Final(), Hash128(), Short(), and Update().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/spooky.h
/home/infinisql/build/infinisql/infinisqld/spooky.cc