InfiniSQL: SerializedMessage Class Reference
SerializedMessage Class Reference
object carrying a serialized Message variant
#include <Message.h>
Public Member Functions
SerializedMessage (size_t sizearg)
SerializedMessage (string *dataarg)
object carrying a serialized Message variant
virtual ~SerializedMessage ()
payloadtype_e getpayloadtype ()
void ser (size_t s, void *dataptr)
void des (size_t s, void *dataptr)
void ser (int64_t d)
void des (int64_t *d)
void ser (int32_t d)
void des (int32_t *d)
void ser (int16_t d)
void des (int16_t *d)
void ser (int8_t d)
void des (int8_t *d)
void ser (const string &d)
void des (string &d)
void ser (vector< int64_t > &d)
void des (vector< int64_t > &d)
void ser (boost::unordered_map< int64_t, int64_t > &d)
void des (boost::unordered_map< int64_t, int64_t > &d)
void ser (Message::message_s &d)
void des (Message::message_s &d)
void ser (MessageSocket::socket_s &d)
void des (MessageSocket::socket_s &d)
void ser (MessageUserSchema::userschema_s &d)
void des (MessageUserSchema::userschema_s &d)
void ser (procedures_s &d)
void des (procedures_s &d)
void ser (MessageDeadlock::deadlock_s &d)
void des (MessageDeadlock::deadlock_s &d)
void ser (MessageTransaction::transaction_s &d)
void des (MessageTransaction::transaction_s &d)
void ser (MessageSubtransactionCmd::subtransaction_s &d)
void des (MessageSubtransactionCmd::subtransaction_s &d)
void ser (nonLockingIndexEntry_s &d)
void des (nonLockingIndexEntry_s &d)
void ser (MessageDispatch::dispatch_s &d)
void des (MessageDispatch::dispatch_s &d)
void ser (MessageAckDispatch::ackdispatch_s &d)
void des (MessageAckDispatch::ackdispatch_s &d)
void ser (MessageApply::apply_s &d)
void des (MessageApply::apply_s &d)
void ser (MessageAckApply::ackapply_s &d)
void des (MessageAckApply::ackapply_s &d)
void ser (boost::unordered_set< string > &d)
void des (boost::unordered_set< string > &d)
void ser (fieldValue_s &d)
void des (fieldValue_s &d)
void ser (returnRow_s &d)
void des (returnRow_s &d)
void ser (MessageDispatch::record_s &d)
void des (MessageDispatch::record_s &d)
void ser (vector< nonLockingIndexEntry_s > &d)
void des (vector< nonLockingIndexEntry_s > &d)
void ser (newDeadLockLists_s &d)
void des (newDeadLockLists_s &d)
void ser (vector< fieldValue_s > &d)
void des (vector< fieldValue_s > &d)
void ser (vector< returnRow_s > &d)
void des (vector< returnRow_s > &d)
void ser (vector< MessageDispatch::record_s > &d)
void des (vector< MessageDispatch::record_s > &d)
void ser (rowOrField_s &d)
void des (rowOrField_s &d)
void ser (MessageApply::applyindex_s &d)
void des (MessageApply::applyindex_s &d)
void ser (searchParams_s &d)
void des (searchParams_s &d)
void ser (vector< rowOrField_s > &d)
void des (vector< rowOrField_s > &d)
void ser (vector< MessageApply::applyindex_s > &d)
void des (vector< MessageApply::applyindex_s > &d)
void ser (boost::unordered_map< int64_t, vector< MessageDispatch::record_s > > &d)
void des (boost::unordered_map< int64_t, vector< MessageDispatch::record_s > > &d)
Static Public Member Functions
static size_t sersize (int64_t d)
static size_t sersize (int32_t d)
static size_t sersize (int16_t d)
static size_t sersize (int8_t d)
static size_t sersize (const string &d)
static size_t sersize (vector< int64_t > &d)
static size_t sersize (boost::unordered_map< int64_t, int64_t > &d)
static size_t sersize (Message::message_s &d)
static size_t sersize (MessageSocket::socket_s &d)
static size_t sersize (MessageUserSchema::userschema_s &d)
static size_t sersize (procedures_s &d)
static size_t sersize (MessageDeadlock::deadlock_s &d)
static size_t sersize (MessageTransaction::transaction_s &d)
static size_t sersize (MessageSubtransactionCmd::subtransaction_s &d)
static size_t sersize (nonLockingIndexEntry_s &d)
static size_t sersize (MessageDispatch::dispatch_s &d)
static size_t sersize (MessageAckDispatch::ackdispatch_s &d)
static size_t sersize (MessageApply::apply_s &d)
static size_t sersize (MessageAckApply::ackapply_s &d)
static size_t sersize (boost::unordered_set< string > &d)
static size_t sersize (fieldValue_s &d)
static size_t sersize (returnRow_s &d)
static size_t sersize (MessageDispatch::record_s &d)
static size_t sersize (vector< nonLockingIndexEntry_s > &d)
static size_t sersize (newDeadLockLists_s &d)
static size_t sersize (vector< fieldValue_s > &d)
static size_t sersize (vector< returnRow_s > &d)
static size_t sersize (vector< MessageDispatch::record_s > &d)
static size_t sersize (rowOrField_s &d)
static size_t sersize (MessageApply::applyindex_s &d)
static size_t sersize (searchParams_s &d)
static size_t sersize (vector< rowOrField_s > &d)
static size_t sersize (vector< MessageApply::applyindex_s > &d)
static size_t sersize (boost::unordered_map< int64_t, vector< MessageDispatch::record_s > > &d)
Public Attributes
size_t size
size_t pos
std::string * data
Detailed Description
object carrying a serialized Message variant
1) sender to obgw: SerializedMessage on stack 2) copy pointer SerializedMessage.data to new MessageSerialized.data 3) send MessageSerialized to obgw 4) obgw takes MessageSerialized.data in boost_unordered::map< int64_t, vector<string *> > for sending to remote node 5) obgw copies string *'s, deletes them, sends to remote node 6) ibgw creates new MessageSerialized for each string * gets destAddr, etc by reading 1st sizeof(Message::message_s) 7) destination copies MessageSerialized.data ptr to SerializedMessage.data 8) destination deserializes into original Message* 9) destination deletes SerializedMessage.data
source actor is the sender of this
Parameters
sizearg size of serialized message
Returns
Definition at line 869 of file Message.h.
Constructor & Destructor Documentation
SerializedMessage::SerializedMessage (size_t sizearg)
Definition at line 786 of file Message.cc.
References data, and size.
                                                    : size(sizearg), pos(0)
 {
     data=new string(size, char(0));
 }
SerializedMessage::SerializedMessage (string * dataarg)
object carrying a serialized Message variant
IbGateway is the sender
Parameters
dataarg serialized message to populate with
Definition at line 791 of file Message.cc.
References data, and size.
                                                     : pos(0), data(dataarg)
 {
     size=data->size();
 }
SerializedMessage::~SerializedMessage () virtual
Definition at line 796 of file Message.cc.
 {
 }
Member Function Documentation
void SerializedMessage::des (size_t s, void * dataptr)
Definition at line 814 of file Message.cc.
References data, and pos.
Referenced by des(), Message::unpack(), MessageSocket::unpack(), MessageUserSchema::unpack(), MessageDeadlock::unpack(), MessageTransaction::unpack(), MessageSubtransactionCmd::unpack(), MessageCommitRollback::unpack(), MessageDispatch::unpack(), MessageAckDispatch::unpack(), MessageApply::unpack(), and MessageAckApply::unpack().
 {
     memcpy(dataptr, &data->at(pos), s);
     pos += s;
 }
void SerializedMessage::des (int64_t * d)
Definition at line 832 of file Message.cc.
References data, and pos.
 {
     memcpy(d, &data->at(pos), sizeof(*d));
     pos += sizeof(*d);
 }
void SerializedMessage::des (int32_t * d)
Definition at line 849 of file Message.cc.
References data, and pos.
 {
     memcpy(d, &data->at(pos), sizeof(*d));
     pos += sizeof(*d);
 }
void SerializedMessage::des (int16_t * d)
Definition at line 866 of file Message.cc.
References data, and pos.
 {
     memcpy(d, &data->at(pos), sizeof(*d));
     pos += sizeof(*d);
 }
void SerializedMessage::des (int8_t * d)
Definition at line 883 of file Message.cc.
References data, and pos.
 {
     memcpy(d, &data->at(pos), sizeof(*d));
     pos += sizeof(*d);
 }
void SerializedMessage::des (string & d)
Definition at line 905 of file Message.cc.
References data, des(), and pos.
Referenced by des().
 {
     size_t s;
     des((int64_t *)&s);
     if (s)
     {
         d.assign((const char *)&data->at(pos), s);
         pos += s;
     }
 }
void SerializedMessage::des (vector< int64_t > & d)
Definition at line 932 of file Message.cc.
References data, des(), and pos.
 {
     size_t s;
     memcpy(&s, &data->at(pos), sizeof(s));
     pos += sizeof(s);
     d.reserve(s);
     for (size_t n=0; n<s; n++)
     {
         int64_t val;
         des(&val);
         d.push_back(val);
     }
 }
void SerializedMessage::des (boost::unordered_map< int64_t, int64_t > & d)
Definition at line 962 of file Message.cc.
References data, des(), and pos.
 {
     size_t s;
     memcpy(&s, &data->at(pos), sizeof(s));
     pos += sizeof(s);
     for (size_t n=0; n<s; n++)
     {
         int64_t val1, val2;
         des(&val1);
         des(&val2);
         d[val1]=val2;
     }
 }
void SerializedMessage::des (Message::message_s & d)
Definition at line 988 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageSocket::socket_s & d)
Definition at line 1006 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageUserSchema::userschema_s & d)
Definition at line 1023 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (procedures_s & d)
Definition at line 1040 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageDeadlock::deadlock_s & d)
Definition at line 1057 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageTransaction::transaction_s & d)
Definition at line 1074 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageSubtransactionCmd::subtransaction_s & d)
Definition at line 1091 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (nonLockingIndexEntry_s & d)
Definition at line 1108 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageDispatch::dispatch_s & d)
Definition at line 1125 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageAckDispatch::ackdispatch_s & d)
Definition at line 1142 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageApply::apply_s & d)
Definition at line 1159 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (MessageAckApply::ackapply_s & d)
Definition at line 1176 of file Message.cc.
References data, and pos.
 {
     memcpy(&d, &data->at(pos), sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::des (boost::unordered_set< string > & d)
Definition at line 1205 of file Message.cc.
References des().
 {
     size_t s;
     des((int64_t *)&s);
     for (size_t n=0; n<s; n++)
     {
         string val;
         des(val);
         d.insert(val);
     }
 }
void SerializedMessage::des (fieldValue_s & d)
Definition at line 1230 of file Message.cc.
References data, des(), fieldValue_s::isnull, pos, fieldValue_s::str, and fieldValue_s::value.
 {
     memcpy(&d.value, &data->at(pos), sizeof(d.value));
     pos += sizeof(d.value);
     des(d.str);
     des((int8_t *)&d.isnull);
 }
void SerializedMessage::des (returnRow_s & d)
Definition at line 1252 of file Message.cc.
References des(), returnRow_s::locktype, returnRow_s::previoussubtransactionid, returnRow_s::row, and returnRow_s::rowid.
 {
     des(&d.rowid);
     des(&d.previoussubtransactionid);
     des((int8_t *)&d.locktype);
     des(d.row);
 }
void SerializedMessage::des (MessageDispatch::record_s & d)
Definition at line 1276 of file Message.cc.
References des(), MessageDispatch::record_s::oldrow, MessageDispatch::record_s::previoussubtransactionid, MessageDispatch::record_s::primitive, MessageDispatch::record_s::row, MessageDispatch::record_s::rowid, and MessageDispatch::record_s::tableid.
 {
     des(&d.rowid);
     des((int8_t *)&d.primitive);
     des(&d.tableid);
     des(&d.previoussubtransactionid);
     des(d.row);
     des(d.oldrow);
 }
void SerializedMessage::des (vector< nonLockingIndexEntry_s > & d)
Definition at line 1302 of file Message.cc.
References des().
 {
     size_t s;
     des((int64_t *)&s);
     d.reserve(s);
     for (size_t n=0; n<s; n++)
     {
         nonLockingIndexEntry_s val;
         des(val);
         d.push_back(val);
     }
 }
void SerializedMessage::des (newDeadLockLists_s & d)
Definition at line 1327 of file Message.cc.
References des(), newDeadLockLists_s::locked, and newDeadLockLists_s::waiting.
 {
     des(d.locked);
     des(d.waiting);
 }
void SerializedMessage::des (vector< fieldValue_s > & d)
Definition at line 1354 of file Message.cc.
References des().
 {
     size_t s;
     des((int64_t *)&s);
     d.reserve(s);
     for (size_t n=0; n<s; n++)
     {
         fieldValue_s val;
         des(val);
         d.push_back(val);
     }
 }
void SerializedMessage::des (vector< returnRow_s > & d)
Definition at line 1388 of file Message.cc.
References des().
 {
     size_t s;
     des((int64_t *)&s);
     d.reserve(s);
     for (size_t n=0; n<s; n++)
     {
         returnRow_s val;
         des(val);
         d.push_back(val);
     }
 }
void SerializedMessage::des (vector< MessageDispatch::record_s > & d)
Definition at line 1422 of file Message.cc.
References des().
 {
     size_t s;
     des((int64_t *)&s);
     d.reserve(s);
     for (size_t n=0; n<s; n++)
     {
         MessageDispatch::record_s val;
         des(val);
         d.push_back(val);
     }
 }
void SerializedMessage::des (rowOrField_s & d)
Definition at line 1460 of file Message.cc.
References rowOrField_s::deleteindexentry, des(), rowOrField_s::engineid, rowOrField_s::fieldid, rowOrField_s::fieldVal, rowOrField_s::isnotaddunique, rowOrField_s::isreplace, rowOrField_s::isrow, rowOrField_s::newengineid, rowOrField_s::newrowid, rowOrField_s::rowid, and rowOrField_s::tableid.
 {
     des((int8_t *)&d.isrow);
     des(&d.tableid);
     des(&d.rowid);
     des(&d.fieldid);
     des(&d.engineid);
     des((int8_t *)&d.deleteindexentry);
     des((int8_t *)&d.isnotaddunique);
     des((int8_t *)&d.isreplace);
     des(&d.newrowid);
     des(&d.newengineid);
     des(d.fieldVal);
 }
void SerializedMessage::des (MessageApply::applyindex_s & d)
Definition at line 1490 of file Message.cc.
References data, des(), MessageApply::applyindex_s::entry, MessageApply::applyindex_s::fieldid, MessageApply::applyindex_s::fieldVal, MessageApply::applyindex_s::flags, pos, and MessageApply::applyindex_s::tableid.
 {
     des(d.fieldVal);
     des(d.entry);
     d.flags=data->at(pos++);
     des(&d.tableid);
     des(&d.fieldid);
 }
void SerializedMessage::des (searchParams_s & d)
Definition at line 1512 of file Message.cc.
References des(), searchParams_s::op, searchParams_s::regexString, and searchParams_s::values.
 {
     des((int8_t *)&d.op);
     des(d.values);
     des(d.regexString);
 }
void SerializedMessage::des (vector< rowOrField_s > & d)
Definition at line 1540 of file Message.cc.
References des().
 {
     size_t s;
     des((int64_t *)&s);
     d.reserve(s);
     for (size_t n=0; n<s; n++)
     {
         rowOrField_s val;
         des(val);
         d.push_back(val);
     }
 }
void SerializedMessage::des (vector< MessageApply::applyindex_s > & d)
Definition at line 1574 of file Message.cc.
References des().
 {
     size_t s;
     des((int64_t *)&s);
     d.reserve(s);
     for (size_t n=0; n<s; n++)
     {
         MessageApply::applyindex_s val;
         des(val);
         d.push_back(val);
     }
 }
void SerializedMessage::des (boost::unordered_map< int64_t, vector< MessageDispatch::record_s > > & d)
Definition at line 1606 of file Message.cc.
References data, des(), and pos.
 {
     size_t s;
     memcpy(&s, &data->at(pos), sizeof(s));
     pos += sizeof(s);
     for (size_t n=0; n<s; n++)
     {
         int64_t val1;
         des(&val1);
         vector<MessageDispatch::record_s> val2;
         des(val2);
         d[val1]=val2;
     }
 }
payloadtype_e SerializedMessage::getpayloadtype ()
Definition at line 800 of file Message.cc.
References data, and Message::message_s::payloadtype.
Referenced by Message::des(), Message::ser(), MessageSocket::ser(), MessageUserSchema::ser(), MessageDeadlock::ser(), MessageTransaction::ser(), MessageSubtransactionCmd::ser(), MessageCommitRollback::ser(), MessageDispatch::ser(), MessageAckDispatch::ser(), MessageApply::ser(), and MessageAckApply::ser().
 {
     Message::message_s tmpheader;
     memcpy(&tmpheader, data->c_str(), sizeof(tmpheader));
     return tmpheader.payloadtype;
 }
void SerializedMessage::ser (size_t s, void * dataptr)
Definition at line 808 of file Message.cc.
References data, and pos.
Referenced by Message::package(), MessageSocket::package(), MessageUserSchema::package(), MessageDeadlock::package(), MessageTransaction::package(), MessageSubtransactionCmd::package(), MessageCommitRollback::package(), MessageDispatch::package(), MessageAckDispatch::package(), MessageApply::package(), MessageAckApply::package(), and ser().
 {
     memcpy(&data->at(pos), dataptr, s);
     pos += s;
 }
void SerializedMessage::ser (int64_t d)
Definition at line 821 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (int32_t d)
Definition at line 838 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (int16_t d)
Definition at line 855 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (int8_t d)
Definition at line 872 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (const string & d)
Definition at line 890 of file Message.cc.
References data, pos, and ser().
 {
     ser((int64_t)d.size());
     if (d.size())
     {
         memcpy(&data->at(pos), d.c_str(), d.size());
         pos += d.size();
     }
 }
void SerializedMessage::ser (vector< int64_t > & d)
Definition at line 916 of file Message.cc.
References data, pos, and ser().
 {
     size_t s=d.size();
     memcpy(&data->at(pos), &s, sizeof(s));
     pos += sizeof(s);
     for (size_t n=0; n<s; n++)
     {
         ser(d[n]);
     }
 }
void SerializedMessage::ser (boost::unordered_map< int64_t, int64_t > & d)
Definition at line 946 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     boost::unordered_map<int64_t, int64_t>::const_iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(it->first);
         ser(it->second);
     }
 }
void SerializedMessage::ser (Message::message_s & d)
Definition at line 977 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageSocket::socket_s & d)
Definition at line 995 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageUserSchema::userschema_s & d)
Definition at line 1012 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (procedures_s & d)
Definition at line 1029 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageDeadlock::deadlock_s & d)
Definition at line 1046 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageTransaction::transaction_s & d)
Definition at line 1063 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageSubtransactionCmd::subtransaction_s & d)
Definition at line 1080 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (nonLockingIndexEntry_s & d)
Definition at line 1097 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageDispatch::dispatch_s & d)
Definition at line 1114 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageAckDispatch::ackdispatch_s & d)
Definition at line 1131 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageApply::apply_s & d)
Definition at line 1148 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (MessageAckApply::ackapply_s & d)
Definition at line 1165 of file Message.cc.
References data, and pos.
 {
     memcpy(&data->at(pos), &d, sizeof(d));
     pos += sizeof(d);
 }
void SerializedMessage::ser (boost::unordered_set< string > & d)
Definition at line 1183 of file Message.cc.
References ser().
 {
     size_t s=d.size();
     ser((int64_t)s);
     boost::unordered_set<string>::const_iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(*it);
     }
 }
void SerializedMessage::ser (fieldValue_s & d)
Definition at line 1217 of file Message.cc.
References data, fieldValue_s::isnull, pos, ser(), fieldValue_s::str, and fieldValue_s::value.
 {
     memcpy(&data->at(pos), &d.value, sizeof(d.value));
     pos += sizeof(d.value);
     ser(d.str);
     ser((int8_t)d.isnull);
 }
void SerializedMessage::ser (returnRow_s & d)
Definition at line 1238 of file Message.cc.
References returnRow_s::locktype, returnRow_s::previoussubtransactionid, returnRow_s::row, returnRow_s::rowid, and ser().
 {
     ser(d.rowid);
     ser(d.previoussubtransactionid);
     ser((int8_t)d.locktype);
     ser(d.row);
 }
void SerializedMessage::ser (MessageDispatch::record_s & d)
Definition at line 1260 of file Message.cc.
References MessageDispatch::record_s::oldrow, MessageDispatch::record_s::previoussubtransactionid, MessageDispatch::record_s::primitive, MessageDispatch::record_s::row, MessageDispatch::record_s::rowid, ser(), and MessageDispatch::record_s::tableid.
 {
     ser(d.rowid);
     ser((int8_t)d.primitive);
     ser(d.tableid);
     ser(d.previoussubtransactionid);
     ser(d.row);
     ser(d.oldrow);
 }
void SerializedMessage::ser (vector< nonLockingIndexEntry_s > & d)
Definition at line 1286 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     vector<nonLockingIndexEntry_s>::iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(*it);
     }
 }
void SerializedMessage::ser (newDeadLockLists_s & d)
Definition at line 1316 of file Message.cc.
References newDeadLockLists_s::locked, ser(), and newDeadLockLists_s::waiting.
 {
     ser(d.locked);
     ser(d.waiting);
 }
void SerializedMessage::ser (vector< fieldValue_s > & d)
Definition at line 1333 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     vector<fieldValue_s>::iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(*it);
     }
 }
void SerializedMessage::ser (vector< returnRow_s > & d)
Definition at line 1367 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     vector<returnRow_s>::iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(*it);
     }
 }
void SerializedMessage::ser (vector< MessageDispatch::record_s > & d)
Definition at line 1401 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     vector<MessageDispatch::record_s>::iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(*it);
     }
 }
void SerializedMessage::ser (rowOrField_s & d)
Definition at line 1435 of file Message.cc.
References rowOrField_s::deleteindexentry, rowOrField_s::engineid, rowOrField_s::fieldid, rowOrField_s::fieldVal, rowOrField_s::isnotaddunique, rowOrField_s::isreplace, rowOrField_s::isrow, rowOrField_s::newengineid, rowOrField_s::newrowid, rowOrField_s::rowid, ser(), and rowOrField_s::tableid.
 {
     ser((int8_t)d.isrow);
     ser(d.tableid);
     ser(d.rowid);
     ser(d.fieldid);
     ser(d.engineid);
     ser((int8_t)d.deleteindexentry);
     ser((int8_t)d.isnotaddunique);
     ser((int8_t)d.isreplace);
     ser(d.newrowid);
     ser(d.newengineid);
     ser(d.fieldVal);
 }
void SerializedMessage::ser (MessageApply::applyindex_s & d)
Definition at line 1475 of file Message.cc.
References data, MessageApply::applyindex_s::entry, MessageApply::applyindex_s::fieldid, MessageApply::applyindex_s::fieldVal, MessageApply::applyindex_s::flags, pos, ser(), and MessageApply::applyindex_s::tableid.
 {
     ser(d.fieldVal);
     ser(d.entry);
     data[pos++]=d.flags;
     ser(d.tableid);
     ser(d.fieldid);
 }
void SerializedMessage::ser (searchParams_s & d)
Definition at line 1500 of file Message.cc.
References searchParams_s::op, searchParams_s::regexString, ser(), and searchParams_s::values.
 {
     ser((int8_t)d.op);
     ser(d.values);
     ser(d.regexString);
 }
void SerializedMessage::ser (vector< rowOrField_s > & d)
Definition at line 1519 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     vector<rowOrField_s>::iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(*it);
     }
 }
void SerializedMessage::ser (vector< MessageApply::applyindex_s > & d)
Definition at line 1553 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     vector<MessageApply::applyindex_s>::iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(*it);
     }
 }
void SerializedMessage::ser (boost::unordered_map< int64_t, vector< MessageDispatch::record_s > > & d)
Definition at line 1587 of file Message.cc.
References ser().
 {
     ser((int64_t)d.size());
     boost::unordered_map< int64_t,
                           vector<MessageDispatch::record_s> >::iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         ser(it->first);
         ser(it->second);
     }
 }
size_t SerializedMessage::sersize (int64_t d) static
Definition at line 827 of file Message.cc.
Referenced by sersize(), Message::size(), MessageSocket::size(), MessageUserSchema::size(), MessageDeadlock::size(), MessageTransaction::size(), MessageSubtransactionCmd::size(), MessageCommitRollback::size(), MessageDispatch::size(), MessageAckDispatch::size(), MessageApply::size(), and MessageAckApply::size().
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (int32_t d) static
Definition at line 844 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (int16_t d) static
Definition at line 861 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (int8_t d) static
Definition at line 878 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (const string & d) static
Definition at line 900 of file Message.cc.
 {
     return sizeof(int64_t)+d.size();
 }
size_t SerializedMessage::sersize (vector< int64_t > & d) static
Definition at line 927 of file Message.cc.
 {
     return sizeof(size_t) + (d.size() * sizeof(int64_t));
 }
size_t SerializedMessage::sersize (boost::unordered_map< int64_t, int64_t > & d) static
Definition at line 957 of file Message.cc.
 {
     return d.size() + (d.size() * 2 * sizeof(int64_t));
 }
size_t SerializedMessage::sersize (Message::message_s & d) static
Definition at line 983 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageSocket::socket_s & d) static
Definition at line 1001 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageUserSchema::userschema_s & d) static
Definition at line 1018 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (procedures_s & d) static
Definition at line 1035 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageDeadlock::deadlock_s & d) static
Definition at line 1052 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageTransaction::transaction_s & d) static
Definition at line 1069 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageSubtransactionCmd::subtransaction_s & d) static
Definition at line 1086 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (nonLockingIndexEntry_s & d) static
Definition at line 1103 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageDispatch::dispatch_s & d) static
Definition at line 1120 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageAckDispatch::ackdispatch_s & d) static
Definition at line 1137 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageApply::apply_s & d) static
Definition at line 1154 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (MessageAckApply::ackapply_s & d) static
Definition at line 1171 of file Message.cc.
 {
     return sizeof(d);
 }
size_t SerializedMessage::sersize (boost::unordered_set< string > & d) static
Definition at line 1194 of file Message.cc.
References sersize().
 {
     size_t retval=sizeof(size_t);
     boost::unordered_set<string>::const_iterator it;
     for (it=d.begin(); it != d.end(); ++it)
     {
         retval += sersize(*it);
     }
     return retval;
 }
size_t SerializedMessage::sersize (fieldValue_s & d) static
Definition at line 1225 of file Message.cc.
References fieldValue_s::isnull, sersize(), fieldValue_s::str, and fieldValue_s::value.
 {
     return sizeof(d.value)+sersize(d.str)+sersize((int8_t)d.isnull);
 }
size_t SerializedMessage::sersize (returnRow_s & d) static
Definition at line 1246 of file Message.cc.
References returnRow_s::locktype, returnRow_s::previoussubtransactionid, returnRow_s::row, returnRow_s::rowid, and sersize().
 {
     return sersize(d.rowid)+sersize(d.previoussubtransactionid)+
         sersize((int8_t)d.locktype)+sersize(d.row);
 }
size_t SerializedMessage::sersize (MessageDispatch::record_s & d) static
Definition at line 1270 of file Message.cc.
References MessageDispatch::record_s::oldrow, MessageDispatch::record_s::previoussubtransactionid, MessageDispatch::record_s::primitive, MessageDispatch::record_s::row, MessageDispatch::record_s::rowid, sersize(), and MessageDispatch::record_s::tableid.
 {
     return sersize(d.rowid)+sersize((int8_t)d.primitive)+sersize(d.tableid)+
         sersize(d.previoussubtransactionid)+sersize(d.row)+sersize(d.oldrow);
 }
size_t SerializedMessage::sersize (vector< nonLockingIndexEntry_s > & d) static
Definition at line 1296 of file Message.cc.
 {
     size_t s=d.size();
     return sizeof(int64_t) + (s *sizeof(nonLockingIndexEntry_s));
 }
size_t SerializedMessage::sersize (newDeadLockLists_s & d) static
Definition at line 1322 of file Message.cc.
References newDeadLockLists_s::locked, sersize(), and newDeadLockLists_s::waiting.
 {
     return sersize(d.locked)+sersize(d.waiting);
 }
size_t SerializedMessage::sersize (vector< fieldValue_s > & d) static
Definition at line 1343 of file Message.cc.
References sersize().
 {
     size_t retval=sizeof(int64_t);
     vector<fieldValue_s>::iterator it;
     for (it = d.begin(); it != d.end(); ++it)
     {
         retval += sersize(*it);
     }
     return retval;
 }
size_t SerializedMessage::sersize (vector< returnRow_s > & d) static
Definition at line 1377 of file Message.cc.
References sersize().
 {
     size_t retval=sizeof(int64_t);
     vector<returnRow_s>::iterator it;
     for (it = d.begin(); it != d.end(); ++it)
     {
         retval += sersize(*it);
     }
     return retval;
 }
size_t SerializedMessage::sersize (vector< MessageDispatch::record_s > & d) static
Definition at line 1411 of file Message.cc.
References sersize().
 {
     size_t retval=sizeof(int64_t);
     vector<MessageDispatch::record_s>::iterator it;
     for (it = d.begin(); it != d.end(); ++it)
     {
         retval += sersize(*it);
     }
     return retval;
 }
size_t SerializedMessage::sersize (rowOrField_s & d) static
Definition at line 1450 of file Message.cc.
References rowOrField_s::deleteindexentry, rowOrField_s::engineid, rowOrField_s::fieldid, rowOrField_s::fieldVal, rowOrField_s::isnotaddunique, rowOrField_s::isreplace, rowOrField_s::isrow, rowOrField_s::newengineid, rowOrField_s::newrowid, rowOrField_s::rowid, sersize(), and rowOrField_s::tableid.
 {
     return sersize((int8_t)d.isrow)+sersize(d.tableid)+sersize(d.rowid)+
         sersize(d.fieldid)+sersize(d.engineid)+
         sersize((int8_t)d.deleteindexentry)+
         sersize((int8_t)d.isnotaddunique)+
         sersize((int8_t)d.isreplace)+sersize(d.newrowid)+
         sersize(d.newengineid)+sersize(d.fieldVal);
 }
size_t SerializedMessage::sersize (MessageApply::applyindex_s & d) static
Definition at line 1484 of file Message.cc.
References MessageApply::applyindex_s::entry, MessageApply::applyindex_s::fieldid, MessageApply::applyindex_s::fieldVal, sersize(), and MessageApply::applyindex_s::tableid.
 {
     return sersize(d.fieldVal)+sersize(d.entry)+1+sersize(d.tableid)+
         sersize(d.fieldid);
 }
size_t SerializedMessage::sersize (searchParams_s & d) static
Definition at line 1507 of file Message.cc.
References searchParams_s::op, searchParams_s::regexString, sersize(), and searchParams_s::values.
 {
     return sersize((int8_t)d.op)+sersize(d.values)+sersize(d.regexString);
 }
size_t SerializedMessage::sersize (vector< rowOrField_s > & d) static
Definition at line 1529 of file Message.cc.
References sersize().
 {
     size_t retval=sizeof(int64_t);
     vector<rowOrField_s>::iterator it;
     for (it = d.begin(); it != d.end(); ++it)
     {
         retval += sersize(*it);
     }
     return retval;
 }
size_t SerializedMessage::sersize (vector< MessageApply::applyindex_s > & d) static
Definition at line 1563 of file Message.cc.
References sersize().
 {
     size_t retval=sizeof(int64_t);
     vector<MessageApply::applyindex_s>::iterator it;
     for (it = d.begin(); it != d.end(); ++it)
     {
         retval += sersize(*it);
     }
     return retval;
 }
size_t SerializedMessage::sersize (boost::unordered_map< int64_t, vector< MessageDispatch::record_s > > & d) static
Definition at line 1600 of file Message.cc.
 {
     return d.size() + (d.size() * 2 * sizeof(int64_t));
 }
Member Data Documentation
std::string* SerializedMessage::data
Definition at line 886 of file Message.h.
Referenced by des(), getpayloadtype(), Message::ser(), MessageSocket::ser(), MessageUserSchema::ser(), MessageDeadlock::ser(), MessageTransaction::ser(), MessageSubtransactionCmd::ser(), MessageCommitRollback::ser(), MessageDispatch::ser(), MessageAckDispatch::ser(), MessageApply::ser(), MessageAckApply::ser(), ser(), and SerializedMessage().
size_t SerializedMessage::pos
Definition at line 885 of file Message.h.
Referenced by des(), Message::ser(), MessageSocket::ser(), MessageUserSchema::ser(), MessageDeadlock::ser(), MessageTransaction::ser(), MessageSubtransactionCmd::ser(), MessageCommitRollback::ser(), MessageDispatch::ser(), MessageAckDispatch::ser(), MessageApply::ser(), MessageAckApply::ser(), and ser().
size_t SerializedMessage::size
Definition at line 884 of file Message.h.
Referenced by SerializedMessage().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc