InfiniSQL: Pg Class Reference
Pg Class Reference
object that handles SQL activities
#include <Pg.h>
Public Types
enum states_e {
STATE_NONE = 0, STATE_BEGIN, STATE_AUTH, STATE_ESTABLISHED,
STATE_ABORTED, STATE_EXITING
}
states for an SQL connection
Public Member Functions
Pg (class TransactionAgent *entrypoint, int statePtr)
virtual ~Pg ()
void doit ()
void continueFunc1 (int64_t entrypoint, void *statePtr)
user-defined continuation function
void continueFunc2 (int64_t entrypoint, void *statePtr)
second user-defined continuation function
void continuePgFunc (int64_t entrypoint, void *statePtr)
after SQL activity is performed
void continuePgCommitimplicit (int64_t entrypoint, void *statePtr)
continuation function after implicit commit
void continuePgCommitexplicit (int64_t entrypoint, void *statePtr)
continuation function after explicit commit
void continuePgRollbackimplicit (int64_t entrypoint, void *statePtr)
continuation function after implicit rollback
void continuePgRollbackexplicit (int64_t entrypoint, void *statePtr)
continuation function after explicit rollback
bool readsocket (string &buf)
read from socket
void closesocket (class TransactionAgent &taRef)
close socket
void cont ()
wire protocol handling
short initcmd (string &newdata)
read new command from socket
void replymsg ()
put message for reply into outbound buffer
short writesocket ()
write response messages to socket
short rewritesocket ()
write stored buffer to socket
bool get (int16_t *val)
read 16bit integer from inbound message string
bool get (int32_t *val)
read 32bit integer from inbound message string
bool get (int64_t *val)
read 64bit integer from inbound message string
bool get (vector< int16_t > &val, size_t nelem)
read list of 16bit integers from inbound message string
bool get (vector< int32_t > &val, size_t nelem)
read array of 32bit integers from inbound message string
bool get (vector< int64_t > &val, size_t nelem)
read array of 64bit integers inbound message string
bool get (char *val)
read Byte1 from inbound message string
bool get (string &val, size_t nelem)
read Byten from inbound message string
bool get (string &val)
read String (c-style) from inbound message string
void put (int16_t val)
write data to outbound message buffer
void put (int32_t val)
write data to outbound message buffer
void put (int64_t val)
write data to outbound message buffer
void put (vector< int16_t > &val)
write data to outbound message buffer
void put (vector< int32_t > &val)
write data to outbound message buffer
void put (vector< int64_t > &val)
write data to outbound message buffer
void put (char val)
write data to outbound message buffer
void put (char *val, size_t nelem)
write Byten to outbound message buffer
void put (string &val)
write data to outbound message buffer
void put (char *val)
write data to outbound message buffer
void putCommandComplete (char *tag)
write completed command to outbound message buffer
void putErrorResponse (char *severity, char *code, char *message)
write error to outbound message buffer
void putNoticeResponse (char *severity, char *code, char *message)
write notice to outbound message buffer
void putRowDescription ()
write field names to outbound message buffer
void putDataRows ()
write rows to outbound message buffer
void putAuthenticationOk ()
write authenticationok status to outbound message buffer
void putParameterStatus (char *name, char *value)
write server parameters in status message to outbound message buffer
void sqlcommitimplicit ()
implicit commit
void sqlcommitexplicit ()
explicit commit
void sqlrollbackimplicit ()
implicit rollback
void sqlrollbackexplicit ()
explicit rollback
bool sqlbegin ()
appears to be orphan
void continueLogin (int cmdstate, class MessageUserSchema &msgrcvref)
continuation after login operation
void executeStatement (string &stmtstr)
tokenize, parse, compile and execute SQL query
void errorStatus (int64_t status)
output error based on Transaction::resultCode
Public Member Functions inherited from ApiInterface
ApiInterface ()
virtual ~ApiInterface ()
void deserialize2Vector ()
orphan
void beginTransaction ()
start Transaction
void destruct ()
orphan
void bouncebackproxy ()
orphan
void insertRow (apifPtr re, int64_t recmd, void *reptr, int64_t tableid)
deprecated
void deleteRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
deprecated
void replaceRow (apifPtr re, int64_t recmd, void *reptr)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, int64_t input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, uint64_t input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, bool input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, long double input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, char input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, string *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< int64_t > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< uint64_t > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< bool > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< long double > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< char > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< string > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, int64_t lower, int64_t upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, uint64_t lower, uint64_t upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, bool lower, bool upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, long double lower, long double upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, char lower, char upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, string *lower, string *upper)
deprecated
void fetchRows (apifPtr re, int64_t recmd, void *reptr)
deprecated
void unlock (apifPtr re, int64_t recmd, void *reptr, int64_t rowid, int64_t tableid, int64_t engineid)
unlock row
void rollback (apifPtr re, int64_t recmd, void *reptr)
rollback transaction
void rollback (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
rollback transaction
void commit (apifPtr re, int64_t recmd, void *reptr)
commit transaction
void revert (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
deprecated
void updateRowNullField (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, int64_t input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, uint64_t input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, bool input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, long double input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, char input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, string input)
deprecated
bool unmakerow (int64_t tableid, string *rowstring, vector< fieldValue_s > *resultFields)
deprecated
void prepareResponseVector (int64_t resultCode)
deprecated
void addFieldToRow ()
deprecated
void addFieldToRow (int64_t val)
deprecated
void addFieldToRow (uint64_t val)
deprecated
void addFieldToRow (bool val)
deprecated
void addFieldToRow (long double val)
deprecated
void addFieldToRow (char val)
deprecated
void addFieldToRow (string &val)
deprecated
void setReEntry (apifPtr re, int64_t recmd, void *reptr)
set continuation target back to ApiInterface object
void sendResponse (int64_t resultCode, vector< std::string > *v)
deprecated
bool execStatement (const char *stmtname, Statement *stmtPtr, apifPtr reentryfunction, int64_t reentrypoint, void *reentrydata)
execute SQL statement
bool execStatement (const char *stmtname, vector< std::string > &args, apifPtr reentryfunction, int64_t reentrypoint, void *reentrydata)
execute SQL statement
int64_t getResultCode ()
get resultCode from most recent transactional activity
void deleteTransaction ()
delete Transaction
void deleteStatement ()
delete Statement
void getStoredProcedureArgs (Statement *stmtPtr, std::vector< std::string > &argsRef)
put args from stored procedure Statement into vector of strings
Static Public Member Functions
static void pgclosesocket (class TransactionAgent &taRef, int socketfd)
more socket closing-related activities
Public Attributes
states_e state
int sockfd
char pgcmdtype
uint32_t size
std::string inbuf
size_t pos
char outcmd
std::string outmsg
std::string outbuf
int64_t userid
class Schema * schemaPtr
boost::unordered_map
< std::string, std::string > startupArgs
std::string procedureprefix
bool session_isautocommit
bool command_autocommit
bool isintransactionblock
Public Attributes inherited from ApiInterface
class TransactionAgent * taPtr
class ApiInterface * pgPtr
class Statement * statementPtr
std::vector< std::string > inputVector
class Transaction * transactionPtr
procedureResponse_s response
std::vector< std::string > responseVector
void * destroyerPtr
apifPtr continueFunc1Ptr
apifPtr continueFunc2Ptr
apifPtr continuePgFuncPtr
int sockfd
int64_t domainid
results_s results
Detailed Description
object that handles SQL activities
implements PostgreSQL frontend/backend protocol, version 3: http://www.postgresql.org/docs/7.4/static/protocol.html
Parameters
entrypoint
statePtr
Returns
Definition at line 47 of file Pg.h.
Member Enumeration Documentation
enum Pg::states_e
states for an SQL connection
Enumerator
STATE_NONE
STATE_BEGIN
STATE_AUTH
STATE_ESTABLISHED
STATE_ABORTED
STATE_EXITING
Definition at line 54 of file Pg.h.
     {
         STATE_NONE = 0,
         STATE_BEGIN,
         STATE_AUTH,
         STATE_ESTABLISHED,
         STATE_ABORTED,
         STATE_EXITING
     };
Constructor & Destructor Documentation
Pg::Pg (class TransactionAgent * entrypoint, int statePtr)
Definition at line 37 of file Pg.cc.
References ApiInterface::domainid, TransactionAgent::Pgs, sockfd, ApiInterface::statementPtr, ApiInterface::taPtr, and ApiInterface::transactionPtr.
                                                       :
     state(STATE_BEGIN),
     sockfd(sockfdarg), pgcmdtype('\0'), size(0), outcmd('\0'), userid(-1),
     schemaPtr(NULL), session_isautocommit(true), isintransactionblock(false)
 {
     domainid=-1;
     taPtr = taPtrarg;
     statementPtr=NULL;
     transactionPtr=NULL;
     taPtr->Pgs[sockfd]=this;
 }
Pg::~Pg () virtual
Definition at line 50 of file Pg.cc.
 {
 }
Member Function Documentation
void Pg::closesocket (class TransactionAgent & taRef)
close socket
Parameters
taRef TransactionAgent
Definition at line 372 of file Pg.cc.
References ApiInterface::continuePgCommitimplicit(), pgclosesocket(), Transaction::reentryCmd, Transaction::reentryFuncPtr, Transaction::reentryObject, Transaction::reentryState, Transaction::rollback(), sockfd, state, STATE_EXITING, ApiInterface::statementPtr, and ApiInterface::transactionPtr.
Referenced by cont(), continuePgCommitexplicit(), continuePgCommitimplicit(), continuePgFunc(), continuePgRollbackexplicit(), putAuthenticationOk(), and putErrorResponse().
 {
     state=STATE_EXITING;
     pgclosesocket(taRef, sockfd);
     sockfd=-1;
     if (transactionPtr != NULL)
     {
         transactionPtr->reentryObject = NULL;
         transactionPtr->reentryFuncPtr = &ApiInterface::continuePgCommitimplicit;
         transactionPtr->reentryCmd = 1;
         transactionPtr->reentryState = NULL;
         transactionPtr->rollback();
         return;
     }
     if (statementPtr==NULL)
     {
         delete this;
     }
 }
void Pg::cont ()
wire protocol handling
called by TransactionAgent when incoming socket reads ready
Definition at line 55 of file Pg.cc.
References MessageUserSchema::userschema_s::caller, MessageUserSchema::userschema_s::callerstate, closesocket(), CMD_COMMIT, CMD_ROLLBACK, MessageUserSchema::domainname, MessageSocket::socket_s::events, executeStatement(), inbuf, initcmd(), isintransactionblock, TransactionAgent::msgrcv, OPERATION_LOGIN, Operation::operationid, MessageUserSchema::userschema_s::operationid, MessageUserSchema::userschema_s::operationtype, outbuf, outcmd, MessageUserSchema::password, pgcmdtype, pos, put(), putCommandComplete(), putErrorResponse(), Statement::queries, readsocket(), replymsg(), rewritesocket(), schemaPtr, size, MessageSocket::socketStruct, Operation::sockfd, sockfd, startupArgs, state, STATE_ABORTED, STATE_AUTH, STATE_BEGIN, STATE_ESTABLISHED, STATE_EXITING, Larxer::statementPtr, ApiInterface::statementPtr, ApiInterface::taPtr, MessageUserSchema::username, MessageUserSchema::userschemaStruct, and writesocket().
 {
     if (state==STATE_EXITING)
     {
         return;
     }
     class MessageSocket &msgrcvref = *((class MessageSocket *)taPtr->msgrcv);
     string newdata;
     if ((msgrcvref.socketStruct.events & EPOLLERR) ||
         (msgrcvref.socketStruct.events & EPOLLHUP))
     {
         closesocket(*taPtr);
         return;
     }
     if (msgrcvref.socketStruct.events & EPOLLIN)
     {
         // read stuff from the socket
         if (readsocket(newdata)==false)
         {
             closesocket(*taPtr);
             return;
         }
         if (!newdata.size())
         {
             // must've been spurious event from epoll
             return;
         }
     }
     else if (msgrcvref.socketStruct.events & EPOLLOUT)
     {
         if (rewritesocket()==-1)
         {
             closesocket(*taPtr);
         }
         return;
     }
     else
     {
         printf("%s %i anomaly events %u\n", __FILE__, __LINE__,
                msgrcvref.socketStruct.events);
         return;
     }
     short retval = initcmd(newdata);
     switch (retval)
     {
     case -1: // bogus input
         closesocket(*taPtr);
         return;
 //        break;
     case 0: // command not completely received
         return;
 //        break;
     case 1: // command completely received
         pos = 0;
         outbuf.clear();
         break;
     default:
         printf("%s %i anomaly retval %i\n", __FILE__, __LINE__, retval);
     }
     // now, type & size are set.
     switch (state)
     {
     case STATE_BEGIN:
     {
         if (size==8) // ssl request
         {
             int32_t sslreq;
             if (get(&sslreq)==false)
             {
                 closesocket(*taPtr);
                 return;
             }
             if (sslreq != 80877103)
             {
                 closesocket(*taPtr);
                 return;
             }
             outbuf.assign("N");
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
             size = 0;
             return;
         }
         else // normal start packet
         {
             int32_t protvers;
             if (get(&protvers)==false)
             {
                 closesocket(*taPtr);
                 return;
             }
             if (protvers != 196608)
             {
                 closesocket(*taPtr);
                 return;
             }
             while (inbuf[pos] != '\0')
             {
                 string paramstr;
                 if (get(paramstr)==false)
                 {
                     closesocket(*taPtr);
                     return;
                 }
                 string valstr;
                 if (get(valstr)==false)
                 {
                     closesocket(*taPtr);
                     return;
                 }
                 startupArgs[paramstr] = valstr;
             }
             if (!startupArgs.count("user"))
             {
                 closesocket(*taPtr);
                 return;
             }
             if (!startupArgs.count("database"))
             {
                 startupArgs["database"] = startupArgs["user"];
             }
             outcmd = 'R';
             put((int32_t)3);
             replymsg();
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
                 return;
             }
             state = STATE_AUTH;
             size = 0;
             inbuf.clear();
         }
     }
     break;
     case STATE_AUTH:
     {
         if (pgcmdtype != 'p')
         {
             closesocket(*taPtr);
             return;
         }
         string password;
         if (get(password)==false)
         {
             closesocket(*taPtr);
             return;
         }
         // send credentials to USM
         class Operation &operationRef = *(new class Operation(OP_PGLOGIN, taPtr,
                                                               -1, -1));
         operationRef.sockfd = sockfd;
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_OPERATION);
         msg->userschemaStruct.caller = 1;
         msg->userschemaStruct.callerstate = 1;
         msg->userschemaStruct.operationid = operationRef.operationid;
         msg->userschemaStruct.operationtype = OPERATION_LOGIN;
         msg->username = startupArgs["user"];
         msg->domainname = startupArgs["database"];
         msg->password = password;
         taPtr->mboxes.toUserSchemaMgr(taPtr->myIdentity.address, *msg);
     }
     break;
     case STATE_ESTABLISHED:
     {
         switch (pgcmdtype)
         {
         case 'Q':
         {
             string query;
             get(query);
             inbuf.clear();
             size=0;
             executeStatement(query);
         }
         break;
         case 'X':
             closesocket(*taPtr);
             break;
         default:
             printf("%s %i don't know how to handle cmdtype %c\n", __FILE__,
                    __LINE__, pgcmdtype);
         }
     }
     break;
     case STATE_ABORTED:
     {
         switch (pgcmdtype)
         {
         case 'Q':
         {
             string query;
             get(query);
             inbuf.clear();
             size=0;
             class Larxer lx((char *)query.c_str(), taPtr, schemaPtr);
             if (lx.statementPtr==NULL)
             {
                 putErrorResponse("ERROR", "42601", "syntax error, aborted");
                 return;
             }
             statementPtr=lx.statementPtr;
             if (statementPtr->queries[0].type==CMD_COMMIT ||
                 statementPtr->queries[0].type==CMD_ROLLBACK)
             {
                 putCommandComplete("ROLLBACK");
                 state=STATE_ESTABLISHED;
                 isintransactionblock=false;
                 if (writesocket()==-1)
                 {
                     closesocket(*taPtr);
                     return;
                 }
             }
             else
             {
                 putErrorResponse("ERROR", "25P02", "current transaction is aborted, commands ignored until end of transaction block");
             }
             delete statementPtr;
         }
         break;
         case 'X':
             closesocket(*taPtr);
             break;
         default:
             printf("%s %i don't know how to handle cmdtype %c\n", __FILE__,
                    __LINE__, pgcmdtype);
         }
     }
     break;
     default:
         printf("%s %i anomaly state %i\n", __FILE__, __LINE__, state);
     }
 }
void Pg::continueFunc1 (int64_t entrypoint, void * statePtr) inline virtual
user-defined continuation function
Parameters
entrypoint entrypoint for continuation
statePtr state data
Implements ApiInterface.
Definition at line 72 of file Pg.h.
     {
         ;
     }
void Pg::continueFunc2 (int64_t entrypoint, void * statePtr) inline virtual
second user-defined continuation function
Parameters
entrypoint entrypoint for continuation
statePtr state data
Implements ApiInterface.
Definition at line 76 of file Pg.h.
     {
         ;
     }
void Pg::continueLogin (int cmdstate, class MessageUserSchema & msgrcvref)
continuation after login operation
Parameters
cmdstate function state to continue
msgrcvref reply MessageUserSchema
Definition at line 817 of file Pg.cc.
References MessageUserSchema::userschema_s::domainid, ApiInterface::domainid, TransactionAgent::domainidsToSchemata, MessageUserSchema::domainname, procedureprefix, putAuthenticationOk(), putErrorResponse(), schemaPtr, MessageUserSchema::userschema_s::status, STATUS_OK, storedprocprefix, ApiInterface::taPtr, MessageUserSchema::userschema_s::userid, userid, and MessageUserSchema::userschemaStruct.
Referenced by Operation::handleOperation().
 {
     if (msgrcvref.userschemaStruct.status==STATUS_OK)
     {
         userid = msgrcvref.userschemaStruct.userid;
         domainid = msgrcvref.userschemaStruct.domainid;
         procedureprefix.assign(storedprocprefix);
         procedureprefix.append(msgrcvref.domainname);
         procedureprefix.append("_");
         schemaPtr = taPtr->domainidsToSchemata[domainid];
         putAuthenticationOk();
     }
     else // STATUS_NOTOK
     {
         putErrorResponse("FATAL", "28P01", "authenticationfailure");
     }
 }
void Pg::continuePgCommitexplicit (int64_t entrypoint, void * statePtr) virtual
continuation function after explicit commit
explicit commit is sent as COMMIT or END at end of transaction
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implements ApiInterface.
Definition at line 1446 of file Pg.cc.
References closesocket(), logfile, outbuf, putCommandComplete(), state, STATE_EXITING, ApiInterface::statementPtr, ApiInterface::taPtr, ApiInterface::transactionPtr, and writesocket().
Referenced by sqlcommitexplicit().
 {
     putCommandComplete("COMMIT");
     if (transactionPtr != NULL)
     {
         delete transactionPtr;
         transactionPtr=NULL;
     }
     if (state==STATE_EXITING)
     {
         if (statementPtr==NULL)
         {
             fprintf(logfile, "%s %i deleting this %p\n", __FILE__, __LINE__,
                     this);
             delete this;
         }
         return;
     }
     if (writesocket()==-1)
     {
         closesocket(*taPtr);
     }
     outbuf.clear();
 }
void Pg::continuePgCommitimplicit (int64_t entrypoint, void * statePtr) virtual
continuation function after implicit commit
implicit commit done after a single statement is entered, not in a transaction already, and session_isautocommit is true
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implements ApiInterface.
Definition at line 1420 of file Pg.cc.
References closesocket(), logfile, state, STATE_EXITING, ApiInterface::statementPtr, ApiInterface::taPtr, ApiInterface::transactionPtr, and writesocket().
Referenced by sqlcommitimplicit().
 {
     if (transactionPtr != NULL)
     {
         delete transactionPtr;
         transactionPtr=NULL;
     }
     if (state==STATE_EXITING)
     {
         if (statementPtr==NULL)
         {
             fprintf(logfile, "%s %i deleting this %p\n", __FILE__, __LINE__,
                     this);
             delete this;
         }
         return;
     }
     if (writesocket()==-1)
     {
         closesocket(*taPtr);
     }
 }
void Pg::continuePgFunc (int64_t entrypoint, void * statePtr) virtual
after SQL activity is performed
based on the statement type and transaction state, a variety of things if session_isautocommit==true, and is SELECT, INSERT, UPDATE, DELETE, then output If autocommit==false, and SELECT, INSERT, UPDATE, DELETE, then prepare output but don't output if COMMIT (END), then commit open transaction and output results already prepared if ROLLBACK, then rollback open transaction and output results CommandComplete at the end of everything returned If set, then set whatever
Parameters
entrypoint entry point to contiue
statePtr state data to continue with
Implements ApiInterface.
Definition at line 876 of file Pg.cc.
References closesocket(), CMD_BEGIN, CMD_COMMIT, CMD_DELETE, CMD_INSERT, CMD_ROLLBACK, CMD_SELECT, CMD_SET, CMD_STOREDPROCEDURE, CMD_UPDATE, ApiInterface::results_s::cmdtype, command_autocommit, errorStatus(), isintransactionblock, logfile, putCommandComplete(), putDataRows(), putNoticeResponse(), putRowDescription(), ApiInterface::results, ApiInterface::results_s::selectResults, session_isautocommit, sqlcommitexplicit(), sqlcommitimplicit(), sqlrollbackexplicit(), sqlrollbackimplicit(), state, STATE_EXITING, ApiInterface::results_s::statementResults, ApiInterface::results_s::statementStatus, STATUS_NOTOK, STATUS_OK, ApiInterface::taPtr, ApiInterface::results_s::transactionPtr, ApiInterface::transactionPtr, and writesocket().
 {
     /* based on the statement type and transaction state, a variety of things
      * if session_isautocommit==true, and is SELECT, INSERT, UPDATE, DELETE,
      * then output
      * If autocommit==false, and SELECT, INSERT, UPDATE, DELETE, then prepare
      * output but don't output
      * if COMMIT (END), then commit open transaction and output results already
      * prepared
      * if ROLLBACK, then rollback open transaction and output results
      * CommandComplete at the end of everything returned
      * If set, then set whatever
      */
     transactionPtr=results.transactionPtr;
     if (state==STATE_EXITING)
     {
         if (transactionPtr==NULL)
         {
             fprintf(logfile, "%s %i deleting this %p\n", __FILE__, __LINE__,
                     this);
             delete this;
             return;
         }
         else
         {
             sqlrollbackexplicit();
             return;
         }
     }
     switch (results.cmdtype)
     {
     case CMD_SELECT:
     {
         if (results.statementStatus==STATUS_OK)
         {
             putRowDescription();
             putDataRows();
             std::stringstream tag;
             tag << "SELECT " << results.selectResults.size();
             putCommandComplete((char *)tag.str().c_str());
         }
         else
         {
             sqlrollbackimplicit();
             errorStatus(results.statementStatus);
             return;
         }
         if (isintransactionblock==false && (session_isautocommit==true ||
                                             command_autocommit==true))
         {
             sqlcommitimplicit();
         }
         else
         {
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
     }
     break;
     case CMD_INSERT:
         if (results.statementStatus==STATUS_OK)
         {
             putCommandComplete("INSERT 0 1");
         }
         else
         {
             sqlrollbackimplicit();
             errorStatus(results.statementStatus);
             return;
         }
         if (isintransactionblock==false && (session_isautocommit==true ||
                                             command_autocommit==true))
         {
             sqlcommitimplicit();
         }
         else
         {
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
         break;
     case CMD_UPDATE:
     {
         if (results.statementStatus==STATUS_OK)
         {
             std::stringstream tag;
             tag << "UPDATE " << results.statementResults.size();
             putCommandComplete((char *)tag.str().c_str());
         }
         else
         {
             sqlrollbackimplicit();
             errorStatus(STATUS_NOTOK);
             return;
         }
         if (isintransactionblock==false && (session_isautocommit==true ||
                                             command_autocommit==true))
         {
             sqlcommitimplicit();
         }
         else
         {
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
     }
     break;
     case CMD_DELETE:
     {
         if (results.statementStatus==STATUS_OK)
         {
             std::stringstream tag;
             tag << "DELETE " << results.statementResults.size();
             putCommandComplete((char *)tag.str().c_str());
         }
         else
         {
             sqlrollbackimplicit();
             errorStatus(results.statementStatus);
             return;
         }
         if (isintransactionblock==false && (session_isautocommit==true ||
                                             command_autocommit==true))
         {
             sqlcommitimplicit();
         }
         else
         {
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
     }
     break;
     case CMD_BEGIN:
         if (transactionPtr==NULL)
         {
             transactionPtr = new class Transaction(taPtr, schemaPtr->domainid);
             isintransactionblock=true;
             putCommandComplete("BEGIN");
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
         else
         {
             putNoticeResponse("WARNING", "25001", "there is already a transaction in progress");
             putCommandComplete("BEGIN");
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
         break;
     case CMD_COMMIT:
         if (transactionPtr != NULL)
         {
             isintransactionblock=false;
             sqlcommitexplicit();
         }
         else
         {
             putNoticeResponse("WARNING", "25P01", "there is no transaction in progress");
             putCommandComplete("COMMIT");
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
         break;
     case CMD_ROLLBACK:
         if (transactionPtr != NULL)
         {
             isintransactionblock=false;
             sqlrollbackexplicit();
         }
         else
         {
             putNoticeResponse("WARNING", "25P01", "there is no transaction in progress");
             putCommandComplete("ROLLBACK");
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
         break;
     case CMD_SET:
         break;
     case CMD_STOREDPROCEDURE:
     {
         if (results.statementStatus==STATUS_OK)
         {
             putRowDescription();
             putDataRows();
             std::stringstream tag;
             tag << "SELECT " << results.selectResults.size();
             putCommandComplete((char *)tag.str().c_str());
         }
         else
         {
             sqlrollbackimplicit();
             errorStatus(results.statementStatus);
             return;
         }
         if (isintransactionblock==false && (session_isautocommit==true ||
                                             command_autocommit==true))
         {
             sqlcommitimplicit();
         }
         else
         {
             if (writesocket()==-1)
             {
                 closesocket(*taPtr);
             }
         }
     }
     break;
     default:
         printf("%s %i anomaly cmdtype %i statementStatus %li\n", __FILE__,
                __LINE__, results.cmdtype, results.statementStatus);
     }
 }
void Pg::continuePgRollbackexplicit (int64_t entrypoint, void * statePtr) virtual
continuation function after explicit rollback
explicit commit is sent as ROLLBACK statement within transaction
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implements ApiInterface.
Definition at line 1499 of file Pg.cc.
References closesocket(), logfile, outbuf, putCommandComplete(), state, STATE_EXITING, ApiInterface::statementPtr, ApiInterface::taPtr, ApiInterface::transactionPtr, and writesocket().
Referenced by sqlrollbackexplicit().
 {
     if (transactionPtr != NULL)
     {
         delete transactionPtr;
         transactionPtr=NULL;
     }
     if (state==STATE_EXITING)
     {
         if (statementPtr==NULL)
         {
             fprintf(logfile, "%s %i deleting this %p\n", __FILE__, __LINE__,
                     this);
             delete this;
         }
         return;
     }
     putCommandComplete("ROLLBACK");
     if (writesocket()==-1)
     {
         closesocket(*taPtr);
     }
     outbuf.clear();
 }
void Pg::continuePgRollbackimplicit (int64_t entrypoint, void * statePtr) virtual
continuation function after implicit rollback
implicit rollback done generally after a failure of some kind which forces a rollback
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implements ApiInterface.
Definition at line 1476 of file Pg.cc.
References logfile, outbuf, state, STATE_EXITING, ApiInterface::statementPtr, and ApiInterface::transactionPtr.
Referenced by sqlrollbackimplicit().
 {
     outbuf.clear();
     if (transactionPtr != NULL)
     {
         delete transactionPtr;
         transactionPtr=NULL;
     }
     if (state==STATE_EXITING)
     {
         if (statementPtr==NULL)
         {
             fprintf(logfile, "%s %i deleting this %p\n", __FILE__, __LINE__,
                     this);
             delete this;
         }
         return;
     }
 }
void Pg::doit () inline virtual
Implements ApiInterface.
Definition at line 68 of file Pg.h.
     {
         ;
     }
void Pg::errorStatus (int64_t status)
output error based on Transaction::resultCode
Parameters
status value from Transaction::resultCode
Definition at line 1595 of file Pg.cc.
References APISTATUS_LOCK, APISTATUS_NOTOK, APISTATUS_UNIQUECONSTRAINT, and putErrorResponse().
Referenced by continuePgFunc().
 {
     switch (status)
     {
     case APISTATUS_NOTOK:
         putErrorResponse("ERROR", "42000",
                          "generic InfiniSQL error");
         break;
     case APISTATUS_UNIQUECONSTRAINT:
         putErrorResponse("ERROR", "23000", "integrity_constraint_violation");
         break;
     case APISTATUS_LOCK:
         putErrorResponse("ERROR", "55P03", "lock not available");
         break;
     default:
         printf("%s %i anomaly %li\n", __FILE__, __LINE__, status);
         putErrorResponse("ERROR", "42000",
                          "syntax_error_or_access_rule_violation");
     }
 }
void Pg::executeStatement (string & stmtstr)
tokenize, parse, compile and execute SQL query
Parameters
stmtstr query string
Definition at line 836 of file Pg.cc.
References CMD_STOREDPROCEDURE, command_autocommit, ApiInterface::continuePgFunc(), Statement::execute(), procedureprefix, putErrorResponse(), Statement::queries, Statement::resolveTableFields(), ApiInterface::results, schemaPtr, sqlrollbackimplicit(), Larxer::statementPtr, ApiInterface::statementPtr, ApiInterface::taPtr, and ApiInterface::transactionPtr.
Referenced by cont().
 {
     class Larxer lx((char *)stmtstr.c_str(), taPtr, schemaPtr);
     if (lx.statementPtr==NULL)
     {
         putErrorResponse("ERROR", "42601", "syntax error");
         return;
     }
     statementPtr=lx.statementPtr;
     if (statementPtr->resolveTableFields()==false)
     {
         sqlrollbackimplicit();
         putErrorResponse("ERROR", "42704", "table or column does not exist");
         delete statementPtr;
         return;
     }
     if (statementPtr->queries[0].type==CMD_STOREDPROCEDURE)
     {
         statementPtr->queries[0].storedProcedure.insert(0, procedureprefix);
     }
     results = results_s();
     if (transactionPtr==NULL)
     {
         command_autocommit=true;
     }
     else
     {
         command_autocommit=false;
     }
     statementPtr->execute(this, &ApiInterface::continuePgFunc, 1, transactionPtr,
                           transactionPtr, vector<string>());
 }
bool Pg::get (int16_t * val)
read 16bit integer from inbound message string
Parameters
val retrieve buffer
Returns
success or failure
Definition at line 474 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(int16_t) > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     memcpy(val, &inbuf[pos], sizeof(int16_t));
     *val = be16toh(*val);
     pos += sizeof(int16_t);
     return true;
 }
bool Pg::get (int32_t * val)
read 32bit integer from inbound message string
Parameters
val retrieve buffer
Returns
success or failure
Definition at line 489 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(int32_t) > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     memcpy(val, &inbuf[pos], sizeof(int32_t));
     *val = be32toh(*val);
     pos += sizeof(int32_t);
     return true;
 }
bool Pg::get (int64_t * val)
read 64bit integer from inbound message string
Parameters
val retrieve buffer
Returns
success or failure
Definition at line 504 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(int64_t) > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     memcpy(val, &inbuf[pos], sizeof(int64_t));
     *val = be64toh(*val);
     pos += sizeof(int64_t);
     return true;
 }
bool Pg::get (vector< int16_t > & val, size_t nelem)
read list of 16bit integers from inbound message string
Parameters
val retrieve buffer
nelem number of elements
Returns
success or failure
Definition at line 519 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(int16_t)*nelem > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     for (size_t n=0; n < nelem; n++)
     {
         int16_t elem;
         memcpy(&elem, &inbuf[pos], sizeof(int16_t));
         elem = be16toh(elem);
         val.push_back(elem);
         pos += sizeof(int16_t);
     }
     return true;
 }
bool Pg::get (vector< int32_t > & val, size_t nelem)
read array of 32bit integers from inbound message string
Parameters
val retrieve buffer
nelem number of elements
Returns
success or failure
Definition at line 539 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(int32_t)*nelem > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     for (size_t n=0; n < nelem; n++)
     {
         int32_t elem;
         memcpy(&elem, &inbuf[pos], sizeof(int32_t));
         elem = be32toh(elem);
         val.push_back(elem);
         pos += sizeof(int32_t);
     }
     return true;
 }
bool Pg::get (vector< int64_t > & val, size_t nelem)
read array of 64bit integers inbound message string
Parameters
val retrieve buffer
nelem number of elements
Returns
success or failure
Definition at line 559 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(int64_t)*nelem > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     for (size_t n=0; n < nelem; n++)
     {
         int64_t elem;
         memcpy(&elem, &inbuf[pos], sizeof(int64_t));
         elem = be64toh(elem);
         val.push_back(elem);
         pos += sizeof(int64_t);
     }
     return true;
 }
bool Pg::get (char * val)
read Byte1 from inbound message string
Parameters
val retrieve buffer
Returns
success or failure
Definition at line 580 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(char) > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     *val = inbuf[pos];
     pos += sizeof(char);
     return true;
 }
bool Pg::get (string & val, size_t nelem)
read Byten from inbound message string
Parameters
val retrieve buffer
nelem number of bytes (n)
Returns
success or failure
Definition at line 595 of file Pg.cc.
References inbuf, and pos.
 {
     if (pos + sizeof(char)*nelem > inbuf.size())
     {
         // not enough room in inbuf to get requested data
         return false;
     }
     val = inbuf.substr(pos, nelem);
     pos += sizeof(char)*nelem;
     return true;
 }
bool Pg::get (string & val)
read String (c-style) from inbound message string
Parameters
val retrieve buffer
Returns
successor failure
Definition at line 610 of file Pg.cc.
References inbuf, and pos.
 {
     size_t endpos = inbuf.find('\0', pos);
     if (endpos == string::npos)
     {
         return false;
     }
     val = inbuf.substr(pos, endpos-pos);
     pos = endpos+1;
     return 1;
 }
short Pg::initcmd (string & newdata)
read new command from socket
Parameters
newdata buffer for command string
Returns
-1: bad input, 0: not completely received, -1: complete
Definition at line 416 of file Pg.cc.
References inbuf, logfile, pgcmdtype, size, sockfd, state, and STATE_BEGIN.
Referenced by cont().
 {
     if (!size) // i don't have initial data yet
     {
         if (inbuf.size())
         {
             inbuf.append(newdata);
             newdata.swap(inbuf);
             inbuf.clear();
         }
         if (newdata.size() < (state==STATE_BEGIN ? sizeof(size) :
                               sizeof(size)+1))
         {
             // wait for more data
             inbuf.append(newdata);
             return 0;
         }
         // got enough data initially, now set the header vars
         if (state==STATE_BEGIN)
         {
             memcpy(&size, &newdata[0], sizeof(size));
             size=be32toh(size);
             inbuf = newdata.substr(sizeof(size), string::npos);
         }
         else
         {
             pgcmdtype = newdata[0];
             memcpy(&size, &newdata[1], sizeof(size));
             size=be32toh(size);
             inbuf = newdata.substr(sizeof(size)+1, string::npos);
         }
     }
     else
     {
         inbuf.append(newdata);
     }
     //  already have initial data, see if the whole request received
     if (inbuf.size() + sizeof(size) == size)
     {
         // got whole thing
         return 1;
     }
     if (inbuf.size() + sizeof(size) < size)
     {
         // wait for more
         fprintf(logfile, "%s %i sockfd %i pgcmdtype %c inbuf.size() %lu sizeof(size) %lu size %u state %i '%s'\n", __FILE__, __LINE__, sockfd, pgcmdtype,
                 inbuf.size(), sizeof(size), size, state, inbuf.c_str());
         return 0;
     }
     // bogus data
     return -1;
 }
void Pg::pgclosesocket (class TransactionAgent & taRef, int socketfd) static
more socket closing-related activities
Parameters
taRef TransactionAgent
socketfd socket descriptor
Definition at line 394 of file Pg.cc.
References connectionsMutex, Topology::partitionAddress::epollfd, LISTENER_NONE, listenerTypes, logfile, TransactionAgent::myIdentity, NUMSOCKETS, TransactionAgent::Pgs, and socketAffinity.
Referenced by closesocket(), and TransactionAgent::TransactionAgent().
 {
 //  taRef.Pgs.erase(socketfd);
     // NEW WAY
     epoll_ctl(taRef.myIdentity.epollfd, EPOLL_CTL_DEL, socketfd, NULL);
     if (socketfd <= NUMSOCKETS)
     {
         pthread_mutex_lock(&connectionsMutex);
         socketAffinity[socketfd]=0;
         listenerTypes[socketfd]=LISTENER_NONE;
         pthread_mutex_unlock(&connectionsMutex);
     }
     else
     {
         fprintf(logfile, "%s %i fd %i > %i\n", __FILE__, __LINE__, socketfd,
                 NUMSOCKETS);
     }
     taRef.Pgs.erase(socketfd);
     close(socketfd);
 }
void Pg::put (int16_t val)
write data to outbound message buffer
Parameters
val 16bit integer
Definition at line 625 of file Pg.cc.
References outmsg.
Referenced by cont(), putAuthenticationOk(), putCommandComplete(), putDataRows(), putErrorResponse(), putNoticeResponse(), putParameterStatus(), putRowDescription(), and writesocket().
 {
     size_t curpos = outmsg.size();
     outmsg.resize(curpos + sizeof(int16_t));
     val = htobe16(val);
     memcpy(&outmsg[curpos], &val, sizeof(int16_t));
 }
void Pg::put (int32_t val)
write data to outbound message buffer
Parameters
val 32bit integer
Definition at line 633 of file Pg.cc.
References outmsg.
 {
     size_t curpos = outmsg.size();
     outmsg.resize(curpos + sizeof(int32_t));
     val = htobe32(val);
     memcpy(&outmsg[curpos], &val, sizeof(int32_t));
 }
void Pg::put (int64_t val)
write data to outbound message buffer
Parameters
val 64bit integer
Definition at line 641 of file Pg.cc.
References outmsg.
 {
     size_t curpos = outmsg.size();
     outmsg.resize(curpos + sizeof(int64_t));
     val = htobe64(val);
     memcpy(&outmsg[curpos], &val, sizeof(int64_t));
 }
void Pg::put (vector< int16_t > & val)
write data to outbound message buffer
Parameters
val array of 16bit integers
Definition at line 649 of file Pg.cc.
References outmsg.
 {
     size_t curpos = outmsg.size();
     size_t nelem = val.size();
     outmsg.resize(curpos + sizeof(int16_t)*nelem);
     for (size_t n=0; n < nelem; n++)
     {
         int16_t elem = htobe16(val[n]);
         memcpy(&outmsg[curpos], &elem, sizeof(int16_t));
         curpos += sizeof(int16_t);
     }
 }
void Pg::put (vector< int32_t > & val)
write data to outbound message buffer
Parameters
val array of 32bit integers
Definition at line 663 of file Pg.cc.
References outmsg.
 {
     size_t curpos = outmsg.size();
     size_t nelem = val.size();
     outmsg.resize(curpos + sizeof(int32_t)*nelem);
     for (size_t n=0; n < nelem; n++)
     {
         int32_t elem = htobe32(val[n]);
         memcpy(&outmsg[curpos], &elem, sizeof(int32_t));
         curpos += sizeof(int32_t);
     }
 }
void Pg::put (vector< int64_t > & val)
write data to outbound message buffer
Parameters
val array of 64bit integers
Definition at line 677 of file Pg.cc.
References outmsg.
 {
     size_t curpos = outmsg.size();
     size_t nelem = val.size();
     outmsg.resize(curpos + sizeof(int64_t)*nelem);
     for (size_t n=0; n < nelem; n++)
     {
         int64_t elem = htobe64(val[n]);
         memcpy(&outmsg[curpos], &elem, sizeof(int64_t));
         curpos += sizeof(int64_t);
     }
 }
void Pg::put (char val)
write data to outbound message buffer
Parameters
val Byte1
Definition at line 692 of file Pg.cc.
References outmsg.
 {
     size_t curpos = outmsg.size();
     outmsg.resize(curpos + sizeof(char));
     outmsg[curpos] = val;
 }
void Pg::put (char * val, size_t nelem)
write Byten to outbound message buffer
Parameters
val bytes
nelem number of bytes (n)
Definition at line 700 of file Pg.cc.
References outmsg.
 {
     outmsg.append(val, nelem);
 }
void Pg::put (string & val)
write data to outbound message buffer
Parameters
val String (c-style)
Definition at line 705 of file Pg.cc.
References outmsg.
 {
     outmsg.append(val);
     outmsg.append(1, '\0');
 }
void Pg::put (char * val)
write data to outbound message buffer
Parameters
val string literal
Definition at line 711 of file Pg.cc.
References outmsg.
 {
     outmsg.append(val);
     outmsg.append(1, '\0');
 }
void Pg::putAuthenticationOk ()
write authenticationok status to outbound message buffer
Definition at line 1542 of file Pg.cc.
References closesocket(), inbuf, outcmd, put(), putParameterStatus(), replymsg(), size, startupArgs, state, STATE_ESTABLISHED, ApiInterface::taPtr, and writesocket().
Referenced by continueLogin().
 {
     // AuthenticationOk
     outcmd = 'R';
     put((int32_t)0);
     replymsg();
     putParameterStatus("application_name", "");
     putParameterStatus("client_encoding", "LATIN1");
     putParameterStatus("DateStyle", "ISO, MDY");
     putParameterStatus("integer_datetimes", "on");
     putParameterStatus("IntervalStyle", "postgres");
     putParameterStatus("is_superuser", "off");
     putParameterStatus("server_encoding", "LATIN1");
     putParameterStatus("server_version", "9.2.4");
     putParameterStatus("session_authorization",
                        (char *)startupArgs["username"].c_str());
     putParameterStatus("standard_conforming_strings", "on");
     tzset();
     // long TimeZone name from tzname[2] having problems compiling
     putParameterStatus("TimeZone", tzname[1]);
     //    putParameterStatus("TimeZone", "US/Pacific");
     // forget key data for now, but put something here
     outcmd = 'K';
     put(int32_t(1));
     put(int32_t(2));
     replymsg();
     // ReadyForQuery
     outcmd = 'Z';
     put((char)'I');
     replymsg();
     if (writesocket()==-1)
     {
         closesocket(*taPtr);
         return;
     }
     state = STATE_ESTABLISHED;
     size = 0;
     inbuf.clear();
 }
void Pg::putCommandComplete (char * tag)
write completed command to outbound message buffer
Parameters
tag command name
Definition at line 1134 of file Pg.cc.
References outcmd, put(), and replymsg().
Referenced by cont(), continuePgCommitexplicit(), continuePgFunc(), and continuePgRollbackexplicit().
 {
     outcmd='C';
     put(tag);
     replymsg();
 }
void Pg::putDataRows ()
write rows to outbound message buffer
Definition at line 1316 of file Pg.cc.
References BOOL, CHAR, CHARX, Transaction::fieldValues, FLOAT, INT, outcmd, put(), replymsg(), ApiInterface::results, ApiInterface::results_s::selectFields, ApiInterface::results_s::selectResults, UINT, and VARCHAR.
Referenced by continuePgFunc().
 {
     boost::unordered_map< uuRecord_s, vector<fieldValue_s> >::const_iterator it;
     for (it = results.selectResults.begin(); it != results.selectResults.end();
          it++)
     {
         outcmd='D';
         int16_t numfields = (int16_t)results.selectFields.size();
         put(numfields);
         const vector<fieldValue_s> &fieldValues = it->second;
         for (int16_t n=0; n < numfields; n++)
         {
             if (fieldValues[n].isnull==true)
             {
                 put((int32_t)-1);
                 continue;
             }
             switch (results.selectFields[n].type)
             {
             case INT:
             {
                 char val[21]; // length of smallest int64_t + \0
                 int32_t len=sprintf(val, "%li", fieldValues[n].value.integer);
                 put(len);
                 put(val, len);
             }
             break;
             case UINT:
             {
                 char val[21]; // length of largest uint64_t + \0
                 int32_t len=sprintf(val, "%lu", fieldValues[n].value.uinteger);
                 put(len);
                 put(val, len);
             }
             break;
             case BOOL:
                 put((int32_t)1);
                 if (fieldValues[n].value.boolean==true)
                 {
                     put('t');
                 }
                 else
                 {
                     put('f');
                 }
                 break;
             case FLOAT:
             {
                 std::stringstream val;
                 val << (double)fieldValues[n].value.floating;
                 if ((double)fieldValues[n].value.floating /
                     (int64_t)fieldValues[n].value.floating == 1)
                 {
                     val << ".0";
                 }
                 int32_t len=val.str().size();
                 put((int32_t)len);
                 put((char *)val.str().c_str(), len);
             }
             break;
             case CHAR:
                 put((int32_t)1);
                 put(fieldValues[n].value.character);
                 break;
             case CHARX:
             {
                 int32_t len = fieldValues[n].str.size();
                 put((int32_t)len);
                 put((char *)fieldValues[n].str.c_str(), len);
             }
             break;
             case VARCHAR:
             {
                 int32_t len = fieldValues[n].str.size();
                 put((int32_t)len);
                 put((char *)fieldValues[n].str.c_str(), len);
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                        results.selectFields[n].type);
                 return;
             }
         }
         replymsg();
     }
 }
void Pg::putErrorResponse (char * severity, char * code, char * message)
write error to outbound message buffer
Parameters
severity error severity
code error code
message error message
Definition at line 1141 of file Pg.cc.
References closesocket(), outcmd, put(), replymsg(), ApiInterface::taPtr, and writesocket().
Referenced by cont(), continueLogin(), errorStatus(), and executeStatement().
 {
     outcmd='E';
     put('S');
     put(severity);
     put('C');
     put(code);
     put('M');
     put(message);
     put(char(0));
     replymsg();
     if (writesocket()==-1)
     {
         closesocket(*taPtr);
     }
 }
void Pg::putNoticeResponse (char * severity, char * code, char * message)
write notice to outbound message buffer
Parameters
severity notice severity
code notice code
message notice message
Definition at line 1160 of file Pg.cc.
References outcmd, put(), and replymsg().
Referenced by continuePgFunc().
 {
     outcmd='N';
     put('S');
     put(severity);
     put('C');
     put(code);
     put('M');
     put(message);
     put(char(0));
     replymsg();
 }
void Pg::putParameterStatus (char * name, char * value)
write server parameters in status message to outbound message buffer
Parameters
name parameter name
value parameter value
Definition at line 1587 of file Pg.cc.
References outcmd, put(), and replymsg().
Referenced by putAuthenticationOk().
 {
     outcmd='S';
     put(name);
     put(value);
     replymsg();
 }
void Pg::putRowDescription ()
write field names to outbound message buffer
Definition at line 1254 of file Pg.cc.
References BOOL, BOOLOID, BPCHAROID, CHAR, CHAROID, CHARX, FLOAT, FLOAT8OID, INT, INT8OID, outcmd, put(), replymsg(), ApiInterface::results, ApiInterface::results_s::selectFields, UINT, VARCHAR, and VARCHAROID.
Referenced by continuePgFunc().
 {
     outcmd='T';
     int16_t numfields = (int16_t)results.selectFields.size();
     put(numfields);
     for (int16_t n=0; n < numfields; n++)
     {
         put(results.selectFields[n].name);
         put((int32_t)0);
         put((int16_t)0);
         switch (results.selectFields[n].type)
         {
         case INT:
             put((int32_t)INT8OID);
             put((int16_t)8);
             break;
         case UINT:
             put((int32_t)INT8OID);
             put((int16_t)8);
             break;
         case BOOL:
             put((int32_t)BOOLOID);
             put((int16_t)1);
             break;
         case FLOAT:
             put((int32_t)FLOAT8OID);
             put((int16_t)8);
             break;
         case CHAR:
             put((int32_t)CHAROID);
             put((int16_t)1);
             break;
         case CHARX:
             put((int32_t)BPCHAROID);
             put((int16_t)-2);
             break;
         case VARCHAR:
             put((int32_t)VARCHAROID);
             put((int16_t)-2);
             break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                    results.selectFields[n].type);
             return;
         }
         put((int32_t)0);
         put((int16_t)0); // text format code
     }
     replymsg();
 }
bool Pg::readsocket (string & buf)
read from socket
Parameters
buf buffer for data read
Returns
true: something read (or spurious epoll event), false error or EOF
Definition at line 343 of file Pg.cc.
References sockfd.
Referenced by cont().
 {
     char in[8192];
     while (1)
     {
         ssize_t readed = recv(sockfd, in, 8192, 0);
         if (readed > 0)
         {
             buf.append(in, readed);
         }
         else if (readed == -1)
         {
             if (errno==EAGAIN || errno==EWOULDBLOCK)
             {
                 return true;
             }
             return false;
         }
         else
         {
             // EOF
             return false;
         }
     }
 }
void Pg::replymsg ()
put message for reply into outbound buffer
Definition at line 718 of file Pg.cc.
References outbuf, outcmd, and outmsg.
Referenced by cont(), putAuthenticationOk(), putCommandComplete(), putDataRows(), putErrorResponse(), putNoticeResponse(), putParameterStatus(), putRowDescription(), and writesocket().
 {
     uint32_t osize = htobe32((uint32_t)outmsg.size() + sizeof(osize));
     string prependstr(sizeof(osize) + sizeof(outcmd), '\0');
     prependstr[0] = outcmd;
     memcpy(&prependstr[1], &osize, sizeof(osize));
     outmsg.insert(0, prependstr);
     outbuf.append(outmsg);
     outmsg.clear();
 }
short Pg::rewritesocket ()
write stored buffer to socket
called after socket becomes writable
Returns
see writesocket
Definition at line 789 of file Pg.cc.
References Topology::partitionAddress::epollfd, TransactionAgent::myIdentity, sockfd, ApiInterface::taPtr, and writesocket().
Referenced by cont().
 {
     switch (writesocket())
     {
     case -1:
         return -1;
 //        break;
     case 0:
     {
         struct epoll_event epevent;
         epevent.events = EPOLLIN | EPOLLHUP | EPOLLET;
         epevent.data.fd=sockfd;
         epoll_ctl(taPtr->myIdentity.epollfd, EPOLL_CTL_MOD, sockfd, &epevent);
         return 0;
     }
     break;
     case 1:
         return 1;
 //        break;
     default:
         printf("%s %i anomaly WTF\n", __FILE__, __LINE__);
         return -1;
     }
 }
bool Pg::sqlbegin ()
appears to be orphan
Returns
Definition at line 1243 of file Pg.cc.
References ApiInterface::transactionPtr.
 {
     if (transactionPtr != NULL)
     {
         return false;
     }
     transactionPtr = new class Transaction(taPtr, domainid);
     return true;
 }
void Pg::sqlcommitexplicit ()
explicit commit
explicit commit is sent as COMMIT or END at end of transaction
Definition at line 1190 of file Pg.cc.
References Transaction::commit(), continuePgCommitexplicit(), ApiInterface::continuePgCommitexplicit(), Transaction::reentryCmd, Transaction::reentryFuncPtr, Transaction::reentryObject, Transaction::reentryState, and ApiInterface::transactionPtr.
Referenced by continuePgFunc().
 {
     if (transactionPtr==NULL)
     {
         continuePgCommitexplicit(1, NULL);
         return;
     }
     transactionPtr->reentryObject = this;
     transactionPtr->reentryFuncPtr = &ApiInterface::continuePgCommitexplicit;
     transactionPtr->reentryCmd = 1;
     transactionPtr->reentryState = NULL;
     transactionPtr->commit();
 }
void Pg::sqlcommitimplicit ()
implicit commit
implicit commit done after a single statement is entered, not in a transaction already, and session_isautocommit is true
Definition at line 1174 of file Pg.cc.
References Transaction::commit(), continuePgCommitimplicit(), ApiInterface::continuePgCommitimplicit(), Transaction::reentryCmd, Transaction::reentryFuncPtr, Transaction::reentryObject, Transaction::reentryState, and ApiInterface::transactionPtr.
Referenced by continuePgFunc().
 {
     if (transactionPtr==NULL)
     {
         continuePgCommitimplicit(1, NULL);
         return;
     }
     transactionPtr->reentryObject = this;
     transactionPtr->reentryFuncPtr = &ApiInterface::continuePgCommitimplicit;
     transactionPtr->reentryCmd = 1;
     transactionPtr->reentryState = NULL;
     transactionPtr->commit();
 }
void Pg::sqlrollbackexplicit ()
explicit rollback
explicit commit is sent as ROLLBACK statement within transaction
Definition at line 1227 of file Pg.cc.
References continuePgRollbackexplicit(), ApiInterface::continuePgRollbackexplicit(), Transaction::reentryCmd, Transaction::reentryFuncPtr, Transaction::reentryObject, Transaction::reentryState, Transaction::rollback(), and ApiInterface::transactionPtr.
Referenced by continuePgFunc().
 {
     if (transactionPtr==NULL)
     {
         continuePgRollbackexplicit(1, NULL);
         return;
     }
     transactionPtr->reentryObject = this;
     transactionPtr->reentryFuncPtr = &ApiInterface::continuePgRollbackexplicit;
     transactionPtr->reentryCmd = 1;
     transactionPtr->reentryState = NULL;
     transactionPtr->rollback();
 }
void Pg::sqlrollbackimplicit ()
implicit rollback
implicit rollback done generally after a failure of some kind which forces a rollback
Definition at line 1206 of file Pg.cc.
References continuePgRollbackimplicit(), ApiInterface::continuePgRollbackimplicit(), isintransactionblock, Transaction::reentryCmd, Transaction::reentryFuncPtr, Transaction::reentryObject, Transaction::reentryState, Transaction::rollback(), state, STATE_ABORTED, and ApiInterface::transactionPtr.
Referenced by continuePgFunc(), and executeStatement().
 {
     if (isintransactionblock==true)
     {
         state=STATE_ABORTED;
     }
     if (transactionPtr==NULL)
     {
         continuePgRollbackimplicit(1, NULL);
         return;
     }
     transactionPtr->reentryObject = this;
     transactionPtr->reentryFuncPtr = &ApiInterface::continuePgRollbackimplicit;
     transactionPtr->reentryCmd = 1;
     transactionPtr->reentryState = NULL;
     transactionPtr->rollback();
 }
short Pg::writesocket ()
write response messages to socket
if not all data can be written, store data until EPOLLOUT event is received
Returns
-1: socket error, 0: send complete, 1: data remaining to send
Definition at line 731 of file Pg.cc.
References Topology::partitionAddress::epollfd, TransactionAgent::myIdentity, outbuf, outcmd, put(), replymsg(), sockfd, state, STATE_ABORTED, STATE_ESTABLISHED, ApiInterface::taPtr, and ApiInterface::transactionPtr.
Referenced by cont(), continuePgCommitexplicit(), continuePgCommitimplicit(), continuePgFunc(), continuePgRollbackexplicit(), putAuthenticationOk(), putErrorResponse(), and rewritesocket().
 {
     if (state==STATE_ESTABLISHED)
     {
         outcmd='Z';
         if (transactionPtr==NULL)
         {
             put('I');
         }
         else
         {
             put('T');
         }
         replymsg();
     }
     else if (state==STATE_ABORTED)
     {
         outcmd='Z';
         put('E');
         replymsg();
     }
     size_t curpos = 0;
     size_t outbuflen = outbuf.size();
     while (curpos < outbuflen)
     {
         ssize_t sent = send(sockfd, &outbuf[curpos],
                             (outbuflen-curpos) >= 8192 ? 8192 :
                             outbuflen-curpos, 0);
         if (sent == -1)
         {
             if (errno==EAGAIN || errno==EWOULDBLOCK)
             {
                 string backgroundstr = outbuf.substr(curpos, string::npos);
                 outbuf.swap(backgroundstr);
                 struct epoll_event epevent;
                 epevent.events = EPOLLOUT | EPOLLHUP | EPOLLET;
                 epevent.data.fd = sockfd;
                 epoll_ctl(taPtr->myIdentity.epollfd, EPOLL_CTL_MOD, sockfd,
                           &epevent);
                 return 1;
             }
             // some real error, so return & close socket
             return -1;
         }
         curpos += sent;
     }
     outbuf.clear();
     return 0;
 }
Member Data Documentation
bool Pg::command_autocommit
Definition at line 466 of file Pg.h.
Referenced by continuePgFunc(), and executeStatement().
std::string Pg::inbuf
Definition at line 449 of file Pg.h.
Referenced by cont(), get(), initcmd(), and putAuthenticationOk().
bool Pg::isintransactionblock
Definition at line 467 of file Pg.h.
Referenced by cont(), continuePgFunc(), and sqlrollbackimplicit().
std::string Pg::outbuf
Definition at line 453 of file Pg.h.
Referenced by cont(), continuePgCommitexplicit(), continuePgRollbackexplicit(), continuePgRollbackimplicit(), replymsg(), and writesocket().
char Pg::outcmd
Definition at line 451 of file Pg.h.
Referenced by cont(), putAuthenticationOk(), putCommandComplete(), putDataRows(), putErrorResponse(), putNoticeResponse(), putParameterStatus(), putRowDescription(), replymsg(), and writesocket().
std::string Pg::outmsg
Definition at line 452 of file Pg.h.
Referenced by put(), and replymsg().
char Pg::pgcmdtype
Definition at line 447 of file Pg.h.
Referenced by cont(), and initcmd().
size_t Pg::pos
Definition at line 450 of file Pg.h.
Referenced by cont(), and get().
std::string Pg::procedureprefix
Definition at line 461 of file Pg.h.
Referenced by continueLogin(), and executeStatement().
class Schema* Pg::schemaPtr
Definition at line 456 of file Pg.h.
Referenced by cont(), continueLogin(), and executeStatement().
bool Pg::session_isautocommit
Definition at line 464 of file Pg.h.
Referenced by continuePgFunc().
uint32_t Pg::size
Definition at line 448 of file Pg.h.
Referenced by cont(), initcmd(), and putAuthenticationOk().
int Pg::sockfd
Definition at line 445 of file Pg.h.
Referenced by closesocket(), cont(), initcmd(), Pg(), readsocket(), rewritesocket(), and writesocket().
boost::unordered_map<std::string, std::string> Pg::startupArgs
Definition at line 459 of file Pg.h.
Referenced by cont(), and putAuthenticationOk().
states_e Pg::state
Definition at line 444 of file Pg.h.
Referenced by closesocket(), cont(), continuePgCommitexplicit(), continuePgCommitimplicit(), continuePgFunc(), continuePgRollbackexplicit(), continuePgRollbackimplicit(), initcmd(), putAuthenticationOk(), sqlrollbackimplicit(), and writesocket().
int64_t Pg::userid
Definition at line 455 of file Pg.h.
Referenced by continueLogin().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Pg.h
/home/infinisql/build/infinisql/infinisqld/Pg.cc