InfiniSQL: Message Class Reference
Message Class Reference
create Message object
#include <Message.h>
Classes
struct message_s
Message POD (serializable by memcpy) data members.
Public Member Functions
Message ()
virtual ~Message ()
size_t size ()
get Message size
std::string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
string * sermsg ()
return serialized Message variant string
void setEnvelope (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
put addresses in Message variant envelope
Static Public Member Functions
static class Message * des (string *serstr)
deserialize entire message
Public Attributes
__int128 nextmsg
message_s messageStruct
Detailed Description
create Message object
Returns
Definition at line 85 of file Message.h.
Constructor & Destructor Documentation
Message::Message ()
Definition at line 33 of file Message.cc.
 {
 }
Message::~Message () virtual
Definition at line 37 of file Message.cc.
 {
 }
Member Function Documentation
void Message::clear ()
clear contents of this
Definition at line 68 of file Message.cc.
References messageStruct.
Referenced by MessageSocket::clear(), MessageUserSchema::clear(), MessageDeadlock::clear(), MessageTransaction::clear(), MessageDispatch::clear(), MessageAckDispatch::clear(), MessageApply::clear(), and MessageAckApply::clear().
 {
     messageStruct={};
 }
class Message * Message::des (string * serstr) static
deserialize entire message
Parameters
serstr string of serialized message
Returns
deserialized message
Definition at line 73 of file Message.cc.
References SerializedMessage::getpayloadtype(), PAYLOADACKAPPLY, PAYLOADACKDISPATCH, PAYLOADAPPLY, PAYLOADCOMMITROLLBACK, PAYLOADDEADLOCK, PAYLOADDISPATCH, PAYLOADMESSAGE, PAYLOADSOCKET, PAYLOADSUBTRANSACTION, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, unpack(), MessageSocket::unpack(), MessageUserSchema::unpack(), MessageDeadlock::unpack(), MessageSubtransactionCmd::unpack(), MessageCommitRollback::unpack(), MessageDispatch::unpack(), MessageAckDispatch::unpack(), MessageApply::unpack(), and MessageAckApply::unpack().
 {
     message_s tmpheader;
     memcpy(&tmpheader, &serstr->at(0), sizeof(tmpheader));
     class Message *msg;
     class SerializedMessage serobj(serstr);
     switch(serobj.getpayloadtype())
     {
     case PAYLOADMESSAGE:
         msg = (class Message *)new class Message;
         msg->unpack(serobj);
         break;
     case PAYLOADSOCKET:
         msg = (class Message *)new class MessageSocket;
         ((class MessageSocket *)msg)->unpack(serobj);
         break;
     case PAYLOADUSERSCHEMA:
         msg = (class Message *)new class MessageUserSchema;
         ((class MessageUserSchema *)msg)->unpack(serobj);
         break;
     case PAYLOADDEADLOCK:
         msg = (class Message *)new class MessageDeadlock;
         ((class MessageDeadlock *)msg)->unpack(serobj);
         break;
     case PAYLOADSUBTRANSACTION:
         msg = (class Message *)new class MessageSubtransactionCmd;
         ((class MessageSubtransactionCmd *)msg)->unpack(serobj);
         break;
     case PAYLOADCOMMITROLLBACK:
         msg = (class Message *)new class MessageCommitRollback;
         ((class MessageCommitRollback *)msg)->unpack(serobj);
         break;
     case PAYLOADDISPATCH:
         msg = (class Message *)new class MessageDispatch;
         ((class MessageDispatch *)msg)->unpack(serobj);
         break;
     case PAYLOADACKDISPATCH:
         msg = (class Message *)new class MessageAckDispatch;
         ((class MessageAckDispatch *)msg)->unpack(serobj);
         break;
     case PAYLOADAPPLY:
         msg = (class Message *)new class MessageApply;
         ((class MessageApply *)msg)->unpack(serobj);
         break;
     case PAYLOADACKAPPLY:
         msg = (class Message *)new class MessageAckApply;
         ((class MessageAckApply *)msg)->unpack(serobj);
         break;
     default:
         printf("%s %i anomaly %i\n", __FILE__, __LINE__, tmpheader.payloadtype);
         delete serstr;
         return NULL;
     }
     delete serstr;
     return msg;
 }
void Message::package (class SerializedMessage & serobj)
serialize this
Parameters
serobj SerializedMessage
Definition at line 58 of file Message.cc.
References messageStruct, and SerializedMessage::ser().
Referenced by MessageSocket::package(), MessageUserSchema::package(), MessageDeadlock::package(), MessageTransaction::package(), MessageDispatch::package(), MessageAckDispatch::package(), MessageApply::package(), MessageAckApply::package(), and ser().
 {
     serobj.ser(messageStruct);
 }
string * Message::ser ()
create string with serialized message
Returns
serialized message string
Definition at line 46 of file Message.cc.
References SerializedMessage::data, SerializedMessage::getpayloadtype(), logfile, package(), and SerializedMessage::pos.
 {
     class SerializedMessage serobj(size());
     package(serobj);
     if (serobj.data->size() != serobj.pos)
     {
         fprintf(logfile, "%s %i ser %i size %lu pos %lu\n", __FILE__, __LINE__,
                 serobj.getpayloadtype(), serobj.data->size(), serobj.pos);
     }
     return serobj.data;
 }
string * Message::sermsg ()
return serialized Message variant string
Returns
serialized Message variant string
Definition at line 142 of file Message.cc.
References messageStruct, PAYLOADACKAPPLY, PAYLOADACKDISPATCH, PAYLOADAPPLY, PAYLOADCOMMITROLLBACK, PAYLOADDEADLOCK, PAYLOADDISPATCH, PAYLOADMESSAGE, PAYLOADSOCKET, PAYLOADSUBTRANSACTION, Message::message_s::payloadtype, and PAYLOADUSERSCHEMA.
Referenced by MboxProducer::sendMsg().
 {
     string *serstr;
     switch (messageStruct.payloadtype)
     {
     case PAYLOADMESSAGE:
         serstr=((class Message *)this)->ser();
         break;
     case PAYLOADSOCKET:
         serstr=((class MessageSocket *)this)->ser();
         break;
     case PAYLOADUSERSCHEMA:
         serstr=((class MessageUserSchema *)this)->ser();
         break;
     case PAYLOADDEADLOCK:
         serstr=((class MessageDeadlock *)this)->ser();
         break;
     case PAYLOADSUBTRANSACTION:
         serstr=((class MessageSubtransactionCmd *)this)->ser();
         break;
     case PAYLOADCOMMITROLLBACK:
         serstr=((class MessageCommitRollback *)this)->ser();
         break;
     case PAYLOADDISPATCH:
         serstr=((class MessageDispatch *)this)->ser();
         break;
     case PAYLOADACKDISPATCH:
         serstr=((class MessageAckDispatch *)this)->ser();
         break;
     case PAYLOADAPPLY:
         serstr=((class MessageApply *)this)->ser();
         break;
     case PAYLOADACKAPPLY:
         serstr=((class MessageAckApply *)this)->ser();
         break;
     default:
         printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                messageStruct.payloadtype);
         serstr=NULL;
     }
     return serstr;
 }
void Message::setEnvelope (const Topology::addressStruct & source, const Topology::addressStruct & dest, class Message & msg)
put addresses in Message variant envelope
Parameters
source source address
dest destination address
msg Message
Definition at line 197 of file Message.cc.
References Message::message_s::destAddr, messageStruct, and Message::message_s::sourceAddr.
Referenced by Mboxes::toActor(), and Mboxes::toPartition().
 {
     msg.messageStruct.sourceAddr = source;
     msg.messageStruct.destAddr = dest;
 }
size_t Message::size ()
get Message size
Returns
size in bytes
Definition at line 41 of file Message.cc.
References messageStruct, and SerializedMessage::sersize().
Referenced by ObGateway::ObGateway(), MessageSocket::size(), MessageUserSchema::size(), MessageDeadlock::size(), MessageTransaction::size(), MessageDispatch::size(), MessageAckDispatch::size(), MessageApply::size(), and MessageAckApply::size().
 {
     return SerializedMessage::sersize(messageStruct);
 }
void Message::unpack (SerializedMessage & serobj)
deserialize into this
Parameters
serobj SerializedMessage
Definition at line 63 of file Message.cc.
References SerializedMessage::des(), and messageStruct.
Referenced by des(), MessageSocket::unpack(), MessageUserSchema::unpack(), MessageDeadlock::unpack(), MessageTransaction::unpack(), MessageDispatch::unpack(), MessageAckDispatch::unpack(), MessageApply::unpack(), and MessageAckApply::unpack().
 {
     serobj.des(messageStruct);
 }
Member Data Documentation
message_s Message::messageStruct
Definition at line 158 of file Message.h.
Referenced by Transaction::abortCmd(), Engine::addcolumn(), UserSchemaMgr::addcolumn(), TransactionAgent::addcolumn(), Engine::apply(), Engine::background(), TopologyMgr::broadcastConfig(), UserSchemaMgr::changepassword(), TransactionAgent::changepassword(), Transaction::checkLock(), Transaction::checkSqlLock(), clear(), TransactionAgent::compile(), Transaction::continueCommitTransaction(), UserSchemaMgr::createdomain(), TransactionAgent::createdomain(), Engine::createschema(), UserSchemaMgr::createschema(), Engine::createtable(), UserSchemaMgr::createtable(), TransactionAgent::createtable(), UserSchemaMgr::createuser(), TransactionAgent::createuser(), DeadlockMgr::deadlock(), DeadlockMgr::DeadlockMgr(), UserSchemaMgr::deletedomain(), TransactionAgent::deletedomain(), Engine::deleteindex(), UserSchemaMgr::deleteindex(), Engine::deleteschema(), UserSchemaMgr::deleteschema(), Engine::deletetable(), UserSchemaMgr::deletetable(), UserSchemaMgr::deleteuser(), TransactionAgent::deleteuser(), SubTransaction::drainIndexLockQueue(), SubTransaction::drainRowLockQueue(), Engine::Engine(), TransactionAgent::handledispatch(), IbGateway::inbufhandler(), UserSchemaMgr::login(), TransactionAgent::login(), Mbox::Mbox(), MessageBatchSerialized::MessageBatchSerialized(), MessageDeadlock::MessageDeadlock(), MessageDispatch::MessageDispatch(), MessageSerialized::MessageSerialized(), MessageUserSchema::MessageUserSchema(), TransactionAgent::newprocedure(), ObGateway::ObGateway(), UserSchemaMgr::operationHandler(), package(), SubTransaction::processTransactionMessage(), replyTa(), SubTransaction::replyTransaction(), Transaction::rollback(), TransactionAgent::schemaBoilerplate(), MboxProducer::sendMsg(), Transaction::sendTransaction(), sermsg(), setEnvelope(), size(), TransactionAgent::TAaddcolumn(), TransactionAgent::TAcreateschema(), TransactionAgent::TAcreatetable(), TransactionAgent::TAdeleteindex(), TransactionAgent::TAdeleteschema(), TransactionAgent::TAdeletetable(), Mboxes::toAllOfType(), Mboxes::toAllOfTypeThisReplica(), TransactionAgent::TransactionAgent(), unpack(), MessageSocket::unpack(), UserSchemaMgr::UserSchemaMgr(), and TransactionAgent::usmReply().
__int128 Message::nextmsg
Definition at line 157 of file Message.h.
Referenced by Mbox::Mbox(), Mbox::receive(), MboxProducer::sendMsg(), and TransactionAgent::TransactionAgent().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc