InfiniSQL: MessageDispatch Class Reference
MessageDispatch Class Reference
Message variant for synchronous replication.
#include <Message.h>
Classes
struct dispatch_s
MessageDispatch POD (serializable by memcpy) data members.
struct record_s
Public Member Functions
MessageDispatch ()
virtual ~MessageDispatch ()
size_t size ()
get Message size
string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
size_t size ()
get Message size
std::string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
string * sermsg ()
return serialized Message variant string
void setEnvelope (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
put addresses in Message variant envelope
Public Attributes
dispatch_s dispatchStruct
boost::unordered_map< int64_t,
int64_t > pidsids
boost::unordered_map< int64_t,
std::vector< record_s > > records
Public Attributes inherited from Message
__int128 nextmsg
message_s messageStruct
Additional Inherited Members
Static Public Member Functions inherited from Message
static class Message * des (string *serstr)
deserialize entire message
Detailed Description
Message variant for synchronous replication.
Returns
Definition at line 552 of file Message.h.
Constructor & Destructor Documentation
MessageDispatch::MessageDispatch ()
Definition at line 545 of file Message.cc.
References Message::messageStruct, PAYLOADDISPATCH, Message::message_s::payloadtype, Message::message_s::topic, and TOPIC_DISPATCH.
 {
     messageStruct.topic = TOPIC_DISPATCH;
     messageStruct.payloadtype = PAYLOADDISPATCH;
 }
MessageDispatch::~MessageDispatch () virtual
Definition at line 551 of file Message.cc.
 {
 }
Member Function Documentation
void MessageDispatch::clear ()
clear contents of this
Definition at line 590 of file Message.cc.
References Message::clear(), dispatchStruct, pidsids, and records.
 {
     Message::clear();
     dispatchStruct={};
     pidsids.clear();
     records.clear();
 }
void MessageDispatch::package (class SerializedMessage & serobj)
serialize this
Parameters
serobj SerializedMessage
Definition at line 574 of file Message.cc.
References dispatchStruct, Message::package(), pidsids, records, and SerializedMessage::ser().
Referenced by ser().
 {
     Message::package(serobj);
     serobj.ser(dispatchStruct);
     serobj.ser(pidsids);
     serobj.ser(records);
 }
string * MessageDispatch::ser ()
create string with serialized message
Returns
serialized message string
Definition at line 562 of file Message.cc.
References SerializedMessage::data, SerializedMessage::getpayloadtype(), logfile, package(), and SerializedMessage::pos.
 {
     class SerializedMessage serobj(size());
     package(serobj);
     if (serobj.data->size() != serobj.pos)
     {
         fprintf(logfile, "%s %i ser %i size %lu pos %lu\n", __FILE__, __LINE__,
                 serobj.getpayloadtype(), serobj.data->size(), serobj.pos);
     }
     return serobj.data;
 }
size_t MessageDispatch::size ()
get Message size
Returns
size in bytes
Definition at line 555 of file Message.cc.
References dispatchStruct, pidsids, records, SerializedMessage::sersize(), and Message::size().
 {
     return Message::size() + SerializedMessage::sersize(dispatchStruct) +
         SerializedMessage::sersize(pidsids) +
         SerializedMessage::sersize(records);
 }
void MessageDispatch::unpack (SerializedMessage & serobj)
deserialize into this
Parameters
serobj SerializedMessage
Definition at line 582 of file Message.cc.
References SerializedMessage::des(), dispatchStruct, pidsids, records, and Message::unpack().
Referenced by Message::des().
 {
     Message::unpack(serobj);
     serobj.des(dispatchStruct);
     serobj.des(pidsids);
     serobj.des(records);
 }
Member Data Documentation
dispatch_s MessageDispatch::dispatchStruct
Definition at line 608 of file Message.h.
Referenced by clear(), TransactionAgent::handledispatch(), Transaction::makeMessageDispatch(), package(), size(), and unpack().
boost::unordered_map<int64_t, int64_t> MessageDispatch::pidsids
Definition at line 611 of file Message.h.
Referenced by clear(), Transaction::makeMessageDispatch(), package(), size(), and unpack().
boost::unordered_map< int64_t, std::vector<record_s> > MessageDispatch::records
Definition at line 613 of file Message.h.
Referenced by clear(), Transaction::makeMessageDispatch(), package(), size(), and unpack().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc