InfiniSQL: TransactionAgent Class Reference
TransactionAgent Class Reference
execute Transaction Agent actor
#include <TransactionAgent.h>
Public Member Functions
TransactionAgent (Topology::partitionAddress *myIdentityArg)
virtual ~TransactionAgent ()
void updateReplicas ()
update Topology of replicas
void ping (builtincmds_e cmd)
ping operation
void login (builtincmds_e cmd)
login
void logout (builtincmds_e cmd)
logout
void changepassword (builtincmds_e cmd)
change password
void createdomain (builtincmds_e cmd)
create domain
void createuser (builtincmds_e cmd)
create user
void deleteuser (builtincmds_e cmd)
delete user
void deletedomain (builtincmds_e cmd)
delete domain
void createschema (builtincmds_e cmd)
create schema
void createtable (builtincmds_e cmd)
create table
void addcolumn (builtincmds_e cmd)
add column
void deleteindex (builtincmds_e cmd)
delete index
void deletetable (builtincmds_e cmd)
delete table
void deleteschema (builtincmds_e cmd)
delete schema
void loadprocedure (builtincmds_e cmd)
load stored procedure
void compile (builtincmds_e cmd)
compile SQL statement
void schemaBoilerplate (builtincmds_e cmd, int builtin)
common code for many operations, such as login, create table, etc
void TAcreateschema ()
continuation function for createschema
void TAcreatetable ()
continuation for createtable
void TAaddcolumn ()
continuation for addcolumn
void TAdeleteindex ()
continuation for deleteindex
void TAdeletetable ()
continuation for deletetable
void TAdeleteschema ()
continuation for deleteschema
void TAloadprocedure ()
continuation for loadprocedure
void endOperation ()
delete Operation, remove from pendingOperations
void endConnection ()
finish TCP connection on raw interface (not SQL interface)
int64_t readSocket ()
read socket on raw interface
int64_t getnexttransactionid ()
generate unique, constantly increasing Transaction identifier
int64_t getnextapplierid ()
generate unique, constantly increasing Applier identifier
void badMessageHandler ()
stub for Message variants that can't be handled otherwise
void newprocedure (int64_t entrypoint)
called by loadprocedure
void newstatement ()
called by compile to compile SQL statement
void handledispatch ()
for replica to apply transaction changes synchronously
template<typename T >
void sendResponse (bool resending, int64_t resultCode, T response)
send raw protocol TCP responses to builtins, ping, login, logout, etc.
Static Public Member Functions
template<typename T >
static void usmReply (T actor, Topology::addressStruct &dest, class MessageUserSchema &msg)
reply MessageUserSchema to UserSchemaMgr
Public Attributes
int64_t operationid
int64_t domainid
int64_t userid
int64_t status
int64_t tainstance
class Message * msgrcv
REUSEMESSAGES domainidToSchemaMap domainidsToSchemata
Topology::partitionAddress myIdentity
class Mboxes mboxes
class Topology myTopology
int64_t instance
class Mbox * mymboxPtr
int epollfd
int sockfd
char payload [PAYLOADSIZE]
std::string * operation
socketAuthInfo loggedInUsers
int64_t argsize
char args [PAYLOADSIZE]
std::string argstring
sendLaterMap waitingToSend
operationMap pendingOperations
operationMap::iterator pendingOperationsIterator
int64_t operationidcounter
std::string domainName
std::vector< std::string > responseVector
class Operation * operationPtr
domainidToSchemaMap::iterator domainidsToSchemataIterator
boost::unordered_map< int64_t,
domainProceduresMap > domainidsToProcedures
boost::unordered_map< int64_t,
class Transaction * > Transactions
boost::unordered_map< int64_t,
class Applier * > Appliers
boost::unordered_map< int,
class Pg * > Pgs
int64_t nexttransactionid
int64_t nextapplierid
int batchSendCount
size_t myreplica
size_t mymember
Topology::addressStruct replicaAddress
std::vector
< Topology::addressStruct > replicaAddresses
boost::unordered_map< int64_t,
boost::unordered_map
< std::string, class Statement > > statements
Detailed Description
execute Transaction Agent actor
Parameters
myIdentityArg how to identify this
Definition at line 140 of file TransactionAgent.h.
Constructor & Destructor Documentation
TransactionAgent::TransactionAgent (Topology::partitionAddress * myIdentityArg)
Definition at line 33 of file TransactionAgent.cc.
References MessageAckApply::ackapplyStruct, MessageAckDispatch::ackdispatchStruct, addcolumn(), Topology::partitionAddress::address, cfg_s::anonymousping, MessageAckApply::ackapply_s::applierid, Appliers, argsize, MessageUserSchema::argstring, badMessageHandler(), BUILTINADDCOLUMN, schemastruct::builtincmd, MessageUserSchema::userschema_s::builtincmd, BUILTINCREATESCHEMA, BUILTINCREATETABLE, BUILTINDELETEINDEX, BUILTINDELETESCHEMA, BUILTINDELETETABLE, cfgs, changepassword(), compile(), createdomain(), createschema(), createtable(), createuser(), MessageDeadlock::deadlockStruct, deletedomain(), deleteindex(), deleteschema(), deletetable(), deleteuser(), domainid, MessageUserSchema::userschema_s::domainid, domainidsToProcedures, domainidsToSchemata, domainName, endConnection(), Topology::partitionAddress::epollfd, epollfd, MessageSocket::socket_s::events, MessageUserSchema::userschema_s::fieldid, Mbox::getCount(), GETMSG, Mbox::getPtr(), handledispatch(), Operation::handleOperation(), Topology::partitionAddress::instance, MessageUserSchema::userschema_s::instance, instance, LISTENER_PG, LISTENER_RAW, MessageSocket::socket_s::listenertype, loadprocedure(), logfile, loggedInUsers, login(), logout(), Topology::partitionAddress::mbox, mboxes, Message::messageStruct, msgrcv, MSGRECEIVEBATCHSIZE, myIdentity, myTopology, newprocedure(), newstatement(), Message::nextmsg, NOCMD, Topology::addressStruct::nodeid, Mboxes::nodeid, NOTOKCMD, OKCMD, operation, operationid, MessageUserSchema::userschema_s::operationid, operationPtr, MessageAckApply::ackapply_s::partitionid, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, pendingOperations, pendingOperationsIterator, Pg::pgclosesocket(), Pgs, ping(), readSocket(), responseData::resultCode, responseData::sbuf, Operation::schemaData, Mboxes::sendObBatch(), sendResponse(), MessageSocket::socket_s::socket, MessageSocket::socketStruct, sockfd, STARTCMD, schemastruct::state, MessageAckApply::ackapply_s::status, MessageAckApply::ackapply_s::subtransactionid, TAaddcolumn(), MessageUserSchema::userschema_s::tableid, TAcreateschema(), TAcreatetable(), TAdeleteindex(), TAdeleteschema(), TAdeletetable(), tainstance, tasengines, TASENGINESRESPONSECMD, Message::message_s::topic, TOPIC_ACKAPPLY, TOPIC_ACKDISPATCH, TOPIC_CHANGEPASSWORDFAIL, TOPIC_CHANGEPASSWORDOK, TOPIC_COMPILE, TOPIC_CREATEDOMAINFAIL, TOPIC_CREATEDOMAINOK, TOPIC_CREATEUSERFAIL, TOPIC_CREATEUSEROK, TOPIC_DEADLOCKABORT, TOPIC_DELETEDOMAINFAIL, TOPIC_DELETEDOMAINOK, TOPIC_DELETEUSERFAIL, TOPIC_DELETEUSEROK, TOPIC_DISPATCH, TOPIC_FIELDNAME, TOPIC_LOGINFAIL, TOPIC_LOGINOK, TOPIC_OPERATION, TOPIC_PROCEDURE1, TOPIC_PROCEDURE2, TOPIC_SCHEMAREPLY, TOPIC_SCHEMAREQUEST, TOPIC_SOCKET, TOPIC_SOCKETCONNECTED, TOPIC_TABLENAME, TOPIC_TOPOLOGY, TOPIC_TRANSACTION, MessageTransaction::transaction_s::transaction_pendingcmdid, MessageTransaction::transaction_s::transaction_tacmdentrypoint, MessageDeadlock::deadlock_s::transactionid, MessageTransaction::transaction_s::transactionid, MessageAckDispatch::ackdispatch_s::transactionid, Transactions, MessageTransaction::transactionStruct, Mboxes::update(), updateReplicas(), userid, MessageUserSchema::userschemaStruct, usm, USMRESPONSECMD, and waitingToSend.
                                                                           :
     myIdentity(*myIdentityArg), nexttransactionid(0), nextapplierid(0),
     myreplica(-1), mymember(-1)
 {
     delete myIdentityArg;
     epollfd = myIdentity.epollfd;
     instance = myIdentity.instance;
     mboxes.nodeid = myIdentity.address.nodeid;
     builtincmds_e cmd = NOCMD;
     spclasscreate spC;
     spclassdestroy spD;
     uint32_t events = 0;
     typedef boost::unordered_map<std::string,
                                  void (TransactionAgent::*)(builtincmds_e)>
         builtinsMap;
     builtinsMap builtins;
     builtins["ping"] = &TransactionAgent::ping;
     builtins["login"] = &TransactionAgent::login;
     builtins["logout"] = &TransactionAgent::logout;
     builtins["changepassword"] = &TransactionAgent::changepassword;
     builtins["createdomain"] = &TransactionAgent::createdomain;
     builtins["createuser"] = &TransactionAgent::createuser;
     builtins["deleteuser"] = &TransactionAgent::deleteuser;
     builtins["deletedomain"] = &TransactionAgent::deletedomain;
     builtins["createschema"] = &TransactionAgent::createschema;
     builtins["createtable"] = &TransactionAgent::createtable;
     builtins["addcolumn"] = &TransactionAgent::addcolumn;
     builtins["deleteindex"] = &TransactionAgent::deleteindex;
     builtins["deletetable"] = &TransactionAgent::deletetable;
     builtins["deleteschema"] = &TransactionAgent::deleteschema;
     builtins["loadprocedure"] = &TransactionAgent::loadprocedure;
     builtins["compile"] = &TransactionAgent::compile;
     operationid=0;
     int waitfor = 100;
     while (1)
     {
         // clear data from msgrcv
         domainid=-1;
         userid=-1;
         argsize=-1;
         sockfd=-1;
         mboxes.sendObBatch();
         for (size_t inmsg=0; inmsg < MSGRECEIVEBATCHSIZE; inmsg++)
         {
             GETMSG(msgrcv, myIdentity.mbox, waitfor)
                 if (msgrcv==NULL)
                 {
                     waitfor = 100;
                     break;
                 }
             waitfor = 0;
             if (msgrcv->messageStruct.payloadtype==PAYLOADUSERSCHEMA)
             {
                 class MessageUserSchema &msgref =
                     *((class MessageUserSchema *)msgrcv);
                 if (msgrcv->messageStruct.topic != TOPIC_SCHEMAREQUEST)
                 {
                     pendingOperationsIterator =
                         pendingOperations.find(msgref.userschemaStruct.operationid);
                     if (pendingOperationsIterator == pendingOperations.end())
                     {
                         ;
                     }
                     else
                     {
                         sockfd = pendingOperations[msgref.userschemaStruct.operationid]->sockfd;
                         userid = pendingOperations[msgref.userschemaStruct.operationid]->userid;
                         domainid = pendingOperations[msgref.userschemaStruct.operationid]->domainid;
                     }
                 }
                 operationid = msgref.userschemaStruct.operationid;
             }
             switch (msgrcv->messageStruct.topic)
             {
             case TOPIC_SOCKET:
             {
                 switch (((class MessageSocket *)msgrcv)->socketStruct.listenertype)
                 {
                 case LISTENER_RAW:
                 {
                     sockfd=((class MessageSocket *)msgrcv)->socketStruct.socket;
                     events=((class MessageSocket *)msgrcv)->socketStruct.events;
                     if ((events & EPOLLERR) || (events & EPOLLHUP))
                     {
                         endConnection();
                         break;
                     }
                     if (events & EPOLLIN)
                     {
                         operation = (string *)new string;
                         argsize = readSocket();
                         if (argsize < 0)
{
                             delete operation;
                             endConnection();
                             break;
                         }
                         // ok, if no user logged in, then can only login, else
                         // break connection exit
                         // if user logged in, then cannot login but everything
                         // else
                         // login shouldn't be in binFunctions map therefore
                         socketAuthInfo::iterator loggedInUsersIterator;
                         loggedInUsersIterator = loggedInUsers.find(sockfd);
                         if (loggedInUsersIterator == loggedInUsers.end())
{
                             // this means not logged in
                             if (operation->compare("login")==0)
{
                                 // so, login
                                 login(STARTCMD);
                             }
                             else if (operation->compare("ping")==0 &&
                                      __sync_add_and_fetch(&cfgs.anonymousping,
                                                           0))
{
                                 ping(STARTCMD);
                             }
                             else     // gtfo
{
                                 endConnection();
                                 break;
                             }
                         }
                         else
{
                             // get my domainid & userid
                             domainid = loggedInUsersIterator->second.domainid;
                             userid = loggedInUsersIterator->second.userid;
                             domainName =
                                 loggedInUsersIterator->second.domainName;
                             // first, check domain operations, when those are
                             // built
                             if (domainidsToProcedures.count(domainid))
{
                                 if (domainidsToProcedures[domainid].count(*operation))
{
                                     spC=(spclasscreate)domainidsToProcedures[domainid][*operation].procedurecreator;
                                     spD=(spclassdestroy)domainidsToProcedures[domainid][*operation].proceduredestroyer;
                                     spC(this, NULL, (void *)spD);
                                     continue;
 //                                    break;
                                 }
                             }
                             builtinsMap::iterator builtinsIterator;
                             builtinsIterator = builtins.find(*operation);
                             if (builtinsIterator != builtins.end())
{
                                 (this->*(builtinsIterator->second))(STARTCMD);
                             }
                             else
{
                                 // terminate with extreme prejudice
                                 endConnection();
                             }
                         }
                         delete operation;
                     }
                     if (events & EPOLLOUT)
                     {
                         struct epoll_event ev;
                         ev.events = EPOLLIN | EPOLLHUP | EPOLLET;
                         ev.data.fd = sockfd;
                         if (epoll_ctl(epollfd, EPOLL_CTL_MOD, sockfd, &ev))
{
                             endConnection();
                             break;
                         }
                         // write data that's waiting
                         sendLaterMap::iterator waitingToSendIterator;
                         waitingToSendIterator = waitingToSend.find(sockfd);
                         if (waitingToSendIterator != waitingToSend.end())
{
                             responseData response =
                                 waitingToSendIterator->second;
                             sendResponse(true, response.resultCode,
                                          response.sbuf);
                         }
                     }
                 }
                 break;
                 case LISTENER_PG:
                 {
                     class MessageSocket &msgrcvref =
                         *(class MessageSocket *)msgrcv;
                     if (!Pgs.count(msgrcvref.socketStruct.socket))
                     {
                         if ((msgrcvref.socketStruct.events & EPOLLERR) ||
                             (msgrcvref.socketStruct.events & EPOLLHUP))
{
                             fprintf(logfile, "\t%s %i hanging it up\n",
                                     __FILE__, __LINE__);
                             Pg::pgclosesocket(*this,
                                               msgrcvref.socketStruct.socket);
                             break;
                         }
                         break;
                     }
                     Pgs[msgrcvref.socketStruct.socket]->cont();
                 }
                 break;
                 default:
                     printf("%s %i anomaly listenertype %i\n", __FILE__, __LINE__,
                            ((class MessageSocket *)msgrcv)->socketStruct.listenertype);
                 }
             }
             break;
             case TOPIC_SOCKETCONNECTED:
             {
                 switch (((class MessageSocket *)msgrcv)->socketStruct.listenertype)
                 {
                 case LISTENER_RAW:
                     break;
                 case LISTENER_PG:
                 {
                     class MessageSocket &msgrcvref =
                         *(class MessageSocket *)msgrcv;
                     if (!Pgs.count(msgrcvref.socketStruct.socket))
                     {
                         new class Pg(this, msgrcvref.socketStruct.socket);
                     }
                     else
                     {
                         fprintf(logfile, "%s %i sockfd %i already mapped\n",
                                 __FILE__, __LINE__,
                                 msgrcvref.socketStruct.socket);
                     }
                 }
                 break;
                 default:
                     printf("%s %i anomaly listenertype %i\n", __FILE__, __LINE__,
                            ((class MessageSocket *)msgrcv)->socketStruct.listenertype);
                 }
             }
             break;
             case TOPIC_LOGINOK:
                 // set data members based on msgrcv
                 login(OKCMD);
                 break;
             case TOPIC_LOGINFAIL:
                 // set data members base on msgrcv
                 login(NOTOKCMD);
                 break;
             case TOPIC_CHANGEPASSWORDOK:
                 // set data members based on msgrcv
                 changepassword(OKCMD);
                 break;
             case TOPIC_CHANGEPASSWORDFAIL:
                 // set data members base on msgrcv
                 changepassword(NOTOKCMD);
                 break;
             case TOPIC_CREATEDOMAINOK:
                 // set data members based on msgrcv
                 createdomain(OKCMD);
                 break;
             case TOPIC_CREATEDOMAINFAIL:
                 // set data members base on msgrcv
                 createdomain(NOTOKCMD);
                 break;
             case TOPIC_CREATEUSEROK:
                 // set data members based on msgrcv
                 createuser(OKCMD);
                 break;
             case TOPIC_CREATEUSERFAIL:
                 // set data members base on msgrcv
                 createuser(NOTOKCMD);
                 break;
             case TOPIC_DELETEUSEROK:
                 // set data members based on msgrcv
                 deleteuser(OKCMD);
                 break;
             case TOPIC_DELETEUSERFAIL:
                 // set data members base on msgrcv
                 deleteuser(NOTOKCMD);
                 break;
             case TOPIC_DELETEDOMAINOK:
                 // set data members based on msgrcv
                 deletedomain(OKCMD);
                 break;
             case TOPIC_DELETEDOMAINFAIL:
                 // set data members base on msgrcv
                 deletedomain(NOTOKCMD);
                 break;
                 /* schema */
             case TOPIC_SCHEMAREPLY:
                 pendingOperationsIterator = pendingOperations.find(operationid);
                 if (pendingOperationsIterator == pendingOperations.end())
                 {
                     fprintf(logfile, "bad operationid %li %s %i\n", operationid,
                             __FILE__, __LINE__);
                     break;
                 }
                 operationPtr = pendingOperationsIterator->second;
                 switch (operationPtr->schemaData.state)
                 {
                 case usm:
                     cmd = USMRESPONSECMD;
                     break;
                 case tasengines:
                     cmd = TASENGINESRESPONSECMD;
                 }
                 switch (operationPtr->schemaData.builtincmd)
                 {
                 case BUILTINCREATESCHEMA:
                     createschema(cmd);
                     break;
                 case BUILTINCREATETABLE:
                     createtable(cmd);
                     break;
                 case BUILTINADDCOLUMN:
                     addcolumn(cmd);
                     break;
                 case BUILTINDELETEINDEX:
                     deleteindex(cmd);
                     break;
                 case BUILTINDELETETABLE:
                     deletetable(cmd);
                     break;
                 case BUILTINDELETESCHEMA:
                     deleteschema(cmd);
                     break;
                 default:
                     fprintf(logfile, "builtincmd %i %s %i\n",
                             operationPtr->schemaData.builtincmd, __FILE__,
                             __LINE__);
                 }
                 break;
             case TOPIC_SCHEMAREQUEST:
             {
                 class MessageUserSchema &msgref =
                     *(class MessageUserSchema *)msgrcv;
                 tainstance = msgref.userschemaStruct.instance;
                 switch (msgref.userschemaStruct.builtincmd)
                 {
                 case BUILTINCREATESCHEMA:
                     TAcreateschema();
                     break;
                 case BUILTINCREATETABLE:
                     TAcreatetable();
                     break;
                 case BUILTINADDCOLUMN:
                     TAaddcolumn();
                     break;
                 case BUILTINDELETEINDEX:
                     TAdeleteindex();
                     break;
                 case BUILTINDELETETABLE:
                     TAdeletetable();
                     break;
                 case BUILTINDELETESCHEMA:
                     TAdeleteschema();
                     break;
                 default:
                     fprintf(logfile, "builtincmd unrecognized %li %s %i\n",
                             msgref.userschemaStruct.builtincmd, __FILE__,
                             __LINE__);
                 }
             }
             break;
             case TOPIC_TRANSACTION:
             {
                 class MessageTransaction &msgref =
                     *(class MessageTransaction *)msgrcv;
                 // need pendingTransactions
                 if (Transactions.count(msgref.transactionStruct.transactionid))
                 {
                     Transactions[msgref.transactionStruct.transactionid]->processTransactionMessage(msgrcv);
                 }
                 else
                 {
                     // have to check for a LOCKED message cmd, to bounce back a
                     // message to roll it back
                     fprintf(logfile, "%s %i transactionid %li\n", __FILE__,
                             __LINE__,
                             msgref.transactionStruct.transactionid);
                     fprintf(logfile, "%s %i thismsg %p next ptr, count %p %lu, messageStruct.payloadtype %i pendingcmdid %i entrypoint %i locktype %i\n", __FILE__, __LINE__, msgrcv, Mbox::getPtr(msgref.nextmsg), Mbox::getCount(msgref.nextmsg), msgref.messageStruct.payloadtype, msgref.transactionStruct.transaction_pendingcmdid, msgref.transactionStruct.transaction_tacmdentrypoint, ((class MessageSubtransactionCmd *)msgrcv)->subtransactionStruct.locktype);
                     badMessageHandler();
                 }
                 break;
             }
             case TOPIC_DEADLOCKABORT:
             {
                 class MessageDeadlock &msgref = *(class MessageDeadlock *)msgrcv;
                 if (Transactions.count(msgref.deadlockStruct.transactionid))
                 {
                     Transactions[msgref.deadlockStruct.transactionid]->deadlockAbort(msgref);
                 }
             }
             break;
             case TOPIC_TOPOLOGY:
                 mboxes.update(myTopology, instance);
                 updateReplicas();
                 break;
             case TOPIC_ACKDISPATCH:
             {
                 class MessageAckDispatch &msgref =
                     *(class MessageAckDispatch *)msgrcv;
                 // need pendingTransactions
                 if (Transactions.count(msgref.ackdispatchStruct.transactionid))
                 {
                     // for now 4/5/13 don't think about msgref.status
                     Transactions[msgref.ackdispatchStruct.transactionid]->continueCommitTransaction(1);
                 }
             }
             break;
             case TOPIC_PROCEDURE1:
                 newprocedure(2);
                 break;
             case TOPIC_PROCEDURE2:
                 newprocedure(3);
                 break;
             case TOPIC_DISPATCH:
                 handledispatch();
                 break;
             case TOPIC_ACKAPPLY:
             {
                 class MessageAckApply &msgref = *(class MessageAckApply *)msgrcv;
                 if (Appliers.count(msgref.ackapplyStruct.applierid))
                 {
                     Appliers[msgref.ackapplyStruct.applierid]->ackedApply(msgref);
                 }
                 else
                 {
                     printf("%s %i no Applier to ack status %i %li,%li,%li\n",
                            __FILE__,
                            __LINE__, msgref.ackapplyStruct.status,
                            msgref.ackapplyStruct.subtransactionid,
                            msgref.ackapplyStruct.applierid,
                            msgref.ackapplyStruct.partitionid);
                 }
             }
             break;
             case TOPIC_OPERATION:
             {
                 operationMap::iterator it;
                 it = pendingOperations.find(((class MessageUserSchema *)msgrcv)->userschemaStruct.operationid);
                 if (it != pendingOperations.end())
                 {
                     class Operation &operationRef = *it->second;
                     operationRef.handleOperation(*((class MessageUserSchema *)msgrcv));
                 }
             }
             break;
             case TOPIC_COMPILE:
                 newstatement();
                 break;
             case TOPIC_TABLENAME:
             {
                 class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
                 domainidsToSchemata[msgrcvref.userschemaStruct.domainid]->tableNameToId[msgrcvref.argstring] =
                     msgrcvref.userschemaStruct.tableid;
             }
             break;
             case TOPIC_FIELDNAME:
             {
                 class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
                 domainidsToSchemata[msgrcvref.userschemaStruct.domainid]->fieldNameToId[msgrcvref.userschemaStruct.tableid][msgrcvref.argstring] = msgrcvref.userschemaStruct.fieldid;
             }
             break;
             default:
                 fprintf(logfile, "anomaly %i %s %i\n",
                         msgrcv->messageStruct.topic, __FILE__, __LINE__);
             }
         }
     }
 }
TransactionAgent::~TransactionAgent () virtual
Definition at line 585 of file TransactionAgent.cc.
 {
 }
Member Function Documentation
void TransactionAgent::addcolumn (builtincmds_e cmd)
add column
Parameters
cmd continuation entry point
Definition at line 1011 of file TransactionAgent.cc.
References Topology::partitionAddress::address, MessageUserSchema::argstring, BUILTINADDCOLUMN, MessageUserSchema::userschema_s::domainid, MessageUserSchema::userschema_s::fieldid, logfile, mboxes, Message::messageStruct, msgrcv, myIdentity, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, responseVector, schemaBoilerplate(), STARTCMD, MessageUserSchema::userschema_s::tableid, TASENGINESRESPONSECMD, Mboxes::toAllOfType(), Message::message_s::topic, TOPIC_FIELDNAME, MessageUserSchema::userschemaStruct, and USMRESPONSECMD.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
         schemaBoilerplate(cmd, BUILTINADDCOLUMN);
         break;
     case USMRESPONSECMD:
     {
         schemaBoilerplate(cmd, BUILTINADDCOLUMN);
         class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
         class MessageUserSchema msg;
         msg.messageStruct.topic = TOPIC_FIELDNAME;
         msg.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msg.userschemaStruct.domainid = msgrcvref.userschemaStruct.domainid;
         msg.userschemaStruct.tableid = msgrcvref.userschemaStruct.tableid;
         msg.userschemaStruct.fieldid = msgrcvref.userschemaStruct.fieldid;
         msg.argstring = msgrcvref.argstring;
         mboxes.toAllOfType(ACTOR_TRANSACTIONAGENT, myIdentity.address, msg);
     }
     break;
     case TASENGINESRESPONSECMD:
         responseVector.clear();
         responseVector.push_back(boost::lexical_cast<string>
                                  (((class MessageUserSchema *)msgrcv)->userschemaStruct.fieldid));
         schemaBoilerplate(cmd, BUILTINADDCOLUMN);
         break;
     default:
         fprintf(logfile, "topic unrecognized %i %s %i\n", cmd, __FILE__,
                 __LINE__);
     }
 }
void TransactionAgent::badMessageHandler ()
stub for Message variants that can't be handled otherwise
Definition at line 1373 of file TransactionAgent.cc.
References logfile.
Referenced by TransactionAgent().
 {
     fprintf(logfile, "TA bad message stub %s %i\n", __FILE__, __LINE__);
 }
void TransactionAgent::changepassword (builtincmds_e cmd)
change password
Parameters
cmd continuation entry point
Definition at line 713 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, argsize, domainid, endOperation(), Operation::getid(), instance, logfile, mboxes, Message::messageStruct, myIdentity, NOTOKCMD, OKCMD, operationid, operationPtr, PAYLOADUSERSCHEMA, sendResponse(), STARTCMD, STATUS_NOTOK, STATUS_OK, Message::message_s::topic, TOPIC_CHANGEPASSWORD, Mboxes::toUserSchemaMgr(), and userid.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
     {
         operationPtr = new class Operation(OP_AUTH, this, userid, domainid);
         operationid = operationPtr->getid();
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_CHANGEPASSWORD);
         class MessageUserSchema &msgref = *msg;
         msgref.messageStruct.topic = TOPIC_CHANGEPASSWORD;
         msgref.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msgref.userschemaStruct.argsize = argsize;
         msgref.userschemaStruct.instance = instance;
         msgref.userschemaStruct.operationid = operationid;
         msgref.userschemaStruct.domainid = domainid;
         msgref.userschemaStruct.userid = userid;
         msgref.argstring.assign(args, 0, argsize);
         mboxes.toUserSchemaMgr(this->myIdentity.address, msgref);
     }
     break;
     case OKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_OK, &rv);
         endOperation();
     }
     break;
     case NOTOKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_NOTOK, &rv);
         endOperation();
     }
     break;
     default:
         fprintf(logfile, "TransactionAgent::changepassword cmd unrecognized %i\n", cmd);
     }
 }
void TransactionAgent::compile (builtincmds_e cmd)
compile SQL statement
Parameters
cmd continuation entry point
Definition at line 1311 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, argsize, MessageUserSchema::argstring, domainid, MessageUserSchema::userschema_s::domainid, domainidsToSchemata, mboxes, Message::messageStruct, msgpack2Vector(), myIdentity, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, MessageUserSchema::procname, sendResponse(), Larxer::statementPtr, STATUS_NOTOK, STATUS_OK, Mboxes::toAllOfType(), Message::message_s::topic, TOPIC_COMPILE, and MessageUserSchema::userschemaStruct.
Referenced by TransactionAgent().
 {
     vector<string> resultVector;
     msgpack2Vector(&resultVector, args, argsize);
     //  int64_t sid = atol(resultVector[0].c_str());
     string statementname(resultVector[0]);
     string sqlstatement(resultVector[1]);
     class Larxer lx2((char *)sqlstatement.c_str(), this,
                      domainidsToSchemata[domainid]);
     if (lx2.statementPtr==NULL)
     {
         vector<string> rv;
         sendResponse(false, STATUS_NOTOK, &rv);
         return;
     }
     delete lx2.statementPtr;
     class MessageUserSchema msg;
     msg.messageStruct.topic = TOPIC_COMPILE;
     msg.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
     msg.userschemaStruct.domainid = domainid;
     msg.procname = statementname;
     msg.argstring = sqlstatement;
     mboxes.toAllOfType(ACTOR_TRANSACTIONAGENT, myIdentity.address, msg);
     vector<string> rv;
     rv.push_back(statementname);
     sendResponse(false, STATUS_OK, &rv);
 }
void TransactionAgent::createdomain (builtincmds_e cmd)
create domain
Parameters
cmd continuation entry point
Definition at line 757 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, argsize, domainid, endOperation(), Operation::getid(), instance, logfile, mboxes, Message::messageStruct, myIdentity, NOTOKCMD, OKCMD, operationid, operationPtr, PAYLOADUSERSCHEMA, sendResponse(), STARTCMD, STATUS_NOTOK, STATUS_OK, Message::message_s::topic, TOPIC_CREATEDOMAIN, Mboxes::toUserSchemaMgr(), and userid.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
     {
         operationPtr = new class Operation(OP_AUTH, this, userid, domainid);
         operationid = operationPtr->getid();
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_CREATEDOMAIN);
         class MessageUserSchema &msgref = *msg;
         msgref.messageStruct.topic = TOPIC_CREATEDOMAIN;
         msgref.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msgref.userschemaStruct.argsize = argsize;
         msgref.userschemaStruct.instance = instance;
         msgref.userschemaStruct.operationid = operationid;
         msgref.userschemaStruct.domainid = domainid;
         msgref.userschemaStruct.userid = userid;
         msgref.argstring.assign(args, 0, argsize);
         //      mboxes.userSchemaMgr.send(msgsnd, true);
         mboxes.toUserSchemaMgr(this->myIdentity.address, msgref);
     }
     break;
     case OKCMD:
     {
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_CREATEUSER);
         class MessageUserSchema &msgref = *msg;
         vector<string> rv;
         // this is created domainid:
         rv.push_back(boost::lexical_cast<string>(msgref.userschemaStruct.domainid));
         sendResponse(false, STATUS_OK, &rv);
         endOperation();
     }
     break;
     case NOTOKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_NOTOK, &rv);
         endOperation();
     }
     break;
     default:
         fprintf(logfile, "TransactionAgent::createdomain cmd unrecognized %i\n",
                 cmd);
     }
 }
void TransactionAgent::createschema (builtincmds_e cmd)
create schema
Parameters
cmd continuation entry point
Definition at line 951 of file TransactionAgent.cc.
References BUILTINCREATESCHEMA, logfile, responseVector, schemaBoilerplate(), STARTCMD, TASENGINESRESPONSECMD, and USMRESPONSECMD.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
         schemaBoilerplate(cmd, BUILTINCREATESCHEMA);
         break;
     case USMRESPONSECMD:
         schemaBoilerplate(cmd, BUILTINCREATESCHEMA);
         break;
     case TASENGINESRESPONSECMD:
         responseVector.clear();
         schemaBoilerplate(cmd, BUILTINCREATESCHEMA);
         break;
     default:
         fprintf(logfile, "topic unrecognized %i %s %i\n", cmd, __FILE__,
                 __LINE__);
     }
 }
void TransactionAgent::createtable (builtincmds_e cmd)
create table
Parameters
cmd continuation entry point
Definition at line 974 of file TransactionAgent.cc.
References Topology::partitionAddress::address, MessageUserSchema::argstring, BUILTINCREATETABLE, MessageUserSchema::userschema_s::domainid, logfile, mboxes, Message::messageStruct, msgrcv, myIdentity, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, responseVector, schemaBoilerplate(), STARTCMD, MessageUserSchema::userschema_s::tableid, TASENGINESRESPONSECMD, Mboxes::toAllOfType(), Message::message_s::topic, TOPIC_TABLENAME, MessageUserSchema::userschemaStruct, and USMRESPONSECMD.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
         schemaBoilerplate(cmd, BUILTINCREATETABLE);
         break;
     case USMRESPONSECMD:
     {
         schemaBoilerplate(cmd, BUILTINCREATETABLE);
         class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
         class MessageUserSchema msg;
         msg.messageStruct.topic = TOPIC_TABLENAME;
         msg.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msg.userschemaStruct.domainid = msgrcvref.userschemaStruct.domainid;
         msg.userschemaStruct.tableid = msgrcvref.userschemaStruct.tableid;
         msg.argstring = msgrcvref.argstring;
         mboxes.toAllOfType(ACTOR_TRANSACTIONAGENT, myIdentity.address, msg);
     }
     break;
     case TASENGINESRESPONSECMD:
         responseVector.clear();
         responseVector.push_back(boost::lexical_cast<string>
                                  (((class MessageUserSchema *)msgrcv)->userschemaStruct.tableid));
         schemaBoilerplate(cmd, BUILTINCREATETABLE);
         break;
     default:
         fprintf(logfile, "topic unrecognized %i %s %i\n", cmd, __FILE__,
                 __LINE__);
     }
 }
void TransactionAgent::createuser (builtincmds_e cmd)
create user
Parameters
cmd continuation entry point
Definition at line 808 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, argsize, domainid, endOperation(), Operation::getid(), instance, logfile, mboxes, Message::messageStruct, myIdentity, NOTOKCMD, OKCMD, operationid, operationPtr, PAYLOADUSERSCHEMA, sendResponse(), STARTCMD, STATUS_NOTOK, STATUS_OK, Message::message_s::topic, TOPIC_CREATEUSER, Mboxes::toUserSchemaMgr(), and userid.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
     {
         operationPtr = new class Operation(OP_AUTH, this, userid, domainid);
         operationid = operationPtr->getid();
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_CREATEUSER);
         class MessageUserSchema &msgref = *msg;
         msgref.messageStruct.topic = TOPIC_CREATEUSER;
         msgref.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msgref.userschemaStruct.argsize = argsize;
         msgref.userschemaStruct.instance = instance;
         msgref.userschemaStruct.operationid = operationid;
         msgref.userschemaStruct.domainid = domainid;
         msgref.userschemaStruct.userid = userid;
         msgref.argstring.assign(args, 0, argsize);
         mboxes.toUserSchemaMgr(this->myIdentity.address, msgref);
     }
     break;
     case OKCMD:
     {
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_CREATEUSER);
         class MessageUserSchema &msgref = *msg;
         vector<string> rv;
         // this is created userid:
         rv.push_back(boost::lexical_cast<string>(msgref.userschemaStruct.userid));
         sendResponse(false, STATUS_OK, &rv);
         endOperation();
     }
     break;
     case NOTOKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_NOTOK, &rv);
         endOperation();
     }
     break;
     default:
         fprintf(logfile, "TransactionAgent::createuser cmd unrecognized %i\n",
                 cmd);
     }
 }
void TransactionAgent::deletedomain (builtincmds_e cmd)
delete domain
Parameters
cmd continuation entry point
Definition at line 904 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, argsize, domainid, endOperation(), Operation::getid(), instance, logfile, mboxes, Message::messageStruct, myIdentity, NOTOKCMD, OKCMD, operationid, operationPtr, PAYLOADUSERSCHEMA, sendResponse(), STARTCMD, STATUS_NOTOK, STATUS_OK, Message::message_s::topic, TOPIC_DELETEDOMAIN, Mboxes::toUserSchemaMgr(), and userid.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
     {
         operationPtr = new class Operation(OP_AUTH, this, userid, domainid);
         operationid = operationPtr->getid();
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_DELETEDOMAIN);
         class MessageUserSchema &msgref = *msg;
         msgref.messageStruct.topic = TOPIC_DELETEDOMAIN;
         msgref.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msgref.userschemaStruct.argsize = argsize;
         msgref.userschemaStruct.instance = instance;
         msgref.userschemaStruct.operationid = operationid;
         msgref.userschemaStruct.domainid = domainid;
         msgref.userschemaStruct.userid = userid;
         msgref.argstring.assign(args, 0, argsize);
         //      mboxes.userSchemaMgr.send(msgsnd, true);
         mboxes.toUserSchemaMgr(this->myIdentity.address, msgref);
     }
     break;
     case OKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_OK, &rv);
         endOperation();
     }
     break;
     case NOTOKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_NOTOK, &rv);
         endOperation();
     }
     break;
     default:
         fprintf(logfile, "TransactionAgent::deletedomain cmd unrecognized %i\n",
                 cmd);
     }
 }
void TransactionAgent::deleteindex (builtincmds_e cmd)
delete index
Parameters
cmd continuation entry point
Definition at line 1049 of file TransactionAgent.cc.
References BUILTINDELETEINDEX, logfile, responseVector, schemaBoilerplate(), STARTCMD, TASENGINESRESPONSECMD, and USMRESPONSECMD.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
         schemaBoilerplate(cmd, BUILTINDELETEINDEX);
         break;
     case USMRESPONSECMD:
         schemaBoilerplate(cmd, BUILTINDELETEINDEX);
         break;
     case TASENGINESRESPONSECMD:
         responseVector.clear();
         schemaBoilerplate(cmd, BUILTINDELETEINDEX);
         break;
     default:
         fprintf(logfile, "topic unrecognized %i %s %i\n", cmd, __FILE__,
                 __LINE__);
     }
 }
void TransactionAgent::deleteschema (builtincmds_e cmd)
delete schema
Parameters
cmd continuation entry point
Definition at line 1095 of file TransactionAgent.cc.
References BUILTINDELETESCHEMA, logfile, responseVector, schemaBoilerplate(), STARTCMD, TASENGINESRESPONSECMD, and USMRESPONSECMD.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
         schemaBoilerplate(cmd, BUILTINDELETESCHEMA);
         break;
     case USMRESPONSECMD:
         schemaBoilerplate(cmd, BUILTINDELETESCHEMA);
         break;
     case TASENGINESRESPONSECMD:
         responseVector.clear();
         schemaBoilerplate(cmd, BUILTINDELETESCHEMA);
         break;
     default:
         fprintf(logfile, "topic unrecognized %i %s %i\n", cmd, __FILE__,
                 __LINE__);
     }
 }
void TransactionAgent::deletetable (builtincmds_e cmd)
delete table
Parameters
cmd continuation entry point
Definition at line 1072 of file TransactionAgent.cc.
References BUILTINDELETETABLE, logfile, responseVector, schemaBoilerplate(), STARTCMD, TASENGINESRESPONSECMD, and USMRESPONSECMD.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
         schemaBoilerplate(cmd, BUILTINDELETETABLE);
         break;
     case USMRESPONSECMD:
         schemaBoilerplate(cmd, BUILTINDELETETABLE);
         break;
     case TASENGINESRESPONSECMD:
         responseVector.clear();
         schemaBoilerplate(cmd, BUILTINDELETETABLE);
         break;
     default:
         fprintf(logfile, "topic unrecognized %i %s %i\n", cmd, __FILE__,
                 __LINE__);
     }
 }
void TransactionAgent::deleteuser (builtincmds_e cmd)
delete user
Parameters
cmd continuation entry point
Definition at line 858 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, argsize, domainid, endOperation(), Operation::getid(), instance, logfile, mboxes, Message::messageStruct, myIdentity, NOTOKCMD, OKCMD, operationid, operationPtr, PAYLOADUSERSCHEMA, sendResponse(), STARTCMD, STATUS_NOTOK, STATUS_OK, Message::message_s::topic, TOPIC_DELETEUSER, Mboxes::toUserSchemaMgr(), and userid.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
     {
         operationPtr = new class Operation(OP_AUTH, this, userid, domainid);
         operationid = operationPtr->getid();
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_DELETEUSER);
         class MessageUserSchema &msgref = *msg;
         msgref.messageStruct.topic = TOPIC_DELETEUSER;
         msgref.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msgref.userschemaStruct.argsize = argsize;
         msgref.userschemaStruct.instance = instance;
         msgref.userschemaStruct.operationid = operationid;
         msgref.userschemaStruct.domainid = domainid;
         msgref.userschemaStruct.userid = userid;
         msgref.argstring.assign(args, 0, argsize);
         //      mboxes.userSchemaMgr.send(msgsnd, true);
         mboxes.toUserSchemaMgr(this->myIdentity.address, msgref);
     }
     break;
     case OKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_OK, &rv);
         endOperation();
     }
     break;
     case NOTOKCMD:
     {
         vector<string> rv;
         sendResponse(false, STATUS_NOTOK, &rv);
         endOperation();
     }
     break;
     default:
         fprintf(logfile, "TransactionAgent::deleteuser cmd unrecognized %i\n",
                 cmd);
     }
 }
void TransactionAgent::endConnection ()
finish TCP connection on raw interface (not SQL interface)
Definition at line 589 of file TransactionAgent.cc.
References epollfd, loggedInUsers, and sockfd.
Referenced by login(), logout(), sendResponse(), and TransactionAgent().
 {
     epoll_ctl(epollfd, EPOLL_CTL_DEL, sockfd, NULL);
     close(sockfd);
     loggedInUsers.erase(sockfd);
 }
void TransactionAgent::endOperation ()
delete Operation, remove from pendingOperations
Definition at line 1119 of file TransactionAgent.cc.
References operationid, and pendingOperations.
Referenced by changepassword(), createdomain(), createuser(), deletedomain(), deleteuser(), login(), and schemaBoilerplate().
 {
     delete pendingOperations[operationid];
     pendingOperations.erase(operationid);
 }
int64_t TransactionAgent::getnextapplierid ()
generate unique, constantly increasing Applier identifier
Returns
next applierid
Definition at line 1368 of file TransactionAgent.cc.
References nextapplierid.
Referenced by Applier::Applier().
 {
     return ++nextapplierid;
 }
int64_t TransactionAgent::getnexttransactionid ()
generate unique, constantly increasing Transaction identifier
Returns
next transactionid
Definition at line 1363 of file TransactionAgent.cc.
References nexttransactionid.
Referenced by Transaction::Transaction().
 {
     return ++nexttransactionid;
 }
void TransactionAgent::handledispatch ()
for replica to apply transaction changes synchronously
Definition at line 1558 of file TransactionAgent.cc.
References Topology::partitionAddress::address, BOOL, CHAR, CHARX, DELETE, MessageDispatch::dispatchStruct, domainid, MessageDispatch::dispatch_s::domainid, domainidsToSchemata, nonLockingIndexEntry_s::engineid, MessageApply::applyindex_s::entry, MessageApply::applyindex_s::fieldid, Table::fields, MessageApply::applyindex_s::fieldVal, MessageApply::applyindex_s::flags, FLOAT, getPartitionid(), INSERT, INT, mboxes, Message::messageStruct, msgrcv, myIdentity, myTopology, NONE, Topology::numpartitions, partitioncount, MessageApply::rows, MessageApply::setisaddflag(), Message::message_s::sourceAddr, MessageApply::applyindex_s::tableid, Schema::tables, Mboxes::toActor(), Mboxes::toPartition(), UINT, Table::unmakerow(), UPDATE, and VARCHAR.
Referenced by TransactionAgent().
 {
     class MessageDispatch &msgrcvref = *(class MessageDispatch *)msgrcv;
     domainid = msgrcvref.dispatchStruct.domainid;
     class MessageAckDispatch *msg =
         new class MessageAckDispatch(msgrcvref.dispatchStruct.transactionid,
                                      STATUS_OK);
     mboxes.toActor(myIdentity.address, msgrcvref.messageStruct.sourceAddr, *msg);
     int64_t partitioncount=0;
     boost::unordered_map<int64_t, class MessageApply *> msgs;
     class Applier *applierPtr = new class Applier(this, domainid,
                                                   msgrcvref.messageStruct.sourceAddr, partitioncount);
     boost::unordered_map< int64_t,
                           vector<MessageDispatch::record_s> >::iterator it;
     for (it = msgrcvref.records.begin(); it != msgrcvref.records.end(); it++)
     {
         // it->first int64_t partitionid, it->second vector of records
         vector<MessageDispatch::record_s> &recordsref = it->second;
         if (!msgs.count(it->first))
         {
             msgs[it->first] =
                 new class MessageApply(msgrcvref.pidsids[it->first],
                                                      applierPtr->applierid,
                                        domainid);
         }
         msgs[it->first]->rows = recordsref;
         class Schema *schemaPtr = domainidsToSchemata[domainid];
         for (size_t n=0; n < recordsref.size(); n++)
         {
             class Table &tableRef = *schemaPtr->tables[recordsref[n].tableid];
             switch (recordsref[n].primitive)
             {
             case INSERT:
             {
                 vector<fieldValue_s> fields;
                 tableRef.unmakerow(&recordsref[n].row, &fields);
                 for (uint16_t f=0; f < tableRef.fields.size(); f++)
                 {
                     if (tableRef.fields[f].indextype==NONE)
                     {
                         continue;
                     }
                     // hence, create new index entry
                     MessageApply::applyindex_s indexinfo;
                     indexinfo.fieldVal = fields[f];
                     indexinfo.fieldid = f;
                     indexinfo.flags = 0;
                     MessageApply::setisaddflag(&indexinfo.flags);
                     indexinfo.tableid = recordsref[n].tableid;
                     indexinfo.entry = {recordsref[n].rowid,
                                        getPartitionid(fields[f],
                                                       tableRef.fields[f].type,
                                                       (int16_t)myTopology.numpartitions)
                     };
                     msgs[indexinfo.entry.engineid]->indices.push_back(indexinfo);
                 }
             }
             break;
             case UPDATE:
             {
                 vector<fieldValue_s> newfields;
                 tableRef.unmakerow(&recordsref[n].row, &newfields);
                 vector<fieldValue_s> oldfields;
                 tableRef.unmakerow(&recordsref[n].oldrow, &oldfields);
                 for (size_t f=0; f < tableRef.fields.size(); f++)
                 {
                     if (tableRef.fields[f].indextype==NONE)
                     {
                         continue;
                     }
                     // only add entries if new & old are different
                     bool aredifferent;
                     switch (tableRef.fields[f].type)
                     {
                     case INT:
                         aredifferent = newfields[f].value.integer !=
                             oldfields[f].value.integer ? true : false;
                         break;
                     case UINT:
                         aredifferent = newfields[f].value.uinteger !=
                             oldfields[f].value.uinteger ? true : false;
                         break;
                     case BOOL:
                         aredifferent = newfields[f].value.boolean !=
                             oldfields[f].value.boolean ? true : false;
                         break;
                     case FLOAT:
                         aredifferent = newfields[f].value.floating !=
                             oldfields[f].value.floating ? true : false;
                         break;
                     case CHAR:
                         aredifferent = newfields[f].value.character !=
                             oldfields[f].value.character ? true : false;
                         break;
                     case CHARX:
                         aredifferent = newfields[f].str.compare(oldfields[f].str)
                             ? true : false;
                         break;
                     case VARCHAR:
                         aredifferent = newfields[f].str.compare(oldfields[f].str)
                             ? true : false;
                         break;
                     default:
                         printf("%s %i anomaly fieldtype %i\n", __FILE__,
                                __LINE__, tableRef.fields[f].type);
                         aredifferent=false;
                     }
                     if (aredifferent==true)
                     {
                         // delete the old, add the new
                         MessageApply::applyindex_s indexinfo;
                         indexinfo.fieldVal = oldfields[f];
                         indexinfo.fieldid = f;
                         indexinfo.flags = 0;
                         indexinfo.tableid = recordsref[n].tableid;
                         indexinfo.entry = {recordsref[n].rowid,
                                            getPartitionid(oldfields[f],
                                                           tableRef.fields[f].type,
                                                           myTopology.numpartitions)
                         };
                         msgs[indexinfo.entry.engineid]->indices.push_back(indexinfo);
                         indexinfo.fieldVal = newfields[f];
                         indexinfo.fieldid = f;
                         indexinfo.flags = 0;
                         MessageApply::setisaddflag(&indexinfo.flags);
                         indexinfo.tableid = recordsref[n].tableid;
                         indexinfo.entry = {recordsref[n].rowid,
                                            getPartitionid(newfields[f],
                                                           tableRef.fields[f].type,
                                                           myTopology.numpartitions)
                         };
                         msgs[indexinfo.entry.engineid]->indices.push_back(indexinfo);
                     }
                 }
             }
             break;
             case DELETE:
             {
                 vector<fieldValue_s> fields;
                 tableRef.unmakerow(&recordsref[n].oldrow, &fields);
                 for (size_t f=0; f < tableRef.fields.size(); f++)
                 {
                     if (tableRef.fields[f].indextype==NONE)
                     {
                         continue;
                     }
                     // hence, create new index entry
                     MessageApply::applyindex_s indexinfo;
                     indexinfo.fieldVal = fields[f];
                     indexinfo.flags = 0;
                     indexinfo.fieldid = f;
                     indexinfo.tableid = recordsref[n].tableid;
                     indexinfo.entry = {recordsref[n].rowid,
                                        getPartitionid(fields[f],
                                                       tableRef.fields[f].type,
                                                       myTopology.numpartitions)
                     };
                     msgs[indexinfo.entry.engineid]->indices.push_back(indexinfo);
                 }
             }
             break;
             default:
                 printf("%s %i anomaly primitive %i\n", __FILE__, __LINE__,
                        recordsref[n].primitive);
             }
         }
     }
     boost::unordered_map<int64_t, class MessageApply *>::iterator it2;
     for (it2 = msgs.begin(); it2 != msgs.end(); it2++)
     {
         mboxes.toPartition(myIdentity.address, it2->first, *it2->second);
     }
 }
void TransactionAgent::loadprocedure (builtincmds_e cmd)
load stored procedure
Parameters
cmd continuation entry point
Definition at line 1306 of file TransactionAgent.cc.
References newprocedure().
Referenced by TransactionAgent().
 {
     newprocedure(1);
 }
void TransactionAgent::login (builtincmds_e cmd)
login
Parameters
cmd continuation entry point
Definition at line 646 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, argsize, cfg_s::badloginmessages, cfgs, authInfo::domainid, MessageUserSchema::userschema_s::domainid, Operation::domainName, authInfo::domainName, endConnection(), endOperation(), Operation::getid(), instance, logfile, loggedInUsers, mboxes, Message::messageStruct, msgpack2Vector(), msgrcv, myIdentity, NOTOKCMD, OKCMD, operationid, operationPtr, PAYLOADUSERSCHEMA, pendingOperations, sendResponse(), Operation::setDomainName(), sockfd, STARTCMD, STATUS_NOTOK, STATUS_OK, Message::message_s::topic, TOPIC_LOGIN, Mboxes::toUserSchemaMgr(), authInfo::userid, MessageUserSchema::userschema_s::userid, and MessageUserSchema::userschemaStruct.
Referenced by TransactionAgent().
 {
     switch (cmd)
     {
     case STARTCMD:
     {
         operationPtr = new class Operation(OP_AUTH, this, -1, -1);
         operationid = operationPtr->getid();
         vector<string> v;
         msgpack2Vector(&v, args, argsize);
         operationPtr->setDomainName(v[0]);
         class MessageUserSchema *msg = new class MessageUserSchema(TOPIC_LOGIN);
         class MessageUserSchema &msgref = *msg;
         msgref.messageStruct.topic = TOPIC_LOGIN;
         msgref.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msgref.userschemaStruct.argsize = argsize;
         msgref.userschemaStruct.instance = instance;
         msgref.userschemaStruct.operationid = operationid;
         msgref.argstring.assign(args, 0, argsize);
         mboxes.toUserSchemaMgr(this->myIdentity.address, msgref);
     }
     break;
     case OKCMD:
     {
         // let's hope I remember to populate the object's domainid & userid
         // before calling this
         class MessageUserSchema &msgrcvref =
             *(class MessageUserSchema *)msgrcv;
         operationPtr = pendingOperations[operationid];
         authInfo aInfo;
         aInfo.domainid = msgrcvref.userschemaStruct.domainid;
         aInfo.userid = msgrcvref.userschemaStruct.userid;
         aInfo.domainName.assign(operationPtr->domainName);
         loggedInUsers[sockfd] = aInfo;
         vector<string> rv;
         sendResponse(false, STATUS_OK, &rv);
         endOperation();
     }
     break;
     case NOTOKCMD:
     {
         if (__sync_add_and_fetch(&cfgs.badloginmessages, 0))
         {
             vector<string> rv;
             sendResponse(false, STATUS_NOTOK, &rv);
         }
         endOperation();
         endConnection();
     }
     break;
     default:
         fprintf(logfile, "TransactionAgent::login cmd unrecognized %i\n", cmd);
     }
 }
void TransactionAgent::logout (builtincmds_e cmd)
logout
Parameters
cmd continuation entry point
Definition at line 706 of file TransactionAgent.cc.
References endConnection(), sendResponse(), and STATUS_OK.
Referenced by TransactionAgent().
 {
     vector<string> rv;
     sendResponse(false, STATUS_OK, &rv);
     endConnection();
 }
void TransactionAgent::newprocedure (int64_t entrypoint)
called by loadprocedure
communicates back and forth with UserSchemaMgr and all TransactionAgents to load stored procedure
Parameters
entrypoint entry point
Definition at line 1438 of file TransactionAgent.cc.
References Topology::partitionAddress::address, Topology::allActors, args, argsize, MessageUserSchema::argstring, domainid, MessageUserSchema::userschema_s::domainid, domainName, Topology::partitionAddress::instance, MessageUserSchema::userschema_s::intdata, mboxes, Message::messageStruct, msgpack2Vector(), msgrcv, myIdentity, myTopology, Topology::nodeid, MessageUserSchema::pathname, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, procedures_s::procedurecreator, procedures_s::proceduredestroyer, MessageUserSchema::procname, MessageUserSchema::procs, sendResponse(), STATUS_OK, storedprocprefix, Mboxes::toActor(), Message::message_s::topic, TOPIC_PROCEDURE1, TOPIC_PROCEDURE2, and MessageUserSchema::userschemaStruct.
Referenced by loadprocedure(), and TransactionAgent().
 {
     switch (entrypoint)
     {
     case 1: // client sends loadprocedure command
     {
         vector<string> resultVector;
         msgpack2Vector(&resultVector, args, argsize);
         class MessageUserSchema msg;
         msg.messageStruct.topic = TOPIC_PROCEDURE1;
         msg.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msg.userschemaStruct.domainid = domainid;
         msg.pathname = resultVector[0];
         msg.procname = storedprocprefix;
         msg.procname += domainName;
         msg.procname += "_";
         msg.procname.append(resultVector[1]);
         // get 1 ta from each node and send a copy of that message
         for (size_t n=0; n < myTopology.allActors.size(); n++)
         {
             for (size_t m=0; m < myTopology.allActors[n].size(); m++)
             {
                 if (myTopology.allActors[n][m]==ACTOR_TRANSACTIONAGENT)
                 {
                     class MessageUserSchema *nmsg = new class MessageUserSchema;
                     *nmsg = msg;
                     mboxes.toActor(myIdentity.address, {(int16_t)n, (int16_t)m},
                                    *nmsg);
                     break;
                 }
             }
         }
         vector<string> rv;
         sendResponse(false, STATUS_OK, &rv);
     }
     break;
     case 2: // TOPIC_PROCEDURE1, load procedure, then send to all ta's this node
     {
         class MessageUserSchema &inmsg = *((class MessageUserSchema *)msgrcv);
         const char *dlsym_error;
         dlerror();
         void *soPtr = dlopen(inmsg.pathname.c_str(), RTLD_LAZY);
         if (!soPtr)
         {
             dlsym_error = dlerror();
             puts(dlsym_error);
             return;
         }
         dlerror();
         string funcNameCreate = inmsg.procname + "_create";
         spclasscreate call_func1create =
             (spclasscreate) dlsym(soPtr, funcNameCreate.c_str());
         dlsym_error = dlerror();
         if (dlsym_error)
         {
             printf("%s %i anomaly nodeid %i instance %li error %s\n", __FILE__,
                    __LINE__, myTopology.nodeid, myIdentity.instance,
                    dlsym_error);
             return;
         }
         dlerror();
         string funcNameDestroy = inmsg.procname + "_destroy";
         spclassdestroy call_func1destroy =
             (spclassdestroy) dlsym(soPtr, funcNameDestroy.c_str());
         dlsym_error = dlerror();
         if (dlsym_error)
         {
             return;
         }
         dlerror();
         class MessageUserSchema msg;
         msg.messageStruct.topic = TOPIC_PROCEDURE2;
         msg.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msg.userschemaStruct.domainid = inmsg.userschemaStruct.domainid;
         msg.procs.procedurecreator = (void *)call_func1create;
         msg.procs.proceduredestroyer = (void *)call_func1destroy;
         msg.userschemaStruct.intdata = inmsg.procname.length();
         msg.argstring.assign(inmsg.procname, 0, msg.userschemaStruct.intdata);
         for (size_t n=0; n < myTopology.allActors[myTopology.nodeid].size(); n++)
         {
             if (myTopology.allActors[myTopology.nodeid][n]==
                 ACTOR_TRANSACTIONAGENT)
             {
                 class MessageUserSchema *nmsg = new class MessageUserSchema;
                 *nmsg = msg;
                 mboxes.toActor(myIdentity.address, {myTopology.nodeid,
                             (int16_t)n}, *nmsg);
             }
         }
     }
     break;
     case 3:
     {
         class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
         domainidsToProcedures[msgrcvref.userschemaStruct.domainid][msgrcvref.argstring] = msgrcvref.procs;
     }
     break;
     default:
         fprintf(logfile, "anomaly: %lu %s %i\n", entrypoint, __FILE__, __LINE__);
     }
 }
void TransactionAgent::newstatement ()
called by compile to compile SQL statement
Definition at line 1764 of file TransactionAgent.cc.
References MessageUserSchema::argstring, MessageUserSchema::userschema_s::domainid, domainidsToSchemata, msgrcv, MessageUserSchema::procname, Statement::resolveTableFields(), Larxer::statementPtr, statements, and MessageUserSchema::userschemaStruct.
Referenced by TransactionAgent().
 {
     class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
     class Larxer lx((char *)msgrcvref.argstring.c_str(), this,
                     domainidsToSchemata[msgrcvref.userschemaStruct.domainid]);
     if (lx.statementPtr==NULL)
     {
         printf("%s %i anomaly\n", __FILE__, __LINE__);
     }
     lx.statementPtr->resolveTableFields();
     statements[msgrcvref.userschemaStruct.domainid][msgrcvref.procname] =
         *lx.statementPtr;
     delete lx.statementPtr;
 }
void TransactionAgent::ping (builtincmds_e cmd)
ping operation
sends an empty response–used for testing functionality
Parameters
cmd not used
Definition at line 640 of file TransactionAgent.cc.
References sendResponse(), and STATUS_OK.
Referenced by TransactionAgent().
 {
     vector<string> rv;
     sendResponse(false, STATUS_OK, &rv);
 }
int64_t TransactionAgent::readSocket ()
read socket on raw interface
Returns
Definition at line 596 of file TransactionAgent.cc.
References args, operation, PAYLOADSIZE, and sockfd.
Referenced by TransactionAgent().
 {
     char inbuf[PAYLOADSIZE];
     ssize_t bytesread = read(sockfd, inbuf, PAYLOADSIZE);
     if (bytesread < 8)
     {
         return -1;
     }
     uint64_t a;
     memcpy(&a, inbuf, sizeof(a));
     int64_t msgsize = be64toh(a);
     if (bytesread-8 != msgsize)
     {
         printf("%s %i bytesread %li msgsize %li sockfd %i\n", __FILE__, __LINE__,
                bytesread, msgsize, sockfd);
         return -2;
     }
     char operationlength = inbuf[8];
     if ((int)operationlength >= msgsize-1)
     {
         return -3;
     }
     int64_t localargsize = msgsize - 1 - (int)operationlength;
     operation->assign(inbuf+9, (int)operationlength);
     memset(&args, 0, PAYLOADSIZE);
     memcpy(args, inbuf+9+(int)operationlength, localargsize);
     return localargsize;
 }
void TransactionAgent::schemaBoilerplate (builtincmds_e cmd, int builtin)
common code for many operations, such as login, create table, etc
Parameters
cmd continuation entry point
builtin command to work on
Definition at line 1201 of file TransactionAgent.cc.
References Topology::partitionAddress::address, args, MessageUserSchema::userschema_s::argsize, argsize, MessageUserSchema::argstring, BUILTIN_STATUS_OK, MessageUserSchema::userschema_s::builtincmd, domainid, MessageUserSchema::userschema_s::domainid, endOperation(), MessageUserSchema::userschema_s::fieldid, MessageUserSchema::userschema_s::fieldlen, MessageUserSchema::userschema_s::fieldtype, Operation::getid(), MessageUserSchema::userschema_s::indexid, MessageUserSchema::userschema_s::indextype, MessageUserSchema::userschema_s::instance, instance, logfile, mboxes, Message::messageStruct, msgrcv, schemastruct::msgwaits, myIdentity, MessageUserSchema::userschema_s::numfields, operationid, MessageUserSchema::userschema_s::operationid, operationPtr, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, responseVector, Operation::schemaData, sendResponse(), Operation::setbuiltincmd(), MessageUserSchema::userschema_s::simple, STARTCMD, schemastruct::state, MessageUserSchema::userschema_s::status, STATUS_NOTOK, STATUS_OK, MessageUserSchema::userschema_s::tableid, MessageUserSchema::userschema_s::tableindexid, tasengines, TASENGINESRESPONSECMD, Mboxes::toAllOfType(), Message::message_s::topic, TOPIC_SCHEMAREQUEST, Mboxes::toUserSchemaMgr(), userid, MessageUserSchema::userschemaStruct, usm, and USMRESPONSECMD.
Referenced by addcolumn(), createschema(), createtable(), deleteindex(), deleteschema(), and deletetable().
 {
     switch (cmd)
     {
     case STARTCMD:
     {
         operationPtr = new class Operation(OP_SCHEMA, this, userid, domainid);
         operationPtr->setbuiltincmd(builtin);
         operationid = operationPtr->getid();
         operationPtr->schemaData.state = usm;
         class MessageUserSchema *msg =
             new class MessageUserSchema(TOPIC_SCHEMAREQUEST);
         class MessageUserSchema &msgref = *msg;
         msgref.messageStruct.topic = TOPIC_SCHEMAREQUEST;
         msgref.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msgref.userschemaStruct.builtincmd = builtin;
         msgref.userschemaStruct.argsize = argsize;
         msgref.userschemaStruct.instance = instance;
         msgref.userschemaStruct.operationid = operationid;
         msgref.userschemaStruct.userid = userid;
         msgref.userschemaStruct.domainid = domainid;
         msgref.argstring.assign(args, 0, argsize);
         mboxes.toUserSchemaMgr(this->myIdentity.address, msgref);
     }
     break;
     case USMRESPONSECMD:
     {
         class MessageUserSchema &msgrcvref =
             *(class MessageUserSchema *)msgrcv;
         if (msgrcvref.userschemaStruct.status != BUILTIN_STATUS_OK)   // abort
         {
             responseVector.clear();
             sendResponse(false, STATUS_NOTOK, &responseVector);
             endOperation();
             return;
         }
         class MessageUserSchema msg(TOPIC_SCHEMAREQUEST);
         msg.messageStruct.topic = TOPIC_SCHEMAREQUEST;
         msg.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msg.userschemaStruct.tableid = msgrcvref.userschemaStruct.tableid;
         msg.userschemaStruct.builtincmd = builtin;
         msg.userschemaStruct.instance = instance;
         msg.userschemaStruct.operationid = operationid;
         msg.userschemaStruct.domainid = domainid;
         msg.userschemaStruct.fieldtype = msgrcvref.userschemaStruct.fieldtype;
         msg.userschemaStruct.fieldlen = msgrcvref.userschemaStruct.fieldlen;
         if (msgrcvref.userschemaStruct.argsize)
         {
             msg.userschemaStruct.argsize = msgrcvref.userschemaStruct.argsize;
             msg.argstring.assign(args, 0, argsize);
         }
         else
         {
             msg.argstring=msgrcvref.argstring;
         }
         msg.userschemaStruct.indextype = msgrcvref.userschemaStruct.indextype;
         msg.userschemaStruct.indexid = msgrcvref.userschemaStruct.indexid;
         msg.userschemaStruct.tableindexid =
             msgrcvref.userschemaStruct.tableindexid;
         msg.userschemaStruct.simple = msgrcvref.userschemaStruct.simple;
         msg.userschemaStruct.fieldid = msgrcvref.userschemaStruct.fieldid;
         msg.userschemaStruct.numfields = msgrcvref.userschemaStruct.numfields;
         operationPtr->schemaData.msgwaits = mboxes.toAllOfType(
             ACTOR_TRANSACTIONAGENT, myIdentity.address, msg);
         operationPtr->schemaData.msgwaits += mboxes.toAllOfType(
             ACTOR_ENGINE, myIdentity.address, msg);
         operationPtr->schemaData.state = tasengines;
     }
     break;
     case TASENGINESRESPONSECMD:
     {
         class MessageUserSchema &msgrcvref =
             *(class MessageUserSchema *)msgrcv;
         if (msgrcvref.userschemaStruct.status != BUILTIN_STATUS_OK)
         {
             responseVector.clear();
             sendResponse(false, STATUS_NOTOK, &responseVector);
             endOperation();
             return;
         }
         if (--operationPtr->schemaData.msgwaits)
         {
             // not ready yet
             return;
         }
         sendResponse(false, STATUS_OK, &responseVector);
         endOperation();
     }
     break;
     default:
         fprintf(logfile, "bad case %i %s %i\n", cmd, __FILE__, __LINE__);
     }
 }
template<typename T > void TransactionAgent::sendResponse (bool resending, int64_t resultCode, T response) inline
send raw protocol TCP responses to builtins, ping, login, logout, etc.
Parameters
resending
resultCode
response
Definition at line 375 of file TransactionAgent.h.
References endConnection(), epollfd, makeSbuf(), payload, PAYLOADSIZE, responseData::responseVector, responseData::resultCode, responseData::sbuf, sockfd, and waitingToSend.
Referenced by changepassword(), compile(), createdomain(), createuser(), deletedomain(), deleteuser(), login(), logout(), newprocedure(), ping(), schemaBoilerplate(), ApiInterface::sendResponse(), and TransactionAgent().
     {
         msgpack::sbuffer *sbuf = makeSbuf(response);
         int64_t totalsize = 2*sizeof(uint64_t) + sbuf->size();
         char payload[PAYLOADSIZE];
         uint64_t x = htobe64((uint64_t)totalsize);
         memcpy(payload, &x, sizeof(x));
         x = htobe64((uint64_t)resultCode);
         memcpy(payload + sizeof(x), &x, sizeof(x));
         memcpy(payload+(2*sizeof(x)), sbuf->data(), sbuf->size());
         ssize_t totalwritten = write(sockfd, payload, totalsize);
         if (totalwritten == totalsize)   // send was successful
         {
             if (resending)
             {
                 waitingToSend.erase(sockfd);
             }
             delete sbuf;
             return;
         }
         if (totalwritten == -1)
         {
             if (errno==EAGAIN || errno==EWOULDBLOCK)
             {
                 // we wait for a time to send the data
                 sendLaterMap::iterator sendLaterIterator;
                 sendLaterIterator = waitingToSend.find(sockfd);
                 if (sendLaterIterator != waitingToSend.end()) //gratuitous
                 {
                     printf("%s %i endConnection\n", __FILE__, __LINE__);
                     endConnection();
                     return;
                 }
                 if (!resending)
                 {
                     responseData resp;
                     resp.resultCode = resultCode;
                     resp.sbuf = sbuf;
                     resp.responseVector = NULL;
                     waitingToSend[sockfd] = resp;
                 }
                 struct epoll_event ev;
                 ev.events = EPOLLIN | EPOLLOUT | EPOLLHUP | EPOLLET;
                 ev.data.fd = sockfd;
                 if (epoll_ctl(epollfd, EPOLL_CTL_MOD, sockfd, &ev))
                 {
                     printf("%s %i endConnection\n", __FILE__, __LINE__);
                     endConnection();
                 }
             }
             else
             {
                 perror("oops");
                 endConnection();
             }
             return;
         }
     }
void TransactionAgent::TAaddcolumn ()
continuation for addcolumn
Definition at line 1151 of file TransactionAgent.cc.
References Table::addfield(), MessageUserSchema::argstring, BUILTIN_STATUS_OK, MessageUserSchema::userschema_s::domainid, domainidsToSchemata, MessageUserSchema::userschema_s::fieldid, MessageUserSchema::userschema_s::fieldlen, MessageUserSchema::userschema_s::fieldtype, MessageUserSchema::userschema_s::indextype, Message::messageStruct, msgrcv, Message::message_s::sourceAddr, status, MessageUserSchema::userschema_s::tableid, Schema::tables, MessageUserSchema::userschemaStruct, and usmReply().
Referenced by TransactionAgent().
 {
     class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
     class Schema *schemaPtr =
         domainidsToSchemata[msgrcvref.userschemaStruct.domainid];
     class Table *tablePtr =
         schemaPtr->tables[msgrcvref.userschemaStruct.tableid];
     class MessageUserSchema *msg =
         new class MessageUserSchema(TOPIC_SCHEMAREPLY);
     class MessageUserSchema &msgref = *msg;
     msgref.userschemaStruct.fieldid =
         tablePtr->addfield((fieldtype_e) msgrcvref.userschemaStruct.fieldtype,
                            msgrcvref.userschemaStruct.fieldlen,
                            msgrcvref.argstring,
                            (indextype_e) msgrcvref.userschemaStruct.indextype);
     status = BUILTIN_STATUS_OK;
     TransactionAgent::usmReply(this,
                                ((class Message *)msgrcv)->messageStruct.sourceAddr, *msg);
 }
void TransactionAgent::TAcreateschema ()
continuation function for createschema
Definition at line 1126 of file TransactionAgent.cc.
References createSchema(), domainidsToProcedures, Message::messageStruct, msgrcv, Message::message_s::sourceAddr, and usmReply().
Referenced by TransactionAgent().
 {
     createSchema(this);
     class MessageUserSchema *msg =
         new class MessageUserSchema(TOPIC_SCHEMAREPLY);
     TransactionAgent::usmReply(this, msgrcv->messageStruct.sourceAddr, *msg);
     domainProceduresMap domainProcedures;
     int64_t did = ((class MessageUserSchema *)msgrcv)->userschemaStruct.domainid;
     domainidsToProcedures[did] = domainProcedures;
 }
void TransactionAgent::TAcreatetable ()
continuation for createtable
Definition at line 1137 of file TransactionAgent.cc.
References MessageUserSchema::userschema_s::domainid, domainidsToSchemata, Message::messageStruct, msgrcv, Message::message_s::sourceAddr, status, MessageUserSchema::userschema_s::tableid, MessageUserSchema::userschemaStruct, and usmReply().
Referenced by TransactionAgent().
 {
     // either succeeds or fails :-)
     class MessageUserSchema &msgrcvref = *(class MessageUserSchema *)msgrcv;
     status =
         domainidsToSchemata[msgrcvref.userschemaStruct.domainid]->createTable(msgrcvref.userschemaStruct.tableid);
     class MessageUserSchema *msg =
         new class MessageUserSchema(TOPIC_SCHEMAREPLY);
     class MessageUserSchema &msgref = *msg;
     msgref.userschemaStruct.tableid = msgrcvref.userschemaStruct.tableid;
     TransactionAgent::usmReply(this,
                                ((class Message *)msgrcv)->messageStruct.sourceAddr, *msg);
 }
void TransactionAgent::TAdeleteindex ()
continuation for deleteindex
Definition at line 1171 of file TransactionAgent.cc.
References BUILTIN_STATUS_OK, Message::messageStruct, msgrcv, Message::message_s::sourceAddr, status, and usmReply().
Referenced by TransactionAgent().
 {
     // either succeeds or fails :-)
     class MessageUserSchema *msg =
         new class MessageUserSchema(TOPIC_SCHEMAREPLY);
     status = BUILTIN_STATUS_OK;
     TransactionAgent::usmReply(this,
                                msgrcv->messageStruct.sourceAddr, *msg);
 }
void TransactionAgent::TAdeleteschema ()
continuation for deleteschema
Definition at line 1191 of file TransactionAgent.cc.
References BUILTIN_STATUS_OK, Message::messageStruct, msgrcv, Message::message_s::sourceAddr, status, and usmReply().
Referenced by TransactionAgent().
 {
     // either succeeds or fails :-)
     class MessageUserSchema *msg =
         new class MessageUserSchema(TOPIC_SCHEMAREPLY);
     status = BUILTIN_STATUS_OK;
     TransactionAgent::usmReply(this,
                                msgrcv->messageStruct.sourceAddr, *msg);
 }
void TransactionAgent::TAdeletetable ()
continuation for deletetable
Definition at line 1181 of file TransactionAgent.cc.
References BUILTIN_STATUS_OK, Message::messageStruct, msgrcv, Message::message_s::sourceAddr, status, and usmReply().
Referenced by TransactionAgent().
 {
     // either succeeds or fails :-)
     class MessageUserSchema *msg =
         new class MessageUserSchema(TOPIC_SCHEMAREPLY);
     status = BUILTIN_STATUS_OK;
     TransactionAgent::usmReply(this,
                                msgrcv->messageStruct.sourceAddr, *msg);
 }
void TransactionAgent::TAloadprocedure ()
continuation for loadprocedure
void TransactionAgent::updateReplicas ()
update Topology of replicas
Definition at line 1378 of file TransactionAgent.cc.
References Topology::addressStruct::actorid, Topology::partitionAddress::address, Topology::partitionAddress::instance, myIdentity, mymember, myreplica, myTopology, Topology::addressStruct::nodeid, Topology::numreplicas, replicaAddress, replicaAddresses, Topology::replicaMembers, and Topology::tas.
Referenced by TransactionAgent().
 {
     // replicaMembers[replica][member] = nodeid
     //  vector< vector<int64_t> > replicaMembers;
     // tas[nodeid][tainstance] = actorid
     //  vector< vector<int64_t> > tas;
     // get ta instance based on my actorid, then build the replica members
     // if replicas > 2, or just find the other one if numreplicas==2
     // find my replica
     if (myTopology.numreplicas <= 1)
     {
         return;
     }
     for (size_t n=0; n < myTopology.replicaMembers.size(); n++)
     {
         for (size_t m=0; m < myTopology.replicaMembers[n].size(); m++)
         {
             if (myTopology.replicaMembers[n][m]==myIdentity.address.nodeid)
             {
                 myreplica = n;
                 mymember = m;
             }
         }
     }
     if (myTopology.numreplicas==2)
     {
         size_t otherreplica = myreplica==0 ? 1 : 0;
         replicaAddress.nodeid =
             myTopology.replicaMembers[otherreplica][mymember];
         int64_t othernodeid = myTopology.replicaMembers[otherreplica][mymember];
         if (othernodeid)
         {
             replicaAddress.actorid =
                 myTopology.tas[othernodeid][myIdentity.instance];
         }
         return;
     }
     vector<Topology::addressStruct> ras;
     for (size_t n=0; n < myTopology.replicaMembers.size(); n++)
     {
         if (myreplica==n)
         {
             continue;
         }
         ras.push_back({myTopology.replicaMembers[n][mymember],
                     myTopology.tas[n][myIdentity.instance]
                     });
     }
     replicaAddresses.swap(ras);
 }
template<typename T > static void TransactionAgent::usmReply (T actor, Topology::addressStruct & dest, class MessageUserSchema & msg) inline static
reply MessageUserSchema to UserSchemaMgr
for builtin functions, ping, login, createindex, and so on
Parameters
actor sending actor
dest UserSchemaMgr address
msg MessageUserSchema
Definition at line 452 of file TransactionAgent.h.
References MessageUserSchema::userschema_s::domainid, Message::messageStruct, MessageUserSchema::userschema_s::operationid, Message::message_s::payloadtype, PAYLOADUSERSCHEMA, MessageUserSchema::userschema_s::status, MessageUserSchema::userschema_s::userid, and MessageUserSchema::userschemaStruct.
Referenced by Engine::addcolumn(), UserSchemaMgr::addcolumn(), UserSchemaMgr::changepassword(), UserSchemaMgr::createdomain(), Engine::createschema(), UserSchemaMgr::createschema(), Engine::createtable(), UserSchemaMgr::createtable(), UserSchemaMgr::createuser(), UserSchemaMgr::deletedomain(), Engine::deleteindex(), UserSchemaMgr::deleteindex(), Engine::deleteschema(), UserSchemaMgr::deleteschema(), Engine::deletetable(), UserSchemaMgr::deletetable(), UserSchemaMgr::deleteuser(), UserSchemaMgr::login(), TAaddcolumn(), TAcreateschema(), TAcreatetable(), TAdeleteindex(), TAdeleteschema(), and TAdeletetable().
     {
         msg.messageStruct.payloadtype = PAYLOADUSERSCHEMA;
         msg.userschemaStruct.operationid = actor->operationid;
         msg.userschemaStruct.domainid = actor->domainid;
         msg.userschemaStruct.userid = actor->userid;
         msg.userschemaStruct.status = actor->status;
         actor->mboxes.toActor(actor->myIdentity.address, dest, msg);
     }
Member Data Documentation
boost::unordered_map<int64_t, class Applier *> TransactionAgent::Appliers
Definition at line 487 of file TransactionAgent.h.
Referenced by Applier::ackedApply(), Applier::Applier(), and TransactionAgent().
char TransactionAgent::args[PAYLOADSIZE]
Definition at line 475 of file TransactionAgent.h.
Referenced by changepassword(), compile(), createdomain(), createuser(), deletedomain(), deleteuser(), ApiInterface::deserialize2Vector(), login(), newprocedure(), readSocket(), and schemaBoilerplate().
int64_t TransactionAgent::argsize
Definition at line 474 of file TransactionAgent.h.
Referenced by changepassword(), compile(), createdomain(), createuser(), deletedomain(), deleteuser(), ApiInterface::deserialize2Vector(), login(), newprocedure(), schemaBoilerplate(), and TransactionAgent().
std::string TransactionAgent::argstring
Definition at line 476 of file TransactionAgent.h.
int TransactionAgent::batchSendCount
Definition at line 492 of file TransactionAgent.h.
int64_t TransactionAgent::domainid
Definition at line 155 of file TransactionAgent.h.
Referenced by changepassword(), compile(), createdomain(), createuser(), deletedomain(), deleteuser(), handledispatch(), newprocedure(), schemaBoilerplate(), and TransactionAgent().
boost::unordered_map<int64_t, domainProceduresMap> TransactionAgent::domainidsToProcedures
Definition at line 485 of file TransactionAgent.h.
Referenced by Statement::branchtotype(), TAcreateschema(), and TransactionAgent().
REUSEMESSAGES domainidToSchemaMap TransactionAgent::domainidsToSchemata
Definition at line 162 of file TransactionAgent.h.
Referenced by compile(), Pg::continueLogin(), handledispatch(), newstatement(), TAaddcolumn(), TAcreatetable(), Transaction::Transaction(), and TransactionAgent().
domainidToSchemaMap::iterator TransactionAgent::domainidsToSchemataIterator
Definition at line 484 of file TransactionAgent.h.
std::string TransactionAgent::domainName
Definition at line 481 of file TransactionAgent.h.
Referenced by newprocedure(), and TransactionAgent().
int TransactionAgent::epollfd
Definition at line 469 of file TransactionAgent.h.
Referenced by endConnection(), sendResponse(), and TransactionAgent().
int64_t TransactionAgent::instance
Definition at line 467 of file TransactionAgent.h.
Referenced by changepassword(), Transaction::checkLock(), Transaction::checkSqlLock(), createdomain(), createuser(), deletedomain(), deleteuser(), login(), schemaBoilerplate(), Transaction::sendTransaction(), and TransactionAgent().
socketAuthInfo TransactionAgent::loggedInUsers
Definition at line 473 of file TransactionAgent.h.
Referenced by endConnection(), login(), and TransactionAgent().
class Mboxes TransactionAgent::mboxes
Definition at line 465 of file TransactionAgent.h.
Referenced by Transaction::abortCmd(), addcolumn(), changepassword(), Transaction::checkLock(), Transaction::checkSqlLock(), Transaction::commit(), compile(), Transaction::continueCommitTransaction(), createdomain(), createtable(), createuser(), deletedomain(), deleteuser(), handledispatch(), login(), newprocedure(), Transaction::rollback(), schemaBoilerplate(), Transaction::sendTransaction(), and TransactionAgent().
class Message* TransactionAgent::msgrcv
Definition at line 160 of file TransactionAgent.h.
Referenced by addcolumn(), Pg::cont(), createtable(), handledispatch(), login(), newprocedure(), newstatement(), schemaBoilerplate(), TAaddcolumn(), TAcreateschema(), TAcreatetable(), TAdeleteindex(), TAdeleteschema(), TAdeletetable(), and TransactionAgent().
Topology::partitionAddress TransactionAgent::myIdentity
Definition at line 464 of file TransactionAgent.h.
Referenced by Transaction::abortCmd(), addcolumn(), changepassword(), Transaction::checkLock(), Transaction::checkSqlLock(), Transaction::commit(), compile(), Transaction::continueCommitTransaction(), createdomain(), createtable(), createuser(), deletedomain(), deleteuser(), handledispatch(), login(), newprocedure(), Pg::pgclosesocket(), Pg::rewritesocket(), Transaction::rollback(), schemaBoilerplate(), Transaction::sendTransaction(), TransactionAgent(), updateReplicas(), and Pg::writesocket().
class Mbox* TransactionAgent::mymboxPtr
Definition at line 468 of file TransactionAgent.h.
size_t TransactionAgent::mymember
Definition at line 495 of file TransactionAgent.h.
Referenced by updateReplicas().
size_t TransactionAgent::myreplica
Definition at line 494 of file TransactionAgent.h.
Referenced by updateReplicas().
class Topology TransactionAgent::myTopology
Definition at line 466 of file TransactionAgent.h.
Referenced by Transaction::commit(), Transaction::continueCommitTransaction(), handledispatch(), newprocedure(), TransactionAgent(), and updateReplicas().
int64_t TransactionAgent::nextapplierid
Definition at line 491 of file TransactionAgent.h.
Referenced by getnextapplierid().
int64_t TransactionAgent::nexttransactionid
Definition at line 490 of file TransactionAgent.h.
Referenced by getnexttransactionid().
std::string* TransactionAgent::operation
Definition at line 472 of file TransactionAgent.h.
Referenced by readSocket(), and TransactionAgent().
int64_t TransactionAgent::operationid
Definition at line 154 of file TransactionAgent.h.
Referenced by changepassword(), createdomain(), createuser(), deletedomain(), deleteuser(), endOperation(), login(), schemaBoilerplate(), and TransactionAgent().
int64_t TransactionAgent::operationidcounter
Definition at line 480 of file TransactionAgent.h.
Referenced by Operation::Operation().
class Operation* TransactionAgent::operationPtr
Definition at line 483 of file TransactionAgent.h.
Referenced by changepassword(), createdomain(), createuser(), deletedomain(), deleteuser(), login(), schemaBoilerplate(), and TransactionAgent().
char TransactionAgent::payload[PAYLOADSIZE]
Definition at line 471 of file TransactionAgent.h.
Referenced by sendResponse().
operationMap TransactionAgent::pendingOperations
Definition at line 478 of file TransactionAgent.h.
Referenced by endOperation(), Operation::handleOperation(), login(), Operation::Operation(), and TransactionAgent().
operationMap::iterator TransactionAgent::pendingOperationsIterator
Definition at line 479 of file TransactionAgent.h.
Referenced by TransactionAgent().
boost::unordered_map<int, class Pg *> TransactionAgent::Pgs
Definition at line 489 of file TransactionAgent.h.
Referenced by Operation::handleOperation(), Pg::Pg(), Pg::pgclosesocket(), and TransactionAgent().
Topology::addressStruct TransactionAgent::replicaAddress
Definition at line 496 of file TransactionAgent.h.
Referenced by Transaction::commit(), and updateReplicas().
std::vector<Topology::addressStruct> TransactionAgent::replicaAddresses
Definition at line 497 of file TransactionAgent.h.
Referenced by Transaction::commit(), and updateReplicas().
std::vector<std::string> TransactionAgent::responseVector
Definition at line 482 of file TransactionAgent.h.
Referenced by addcolumn(), createschema(), createtable(), deleteindex(), deleteschema(), deletetable(), and schemaBoilerplate().
int TransactionAgent::sockfd
Definition at line 470 of file TransactionAgent.h.
Referenced by endConnection(), login(), Operation::Operation(), readSocket(), sendResponse(), ApiInterface::sendResponse(), and TransactionAgent().
boost::unordered_map< int64_t, boost::unordered_map<std::string, class Statement> > TransactionAgent::statements
Definition at line 502 of file TransactionAgent.h.
Referenced by ApiInterface::execStatement(), and newstatement().
int64_t TransactionAgent::status
Definition at line 157 of file TransactionAgent.h.
Referenced by TAaddcolumn(), TAcreatetable(), TAdeleteindex(), TAdeleteschema(), and TAdeletetable().
int64_t TransactionAgent::tainstance
Definition at line 158 of file TransactionAgent.h.
Referenced by TransactionAgent().
boost::unordered_map<int64_t, class Transaction *> TransactionAgent::Transactions
Definition at line 486 of file TransactionAgent.h.
Referenced by Transaction::Transaction(), TransactionAgent(), and Transaction::~Transaction().
int64_t TransactionAgent::userid
Definition at line 156 of file TransactionAgent.h.
Referenced by changepassword(), createdomain(), createuser(), deletedomain(), deleteuser(), schemaBoilerplate(), and TransactionAgent().
sendLaterMap TransactionAgent::waitingToSend
Definition at line 477 of file TransactionAgent.h.
Referenced by sendResponse(), and TransactionAgent().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/TransactionAgent.h
/home/infinisql/build/infinisql/infinisqld/TransactionAgent.cc