InfiniSQL: MboxProducer Class Reference
MboxProducer Class Reference
mailbox producer
#include <Mbox.h>
Public Member Functions
MboxProducer ()
MboxProducer (class Mbox *mboxarg, int16_t nodeidarg)
create mailbox producer
virtual ~MboxProducer ()
void sendMsg (class Message &msgsnd)
produce Message onto mailbox
Public Attributes
class Mbox * mbox
int16_t nodeid
class MessageBatchSerialized * obBatchMsg
class Mboxes * mboxes
Friends
class Mboxes
Detailed Description
mailbox producer
Definition at line 108 of file Mbox.h.
Constructor & Destructor Documentation
MboxProducer::MboxProducer ()
Definition at line 125 of file Mbox.cc.
                            : mbox(NULL), obBatchMsg(NULL)
 {
 }
MboxProducer::MboxProducer (class Mbox * mboxarg, int16_t nodeidarg)
create mailbox producer
Parameters
mboxarg Mbox to put Message object onto
nodeidarg nodeid
Definition at line 129 of file Mbox.cc.
                                                                  :
     mbox(mboxarg), nodeid(nodeidarg), obBatchMsg(NULL)
 {
 }
MboxProducer::~MboxProducer () virtual
Definition at line 134 of file Mbox.cc.
 {
 }
Member Function Documentation
void MboxProducer::sendMsg (class Message & msgsnd)
produce Message onto mailbox
Parameters
msgsnd Message
Definition at line 138 of file Mbox.cc.
References Mbox::counter, Message::message_s::destAddr, Mbox::getInt128FromPointer(), Mbox::getPtr(), mbox, mboxes, Message::messageStruct, MessageBatchSerialized::msgbatch, Message::nextmsg, MessageBatchSerialized::nmsgs, Topology::addressStruct::nodeid, nodeid, obBatchMsg, OBGWMSGBATCHSIZE, Mboxes::sendObBatch(), Message::sermsg(), and Mbox::tail.
Referenced by Listener::Listener(), Mboxes::sendObBatch(), Mboxes::toActor(), and Mboxes::toPartition().
 {
     class Message *msgptr;
     if (nodeid != msgsnd.messageStruct.destAddr.nodeid)
     { // must be sending to obgw then, so serialize here
         if (obBatchMsg==NULL)
         {
             obBatchMsg=new class MessageBatchSerialized(nodeid);
         }
         obBatchMsg->msgbatch[obBatchMsg->nmsgs++]=
             {msgsnd.messageStruct.destAddr.nodeid, msgsnd.sermsg()};
         delete &msgsnd;
         if (obBatchMsg->nmsgs==OBGWMSGBATCHSIZE)
         {
             mboxes->sendObBatch();
         }
         return;
     }
     else
     {
         msgptr=&msgsnd;
     }
     class Message &msg=*msgptr;
     msg.nextmsg = Mbox::getInt128FromPointer(NULL, 5555);
     __int128 mytail;
     __int128 mynext;
     while (1)
     {
         mytail = __atomic_load_n(&mbox->tail, __ATOMIC_SEQ_CST);
         mynext = __atomic_load_n(&(Mbox::getPtr(mytail)->nextmsg),
                                  __ATOMIC_SEQ_CST);
         if (mytail == __atomic_load_n(&mbox->tail, __ATOMIC_SEQ_CST))
         {
             if (Mbox::getPtr(mynext) == NULL)
             {
                 if (__atomic_compare_exchange_n(&(Mbox::getPtr(mytail)->nextmsg), &mynext, Mbox::getInt128FromPointer(&msg, __atomic_add_fetch(&mbox->counter, 1, __ATOMIC_SEQ_CST)), false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST))
                 {
                     break;
                 }
             }
             else
             {
                 // CAS(&Q->Tail, tail, <next.ptr, tail.count+1>)
                 __atomic_compare_exchange_n(&mbox->tail, &mytail, Mbox::getInt128FromPointer(Mbox::getPtr(mynext), __atomic_add_fetch(&mbox->counter, 1, __ATOMIC_SEQ_CST)), false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
             }
         }
     }
     __atomic_compare_exchange_n(&mbox->tail, &mytail, Mbox::getInt128FromPointer(&msg, __atomic_add_fetch(&mbox->counter, 1, __ATOMIC_SEQ_CST)), false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
 }
Friends And Related Function Documentation
friend class Mboxes friend
Definition at line 132 of file Mbox.h.
Member Data Documentation
class Mbox* MboxProducer::mbox
Definition at line 127 of file Mbox.h.
Referenced by Mboxes::Mboxes(), and sendMsg().
class Mboxes* MboxProducer::mboxes
Definition at line 130 of file Mbox.h.
Referenced by sendMsg().
int16_t MboxProducer::nodeid
Definition at line 128 of file Mbox.h.
Referenced by sendMsg().
class MessageBatchSerialized* MboxProducer::obBatchMsg
Definition at line 129 of file Mbox.h.
Referenced by sendMsg(), and Mboxes::sendObBatch().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Mbox.h
/home/infinisql/build/infinisql/infinisqld/Mbox.cc