InfiniSQL: Statement Class Reference
Statement Class Reference
contains all necessary information to execute a SQL statement
#include <Asts.h>
Classes
struct column_s
FROM clause column.
struct inobject_s
IN (or NOT IN) row values.
struct orderbyitem_s
ORDER BY fields and order.
struct query_s
all elements for a main or sub-query
struct reentry_s
continuation destination
struct results_s
results of evaulations during query execution, including final results
Public Types
enum direction_e { FROM_ABOVE = 1, FROM_LEFT = 2, FROM_RIGHT = 3 }
Ast walking direction.
Public Member Functions
Statement ()
Statement (class TransactionAgent *taPtrarg, class Schema *schemaPtrarg)
create Statement object
Statement (const Statement &orig)
Statement & operator= (const Statement &orig)
void cp (const Statement &orig)
deep copy of Statement
virtual ~Statement ()
query_s cpquery (const query_s &orig)
deep copy of query_s instance
bool resolveTableFields ()
resolves table and field names to integers
bool resolveTableFields2 ()
bool resolveFieldNames (class Ast *myPosition)
int64_t getfieldid (int64_t tableid, const string &fieldName)
returns fieldid
bool stagedPredicate (operatortypes_e op, int64_t tableid, string &leftoperand, string &rightoperand, vector< fieldValue_s > &inValues, const boost::unordered_map< uuRecord_s, stagedRow_s > &stagedRows, boost::unordered_map< uuRecord_s, returnRow_s > &results)
void andPredicate (operatortypes_e op, int64_t tableid, string &leftoperand, string &rightoperand, vector< fieldValue_s > &inValues, const boost::unordered_map< uuRecord_s, returnRow_s > &andResults, boost::unordered_map< uuRecord_s, returnRow_s > &results)
void execute (class ApiInterface *reentryObject, apifPtr reentryfptr, int64_t reentrypoint, void *reentrydata, class Transaction *transactionPtrarg, const vector< string > &parametersarg)
execute SQL statement
void searchExpression (int64_t entrypoint, class Ast *astNode)
perform search expression
void branchtotype ()
SELECT, INSERT, UPDATE, DELETE, stored proc branch to.
void reenter (int64_t status)
return to calling function (Statement execution complete)
void continueSelect (int64_t entrypoint, class Ast *ignorethis)
continuation for SELECT statement
void continueDelete (int64_t entrypoint, class Ast *ignorethis)
continuation for DELETE statement
void continueInsert (int64_t entrypoint, class Ast *ignorethis)
continuation for INSERT statement
void continueUpdate (int64_t entrypoint, class Ast *ignorethis)
continuation for UPDATE statement
void startQuery ()
begin query execution
void subqueryScalar (class Ast *astnode)
subquery that returns a scalar
void subqueryUnique (class Ast *astnode)
UNIQUE type of subquery.
void subqueryExists (class Ast *astnode)
EXISTS subquery.
void subqueryIn (class Ast *astnode)
subquery returns list of values for IN predicate
void abortQuery (int64_t status)
g-bye
Public Attributes
class TransactionAgent * taPtr
class Schema * schemaPtr
reentry_s reentry
class Transaction * transactionPtr
query_s * currentQuery
std::vector< query_s > queries
std::vector< std::string > parameters
ssize_t queryindex
Detailed Description
contains all necessary information to execute a SQL statement
Definition at line 156 of file Asts.h.
Member Enumeration Documentation
enum Statement::direction_e
Ast walking direction.
Enumerator
FROM_ABOVE
FROM_LEFT
FROM_RIGHT
Definition at line 256 of file Asts.h.
     {
         FROM_ABOVE = 1,
         FROM_LEFT = 2,
         FROM_RIGHT = 3
     };
Constructor & Destructor Documentation
Statement::Statement ()
Definition at line 1989 of file Asts.cc.
 {
 }
Statement::Statement (class TransactionAgent * taPtrarg, class Schema * schemaPtrarg)
create Statement object
Parameters
taPtrarg associated TransactionAgent
schemaPtrarg associated Schema
Definition at line 1993 of file Asts.cc.
References reentry.
                                                  :
     taPtr(taPtrarg), schemaPtr(schemaPtrarg), transactionPtr(NULL),
     currentQuery(NULL)
 {
     reentry = reentry_s();
 }
Statement::Statement (const Statement & orig)
Definition at line 2001 of file Asts.cc.
References cp().
 {
     cp(orig);
 }
Statement::~Statement () virtual
Definition at line 2097 of file Asts.cc.
References Statement::inobject_s::expressionlist, Statement::query_s::fieldidAssignments, Statement::query_s::inobject, Statement::query_s::insertColumns, queries, and Statement::query_s::searchCondition.
 {
     for (size_t n=0; n < queries.size(); n++)
     {
         query_s &queryRef = queries[n];
         if (queryRef.searchCondition != NULL)
         {
             delete queryRef.searchCondition;
         }
         for (size_t m=0; m < queryRef.inobject.expressionlist.size(); m++)
         {
             delete queryRef.inobject.expressionlist[m];
         }
         boost::unordered_map<int64_t, class Ast *>::iterator it;
         for (it = queryRef.fieldidAssignments.begin();
              it != queryRef.fieldidAssignments.end(); it++)
         {
             delete it->second;
         }
         for (size_t m=0; m < queryRef.insertColumns.size(); m++)
         {
             delete queryRef.insertColumns[m];
         }
     }
 }
Member Function Documentation
void Statement::abortQuery (int64_t status)
g-bye
Parameters
status status code returned to caller
Definition at line 5803 of file Asts.cc.
References reenter().
Referenced by Transaction::continueSqlDelete(), Transaction::continueSqlInsert(), Transaction::continueSqlPredicate(), Transaction::continueSqlReplace(), Transaction::continueSqlUpdate(), and continueUpdate().
 {
     // entire transaction should be rolled back if non-zero status
     reenter(status);
 }
void Statement::andPredicate (operatortypes_e op, int64_t tableid, string & leftoperand, string & rightoperand, vector< fieldValue_s > & inValues, const boost::unordered_map< uuRecord_s, returnRow_s > & andResults, boost::unordered_map< uuRecord_s, returnRow_s > & results)
not yet functional, possibly gratuitous, redundant to stagedPredicate
Definition at line 3472 of file Asts.cc.
References BOOL, fieldInput_u::boolean, CHAR, fieldInput_u::character, CHARX, compareFields(), Table::fields, FLOAT, fieldInput_u::floating, INT, fieldInput_u::integer, fieldValue_s::isnull, like2Regex(), logfile, OPERAND_FIELDID, OPERATOR_BETWEEN, OPERATOR_EQ, OPERATOR_GT, OPERATOR_GTE, OPERATOR_IN, OPERATOR_ISNOTNULL, OPERATOR_ISNULL, OPERATOR_LIKE, OPERATOR_LT, OPERATOR_LTE, OPERATOR_NE, OPERATOR_NOTBETWEEN, OPERATOR_NOTIN, OPERATOR_NOTLIKE, returnRow_s::row, schemaPtr, fieldValue_s::str, Schema::tables, Ast::toFloat(), UINT, fieldInput_u::uinteger, Table::unmakerow(), fieldValue_s::value, and VARCHAR.
Referenced by Ast::evaluate().
 {
     if (leftoperand[0] != OPERAND_FIELDID)
     {
         printf("%s %i left operand is not fieldid, it is %c\n", __FILE__,
                __LINE__, leftoperand[0]);
         return;
     }
     int64_t fieldid;
     memcpy(&fieldid, &leftoperand[1], sizeof(fieldid));
     class Table &tableRef = *schemaPtr->tables[tableid];
     vector<fieldValue_s> fieldValues;
     boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
     for (it = andResults.begin(); it != andResults.end(); it++)
     {
         const uuRecord_s &uurRef = it->first;
         const returnRow_s &returnRowRef = it->second;
         tableRef.unmakerow((string *)&returnRowRef.row, &fieldValues);
         fieldValue_s &lhs = fieldValues[fieldid];
         switch (tableRef.fields[fieldid].type)
         {
         case INT:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer==rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer!=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer>rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer<rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer>=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer<=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 int64_t rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.integer >= rhsval && lhs.value.integer <= rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 int64_t rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.integer < rhsval || lhs.value.integer > rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 /* do after AST is walkable since inobject contains a
                  * vector of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = returnRowRef;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 // do after AST is walkable since inobject contains a vector of Ast *
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = returnRowRef;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
             }
         }
         break;
         case UINT:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.uinteger==rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.uinteger!=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.uinteger>rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.uinteger<rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.uinteger>=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.uinteger<=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 uint64_t rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.uinteger >= rhsval && lhs.value.uinteger <=
                     rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 uint64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 uint64_t rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.uinteger < rhsval || lhs.value.uinteger > rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = returnRowRef;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 // do after AST is walkable since inobject contains a vector of Ast *
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = returnRowRef;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
             }
         }
         break;
         case BOOL:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean==rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean!=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean>rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean<rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean>=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean<=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 bool rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.boolean >= rhsval && lhs.value.boolean <= rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 bool rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.boolean < rhsval || lhs.value.boolean > rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 // why do IN on a bool field?
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = returnRowRef;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 // why do NOT IN on a bool field?
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = returnRowRef;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
             }
         }
         break;
         case FLOAT:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating==rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating!=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating>rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating<rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating>=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating<=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 long double rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.floating >= rhsval && lhs.value.floating <=
                     rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 long double rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.floating < rhsval || lhs.value.floating > rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = returnRowRef;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = returnRowRef;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
             }
         }
         break;
         case CHAR:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character==rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character!=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character>rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character<rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character>=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character<=rhsval)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 char rhsval=rightoperand[1+sizeof(int64_t)];
                 char rhsval2=rightoperand[1+sizeof(int64_t)+1];
                 if (lhs.value.character >= rhsval && lhs.value.character <=
                     rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 char rhsval=rightoperand[1+sizeof(int64_t)];
                 char rhsval2=rightoperand[1+sizeof(int64_t)+1];
                 if (lhs.value.character < rhsval || lhs.value.character >
                     rhsval2)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = returnRowRef;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = returnRowRef;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
             }
         }
         break;
         case CHARX:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (!lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = returnRowRef;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = returnRowRef;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LIKE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 like2Regex(rhsval);
                 pcrecpp::RE re(rhsval);
                 if (re.FullMatch(lhs.str)==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NOTLIKE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 like2Regex(rhsval);
                 pcrecpp::RE re(rhsval);
                 rhsval.insert(0, "^((?!");
                 rhsval.append(").)*$");
                 if (re.FullMatch(lhs.str)==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
             }
         }
         break;
         case VARCHAR:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (!lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = returnRowRef;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 /* do after AST is walkable since inobject contains a vector
                  * of Ast */
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
                 for (it = andResults.begin(); it != andResults.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const returnRow_s &returnRowRef = it->second;
                     tableRef.unmakerow((string *)&returnRowRef.row,
                                        &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = returnRowRef;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_LIKE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 like2Regex(rhsval);
                 pcrecpp::RE re(rhsval);
                 if (re.FullMatch(lhs.str)==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             case OPERATOR_NOTLIKE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 like2Regex(rhsval);
                 pcrecpp::RE re(rhsval);
                 rhsval.insert(0, "^((?!");
                 rhsval.append(").)*$");
                 if (re.FullMatch(lhs.str)==true)
                 {
                     results[uurRef] = returnRowRef;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
             }
         }
         break;
         default:
             fprintf(logfile, "anomaly: %i %s %i\n",
                     tableRef.fields[fieldid].type, __FILE__, __LINE__);
         }
     }
 }
void Statement::branchtotype ()
SELECT, INSERT, UPDATE, DELETE, stored proc branch to.
Definition at line 4908 of file Asts.cc.
References APISTATUS_NOTOK, APISTATUS_NULLCONSTRAINT, APISTATUS_PENDING, BOOL, fieldInput_u::boolean, CHAR, fieldInput_u::character, CHARX, CMD_BEGIN, CMD_COMMIT, CMD_DELETE, CMD_INSERT, CMD_ROLLBACK, CMD_SELECT, CMD_STOREDPROCEDURE, CMD_UPDATE, continueDelete(), continueSelect(), continueUpdate(), currentQuery, Schema::domainid, TransactionAgent::domainidsToProcedures, Table::fields, FLOAT, Transaction::getengine(), Transaction::getnextpendingcmdid(), Statement::query_s::haswhere, Field::indextype, Statement::query_s::insertColumns, Statement::results_s::insertValues, INT, fieldInput_u::integer, fieldValue_s::isnull, Statement::query_s::locktype, Table::makerow(), Statement::results_s::newrow, NEWROW, Statement::results_s::newrowengineid, NOCOMMAND, NONUNIQUENOTNULL, Ast::operand, OPERAND_NULL, PAYLOADSUBTRANSACTION, Transaction::pendingcmd, Transaction::pendingcmdid, PRIMITIVE_SQLINSERT, PRIMITIVE_SQLSELECTALL, PRIMITIVE_SQLSELECTALLFORDELETE, PRIMITIVE_SQLSELECTALLFORUPDATE, procedures_s::procedurecreator, procedures_s::proceduredestroyer, reenter(), reentry, Statement::reentry_s::reentryObject, Statement::query_s::results, ApiInterface::results, MessageSubtransactionCmd::row, schemaPtr, searchExpression(), Statement::results_s::searchResults, Transaction::sendTransaction(), Transaction::sqlcmdstate, Transaction::sqlSelectAll(), stagedRow2ReturnRow(), Transaction::stagedRows, startQuery(), Transaction::sqlcmdstate_s::statement, STATUS_NOTOK, Statement::query_s::storedProcedure, fieldValue_s::str, MessageSubtransactionCmd::subtransactionStruct, Transaction::sqlcmdstate_s::tableid, Statement::query_s::tableid, MessageSubtransactionCmd::subtransaction_s::tableid, Schema::tables, taPtr, Ast::toFloat(), transactionPtr, Statement::query_s::type, UINT, fieldInput_u::uinteger, UNIQUENOTNULL, UNORDEREDNOTNULL, fieldValue_s::value, VARCHAR, and WRITELOCK.
Referenced by searchExpression(), and startQuery().
 {
     switch (currentQuery->type)
     {
     case CMD_SELECT:
     {
         if (currentQuery->haswhere==false)
         {
             /* select everything, checking existing staged rows first */
             boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
             for (it = transactionPtr->stagedRows.begin();
                  it != transactionPtr->stagedRows.end(); it++)
             {
                 const uuRecord_s &uurRef = it->first;
                 const stagedRow_s &stagedRowRef = it->second;
                 returnRow_s returnRow;
                 stagedRow2ReturnRow(stagedRowRef, returnRow);
                 currentQuery->results.searchResults[uurRef]=returnRow;
             }
             transactionPtr->sqlSelectAll(this, currentQuery->tableid,
                                          currentQuery->locktype,
                                          PRIMITIVE_SQLSELECTALL,
                                          currentQuery->results.searchResults);
         }
         else
         {
             continueSelect(1, NULL);
         }
     }
     break;
     case CMD_INSERT:
     {
         class Table &tableRef = *schemaPtr->tables[currentQuery->tableid];
         size_t numfields = currentQuery->insertColumns.size();
         currentQuery->results.insertValues.reserve(numfields);
         for (size_t n=0; n < numfields; n++)
         {
             fieldValue_s fieldValue = {};
             class Ast &astRef = *currentQuery->insertColumns[numfields-1-n];
             searchExpression(0, &astRef);
             if (astRef.operand[0]==OPERAND_NULL)
             {
                 class Field &fieldRef =
                     tableRef.fields[n];
                 if (fieldRef.indextype==UNIQUENOTNULL ||
                     fieldRef.indextype==NONUNIQUENOTNULL ||
                     fieldRef.indextype==UNORDEREDNOTNULL)
                 {
                     reenter(APISTATUS_NULLCONSTRAINT);
                     return;
                 }
                 fieldValue.isnull=true;
                 currentQuery->results.insertValues.push_back(fieldValue);
             }
             else
             {
                 switch (tableRef.fields[n].type)
                 {
                 case INT:
                     memcpy(&fieldValue.value.integer, &astRef.operand[1],
                            sizeof(int64_t));
                     currentQuery->results.insertValues.push_back(fieldValue);
                     break;
                 case UINT:
                     memcpy(&fieldValue.value.uinteger, &astRef.operand[1],
                            sizeof(int64_t));
                     currentQuery->results.insertValues.push_back(fieldValue);
                     break;
                 case BOOL:
                     if (astRef.operand[1]=='t')
                     {
                         fieldValue.value.boolean=true;
                     }
                     else
                     {
                         fieldValue.value.boolean=false;
                     }
                     currentQuery->results.insertValues.push_back(fieldValue);
                     break;
                 case FLOAT:
                     Ast::toFloat(astRef.operand, fieldValue);
                     currentQuery->results.insertValues.push_back(fieldValue);
                     break;
                 case CHAR:
                     fieldValue.value.character=astRef.operand[1];
                     currentQuery->results.insertValues.push_back(fieldValue);
                     break;
                 case CHARX:
                     fieldValue.str=astRef.operand.substr(1, string::npos);
                     currentQuery->results.insertValues.push_back(fieldValue);
                     break;
                 case VARCHAR:
                     fieldValue.str=astRef.operand.substr(1, string::npos);
                     currentQuery->results.insertValues.push_back(fieldValue);
                     break;
                 default:
                     printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                            tableRef.fields[n].type);
                 }
             }
         }
         if (tableRef.makerow(&currentQuery->results.insertValues,
                              &currentQuery->results.newrow)==false)
         {
             reenter(APISTATUS_NOTOK);
         }
         currentQuery->results.newrowengineid = transactionPtr->getengine(
             tableRef.fields[0].type, currentQuery->results.insertValues[0]);
         if (transactionPtr->pendingcmd != NOCOMMAND)
         {
             reenter(APISTATUS_PENDING);
             return;
         }
         transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
         transactionPtr->pendingcmd = PRIMITIVE_SQLINSERT;
         transactionPtr->sqlcmdstate = (Transaction::sqlcmdstate_s)
             {
                 0
             };
         transactionPtr->sqlcmdstate.statement=this;
         transactionPtr->sqlcmdstate.tableid = currentQuery->tableid;
         class MessageSubtransactionCmd *msg =
             new class MessageSubtransactionCmd();
         class MessageSubtransactionCmd &msgref = *msg;
         msgref.subtransactionStruct.tableid = currentQuery->tableid;
         msgref.row = currentQuery->results.newrow;
         transactionPtr->sendTransaction(NEWROW, PAYLOADSUBTRANSACTION, 1,
                                         currentQuery->results.newrowengineid,
                                         msg);
     }
     break;
     case CMD_UPDATE:
     {
         if (currentQuery->haswhere==false)
         {
             boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
             for (it = transactionPtr->stagedRows.begin();
                  it != transactionPtr->stagedRows.end(); it++)
             {
                 const uuRecord_s &uurRef = it->first;
                 const stagedRow_s &stagedRowRef = it->second;
                 returnRow_s returnRow;
                 stagedRow2ReturnRow(stagedRowRef, returnRow);
                 currentQuery->results.searchResults[uurRef]=returnRow;
             }
             transactionPtr->sqlSelectAll(this, currentQuery->tableid, WRITELOCK,
                                          PRIMITIVE_SQLSELECTALLFORUPDATE,
                                          currentQuery->results.searchResults);
             return;
         }
         else
         {
             continueUpdate(1, NULL);
         }
     }
     break;
     case CMD_DELETE:
     {
         if (currentQuery->haswhere==false)
         {
             boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
             for (it = transactionPtr->stagedRows.begin();
                  it != transactionPtr->stagedRows.end(); it++)
             {
                 const uuRecord_s &uurRef = it->first;
                 const stagedRow_s &stagedRowRef = it->second;
                 returnRow_s returnRow;
                 stagedRow2ReturnRow(stagedRowRef, returnRow);
                 currentQuery->results.searchResults[uurRef]=returnRow;
             }
             transactionPtr->sqlSelectAll(this, currentQuery->tableid, WRITELOCK,
                                          PRIMITIVE_SQLSELECTALLFORDELETE,
                                          currentQuery->results.searchResults);
         }
         else
         {
             continueDelete(1, NULL);
         }
     }
     break;
     case CMD_STOREDPROCEDURE:
     {
         reentry.reentryObject->results.cmdtype = CMD_STOREDPROCEDURE;
         if (taPtr->domainidsToProcedures.count(schemaPtr->domainid))
         {
             domainProceduresMap &procsMapRef =
                 taPtr->domainidsToProcedures[schemaPtr->domainid];
             if (procsMapRef.count(currentQuery->storedProcedure))
             {
                 procedures_s &proceduresRef =
                     procsMapRef[currentQuery->storedProcedure];
                 spclasscreate spC =
                     (spclasscreate)proceduresRef.procedurecreator;
                 spclasscreate spD =
                     (spclasscreate)proceduresRef.proceduredestroyer;
                 // make sure to delete this statement in the procedure!
                 spC(NULL, reentry.reentryObject, (void *)spD);
             }
             else
             {
                 reenter(STATUS_NOTOK);
                 return;
             }
         }
         else
         {
             reenter(STATUS_NOTOK);
             return;
         }
     }
     break;
     case CMD_BEGIN:
         startQuery();
         break;
     case CMD_COMMIT:
         startQuery();
         break;
     case CMD_ROLLBACK:
         startQuery();
         break;
     default:
         printf("%s %i unhandled statement type %i\n", __FILE__, __LINE__,
                currentQuery->type);
         reenter(STATUS_NOTOK);
         return;
     }
 }
void Statement::continueDelete (int64_t entrypoint, class Ast * ignorethis)
continuation for DELETE statement
Parameters
entrypoint
ignorethis
Definition at line 5230 of file Asts.cc.
References stagedRow_s::cmd, currentQuery, DELETE, DELETEROW, uuRecord_s::engineid, MessageSubtransactionCmd::subtransaction_s::engineid, Transaction::sqlcmdstate_s::eventwaitcount, Transaction::getnextpendingcmdid(), stagedRow_s::originalRow, PAYLOADSUBTRANSACTION, Transaction::pendingcmd, Transaction::pendingcmdid, PRIMITIVE_SQLDELETE, Statement::query_s::results, returnRow_s::row, uuRecord_s::rowid, MessageSubtransactionCmd::subtransaction_s::rowid, Statement::results_s::searchResults, Transaction::sendTransaction(), Transaction::sqlcmdstate, Transaction::stagedRows, startQuery(), Transaction::sqlcmdstate_s::statement, MessageSubtransactionCmd::subtransactionStruct, uuRecord_s::tableid, MessageSubtransactionCmd::subtransaction_s::tableid, and transactionPtr.
Referenced by branchtotype(), Transaction::continueSqlDelete(), and Transaction::continueSqlPredicate().
 {
     switch (entrypoint)
     {
     case 1:
     {
         transactionPtr->sqlcmdstate = (Transaction::sqlcmdstate_s)
             {
                 0
             };
         transactionPtr->sqlcmdstate.statement=this;
         transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
         transactionPtr->pendingcmd = PRIMITIVE_SQLDELETE;
         boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
         for (it = currentQuery->results.searchResults.begin();
              it != currentQuery->results.searchResults.end(); it++)
         {
             const uuRecord_s &uurRef = it->first;
             const returnRow_s &returnRowRef = it->second;
             class MessageSubtransactionCmd *msg =
                 new class MessageSubtransactionCmd();
             msg->subtransactionStruct.tableid = uurRef.tableid;
             msg->subtransactionStruct.rowid = uurRef.rowid;
             msg->subtransactionStruct.engineid = uurRef.engineid;
             transactionPtr->sendTransaction(DELETEROW, PAYLOADSUBTRANSACTION, 1,
                                             uurRef.engineid, msg);
             stagedRow_s &stagedRowRef = transactionPtr->stagedRows[uurRef];
             stagedRowRef.cmd=DELETE;
             stagedRowRef.originalRow=returnRowRef.row;
             transactionPtr->stagedRows[uurRef].cmd=DELETE;
         }
         transactionPtr->sqlcmdstate.eventwaitcount =
             currentQuery->results.searchResults.size();
     }
     break;
     case 2:
         startQuery();
         break;
     default:
         printf("%s %i anomaly %li\n", __FILE__, __LINE__, entrypoint);
     }
 }
void Statement::continueInsert (int64_t entrypoint, class Ast * ignorethis)
continuation for INSERT statement
Parameters
entrypoint
ignorethis
Definition at line 5517 of file Asts.cc.
References startQuery().
Referenced by Transaction::continueSqlInsert().
 {
     startQuery();
 }
void Statement::continueSelect (int64_t entrypoint, class Ast * ignorethis)
continuation for SELECT statement
Parameters
entrypoint
ignorethis
Definition at line 5190 of file Asts.cc.
References stagedRow_s::cmd, currentQuery, Statement::query_s::fromColumnids, returnRow_s::locktype, stagedRow_s::locktype, NOCOMMAND, stagedRow_s::originalRow, stagedRow_s::originalrowid, Statement::query_s::results, returnRow_s::row, returnRow_s::rowid, schemaPtr, Statement::results_s::searchResults, Statement::results_s::selectResults, Transaction::stagedRows, startQuery(), Statement::query_s::tableid, Schema::tables, transactionPtr, and Table::unmakerow().
Referenced by branchtotype(), Transaction::continueSqlPredicate(), and Transaction::sqlSelectAll().
 {
     /* there should be nothing special to do for selectall vs predicate search
      * because the searchResults have already been populated
      */
     class Table &tableRef = *schemaPtr->tables[currentQuery->tableid];
     boost::unordered_map<uuRecord_s, returnRow_s>::const_iterator it;
     for (it = currentQuery->results.searchResults.begin();
          it != currentQuery->results.searchResults.end(); it++)
     {
         const uuRecord_s &uurRef = it->first;
         const returnRow_s &returnRowRef = it->second;
         vector<fieldValue_s> foundFields;
         tableRef.unmakerow((string *)&returnRowRef.row, &foundFields);
         vector<fieldValue_s> returnFields;
         for (size_t n=0; n < currentQuery->fromColumnids.size(); n++)
         {
             returnFields.push_back(foundFields[currentQuery->fromColumnids[n].fieldid]);
         }
         currentQuery->results.selectResults[uurRef] = returnFields;
         if (!transactionPtr->stagedRows.count(uurRef))
         {
             stagedRow_s srow = {};
             srow.cmd=NOCOMMAND;
             srow.locktype=returnRowRef.locktype;
             srow.originalRow=returnRowRef.row;
             srow.originalrowid=returnRowRef.rowid;
             transactionPtr->stagedRows[uurRef]=srow;
         }
     }
     startQuery();
 }
void Statement::continueUpdate (int64_t entrypoint, class Ast * ignorethis)
continuation for UPDATE statement
Parameters
entrypoint
ignorethis
Definition at line 5278 of file Asts.cc.
References abortQuery(), APISTATUS_PENDING, BOOL, fieldInput_u::boolean, CHAR, fieldInput_u::character, CHARX, stagedRow_s::cmd, currentQuery, uuRecord_s::engineid, MessageSubtransactionCmd::subtransaction_s::engineid, lockFieldValue_s::engineid, Transaction::sqlcmdstate_s::eventwaitcount, MessageSubtransactionCmd::subtransaction_s::fieldid, Statement::query_s::fieldidAssignments, Table::fields, lockFieldValue_s::fieldVal, MessageSubtransactionCmd::fieldVal, FLOAT, Transaction::getengine(), Transaction::getnextpendingcmdid(), Field::index, INDEXLOCK, INT, fieldInput_u::integer, fieldValue_s::isnull, MessageSubtransactionCmd::subtransaction_s::isrow, Index::isunique, lockFieldValue_s::locktype, stagedRow_s::locktype, Table::makerow(), stagedRow_s::newengineid, NEWROW, stagedRow_s::newRow, Statement::results_s::newrowengineid, stagedRow_s::newrowid, NOCOMMAND, OPERAND_NULL, stagedRow_s::originalengineid, stagedRow_s::originalRow, stagedRow_s::originalrowid, Statement::results_s::originalrowuur, PAYLOADSUBTRANSACTION, Transaction::pendingcmd, Transaction::pendingcmdid, returnRow_s::previoussubtransactionid, stagedRow_s::previoussubtransactionid, PRIMITIVE_SQLREPLACE, PRIMITIVE_SQLUPDATE, Statement::query_s::results, returnRow_s::row, MessageSubtransactionCmd::row, uuRecord_s::rowid, MessageSubtransactionCmd::subtransaction_s::rowid, schemaPtr, Statement::results_s::searchResults, Transaction::sendTransaction(), Statement::results_s::setFields, Transaction::sqlcmdstate, Transaction::stagedRows, startQuery(), Transaction::sqlcmdstate_s::statement, fieldValue_s::str, MessageSubtransactionCmd::subtransactionStruct, uuRecord_s::tableid, Statement::query_s::tableid, MessageSubtransactionCmd::subtransaction_s::tableid, Schema::tables, Ast::toFloat(), transactionPtr, Field::type, UINT, fieldInput_u::uinteger, UNIQUEINDEX, stagedRow_s::uniqueIndices, Table::unmakerow(), UPDATE, Statement::results_s::updateIterator, UPDATEROW, fieldValue_s::value, VARCHAR, and WRITELOCK.
Referenced by branchtotype(), Transaction::continueSqlPredicate(), Transaction::continueSqlReplace(), and Transaction::continueSqlUpdate().
 {
     switch (entrypoint)
     {
     case 1:
     {
         /* walk through each search result, doing update on each one
          * and calling Ast::evaluateAssignment(fieldValues) for each
          * field to modify
          */
         currentQuery->results.updateIterator=
             currentQuery->results.searchResults.begin();
     }
     //    break; fall right through
     case 2:
     {
         /* walk through each search result, doing update on each one
          * and calling Ast::evaluateAssignment(fieldValues) for each
          * field to modify
          */
         if (transactionPtr->pendingcmd != NOCOMMAND)
         {
             printf("%s %i APISTATUS_PENDING pendingcmd %i\n", __FILE__, __LINE__, transactionPtr->pendingcmd);
             abortQuery(APISTATUS_PENDING);
             return;
         }
         transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
         transactionPtr->sqlcmdstate = (Transaction::sqlcmdstate_s)
             {
                 0
             };
         transactionPtr->sqlcmdstate.statement=this;
         class Table &tableRef = *schemaPtr->tables[currentQuery->tableid];
         if (currentQuery->results.updateIterator !=
             currentQuery->results.searchResults.end())
         {
             vector<fieldValue_s> fieldValues;
             const returnRow_s &returnRowRef=
                 currentQuery->results.updateIterator->second;
             tableRef.unmakerow((string *)&returnRowRef.row, &fieldValues);
             // do update stuff
             // boost::unordered_map<int64_t, class Ast *> fieldidAssignments
             boost::unordered_map<int64_t, class Ast *>::iterator it;
             for (it = currentQuery->fieldidAssignments.begin();
                  it != currentQuery->fieldidAssignments.end(); it++)
             {
                 it->second->evaluateAssignment(fieldValues, this);
                 // fieldid is it->first; class Ast * is it->second;
                 class Field &fieldRef = tableRef.fields[it->first];
                 fieldValue_s fieldValue = {};
                 if (it->second->operand[0]==OPERAND_NULL)
                 {
                     fieldValue.isnull=true;
                 }
                 else
                 {
                     switch (fieldRef.type)
                     {
                     case INT:
                         memcpy(&fieldValue.value.integer,
                                &it->second->operand[1],
                                sizeof(int64_t));
                         break;
                     case UINT:
                         memcpy(&fieldValue.value.uinteger,
                                &it->second->operand[1],
                                sizeof(int64_t));
                         break;
                     case BOOL:
                     {
                         int64_t boolval;
                         memcpy(&boolval, &it->second->operand[1],
                                sizeof(int64_t));
                         fieldValue.value.boolean = (bool)boolval;
                     }
                     break;
                     case FLOAT:
                         Ast::toFloat(it->second->operand, fieldValue);
                         break;
                     case CHAR:
                         fieldValue.value.character=it->second->operand[1];
                         break;
                     case CHARX:
                         fieldValue.str=it->second->operand.substr(1,
                                                                   string::npos);
                         break;
                     case VARCHAR:
                         fieldValue.str=it->second->operand.substr(1,
                                                                   string::npos);
                         break;
                     default:
                         printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                                tableRef.fields[it->first].type);
                         return;
                     }
                 }
                 currentQuery->results.setFields[it->first]=fieldValue;
             }
             const uuRecord_s &uurRef=
                 currentQuery->results.updateIterator->first;
             if (!currentQuery->results.setFields.count(0))
             {
                 // update
                 transactionPtr->pendingcmd = PRIMITIVE_SQLUPDATE;
                 stagedRow_s stagedRow= {};
                 vector<fieldValue_s> fieldValues;
                 tableRef.unmakerow((string *)&returnRowRef.row, &fieldValues);
                 for (size_t n=0; n < fieldValues.size(); n++)
                 {
                     class Field &fieldRef = tableRef.fields[n];
                     if (currentQuery->results.setFields.count(n))
                     {
                         fieldValues[n] = currentQuery->results.setFields[n];
                         // index stuff
                         if (fieldRef.index.isunique==true)
{
                             lockFieldValue_s lockFieldValue = {};
                             lockFieldValue.engineid =
                                 transactionPtr->getengine(fieldRef.type,
                                                           fieldValues[n]);
                             // locktype could potentially change
                             lockFieldValue.locktype = INDEXLOCK;
                             lockFieldValue.fieldVal = fieldValues[n];
                             stagedRow.uniqueIndices[n]=lockFieldValue;
                             transactionPtr->sqlcmdstate.eventwaitcount++;
                             class MessageSubtransactionCmd *msg =
                                 new class MessageSubtransactionCmd();
                             msg->subtransactionStruct.isrow = false;
                             msg->subtransactionStruct.tableid = uurRef.tableid;
                             msg->subtransactionStruct.rowid = uurRef.rowid;
                             msg->subtransactionStruct.engineid = uurRef.engineid;
                             msg->subtransactionStruct.fieldid = n;
                             msg->fieldVal = lockFieldValue.fieldVal;
                             transactionPtr->sendTransaction(UNIQUEINDEX,
                                                             PAYLOADSUBTRANSACTION,
                                                             1,
                                                             lockFieldValue.engineid,
                                                             msg);
                         }
                     }
                 }
                 stagedRow.originalRow=returnRowRef.row;
                 stagedRow.originalrowid=uurRef.rowid;
                 stagedRow.newrowid=uurRef.rowid;
                 stagedRow.previoussubtransactionid=
                     returnRowRef.previoussubtransactionid;
                 stagedRow.locktype=WRITELOCK;
                 stagedRow.originalengineid=uurRef.engineid;
                 stagedRow.newengineid=uurRef.engineid;
                 tableRef.makerow(&fieldValues, &stagedRow.newRow);
                 stagedRow.cmd=UPDATE;
                 transactionPtr->stagedRows[uurRef]=stagedRow;
                 transactionPtr->sqlcmdstate.eventwaitcount++;
                 class MessageSubtransactionCmd *msg =
                     new class MessageSubtransactionCmd();
                 msg->subtransactionStruct.tableid = uurRef.tableid;
                 msg->subtransactionStruct.rowid = uurRef.rowid;
                 msg->row = stagedRow.newRow;
                 transactionPtr->sendTransaction(UPDATEROW, PAYLOADSUBTRANSACTION,
                                                 1, uurRef.engineid, msg);
             }
             else
             {
                 //replace
                 stagedRow_s &stagedRowRef = transactionPtr->stagedRows[uurRef];
                 stagedRowRef.cmd=UPDATE;
                 stagedRowRef.originalRow=returnRowRef.row;
                 stagedRowRef.originalrowid=uurRef.rowid;
                 stagedRowRef.originalengineid=uurRef.engineid;
                 stagedRowRef.previoussubtransactionid=
                     returnRowRef.previoussubtransactionid;
                 stagedRowRef.locktype=WRITELOCK;
                 transactionPtr->pendingcmd = PRIMITIVE_SQLREPLACE;
                 currentQuery->results.originalrowuur = uurRef;
                 vector<fieldValue_s> fieldValues;
                 tableRef.unmakerow((string *)&returnRowRef.row, &fieldValues);
                 for (size_t n=0; n < fieldValues.size(); n++)
                 {
                     if (currentQuery->results.setFields.count(n))
                     {
                         fieldValues[n] = currentQuery->results.setFields[n];
                     }
                 }
                 tableRef.makerow(&fieldValues, &stagedRowRef.newRow);
                 currentQuery->results.newrowengineid =
                     transactionPtr->getengine(tableRef.fields[0].type,
                                               fieldValues[0]);
                 stagedRowRef.newengineid=currentQuery->results.newrowengineid;
                 class MessageSubtransactionCmd *msg =
                     new class MessageSubtransactionCmd();
                 class MessageSubtransactionCmd &msgref = *msg;
                 msgref.subtransactionStruct.tableid = currentQuery->tableid;
                 msgref.row = stagedRowRef.newRow;
                 transactionPtr->sendTransaction(NEWROW, PAYLOADSUBTRANSACTION, 1,
                                                 stagedRowRef.newengineid, msg);
             }
             currentQuery->results.updateIterator++;
             return;
         }
         startQuery();
     }
     break;
     default:
         printf("%s %i anomaly %li\n", __FILE__, __LINE__, entrypoint);
     }
 }
void Statement::cp (const Statement & orig)
deep copy of Statement
Parameters
orig source Statement
Definition at line 2013 of file Asts.cc.
References cpquery(), currentQuery, parameters, queries, queryindex, reentry, schemaPtr, taPtr, and transactionPtr.
Referenced by operator=(), and Statement().
 {
     taPtr = orig.taPtr;
     schemaPtr = orig.schemaPtr;
     reentry = orig.reentry;
     transactionPtr = orig.transactionPtr;
     currentQuery = orig.currentQuery;
     for (size_t n=0; n < orig.queries.size(); n++)
     {
         queries.push_back(cpquery(orig.queries[n]));
     }
     parameters = orig.parameters;
     queryindex = orig.queryindex;
 }
Statement::query_s Statement::cpquery (const query_s & orig)
deep copy of query_s instance
Parameters
orig source query_s
Returns
new query_s
Definition at line 2030 of file Asts.cc.
References Statement::inobject_s::expressionlist, Statement::query_s::fieldidAssignments, Statement::query_s::fromColumnids, Statement::query_s::fromColumns, Statement::query_s::groupByList, Statement::query_s::hasgroupby, Statement::query_s::hashaving, Statement::query_s::hasnolock, Statement::query_s::hasorderby, Statement::query_s::haswhere, Statement::query_s::inobject, Statement::query_s::insertColumns, Statement::query_s::instance, Statement::query_s::isforupdate, Statement::inobject_s::issubquery, Statement::query_s::locktype, Statement::query_s::orderbylist, Statement::query_s::searchCondition, Statement::inobject_s::subquery, Statement::query_s::table, Statement::query_s::tableid, and Statement::query_s::type.
Referenced by cp().
 {
     query_s newstmt;
     newstmt.instance = orig.instance;
     newstmt.type = orig.type;
     newstmt.isforupdate = orig.isforupdate;
     newstmt.hasnolock = orig.hasnolock;
     newstmt.haswhere = orig.haswhere;
     newstmt.hasgroupby= orig.hasgroupby;
     newstmt.hashaving = orig.hashaving;
     newstmt.hasorderby = orig.hasorderby;
     newstmt.table = orig.table;
     newstmt.tableid = orig.tableid;
     newstmt.locktype = orig.locktype;
     newstmt.groupByList = orig.groupByList;
     newstmt.fromColumns = orig.fromColumns;
     newstmt.fromColumnids = orig.fromColumnids;
     newstmt.orderbylist = orig.orderbylist;
     newstmt.inobject.issubquery = orig.inobject.issubquery;
     newstmt.inobject.subquery = orig.inobject.subquery;
     size_t siz = orig.inobject.expressionlist.size();
     newstmt.inobject.expressionlist.resize(siz, NULL);
     for (size_t n=0; n < siz; n++)
     {
         newstmt.inobject.expressionlist[n] = new class Ast;
         *newstmt.inobject.expressionlist[n] = *orig.inobject.expressionlist[n];
     }
     if (orig.searchCondition != NULL)
     {
         newstmt.searchCondition = new class Ast;
         *newstmt.searchCondition = *orig.searchCondition;
     }
     else
     {
         newstmt.searchCondition=NULL;
     }
     /* don't copy assignments, as fieldid assumedly has already been
      * resolved, and it makes keeping track of new Ast * objects difficult
      */
     boost::unordered_map<int64_t, class Ast *>::const_iterator it;
     for (it = orig.fieldidAssignments.begin();
          it != orig.fieldidAssignments.end(); it++)
     {
         newstmt.fieldidAssignments[it->first] = new class Ast;
         *newstmt.fieldidAssignments[it->first] = *it->second;
     }
     for (size_t n=0; n < orig.insertColumns.size(); n++)
     {
         newstmt.insertColumns.push_back(new class Ast);
         *newstmt.insertColumns[n] = *orig.insertColumns[n];
     }
     /* results should not need to be copied, as they are created only by
      * an executing statement
      */
     return newstmt;
 }
void Statement::execute (class ApiInterface * reentryObject, apifPtr reentryfptr, int64_t reentrypoint, void * reentrydata, class Transaction * transactionPtrarg, const vector< string > & parametersarg)
execute SQL statement
Parameters
reentryObject object to continue to after execution
reentryfptr function pointer to continue to
reentrypoint entry point to continue to
reentrydata arbitrary data to pass to continuation
transactionPtrarg associated Transaction (NULL if none)
parametersarg parameters to SQL statement
Definition at line 4783 of file Asts.cc.
References CMD_DELETE, CMD_INSERT, CMD_SELECT, CMD_UPDATE, parameters, queries, queryindex, reentry, Statement::reentry_s::reentrydata, Statement::reentry_s::reentryfptr, Statement::reentry_s::reentryObject, Statement::reentry_s::reentrypoint, ApiInterface::results, startQuery(), and transactionPtr.
Referenced by ApiInterface::execStatement(), and Pg::executeStatement().
 {
     reentry.reentryObject=reentryObject;
     reentry.reentryfptr=reentryfptr;
     reentry.reentrypoint=reentrypoint;
     reentry.reentrydata=reentrydata;
     reentryObject->results.cmdtype=queries[0].type;
     switch (reentryObject->results.cmdtype)
     {
     case CMD_SELECT:
         if (transactionPtrarg==NULL)
         {
             transactionPtr = new class Transaction(taPtr, schemaPtr->domainid);
         }
         else
         {
             transactionPtr = transactionPtrarg;
         }
         break;
     case CMD_INSERT:
         if (transactionPtrarg==NULL)
         {
             transactionPtr = new class Transaction(taPtr, schemaPtr->domainid);
         }
         else
         {
             transactionPtr = transactionPtrarg;
         }
         break;
     case CMD_UPDATE:
         if (transactionPtrarg==NULL)
         {
             transactionPtr = new class Transaction(taPtr, schemaPtr->domainid);
         }
         else
         {
             transactionPtr = transactionPtrarg;
         }
         break;
     case CMD_DELETE:
         if (transactionPtrarg==NULL)
         {
             transactionPtr = new class Transaction(taPtr, schemaPtr->domainid);
         }
         else
         {
             transactionPtr = transactionPtrarg;
         }
         break;
     default:
         transactionPtr = transactionPtrarg;
     }
     parameters = parametersarg;
     queryindex = queries.size()-1;
     startQuery();
 }
int64_t Statement::getfieldid (int64_t tableid, const string & fieldName)
returns fieldid
Parameters
tableid tableid
fieldName name of field
Returns
fieldid
Definition at line 2375 of file Asts.cc.
References Schema::fieldNameToId, and schemaPtr.
Referenced by resolveFieldNames(), and resolveTableFields2().
 {
     if (!schemaPtr->fieldNameToId.count(tableid))
     {
         return -1;
     }
     boost::unordered_map<string, int64_t> &ref =
         schemaPtr->fieldNameToId[tableid];
     boost::unordered_map<string, int64_t>::iterator it;
     it = ref.find(fieldName);
     if (it==ref.end())
     {
         return -1;
     }
     return ref[fieldName];
 }
Statement & Statement::operator= (const Statement & orig)
Definition at line 2006 of file Asts.cc.
References cp().
 {
     cp(orig);
     return *this;
 }
void Statement::reenter (int64_t status)
return to calling function (Statement execution complete)
Parameters
status
Definition at line 5170 of file Asts.cc.
References NOCOMMAND, Transaction::pendingcmd, Transaction::pendingcmdid, reentry, Statement::reentry_s::reentrydata, Statement::reentry_s::reentryfptr, Statement::reentry_s::reentryObject, Statement::reentry_s::reentrypoint, ApiInterface::results, ApiInterface::statementPtr, and transactionPtr.
Referenced by abortQuery(), branchtotype(), and startQuery().
 {
     class ApiInterface *reentryObject=reentry.reentryObject;
     apifPtr reentryfptr=reentry.reentryfptr;
     int64_t reentrypoint=reentry.reentrypoint;
     void *reentrydata=reentry.reentrydata;
     if (transactionPtr != NULL)
     {
         transactionPtr->pendingcmd=NOCOMMAND;
         transactionPtr->pendingcmdid=0;
     }
     delete this;
     reentryObject->statementPtr=NULL;
     reentryObject->results.statementStatus=status;
     reentryObject->results.transactionPtr=transactionPtr;
     (*reentryObject.*reentryfptr)(reentrypoint, reentrydata);
 }
bool Statement::resolveFieldNames (class Ast * myPosition)
field name resolution for resolveTableFields
Parameters
myPosition Ast with field name as operand
Returns
success (true) or failure (false)
Definition at line 2283 of file Asts.cc.
References currentQuery, FROM_ABOVE, FROM_LEFT, FROM_RIGHT, getfieldid(), Ast::isoperator, Ast::leftchild, Ast::operand, OPERAND_FIELDID, OPERAND_IDENTIFIER, Ast::parent, Ast::rightchild, and Statement::query_s::tableid.
Referenced by resolveTableFields2().
 {
     direction_e direction = FROM_ABOVE;
     bool isbreakout=false;
     while (1)
     {
         if (myPosition->isoperator==false &&
             myPosition->operand[0]==OPERAND_IDENTIFIER)
         {
             // CONVERT
             string fname = myPosition->operand.substr(1, string::npos);
             int64_t fid = getfieldid(currentQuery->tableid, fname);
             if (fid==-1)
             {
                 printf("%s %i tableid field not found %li %s\n", __FILE__,
                        __LINE__, currentQuery->tableid, fname.c_str());
                 return false;
             }
             else
             {
                 myPosition->operand.assign(1 + sizeof(fid), char(0));
                 myPosition->operand[0] = OPERAND_FIELDID;
                 memcpy(&myPosition->operand[1], &fid, sizeof(fid));
             }
             direction=FROM_RIGHT;
         }
         switch (direction)
         {
         case FROM_ABOVE:
             if (myPosition->leftchild==NULL || myPosition==myPosition->leftchild)
             {
                 direction=FROM_LEFT;
             }
             else
             {
                 myPosition=myPosition->leftchild;
                 //          direction=FROM_ABOVE; already set
             }
             break;
         case FROM_LEFT:
             if (myPosition->rightchild==NULL)
             {
                 direction=FROM_RIGHT;
             }
             else
             {
                 myPosition=myPosition->rightchild;
                 direction=FROM_ABOVE;
             }
             break;
         case FROM_RIGHT:
             if (myPosition->parent==NULL)
             {
                 isbreakout=true;
             }
             else
             {
                 if (myPosition==myPosition->parent->leftchild)
                 {
                     direction=FROM_LEFT;
                 }
                 else // i am parent's right child
                 {
                     direction=FROM_RIGHT;
                 }
                 myPosition=myPosition->parent;
             }
             break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, direction);
             return false;
         }
         if (isbreakout==true)
         {
             return true;
             //      break;
         }
     }
 }
bool Statement::resolveTableFields ()
resolves table and field names to integers
Returns
success (true) or failure (false)
Definition at line 2128 of file Asts.cc.
References CMD_DELETE, CMD_INSERT, CMD_SELECT, CMD_UPDATE, currentQuery, queries, resolveTableFields2(), and Statement::query_s::type.
Referenced by Pg::executeStatement(), and TransactionAgent::newstatement().
 {
     for (size_t n=0; n < queries.size(); n++)
     {
         currentQuery=&queries[n];
         switch (currentQuery->type)
         {
         case CMD_SELECT:
             break;
         case CMD_INSERT:
             break;
         case CMD_UPDATE:
             break;
         case CMD_DELETE:
             break;
         default: // noop, must be BEGIN, COMMIT, etc.
             return true;
         }
         if (resolveTableFields2()==false)
         {
             return false;
         }
     }
     return true;
 }
bool Statement::resolveTableFields2 ()
called by resolveTableFields recursively on each query then subquery to resolve table and field names to integers
Returns
success (true) or failure (false)
Definition at line 2161 of file Asts.cc.
References Statement::query_s::assignments, CMD_SELECT, CMD_UPDATE, currentQuery, Statement::query_s::fieldidAssignments, Table::fields, Statement::query_s::fromColumnids, Statement::query_s::fromColumns, getfieldid(), Statement::query_s::haswhere, OPERAND_AGGREGATE, OPERAND_FIELDID, OPERAND_IDENTIFIER, resolveFieldNames(), schemaPtr, Statement::query_s::searchCondition, Statement::query_s::table, Statement::query_s::tableid, Schema::tableNameToId, Schema::tables, and Statement::query_s::type.
Referenced by resolveTableFields().
 {
     // resolve tableid
     if (schemaPtr->tableNameToId.count(currentQuery->table))
     {
         currentQuery->tableid =
             schemaPtr->tableNameToId[currentQuery->table];
     }
     else
     {
         return false;
     }
     class Table &tableRef = *schemaPtr->tables[currentQuery->tableid];
     // resolve fieldids in select columns
     if (currentQuery->type==CMD_SELECT)
     {
         for (ssize_t n=currentQuery->fromColumns.size()-1; n >= 0; n--)
         {
             string &fromColumnRef = currentQuery->fromColumns[n];
             switch (fromColumnRef[0])
             {
             case '*':
             {
                 for (size_t n=0;
                      n < tableRef.fields.size();
                      n++)
                 {
                     currentQuery->fromColumnids.push_back({OPERAND_FIELDID,
                                 (int64_t)n, tableRef.fields[n].name
                                 });
                 }
             }
             break;
             case OPERAND_IDENTIFIER: // regular identifier
             {
                 string fname = fromColumnRef.substr(1, string::npos);
                 int64_t fid = getfieldid(currentQuery->tableid, fname);
                 if (fid==-1)
                 {
                     printf("%s %i tableid field not found %li %s\n", __FILE__,
                            __LINE__, currentQuery->tableid, fname.c_str());
                     return false;
                 }
                 else
                 {
                     currentQuery->fromColumnids.push_back({OPERAND_FIELDID, fid,
                                 tableRef.fields[fid].name
                                 });
                 }
             }
             break;
             case OPERAND_AGGREGATE: // aggregate
             {
                 string fname = fromColumnRef.substr(2, string::npos);
                 int64_t fid = getfieldid(currentQuery->tableid, fname);
                 if (fid==-1)
                 {
                     printf("%s %i tableid field not found %li %s\n", __FILE__,
                            __LINE__, currentQuery->tableid, fname.c_str());
                     return false;
                 }
                 else
                 {
                     currentQuery->fromColumnids.push_back({fromColumnRef[1], fid,
                                 tableRef.fields[fid].name
                                 });
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %c\n", __FILE__, __LINE__,
                        fromColumnRef[0]);
                 return false;
             }
         }
     }
     else if (currentQuery->type==CMD_UPDATE)
     {
         boost::unordered_map<string, class Ast *>::iterator it;
         for (it = currentQuery->assignments.begin();
              it != currentQuery->assignments.end(); it++)
         {
             int64_t fid = getfieldid(currentQuery->tableid, it->first);
             if (fid==-1)
             {
                 printf("%s %i tableid field not found %li %s\n", __FILE__,
                        __LINE__, currentQuery->tableid, it->first.c_str());
                 return false;
             }
             else
             {
                 currentQuery->fieldidAssignments[fid] = it->second;
             }
             if (resolveFieldNames(it->second)==false)
             {
                 return false;
             }
         }
     }
     if (currentQuery->haswhere==true)
     {
         if (resolveFieldNames(currentQuery->searchCondition)==false)
         {
             return false;
         }
     }
     return true;
 }
void Statement::searchExpression (int64_t entrypoint, class Ast * astNode)
perform search expression
return if evaluation is complete (true), or incomplete (false) if incomplete, caller should return as it means a background transaction call is taking place if the nextastnode is NULL, or it should execute the nextastnode, which is one of the children
Parameters
entrypoint entrypoint in calling function to return to
astNode Ast to evaluate
Definition at line 4857 of file Asts.cc.
References branchtotype(), currentQuery, Ast::evaluate(), Ast::predicateResults, Statement::query_s::results, Statement::query_s::searchCondition, and Statement::results_s::searchResults.
Referenced by branchtotype(), Transaction::continueSqlPredicate(), Ast::evaluate(), Transaction::sqlPredicate(), and startQuery().
 {
     class Ast *nextAstNode=NULL;
     while (1)
     {
         if (astNode->evaluate(&nextAstNode, this)==true)
         {
             // node evaluated successfully
             if (nextAstNode==NULL) // rootnode evaluated, carry on with statement
             {
                 switch (entrypoint)
                     if (entrypoint==1)
                     {
                     case 1:
                         currentQuery->results.searchResults =
                             currentQuery->searchCondition->predicateResults;
                         delete currentQuery->searchCondition;
                         currentQuery->searchCondition=NULL;
                         branchtotype();
                         break;
                     case 2:
                         branchtotype();
                         break;
                     default:
                         ;
                     }
                 return;
             }
             // non-rootnode evaluated, so set up for the next
             astNode=nextAstNode;
         }
         else
         {
             // node not evaluated successfully
             if (nextAstNode==NULL)
             {
                 /* backgrounded query, will continue */
                 return;
             }
             // evaluate a child
             astNode=nextAstNode;
         }
     }
 }
bool Statement::stagedPredicate (operatortypes_e op, int64_t tableid, string & leftoperand, string & rightoperand, vector< fieldValue_s > & inValues, const boost::unordered_map< uuRecord_s, stagedRow_s > & stagedRows, boost::unordered_map< uuRecord_s, returnRow_s > & results)
perform search predicate query on results already gathered by this transaction. saves from having to do unnecessary message traffic with engines
Parameters
op operation
tableid tbaleid
leftoperand left operand of Ast
rightoperand right operand of Ast
inValues for IN (or NOT IN) predicate, these are the values
stagedRows rows already gathered
results rows matched by predicate
Returns
true if rows matched, false if none
Definition at line 2395 of file Asts.cc.
References BOOL, fieldInput_u::boolean, CHAR, fieldInput_u::character, CHARX, compareFields(), Table::fields, FLOAT, fieldInput_u::floating, INT, fieldInput_u::integer, fieldValue_s::isnull, OPERAND_FIELDID, OPERATOR_BETWEEN, OPERATOR_EQ, OPERATOR_GT, OPERATOR_GTE, OPERATOR_IN, OPERATOR_ISNOTNULL, OPERATOR_ISNULL, OPERATOR_LT, OPERATOR_LTE, OPERATOR_NE, OPERATOR_NOTBETWEEN, OPERATOR_NOTIN, returnRow_s::row, schemaPtr, stagedRow2ReturnRow(), fieldValue_s::str, uuRecord_s::tableid, Schema::tables, Ast::toFloat(), Table::unmakerow(), fieldValue_s::value, and VARCHAR.
Referenced by Ast::evaluate().
 {
     bool equalhit=false;
     if (op != OPERATOR_IN && op != OPERATOR_NOTIN && op != OPERATOR_ISNULL &&
         op != OPERATOR_ISNOTNULL)
     {
         if (leftoperand[0] != OPERAND_FIELDID)
         {
             printf("%s %i left operand is not fieldid, it is '%c'\n",
                    __FILE__, __LINE__, leftoperand[0]);
             return equalhit;
         }
     }
     int64_t fieldid;
     memcpy(&fieldid, &leftoperand[1], sizeof(fieldid));
     class Table &tableRef = *schemaPtr->tables[tableid];
     vector<fieldValue_s> fieldValues;
     boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
     for (it = stagedRows.begin(); it != stagedRows.end(); it++)
     {
         const uuRecord_s &uurRef = it->first;
         if (uurRef.tableid != tableid)
         {
             continue;
         }
         const stagedRow_s &stagedRowRef = it->second;
         returnRow_s returnRow;
         stagedRow2ReturnRow(stagedRowRef, returnRow);
         tableRef.unmakerow((string *)&returnRow.row, &fieldValues);
         fieldValue_s &lhs = fieldValues[fieldid];
         switch (tableRef.fields[fieldid].type)
         {
         case INT:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 // indexRef.getequal
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer==rhsval)
                 {
                     results[uurRef] = returnRow;
                     equalhit=true;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer!=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer>rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer<rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer>=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.integer<=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 int64_t rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.integer >= rhsval && lhs.value.integer <= rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 int64_t rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 int64_t rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.integer < rhsval || lhs.value.integer > rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = rRow;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = rRow;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
                 return equalhit;
             }
         }
         break;
         case BOOL:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 // indexRef.getequal
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean==rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean!=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean>rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean<rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean>=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.boolean<=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 bool rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.boolean >= rhsval && lhs.value.boolean <= rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 bool rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 bool rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.boolean < rhsval || lhs.value.boolean > rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = rRow;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = rRow;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
                 return equalhit;
             }
         }
         break;
         case FLOAT:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 // indexRef.getequal
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating==rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating!=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating>rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating<rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating>=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 Ast::toFloat(rightoperand, rightoperand);
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 if (lhs.value.floating<=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 long double rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.floating >= rhsval && lhs.value.floating <=
                     rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 long double rhsval;
                 memcpy(&rhsval, &rightoperand[1], sizeof(rhsval));
                 long double rhsval2;
                 memcpy(&rhsval2, &rightoperand[1+sizeof(rhsval)],
                        sizeof(rhsval2));
                 if (lhs.value.floating < rhsval || lhs.value.floating > rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = rRow;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = rRow;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
                 return equalhit;
             }
         }
         break;
         case CHAR:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 // indexRef.getequal
                 char rhsval=rightoperand[1];
                 if (lhs.value.character==rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character!=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GT:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character>rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LT:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character<rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_GTE:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character>=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_LTE:
             {
                 char rhsval=rightoperand[1];
                 if (lhs.value.character<=rhsval)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_BETWEEN:
             {
                 char rhsval=rightoperand[1+sizeof(int64_t)];
                 char rhsval2=rightoperand[1+sizeof(int64_t)+1];
                 if (lhs.value.character >= rhsval && lhs.value.character <=
                     rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NOTBETWEEN:
             {
                 char rhsval=rightoperand[1+sizeof(int64_t)];
                 char rhsval2=rightoperand[1+sizeof(int64_t)+1];
                 if (lhs.value.character < rhsval || lhs.value.character >
                     rhsval2)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = rRow;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = rRow;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
                 return equalhit;
             }
         }
         break;
         case CHARX:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 // indexRef.getequal
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (!lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = rRow;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = rRow;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
                 return equalhit;
             }
         }
         break;
         case VARCHAR:
         {
             switch (op)
             {
             case OPERATOR_EQ:
             {
                 // indexRef.getequal
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (!lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_NE:
             {
                 string rhsval=rightoperand.substr(1, string::npos);
                 if (lhs.str.compare(rhsval))
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_IN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             results[uurRef] = rRow;
                         }
                     }
                 }
             }
             break;
             case OPERATOR_NOTIN:
             {
                 int64_t fieldid;
                 memcpy(&fieldid, &rightoperand[1], sizeof(fieldid));
                 vector<fieldValue_s> fieldValues;
                 class Table &tableRef = *schemaPtr->tables[tableid];
                 fieldtype_e fieldtype = tableRef.fields[fieldid].type;
                 boost::unordered_map<uuRecord_s, stagedRow_s>::const_iterator it;
                 for (it = stagedRows.begin(); it != stagedRows.end(); it++)
                 {
                     const uuRecord_s &uurRef = it->first;
                     const stagedRow_s &sRowRef = it->second;
                     returnRow_s rRow;
                     stagedRow2ReturnRow(sRowRef, rRow);
                     tableRef.unmakerow(&rRow.row, &fieldValues);
                     bool notin=true;
                     for (size_t n=0; inValues.size(); n++)
                     {
                         if (compareFields(fieldtype, fieldValues[fieldid],
                                           inValues[n])==true)
{
                             notin=false;
                             break;
                         }
                     }
                     if (notin==true)
                     {
                         results[uurRef] = rRow;
                     }
                 }
             }
             break;
             case OPERATOR_ISNULL:
             {
                 if (lhs.isnull==true)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             case OPERATOR_ISNOTNULL:
             {
                 if (lhs.isnull==false)
                 {
                     results[uurRef] = returnRow;
                 }
             }
             break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__, op);
                 return equalhit;
             }
         }
         break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                    tableRef.fields[fieldid].type);
             return equalhit;
         }
     }
     return equalhit;
 }
void Statement::startQuery ()
begin query execution
Definition at line 5522 of file Asts.cc.
References branchtotype(), CMD_BEGIN, CMD_COMMIT, CMD_DELETE, CMD_INSERT, CMD_ROLLBACK, CMD_SELECT, CMD_UPDATE, currentQuery, Table::fields, Statement::query_s::fromColumnids, Statement::query_s::haswhere, returnRow_s::locktype, Statement::results_s::newrow, Statement::results_s::newrowuur, returnRow_s::previoussubtransactionid, queries, queryindex, reenter(), reentry, Statement::reentry_s::reentryObject, Statement::query_s::results, ApiInterface::results, returnRow_s::row, uuRecord_s::rowid, returnRow_s::rowid, schemaPtr, Statement::query_s::searchCondition, searchExpression(), Statement::results_s::searchResults, Statement::results_s::selectResults, STATUS_OK, Statement::query_s::tableid, Schema::tables, Statement::query_s::type, and WRITELOCK.
Referenced by branchtotype(), continueDelete(), continueInsert(), continueSelect(), continueUpdate(), and execute().
 {
     if (queryindex >= 0)
     {
         currentQuery = &queries[queryindex--];
         if (currentQuery->haswhere==true)
         {
             searchExpression(1, currentQuery->searchCondition);
         }
         else
         {
             branchtotype();
         }
     }
     else
     {
         // reenter
         /* put the final query results somewhere, like staged rows,
          * locking every row in every query, then put the results
          * somewhere the user can find them */
         switch (currentQuery->type)
         {
         case CMD_SELECT:
         {
             reentry.reentryObject->results.cmdtype = CMD_SELECT;
             reentry.reentryObject->results.statementStatus = STATUS_OK;
             reentry.reentryObject->results.selectResults =
                 currentQuery->results.selectResults;
             class Table &tableRef = *schemaPtr->tables[currentQuery->tableid];
             for (size_t n=0; n < currentQuery->fromColumnids.size(); n++)
             {
                 reentry.reentryObject->results.selectFields.push_back(
                     {tableRef.fields[currentQuery->fromColumnids[n].fieldid].type, currentQuery->fromColumnids[n].name});
             }
         }
         break;
         case CMD_INSERT:
         {
             reentry.reentryObject->results.cmdtype = CMD_INSERT;
             reentry.reentryObject->results.statementStatus = STATUS_OK;
             returnRow_s returnRow;
             returnRow.rowid = currentQuery->results.newrowuur.rowid;
             returnRow.previoussubtransactionid = 0;
             returnRow.locktype = WRITELOCK;
             returnRow.row = currentQuery->results.newrow;
             reentry.reentryObject->results.statementResults[currentQuery->results.newrowuur] =
                 returnRow;
         }
         break;
         case CMD_UPDATE:
             reentry.reentryObject->results.cmdtype = CMD_UPDATE;
             reentry.reentryObject->results.statementStatus = STATUS_OK;
             reentry.reentryObject->results.statementResults =
                 currentQuery->results.searchResults;
             break;
         case CMD_DELETE:
             reentry.reentryObject->results.cmdtype = CMD_DELETE;
             reentry.reentryObject->results.statementStatus = STATUS_OK;
             reentry.reentryObject->results.statementResults =
                 currentQuery->results.searchResults;
             break;
         case CMD_BEGIN:
             reentry.reentryObject->results.cmdtype = CMD_BEGIN;
             reentry.reentryObject->results.statementStatus = STATUS_OK;
             break;
         case CMD_COMMIT:
             reentry.reentryObject->results.cmdtype = CMD_COMMIT;
             reentry.reentryObject->results.statementStatus = STATUS_OK;
             break;
         case CMD_ROLLBACK:
             reentry.reentryObject->results.cmdtype = CMD_ROLLBACK;
             reentry.reentryObject->results.statementStatus = STATUS_OK;
             break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, currentQuery->type);
             return;
         }
         reenter(STATUS_OK);
     }
 }
void Statement::subqueryExists (class Ast * astnode)
EXISTS subquery.
Parameters
astnode
Definition at line 5771 of file Asts.cc.
References Ast::operand, OPERAND_BOOLEAN, and queries.
Referenced by Ast::evaluate().
 {
     int64_t queryinstance;
     memcpy(&queryinstance, &astnode->operand[1], sizeof(queryinstance));
     astnode->operand.resize(OPERAND_BOOLEAN, 2);
     if (queries[queryinstance].results.selectResults.size())
     {
         astnode->operand[1]='t';
     }
     else
     {
         astnode->operand[1]='f';
     }
 }
void Statement::subqueryIn (class Ast * astnode)
subquery returns list of values for IN predicate
Parameters
astnode
Definition at line 5788 of file Asts.cc.
References Statement::results_s::inValues, Ast::operand, queries, Statement::query_s::results, and Statement::results_s::selectResults.
Referenced by Ast::evaluate().
 {
     int64_t queryinstance;
     memcpy(&queryinstance, &astnode->operand[1], sizeof(queryinstance));
     query_s &queryRef = queries[queryinstance];
     boost::unordered_map< uuRecord_s, vector<fieldValue_s> >::iterator it;
     for (it = queryRef.results.selectResults.begin();
          it != queryRef.results.selectResults.end(); it++)
     {
         queryRef.results.inValues.push_back(it->second[0]);
     }
 }
void Statement::subqueryScalar (class Ast * astnode)
subquery that returns a scalar
Parameters
astnode
Definition at line 5613 of file Asts.cc.
References BOOL, CHAR, CHARX, FLOAT, INT, Ast::operand, OPERAND_BOOLEAN, OPERAND_FLOAT, OPERAND_INTEGER, OPERAND_NULL, OPERAND_STRING, OPERAND_SUBQUERY, queries, Statement::query_s::results, schemaPtr, Statement::results_s::selectResults, Statement::query_s::tableid, Schema::tables, UINT, and VARCHAR.
Referenced by Ast::evaluate(), and Ast::normalizeSetAssignmentOperand().
 {
     if (astnode->operand[0] != OPERAND_SUBQUERY)
     {
         return;
     }
     int64_t queryinstance;
     memcpy(&queryinstance, &astnode->operand[1], sizeof(queryinstance));
     query_s &queryRef = queries[queryinstance];
     boost::unordered_map< uuRecord_s, vector<fieldValue_s> > &selectResultsRef =
         queryRef.results.selectResults;
     switch (selectResultsRef.size())
     {
     case 0:
         astnode->operand.assign(1, OPERAND_NULL);
         break;
     case 1:
     {
         boost::unordered_map< uuRecord_s,
                               vector<fieldValue_s> >::const_iterator it;
         it = selectResultsRef.begin();
         const vector<fieldValue_s> &fieldValuesRef = it->second;
         if (fieldValuesRef.size()==1)
         {
             // get the field type table.fields[0].type fieldtype_e
             switch (schemaPtr->tables[queryRef.tableid]->fields[0].type)
             {
             case INT:
                 astnode->operand.resize(1+sizeof(int64_t), (char)0);
                 astnode->operand[0] = OPERAND_INTEGER;
                 memcpy(&astnode->operand[1], &fieldValuesRef[0].value.integer,
                        sizeof(int64_t));
                 break;
             case UINT:
                 astnode->operand.resize(1+sizeof(int64_t), (char)0);
                 astnode->operand[0] = OPERAND_INTEGER;
                 memcpy(&astnode->operand[1], &fieldValuesRef[0].value.uinteger,
                        sizeof(int64_t));
                 break;
             case BOOL:
                 astnode->operand.resize(2, OPERAND_BOOLEAN);
                 if (fieldValuesRef[0].value.boolean==true)
                 {
                     astnode->operand[1]='t';
                 }
                 else
                 {
                     astnode->operand[1]='f';
                 }
                 break;
             case FLOAT:
                 astnode->operand.resize(1+sizeof(long double), (char)0);
                 astnode->operand[0] = OPERAND_FLOAT;
                 memcpy(&astnode->operand[1], &fieldValuesRef[0].value.floating,
                        sizeof(int64_t));
                 break;
             case CHAR:
                 astnode->operand.resize(1+sizeof(char), (char)0);
                 astnode->operand[0] = OPERAND_STRING;
                 astnode->operand[1] = fieldValuesRef[0].value.character;
                 break;
             case CHARX:
                 astnode->operand.assign(1, OPERAND_STRING);
                 astnode->operand.append(fieldValuesRef[0].str);
                 break;
             case VARCHAR:
                 astnode->operand.assign(1, OPERAND_STRING);
                 astnode->operand.append(fieldValuesRef[0].str);
                 break;
             default:
                 printf("%s %i anomaly %i\n", __FILE__, __LINE__,
                        schemaPtr->tables[queryRef.tableid]->fields[0].type);
             }
             return;
         }
         else
         {
             printf("%s %i too many columns in scalar subquery %lu\n", __FILE__,
                    __LINE__, fieldValuesRef.size());
         }
     }
     break;
     default:
         printf("%s %i too many returned rows in scalar subquery %lu\n", __FILE__,
                __LINE__, selectResultsRef.size());
     }
 }
void Statement::subqueryUnique (class Ast * astnode)
UNIQUE type of subquery.
Parameters
astnode
Definition at line 5717 of file Asts.cc.
References compareFields(), Table::fields, Statement::query_s::fromColumnids, Ast::operand, OPERAND_BOOLEAN, queries, Statement::query_s::results, schemaPtr, Statement::results_s::selectResults, Statement::query_s::tableid, and Schema::tables.
Referenced by Ast::evaluate().
 {
     int64_t queryinstance;
     memcpy(&queryinstance, &astnode->operand[1], sizeof(queryinstance));
     query_s &queryRef = queries[queryinstance];
     size_t numfields = queryRef.fromColumnids.size();
     class Table &tableRef = *schemaPtr->tables[queryRef.tableid];
     boost::unordered_map< uuRecord_s, vector<fieldValue_s> >::iterator it;
     boost::unordered_map< uuRecord_s, vector<fieldValue_s> >::iterator it2;
     for (it = queryRef.results.selectResults.begin();
          it != queryRef.results.selectResults.end(); it++)
     {
         const uuRecord_s &uurRef1 = it->first;
         const vector<fieldValue_s> &fieldValues = it->second;
         for (it2 = queryRef.results.selectResults.begin();
              it2 != queryRef.results.selectResults.end(); it++)
         {
             const uuRecord_s &uurRef2 = it2->first;
             const vector<fieldValue_s> &fieldValues2 = it->second;
             if (uurRef1==uurRef2)
             {
                 continue;
             }
             bool ismatch=true;
             for (size_t n=0; n < numfields; n++)
             {
                 if (compareFields(
                         tableRef.fields[queryRef.fromColumnids[n].fieldid].type,
                         fieldValues[n], fieldValues2[n])==false)
                 {
                     ismatch=false;
                     break;
                 }
             }
             if (ismatch==true)
             {
                 astnode->operand.resize(OPERAND_BOOLEAN, 2);
                 astnode->operand[1]='f';
                 return;
             }
         }
     }
     astnode->operand.resize(OPERAND_BOOLEAN, 2);
     astnode->operand[1] = 't';
 }
Member Data Documentation
query_s* Statement::currentQuery
Definition at line 468 of file Asts.h.
Referenced by branchtotype(), continueDelete(), continueSelect(), Transaction::continueSqlInsert(), Transaction::continueSqlReplace(), continueUpdate(), cp(), Ast::evaluate(), Ast::normalizeSetAssignmentOperand(), resolveFieldNames(), resolveTableFields(), resolveTableFields2(), searchExpression(), and startQuery().
std::vector<std::string> Statement::parameters
Definition at line 471 of file Asts.h.
Referenced by cp(), Ast::evaluate(), execute(), and Ast::normalizeSetAssignmentOperand().
std::vector<query_s> Statement::queries
Definition at line 470 of file Asts.h.
Referenced by Larxer::consumeSubquery(), Pg::cont(), cp(), Larxer::eatstack(), ApiInterface::execStatement(), execute(), Pg::executeStatement(), ApiInterface::getStoredProcedureArgs(), resolveTableFields(), startQuery(), subqueryExists(), subqueryIn(), subqueryScalar(), subqueryUnique(), and ~Statement().
ssize_t Statement::queryindex
Definition at line 473 of file Asts.h.
Referenced by cp(), execute(), and startQuery().
reentry_s Statement::reentry
Definition at line 466 of file Asts.h.
Referenced by branchtotype(), cp(), execute(), reenter(), startQuery(), and Statement().
class Schema* Statement::schemaPtr
Definition at line 465 of file Asts.h.
Referenced by andPredicate(), branchtotype(), continueSelect(), continueUpdate(), cp(), Ast::evaluate(), getfieldid(), Ast::normalizeSetAssignmentOperand(), resolveTableFields2(), stagedPredicate(), startQuery(), subqueryScalar(), and subqueryUnique().
class TransactionAgent* Statement::taPtr
Definition at line 464 of file Asts.h.
Referenced by branchtotype(), and cp().
class Transaction* Statement::transactionPtr
Definition at line 467 of file Asts.h.
Referenced by branchtotype(), continueDelete(), continueSelect(), continueUpdate(), cp(), Ast::evaluate(), execute(), and reenter().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Asts.h
/home/infinisql/build/infinisql/infinisqld/Asts.cc