InfiniSQL: Operation Class Reference
Operation Class Reference
non-transactional user and schema-related activity
#include <Operation.h>
Public Member Functions
Operation (int typearg, class TransactionAgent *taarg, int64_t uid, int64_t did)
virtual ~Operation ()
void setbuiltincmd (int cmd)
"builtin" is the operation function to perform
void setDomainName (string name)
set domain name
int64_t getid ()
get operation identifier
void handleOperation (class MessageUserSchema &msgrcvref)
perform operation (only for SQL logins)
Public Attributes
int type
class TransactionAgent * taPtr
int64_t operationid
int sockfd
int64_t userid
int64_t domainid
string domainName
schemastruct schemaData
Friends
class TransactionAgent
Detailed Description
non-transactional user and schema-related activity
Parameters
typearg type of operation
taarg TransactionAgent
uid userid
did domainid
Definition at line 60 of file Operation.h.
Constructor & Destructor Documentation
Operation::Operation (int typearg, class TransactionAgent * taarg, int64_t uid, int64_t did)
Definition at line 33 of file Operation.cc.
References schemastruct::msgwaits, nodeTopology, Topology::numengines, Topology::numtransactionagents, OP_SCHEMA, operationid, TransactionAgent::operationidcounter, TransactionAgent::pendingOperations, schemaData, sockfd, TransactionAgent::sockfd, taPtr, and type.
                                   : type(typearg), taPtr(taarg), userid(uid),
                                     domainid(did)
 {
     class TransactionAgent &taRef = *taPtr;
     operationid = ++taRef.operationidcounter;
     taRef.pendingOperations[operationid] = this;
     sockfd = taRef.sockfd;
     if (type==OP_SCHEMA)
     {
         schemaData.msgwaits =
             __sync_add_and_fetch(&nodeTopology.numtransactionagents, 0) +
             __sync_add_and_fetch(&nodeTopology.numengines, 0);
     }
 }
Operation::~Operation () virtual
Definition at line 50 of file Operation.cc.
 {
 }
Member Function Documentation
int64_t Operation::getid ()
get operation identifier
Returns
operation identifier
Definition at line 54 of file Operation.cc.
References operationid.
Referenced by TransactionAgent::changepassword(), TransactionAgent::createdomain(), TransactionAgent::createuser(), TransactionAgent::deletedomain(), TransactionAgent::deleteuser(), TransactionAgent::login(), and TransactionAgent::schemaBoilerplate().
 {
     return operationid;
 }
void Operation::handleOperation (class MessageUserSchema & msgrcvref)
perform operation (only for SQL logins)
Parameters
msgrcvref received MessageUserSchema
Definition at line 69 of file Operation.cc.
References MessageUserSchema::userschema_s::caller, MessageUserSchema::userschema_s::callerstate, Pg::continueLogin(), operationid, TransactionAgent::pendingOperations, TransactionAgent::Pgs, sockfd, taPtr, type, and MessageUserSchema::userschemaStruct.
Referenced by TransactionAgent::TransactionAgent().
 {
     switch (msgrcvref.userschemaStruct.caller)
     {
     case 1: // Pg login
     {
         boost::unordered_map<int, class Pg *>::iterator it;
         it = taPtr->Pgs.find(sockfd);
         if (it != taPtr->Pgs.end())
         {
             class Pg &pgref = *it->second;
             pgref.continueLogin(msgrcvref.userschemaStruct.callerstate, msgrcvref);
             taPtr->pendingOperations.erase(operationid);
             delete this;
         }
         else
         {
             printf("%s %i anomaly Pg object not in Pgs, sockfd %i\n", __FILE__,
                    __LINE__, sockfd);
         }
     }
     break;
     default:
         printf("%s %i anomaly type %i\n", __FILE__, __LINE__, type);
     }
 }
void Operation::setbuiltincmd (int cmd)
"builtin" is the operation function to perform
Parameters
cmd command, one of BUILTIN* macros defined in defs.h
Definition at line 59 of file Operation.cc.
References schemastruct::builtincmd, and schemaData.
Referenced by TransactionAgent::schemaBoilerplate().
 {
     schemaData.builtincmd = cmd;
 }
void Operation::setDomainName (string name)
set domain name
Parameters
name domain name
Definition at line 64 of file Operation.cc.
References domainName.
Referenced by TransactionAgent::login().
 {
     domainName = name;
 }
Friends And Related Function Documentation
friend class TransactionAgent friend
Definition at line 67 of file Operation.h.
Member Data Documentation
int64_t Operation::domainid
Definition at line 101 of file Operation.h.
string Operation::domainName
Definition at line 102 of file Operation.h.
Referenced by TransactionAgent::login(), and setDomainName().
int64_t Operation::operationid
Definition at line 98 of file Operation.h.
Referenced by Pg::cont(), getid(), handleOperation(), and Operation().
schemastruct Operation::schemaData
Definition at line 103 of file Operation.h.
Referenced by Operation(), TransactionAgent::schemaBoilerplate(), setbuiltincmd(), and TransactionAgent::TransactionAgent().
int Operation::sockfd
Definition at line 99 of file Operation.h.
Referenced by Pg::cont(), handleOperation(), and Operation().
class TransactionAgent* Operation::taPtr
Definition at line 97 of file Operation.h.
Referenced by handleOperation(), and Operation().
int Operation::type
Definition at line 96 of file Operation.h.
Referenced by handleOperation(), and Operation().
int64_t Operation::userid
Definition at line 100 of file Operation.h.
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Operation.h
/home/infinisql/build/infinisql/infinisqld/Operation.cc