InfiniSQL: MessageApply Class Reference
MessageApply Class Reference
Message variant for Applier activities.
#include <Message.h>
Classes
struct apply_s
MessageApply POD (serializable by memcpy) data members.
struct applyindex_s
Public Member Functions
MessageApply ()
MessageApply (int64_t subtransactionidarg, int64_t applieridarg, int64_t domainidarg)
Message variant for Applier activities.
virtual ~MessageApply ()
size_t size ()
get Message size
string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
size_t size ()
get Message size
std::string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
string * sermsg ()
return serialized Message variant string
void setEnvelope (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
put addresses in Message variant envelope
Static Public Member Functions
static void setisaddflag (char *c)
set flag for new index entry
static char getisaddflag (char c)
get flag for new index entry
static void cleariaddflag (char *c)
clear flag for new index entry
Static Public Member Functions inherited from Message
static class Message * des (string *serstr)
deserialize entire message
Public Attributes
apply_s applyStruct
std::vector
< MessageDispatch::record_s > rows
std::vector< applyindex_s > indices
Public Attributes inherited from Message
__int128 nextmsg
message_s messageStruct
Detailed Description
Message variant for Applier activities.
Returns
Definition at line 688 of file Message.h.
Constructor & Destructor Documentation
MessageApply::MessageApply ()
Definition at line 658 of file Message.cc.
 {
 }
MessageApply::MessageApply (int64_t subtransactionidarg, int64_t applieridarg, int64_t domainidarg)
Message variant for Applier activities.
Parameters
subtransactionidarg subtransactionid
applieridarg applierid
domainidarg domainid
Returns
Definition at line 662 of file Message.cc.
                                                 :
     applyStruct ({subtransactionidarg, applieridarg, domainidarg})
MessageApply::~MessageApply () virtual
Definition at line 670 of file Message.cc.
 {
 }
Member Function Documentation
void MessageApply::clear ()
clear contents of this
Definition at line 709 of file Message.cc.
References applyStruct, Message::clear(), indices, and rows.
 {
     Message::clear();
     applyStruct={};
     rows.clear();
     indices={};
 }
void MessageApply::cleariaddflag (char * c) static
clear flag for new index entry
Parameters
c flags
Definition at line 727 of file Message.cc.
References ADDFLAG.
 {
     *c &= ~(1 << ADDFLAG);
 }
char MessageApply::getisaddflag (char c) static
get flag for new index entry
Parameters
c flags
Definition at line 722 of file Message.cc.
References ADDFLAG.
Referenced by Engine::applyItem().
 {
     return c & 1 << ADDFLAG;
 }
void MessageApply::package (class SerializedMessage & serobj)
serialize this
Parameters
serobj SerializedMessage
Definition at line 693 of file Message.cc.
References applyStruct, indices, Message::package(), rows, and SerializedMessage::ser().
Referenced by ser().
 {
     Message::package(serobj);
     serobj.ser(applyStruct);
     serobj.ser(rows);
     serobj.ser(indices);
 }
string * MessageApply::ser ()
create string with serialized message
Returns
serialized message string
Definition at line 681 of file Message.cc.
References SerializedMessage::data, SerializedMessage::getpayloadtype(), logfile, package(), and SerializedMessage::pos.
 {
     class SerializedMessage serobj(size());
     package(serobj);
     if (serobj.data->size() != serobj.pos)
     {
         fprintf(logfile, "%s %i ser %i size %lu pos %lu\n", __FILE__, __LINE__,
                 serobj.getpayloadtype(), serobj.data->size(), serobj.pos);
     }
     return serobj.data;
 }
void MessageApply::setisaddflag (char * c) static
set flag for new index entry
Parameters
c flags
Definition at line 717 of file Message.cc.
References ADDFLAG.
Referenced by TransactionAgent::handledispatch().
 {
     *c |= 1 << ADDFLAG;
 }
size_t MessageApply::size ()
get Message size
Returns
size in bytes
Definition at line 674 of file Message.cc.
References applyStruct, indices, rows, SerializedMessage::sersize(), and Message::size().
 {
     return Message::size() + SerializedMessage::sersize(applyStruct) +
         SerializedMessage::sersize(rows) +
         SerializedMessage::sersize(indices);
 }
void MessageApply::unpack (SerializedMessage & serobj)
deserialize into this
Parameters
serobj SerializedMessage
Definition at line 701 of file Message.cc.
References applyStruct, SerializedMessage::des(), indices, rows, and Message::unpack().
Referenced by Message::des().
 {
     Message::unpack(serobj);
     serobj.des(applyStruct);
     serobj.des(rows);
     serobj.des(indices);
 }
Member Data Documentation
apply_s MessageApply::applyStruct
Definition at line 773 of file Message.h.
Referenced by Engine::apply(), Engine::background(), clear(), package(), size(), and unpack().
std::vector<applyindex_s> MessageApply::indices
Definition at line 776 of file Message.h.
Referenced by Engine::apply(), clear(), package(), size(), and unpack().
std::vector<MessageDispatch::record_s> MessageApply::rows
Definition at line 775 of file Message.h.
Referenced by Engine::apply(), clear(), TransactionAgent::handledispatch(), package(), size(), and unpack().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc