InfiniSQL: Mbox Class Reference
Mbox Class Reference
create mailbox
#include <Mbox.h>
Public Member Functions
Mbox ()
virtual ~Mbox ()
class Message * receive (int timeout)
consume a Message
Static Public Member Functions
static __int128 getInt128FromPointer (class Message *ptr, uint64_t count)
create 128bit integer from Message object
static class Message * getPtr (__int128 i128)
return Message pointer from 128bit integer
static uint64_t getCount (__int128 i128)
return count component from 128bit integer
Private Attributes
pthread_mutex_t mutexLast
class Message * firstMsg
class Message * currentMsg
class Message * lastMsg
class Message * myLastMsg
__int128 head
__int128 tail
__int128 current
__int128 mytail
uint64_t counter
Friends
class MboxProducer
Detailed Description
create mailbox
this is a queue, lockfree multi-producer single consumer adapted from: http://www.cs.rochester.edu/research/synchronization/pseudocode/queues.html
Definition at line 46 of file Mbox.h.
Constructor & Destructor Documentation
Mbox::Mbox ()
lockfree producer adapted from: http://www.cs.rochester.edu/research/synchronization/pseudocode/queues.html
Definition at line 37 of file Mbox.cc.
References current, currentMsg, firstMsg, getInt128FromPointer(), head, lastMsg, Message::messageStruct, mutexLast, myLastMsg, mytail, Message::nextmsg, PAYLOADNONE, Message::message_s::payloadtype, and tail.
            : counter(8888)
 {
     firstMsg = new class Message();
     firstMsg->messageStruct.payloadtype = PAYLOADNONE;
     firstMsg->nextmsg = getInt128FromPointer(NULL, 5000);
     currentMsg = firstMsg;
     lastMsg = firstMsg;
     myLastMsg = firstMsg;
     head = getInt128FromPointer(firstMsg, 10000);
     tail = head;
     current = head;
     mytail = head;
     pthread_mutexattr_t attr;
     attr.__align = PTHREAD_MUTEX_ADAPTIVE_NP;
     pthread_mutex_init(&mutexLast, &attr);
 }
Mbox::~Mbox () virtual
Definition at line 56 of file Mbox.cc.
References firstMsg.
 {
     delete firstMsg;
 }
Member Function Documentation
uint64_t Mbox::getCount (__int128 i128) static
return count component from 128bit integer
Parameters
i128 input 128bit integer
Returns
count
Definition at line 120 of file Mbox.cc.
Referenced by receive(), and TransactionAgent::TransactionAgent().
 {
     return *((uint64_t *)&i128+1);
 }
__int128 Mbox::getInt128FromPointer (class Message * ptr, uint64_t count) static
create 128bit integer from Message object
Parameters
ptr Message variant
count count component
Returns
Definition at line 106 of file Mbox.cc.
Referenced by Mbox(), and MboxProducer::sendMsg().
 {
     __int128 i128;
     memcpy(&i128, &ptr, sizeof(ptr));
     memcpy((uint64_t *)&i128+1, &count, sizeof(count));
     return i128;
 }
class Message * Mbox::getPtr (__int128 i128) static
return Message pointer from 128bit integer
Parameters
i128 input 128bit integer
Returns
Message
Definition at line 115 of file Mbox.cc.
Referenced by receive(), MboxProducer::sendMsg(), and TransactionAgent::TransactionAgent().
 {
     return (class Message *)i128;
 }
class Message * Mbox::receive (int timeout)
consume a Message
Parameters
timeout timeout in microseconds
Returns
Message object
Definition at line 66 of file Mbox.cc.
References current, getCount(), getPtr(), and Message::nextmsg.
Referenced by ObGateway::ObGateway().
 {
     __int128 mynext;
     while (1)
     {
         mynext = __atomic_load_n(&(getPtr(current)->nextmsg), __ATOMIC_SEQ_CST);
         if (getPtr(mynext)==NULL)
         {
             switch (timeout)
             {
             case -1:
                 break;
             case 0:
                 return NULL;
                 break;
             default:
                 struct timespec ts = {0, timeout * 1000};
                 nanosleep(&ts, NULL);
                 return NULL;
             }
         }
         else
         {
             if (getPtr(current)==getPtr(mynext))
             {
                 printf("%s %i WTF found it i guess count current %lu next %lu\n",
                        __FILE__, __LINE__, getCount(current), getCount(mynext));
             }
             delete getPtr(current);
             current = mynext;
             return getPtr(current);
         }
     }
 }
Friends And Related Function Documentation
friend class MboxProducer friend
Definition at line 87 of file Mbox.h.
Member Data Documentation
uint64_t Mbox::counter private
Definition at line 102 of file Mbox.h.
Referenced by MboxProducer::sendMsg().
__int128 Mbox::current private
Definition at line 99 of file Mbox.h.
Referenced by Mbox(), and receive().
class Message* Mbox::currentMsg private
Definition at line 93 of file Mbox.h.
Referenced by Mbox().
class Message* Mbox::firstMsg private
Definition at line 92 of file Mbox.h.
Referenced by Mbox(), and ~Mbox().
__int128 Mbox::head private
Definition at line 97 of file Mbox.h.
Referenced by Mbox().
class Message* Mbox::lastMsg private
Definition at line 94 of file Mbox.h.
Referenced by Mbox().
pthread_mutex_t Mbox::mutexLast private
Definition at line 90 of file Mbox.h.
Referenced by Mbox().
class Message* Mbox::myLastMsg private
Definition at line 95 of file Mbox.h.
Referenced by Mbox().
__int128 Mbox::mytail private
Definition at line 100 of file Mbox.h.
Referenced by Mbox().
__int128 Mbox::tail private
Definition at line 98 of file Mbox.h.
Referenced by Mbox(), and MboxProducer::sendMsg().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Mbox.h
/home/infinisql/build/infinisql/infinisqld/Mbox.cc