InfiniSQL: Larxer Class Reference
Larxer Class Reference
create object to tokenize, parse, and compile SQL statement
#include <Larxer.h>
Classes
struct stackmember_s
data populatng pre- Ast stack. SQL token and associated value.
Public Types
enum stacktypes_e {
TYPE_NONE = 0, TYPE_IDENTIFIER = 1, TYPE_SUBQUERY = 2, TYPE_NOT = 3,
TYPE_ISNULL = 4, TYPE_eq = 5, TYPE_ne = 6, TYPE_lt = 7,
TYPE_gt = 8, TYPE_lte = 9, TYPE_gte = 10, TYPE_COMPARISON = 11,
TYPE_ISTRUE = 12, TYPE_ISFALSE = 13, TYPE_ISUNKNOWN = 14, TYPE_INTVAL = 15,
TYPE_FLOATVAL = 16, TYPE_PARAMETER = 17, TYPE_STRINGVAL = 18, TYPE_concat = 19,
TYPE_addition = 20, TYPE_subtraction = 21, TYPE_multiplication = 22, TYPE_division = 23,
TYPE_exponent = 24, TYPE_uminus = 25, TYPE_ASC = 26, TYPE_DESC = 27,
TYPE_ORDERBY = 28, TYPE_FORUPDATE = 29, TYPE_HAVING = 30, TYPE_GROUPBY = 31,
TYPE_WHERE = 32, TYPE_AVG = 33, TYPE_COUNT = 34, TYPE_MAX = 35,
TYPE_MIN = 36, TYPE_SUM = 37, TYPE_ASTERISK = 38, TYPE_DISTINCT = 39,
TYPE_ALL = 40, TYPE_BETWEEN = 41, TYPE_BETWEENEXPRESSIONS = 42, TYPE_IN = 43,
TYPE_LIKE = 44, TYPE_EXISTS = 45, TYPE_UNIQUE = 46, TYPE_assignment = 47,
TYPE_AND = 48, TYPE_OR = 49, TYPE_SELECT = 50, TYPE_INSERT = 51,
TYPE_UPDATE = 52, TYPE_DELETE = 53, TYPE_COLUMNS = 55, TYPE_EXPRESSION = 56,
TYPE_FROM = 57, TYPE_search_condition = 58, TYPE_SORTSPECIFICATION = 59, TYPE_AGGREGATE = 60,
TYPE_operator = 61, TYPE_operand = 62, TYPE_inobject = 63, TYPE_BEGIN = 64,
TYPE_COMMIT = 65, TYPE_ROLLBACK = 66, TYPE_SET = 67, TYPE_storedprocedure = 68,
TYPE_inbegin = 69, TYPE_NOLOCK = 70
}
SQL tokens for pre- Ast stack.
Public Member Functions
Larxer (char *instr, class TransactionAgent *taPtr, class Schema *schemaPtr)
tokenize, parse, and compile SQL statement
virtual ~Larxer ()
void pushstack (stacktypes_e type)
put item on stack
void pushstack (stacktypes_e type, int64_t val)
put item on stack
void pushstack (stacktypes_e type, long double val)
put item on stack
void pushstack (stacktypes_e type, const char *val)
put item on stack
void pushstack (stacktypes_e type, string &val)
put item on stack
void pushoperand (char operandtype)
push operand onto stack
void pushoperand (char operandtype, int64_t val)
push operand onto stack
void pushoperand (char operandtype, long double val)
push operand onto stack
void pushoperand (char operandtype, const char *val)
push operand onto stack
void pushaggregate (char aggregatetype, const char *val)
push aggregate and associated field onto stack
stackmember_s popstack ()
take item off stack
int64_t getintval (string &val)
convert string to integer
long double getfloatval (string &val)
convert string to float
void eatstack (class TransactionAgent *taPtr, class Schema *schemaPtr)
consume entire stack
void printstack ()
show stack entries, for debugging
void consumeSelect (string &columns)
extract SELECT query from stack
void consumeInsert ()
extract INSERT query from stack
void consumeUpdate ()
extract UPDATE query from stack
void consumeDelete ()
extract DELETE query from stack
void consumeStoredProcedure ()
extract stored procedure call query from stack
class Ast * consumeExpression ()
extract expression from stack
int64_t consumeSubquery ()
extract subquery from stack
void consumeInobject ()
extract list of IN values from stack
void consumeColumns (int64_t numcolumns)
extract columns from stack
void consumeFrom ()
extract FROM clause from stack
void consumeWhere ()
extract WHERE clause from stack
void consumeGroupby ()
extract GROUP BY clause from stack
void consumeHaving ()
extract HAVING clause from stack
void consumeOrderby ()
extract ORDER BY clause from stack
Public Attributes
std::stack< stackmember_s > parsedStack
class Statement::query_s * currentQuery
class Statement * statementPtr
Detailed Description
create object to tokenize, parse, and compile SQL statement
many of these functions are called by the lexer.ll and parser.yy generated code
Parameters
instr SQL query
taPtr TransactionAgent
schemaPtr Schema
Returns
Definition at line 49 of file Larxer.h.
Member Enumeration Documentation
enum Larxer::stacktypes_e
SQL tokens for pre- Ast stack.
Enumerator
TYPE_NONE
TYPE_IDENTIFIER
TYPE_SUBQUERY
TYPE_NOT
TYPE_ISNULL
TYPE_eq
TYPE_ne
TYPE_lt
TYPE_gt
TYPE_lte
TYPE_gte
TYPE_COMPARISON
TYPE_ISTRUE
TYPE_ISFALSE
TYPE_ISUNKNOWN
TYPE_INTVAL
TYPE_FLOATVAL
TYPE_PARAMETER
TYPE_STRINGVAL
TYPE_concat
TYPE_addition
TYPE_subtraction
TYPE_multiplication
TYPE_division
TYPE_exponent
TYPE_uminus
TYPE_ASC
TYPE_DESC
TYPE_ORDERBY
TYPE_FORUPDATE
TYPE_HAVING
TYPE_GROUPBY
TYPE_WHERE
TYPE_AVG
TYPE_COUNT
TYPE_MAX
TYPE_MIN
TYPE_SUM
TYPE_ASTERISK
TYPE_DISTINCT
TYPE_ALL
TYPE_BETWEEN
TYPE_BETWEENEXPRESSIONS
TYPE_IN
TYPE_LIKE
TYPE_EXISTS
TYPE_UNIQUE
TYPE_assignment
TYPE_AND
TYPE_OR
TYPE_SELECT
TYPE_INSERT
TYPE_UPDATE
TYPE_DELETE
TYPE_COLUMNS
TYPE_EXPRESSION
TYPE_FROM
TYPE_search_condition
TYPE_SORTSPECIFICATION
TYPE_AGGREGATE
TYPE_operator
TYPE_operand
TYPE_inobject
TYPE_BEGIN
TYPE_COMMIT
TYPE_ROLLBACK
TYPE_SET
TYPE_storedprocedure
TYPE_inbegin
TYPE_NOLOCK
Definition at line 56 of file Larxer.h.
     {
         TYPE_NONE = 0,
         TYPE_IDENTIFIER = 1,
         TYPE_SUBQUERY = 2,
         TYPE_NOT = 3,
         TYPE_ISNULL = 4,
         TYPE_eq = 5,
         TYPE_ne = 6,
         TYPE_lt = 7,
         TYPE_gt = 8,
         TYPE_lte = 9,
         TYPE_gte = 10,
         TYPE_COMPARISON = 11,
         TYPE_ISTRUE = 12,
         TYPE_ISFALSE = 13,
         TYPE_ISUNKNOWN = 14,
         TYPE_INTVAL = 15,
         TYPE_FLOATVAL = 16,
         TYPE_PARAMETER = 17,
         TYPE_STRINGVAL = 18,
         TYPE_concat = 19,
         TYPE_addition = 20,
         TYPE_subtraction = 21,
         TYPE_multiplication = 22,
         TYPE_division = 23,
         TYPE_exponent = 24,
         TYPE_uminus = 25,
         TYPE_ASC = 26,
         TYPE_DESC = 27,
         TYPE_ORDERBY = 28,
         TYPE_FORUPDATE = 29,
         TYPE_HAVING = 30,
         TYPE_GROUPBY = 31,
         TYPE_WHERE = 32,
         TYPE_AVG = 33,
         TYPE_COUNT = 34,
         TYPE_MAX = 35,
         TYPE_MIN = 36,
         TYPE_SUM = 37,
         TYPE_ASTERISK = 38,
         TYPE_DISTINCT = 39,
         TYPE_ALL = 40,
         TYPE_BETWEEN = 41,
         TYPE_BETWEENEXPRESSIONS = 42,
         TYPE_IN = 43,
         TYPE_LIKE = 44,
         TYPE_EXISTS = 45,
         TYPE_UNIQUE = 46,
         TYPE_assignment = 47,
         TYPE_AND = 48,
         TYPE_OR = 49,
         TYPE_SELECT = 50,
         TYPE_INSERT = 51,
         TYPE_UPDATE = 52,
         TYPE_DELETE = 53,
         TYPE_COLUMNS = 55,
         TYPE_EXPRESSION = 56,
         TYPE_FROM = 57,
         TYPE_search_condition = 58,
         TYPE_SORTSPECIFICATION = 59,
         TYPE_AGGREGATE = 60,
         TYPE_operator = 61,
         TYPE_operand = 62,
         TYPE_inobject = 63,
         TYPE_BEGIN = 64,
         TYPE_COMMIT = 65,
         TYPE_ROLLBACK = 66,
         TYPE_SET = 67,
         TYPE_storedprocedure = 68,
         TYPE_inbegin = 69,
         TYPE_NOLOCK = 70
     };
Constructor & Destructor Documentation
Larxer::Larxer (char * instr, class TransactionAgent * taPtr, class Schema * schemaPtr)
tokenize, parse, and compile SQL statement
many of these functions are called by the lexer.ll and parser.yy generated code
Parameters
instr SQL statement
taPtr TransactionAgent
schemaPtr Schema
Definition at line 34 of file Larxer.cc.
References eatstack(), flexbuffer(), flexdestroy(), flexinit(), perlarxer::larxerPtr, parsedStack, perlarxer::scaninfo, statementPtr, and yyparse().
 {
     struct perlarxer pld;
     pld.larxerPtr = this;
     flexinit(&pld);
     flexbuffer(instr, strlen(instr), pld.scaninfo);
     // must clear stack before parsing statement
     while (!parsedStack.empty())
     {
         parsedStack.pop();
     }
     if (yyparse(&pld))
     {
         statementPtr=NULL;
         flexdestroy(pld.scaninfo);
         return;
     }
     flexdestroy(pld.scaninfo);
     eatstack(taPtr, schemaPtr);
 }
Larxer::~Larxer () virtual
Definition at line 59 of file Larxer.cc.
 {
 }
Member Function Documentation
void Larxer::consumeColumns (int64_t numcolumns)
extract columns from stack
Parameters
numcolumns number of columns
Definition at line 699 of file Larxer.cc.
References currentQuery, Statement::query_s::fromColumns, parsedStack, popstack(), Larxer::stackmember_s::type, TYPE_ASTERISK, TYPE_operand, and Larxer::stackmember_s::val.
Referenced by consumeSelect().
 {
     for (int64_t n=0; n < numcolumns; n++)
     {
         if (parsedStack.empty())
         {
             printf("%s %i anomaly parsedStack empty\n", __FILE__, __LINE__);
             return;
         }
         stackmember_s item = popstack();
         switch (item.type)
         {
         case TYPE_ASTERISK:
             currentQuery->fromColumns.push_back("*");
             break;
         case TYPE_operand:
             currentQuery->fromColumns.push_back(item.val);
             break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         }
     }
 }
void Larxer::consumeDelete ()
extract DELETE query from stack
Definition at line 678 of file Larxer.cc.
References CMD_DELETE, consumeFrom(), consumeWhere(), currentQuery, Statement::query_s::locktype, parsedStack, popstack(), Larxer::stackmember_s::type, Statement::query_s::type, TYPE_WHERE, and WRITELOCK.
Referenced by eatstack().
 {
     currentQuery->type = CMD_DELETE;
     currentQuery->locktype = WRITELOCK;
     while (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         if (item.type == TYPE_WHERE)
         {
             consumeWhere();
         }
         else
         {
             parsedStack.push(item);
             consumeFrom();
         }
     }
 }
class Ast * Larxer::consumeExpression ()
extract expression from stack
Returns
Ast object
create Ast, return its root node
Definition at line 206 of file Larxer.cc.
References consumeInobject(), consumeSubquery(), Ast::leftchild, Ast::operand, OPERAND_SUBQUERY, Ast::parent, parsedStack, popstack(), Ast::rightchild, Larxer::stackmember_s::type, TYPE_EXPRESSION, TYPE_inbegin, TYPE_inobject, TYPE_operand, and TYPE_operator.
Referenced by consumeHaving(), consumeInobject(), consumeInsert(), consumeUpdate(), and consumeWhere().
 {
     class Ast *rootnode = NULL;
     class Ast *currentnode = NULL;
     if (parsedStack.empty())
     {
         printf("%s %i anomaly\n", __FILE__, __LINE__);
         return NULL;
     }
     stackmember_s item = popstack();
     if (item.type==TYPE_EXPRESSION)
     {
         /* if called as search_expression, then the next object might be an
          * expression, which is already being handled ;-)
          */
         item = popstack();
     }
     switch (item.type)
     {
     case TYPE_operator:
         rootnode = new class Ast(NULL,
                                  (operatortypes_e)getintval(item.val));
         currentnode = rootnode;
         break;
     case TYPE_operand:
         rootnode = new class Ast(NULL, item.val);
         return rootnode;
 //        break;
     default:
         printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         parsedStack.push(item);
         delete rootnode;
         return NULL;
     }
     while (1)
     {
         while (currentnode->rightchild != NULL && currentnode->leftchild != NULL)
         {
             if (currentnode->parent == NULL)
             {
                 // no place left to allocate new node, therefore ast is complete
                 return rootnode;
             }
             currentnode = currentnode->parent;
         }
         if (parsedStack.empty())
         {
             printf("%s %i anomaly\n", __FILE__, __LINE__);
             return NULL;
         }
         item = popstack();
         class Ast *newnode=NULL;
         switch (item.type)
         {
         case TYPE_operator:
             newnode = new class Ast(currentnode,
                                     (operatortypes_e)getintval(item.val));
             newnode->parent = currentnode;
             if (currentnode->rightchild == NULL)
             {
                 currentnode->rightchild = newnode;
             }
             else
             {
                 currentnode->leftchild = newnode;
             }
             currentnode = newnode;
             break;
         case TYPE_operand:
             newnode = new class Ast(currentnode, item.val);
             if (currentnode->rightchild == NULL)
             {
                 currentnode->rightchild = newnode;
             }
             else
             {
                 currentnode->leftchild = newnode;
             }
             if (item.val[0] == OPERAND_SUBQUERY) // subquery
             {
                 int64_t sq = consumeSubquery();
                 newnode->operand.append(sizeof(sq), char(0));
                 memcpy(&newnode->operand[1], &sq, sizeof(sq));
             }
             break;
         case TYPE_EXPRESSION: // noop, get next item
             break;
         case TYPE_inobject:
             consumeInobject();
             break;
         case TYPE_inbegin:
             //        return rootnode;
             break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
             parsedStack.push(item);
             return rootnode;
         }
     }
 }
void Larxer::consumeFrom ()
extract FROM clause from stack
Definition at line 727 of file Larxer.cc.
References currentQuery, parsedStack, popstack(), Statement::query_s::table, Larxer::stackmember_s::type, TYPE_operand, and Larxer::stackmember_s::val.
Referenced by consumeDelete(), consumeInsert(), consumeSelect(), and consumeUpdate().
 {
     if (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         if (item.type==TYPE_operand)
         {
             currentQuery->table = item.val.substr(1, string::npos);
         }
         else
         {
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         }
     }
     else
     {
         printf("%s %i anomaly parsedStack empty\n", __FILE__, __LINE__);
     }
 }
void Larxer::consumeGroupby ()
extract GROUP BY clause from stack
Definition at line 771 of file Larxer.cc.
References currentQuery, Statement::query_s::groupByList, Statement::query_s::hasgroupby, OPERAND_IDENTIFIER, parsedStack, popstack(), Larxer::stackmember_s::type, TYPE_operand, and Larxer::stackmember_s::val.
Referenced by consumeSelect().
 {
     currentQuery->hasgroupby = true;
     while (1)
     {
         if (parsedStack.empty())
         {
             return;
         }
         stackmember_s item = popstack();
         if (item.type != TYPE_operand)
         {
             parsedStack.push(item);
             return;
         }
         if (item.val[0] != OPERAND_IDENTIFIER)
         {
             printf("%s %i anomaly %c\n", __FILE__, __LINE__, item.val[0]);
             return;
         }
         currentQuery->groupByList.push_back(item.val.substr(1, string::npos));
     }
 }
void Larxer::consumeHaving ()
extract HAVING clause from stack
Definition at line 800 of file Larxer.cc.
References consumeExpression(), currentQuery, Statement::query_s::hashaving, parsedStack, popstack(), Statement::query_s::searchCondition, Larxer::stackmember_s::type, and TYPE_search_condition.
Referenced by consumeSelect().
 {
     currentQuery->hashaving = true;
     if (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         if (item.type==TYPE_search_condition)
         {
             currentQuery->searchCondition = consumeExpression();
         }
         else
         {
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         }
     }
     else
     {
         printf("%s %i anomaly parsedStack empty\n", __FILE__, __LINE__);
     }
 }
void Larxer::consumeInobject ()
extract list of IN values from stack
Definition at line 352 of file Larxer.cc.
References consumeExpression(), consumeSubquery(), currentQuery, Statement::inobject_s::expressionlist, Statement::query_s::inobject, Statement::inobject_s::issubquery, parsedStack, Statement::inobject_s::subquery, TYPE_EXPRESSION, and TYPE_SUBQUERY.
Referenced by consumeExpression().
 {
     if (parsedStack.top().type == TYPE_SUBQUERY)
     {
         parsedStack.pop();
         currentQuery->inobject.issubquery = true;
         currentQuery->inobject.subquery = consumeSubquery();
         return;
     }
     else
     {
         currentQuery->inobject.issubquery = false;
         while (parsedStack.top().type == TYPE_EXPRESSION)
         {
             parsedStack.pop();
             currentQuery->inobject.expressionlist.push_back(consumeExpression());
         }
     }
 }
void Larxer::consumeInsert ()
extract INSERT query from stack
Definition at line 627 of file Larxer.cc.
References CMD_INSERT, consumeExpression(), consumeFrom(), currentQuery, Statement::query_s::insertColumns, Statement::query_s::locktype, parsedStack, popstack(), Larxer::stackmember_s::type, Statement::query_s::type, TYPE_EXPRESSION, and WRITELOCK.
Referenced by eatstack().
 {
     currentQuery->type = CMD_INSERT;
     currentQuery->locktype = WRITELOCK;
     while (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         if (item.type == TYPE_EXPRESSION)
         {
             currentQuery->insertColumns.push_back(consumeExpression());
         }
         else
         {
             parsedStack.push(item);
             consumeFrom();
         }
     }
 }
void Larxer::consumeOrderby ()
extract ORDER BY clause from stack
Definition at line 823 of file Larxer.cc.
References currentQuery, Statement::query_s::hasorderby, Statement::query_s::orderbylist, parsedStack, popstack(), Larxer::stackmember_s::type, TYPE_ASC, TYPE_SORTSPECIFICATION, and Larxer::stackmember_s::val.
Referenced by consumeSelect().
 {
     currentQuery->hasorderby = true;
     while (1)
     {
         stackmember_s item = popstack();
         if (item.type != TYPE_SORTSPECIFICATION)
         {
             parsedStack.push(item);
             return;
         }
         item = popstack();
         stackmember_s item2 = popstack();
         if (item2.type == TYPE_ASC)
         {
             currentQuery->orderbylist.push_back({true, item.val});
         }
         else
         {
             currentQuery->orderbylist.push_back({false, item.val});
         }
     }
 }
void Larxer::consumeSelect (string & columns)
extract SELECT query from stack
Parameters
columns quantity of columns
Definition at line 565 of file Larxer.cc.
References CMD_SELECT, consumeColumns(), consumeFrom(), consumeGroupby(), consumeHaving(), consumeOrderby(), consumeWhere(), currentQuery, getintval(), Statement::query_s::hasnolock, Statement::query_s::isforupdate, Statement::query_s::locktype, NOLOCK, parsedStack, popstack(), READLOCK, Larxer::stackmember_s::type, Statement::query_s::type, TYPE_COLUMNS, TYPE_FORUPDATE, TYPE_FROM, TYPE_GROUPBY, TYPE_HAVING, TYPE_NOLOCK, TYPE_ORDERBY, TYPE_WHERE, and WRITELOCK.
Referenced by consumeSubquery(), and eatstack().
 {
     currentQuery->type = CMD_SELECT;
     while (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         switch (item.type)
         {
         case TYPE_COLUMNS:
             consumeColumns(getintval(columns));
             if (currentQuery->isforupdate==true)
             {
                 currentQuery->locktype=WRITELOCK;
             }
             else if (currentQuery->hasnolock==true)
             {
                 currentQuery->locktype=NOLOCK;
             }
             {
                 currentQuery->locktype=READLOCK;
             }
             return; // end of select statement
 //            break;
         case TYPE_FROM:
             consumeFrom();
             break;
         case TYPE_WHERE:
             consumeWhere();
             break;
         case TYPE_GROUPBY:
             consumeGroupby();
             break;
         case TYPE_HAVING:
             consumeHaving();
             break;
         case TYPE_FORUPDATE:
             currentQuery->isforupdate=true;
             break;
         case TYPE_NOLOCK:
             currentQuery->hasnolock=true;
         case TYPE_ORDERBY:
             consumeOrderby();
             break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         }
     }
 }
void Larxer::consumeStoredProcedure ()
extract stored procedure call query from stack
Definition at line 851 of file Larxer.cc.
References CMD_STOREDPROCEDURE, currentQuery, parsedStack, popstack(), Statement::query_s::storedProcedure, Statement::query_s::storedProcedureArgs, Statement::query_s::type, and Larxer::stackmember_s::val.
Referenced by eatstack().
 {
     currentQuery->type=CMD_STOREDPROCEDURE;
     stackmember_s item;
     while (!parsedStack.empty())
     {
         item=popstack();
         currentQuery->storedProcedureArgs.push_back(item.val);
     }
     currentQuery->storedProcedureArgs.pop_back();
     currentQuery->storedProcedure=item.val.substr(1, string::npos);
     std::reverse(currentQuery->storedProcedureArgs.begin(),
                  currentQuery->storedProcedureArgs.end());
     return;
 }
int64_t Larxer::consumeSubquery ()
extract subquery from stack
Returns
index of vector of queries
Definition at line 330 of file Larxer.cc.
References consumeSelect(), currentQuery, Statement::query_s::instance, popstack(), Statement::queries, statementPtr, Larxer::stackmember_s::type, TYPE_SELECT, and Larxer::stackmember_s::val.
Referenced by consumeExpression(), and consumeInobject().
 {
     ssize_t currentQueryInstance = currentQuery->instance;
     statementPtr->queries.push_back(Statement::query_s());
     size_t i = statementPtr->queries.size()-1;
     currentQuery = &statementPtr->queries[i];
     currentQuery->instance = i;
     stackmember_s item = popstack();
     if (item.type != TYPE_SELECT)
     {
         printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         return -2;
     }
     consumeSelect(item.val);
     currentQuery = &statementPtr->queries[currentQueryInstance];
     return i;
 }
void Larxer::consumeUpdate ()
extract UPDATE query from stack
Definition at line 648 of file Larxer.cc.
References Statement::query_s::assignments, CMD_UPDATE, consumeExpression(), consumeFrom(), consumeWhere(), currentQuery, Statement::query_s::locktype, parsedStack, popstack(), Larxer::stackmember_s::type, Statement::query_s::type, TYPE_assignment, TYPE_WHERE, Larxer::stackmember_s::val, and WRITELOCK.
Referenced by eatstack().
 {
     currentQuery->type = CMD_UPDATE;
     currentQuery->locktype = WRITELOCK;
     while (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         if (item.type == TYPE_WHERE)
         {
             consumeWhere();
         }
         else
         {
             if (item.type != TYPE_assignment)
             {
                 parsedStack.push(item);
                 consumeFrom();
                 return;
             }
             item = popstack(); // expression
             class Ast *expr = consumeExpression();
             stackmember_s item2 = popstack(); // identifier
             currentQuery->assignments[item2.val.substr(1, string::npos)] = expr;
         }
     }
 }
void Larxer::consumeWhere ()
extract WHERE clause from stack
Definition at line 748 of file Larxer.cc.
References consumeExpression(), currentQuery, Statement::query_s::haswhere, parsedStack, popstack(), Statement::query_s::searchCondition, Larxer::stackmember_s::type, and TYPE_search_condition.
Referenced by consumeDelete(), consumeSelect(), and consumeUpdate().
 {
     currentQuery->haswhere = true;
     if (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         if (item.type==TYPE_search_condition)
         {
             currentQuery->searchCondition = consumeExpression();
         }
         else
         {
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         }
     }
     else
     {
         printf("%s %i anomaly parsedStack empty\n", __FILE__, __LINE__);
     }
 }
void Larxer::eatstack (class TransactionAgent * taPtr, class Schema * schemaPtr)
consume entire stack
Parameters
taPtr TransactionAgent
schemaPtr Schema
Definition at line 154 of file Larxer.cc.
References CMD_BEGIN, CMD_COMMIT, CMD_ROLLBACK, consumeDelete(), consumeInsert(), consumeSelect(), consumeStoredProcedure(), consumeUpdate(), currentQuery, Statement::query_s::instance, parsedStack, popstack(), Statement::queries, statementPtr, Larxer::stackmember_s::type, Statement::query_s::type, TYPE_BEGIN, TYPE_COMMIT, TYPE_DELETE, TYPE_INSERT, TYPE_ROLLBACK, TYPE_SELECT, TYPE_storedprocedure, TYPE_UPDATE, and Larxer::stackmember_s::val.
Referenced by Larxer().
 {
     statementPtr = new class Statement(taPtr, schemaPtr);
     statementPtr->queries.push_back(Statement::query_s {});
     currentQuery = &statementPtr->queries[0];
     currentQuery->instance = 0;
     while (!parsedStack.empty())
     {
         stackmember_s item = popstack();
         switch (item.type)
         {
         case TYPE_SELECT:
             consumeSelect(item.val);
             break;
         case TYPE_INSERT:
             consumeInsert();
             break;
         case TYPE_UPDATE:
             consumeUpdate();
             break;
         case TYPE_DELETE:
             consumeDelete();
             break;
         case TYPE_storedprocedure:
             consumeStoredProcedure();
             break;
         case TYPE_COMMIT:
             currentQuery->type = CMD_COMMIT;
             break;
         case TYPE_BEGIN:
             currentQuery->type = CMD_BEGIN;
             break;
         case TYPE_ROLLBACK:
             currentQuery->type = CMD_ROLLBACK;
             break;
         default:
             printf("%s %i anomaly %i\n", __FILE__, __LINE__, item.type);
         }
     }
 }
long double Larxer::getfloatval (string & val)
convert string to float
Parameters
val string input
Returns
float value
Definition at line 147 of file Larxer.cc.
 {
     long double rv;
     memcpy(&rv, &val[0], sizeof(rv));
     return rv;
 }
int64_t Larxer::getintval (string & val)
convert string to integer
Parameters
val string input
Returns
integer value
Definition at line 140 of file Larxer.cc.
Referenced by consumeSelect().
 {
     int64_t rv;
     memcpy(&rv, &val[0], sizeof(rv));
     return rv;
 }
Larxer::stackmember_s Larxer::popstack ()
take item off stack
Returns
item
Definition at line 133 of file Larxer.cc.
References parsedStack.
Referenced by consumeColumns(), consumeDelete(), consumeExpression(), consumeFrom(), consumeGroupby(), consumeHaving(), consumeInsert(), consumeOrderby(), consumeSelect(), consumeStoredProcedure(), consumeSubquery(), consumeUpdate(), consumeWhere(), and eatstack().
 {
     stackmember_s item = parsedStack.top();
     parsedStack.pop();
     return item;
 }
void Larxer::printstack ()
show stack entries, for debugging
Definition at line 373 of file Larxer.cc.
References OPERAND_BOOLEAN, OPERAND_FLOAT, OPERAND_IDENTIFIER, OPERAND_INTEGER, OPERAND_PARAMETER, OPERAND_STRING, OPERAND_SUBQUERY, OPERATOR_ADDITION, OPERATOR_AND, OPERATOR_BETWEEN, OPERATOR_BETWEENAND, OPERATOR_CONCATENATION, OPERATOR_DIVISION, OPERATOR_EQ, OPERATOR_EXISTS, OPERATOR_FALSE, OPERATOR_GT, OPERATOR_GTE, OPERATOR_IN, OPERATOR_ISNULL, OPERATOR_LIKE, OPERATOR_LT, OPERATOR_LTE, OPERATOR_MULTIPLICATION, OPERATOR_NE, OPERATOR_NEGATION, OPERATOR_NONE, OPERATOR_NOT, OPERATOR_OR, OPERATOR_SUBTRACTION, OPERATOR_TRUE, OPERATOR_UNIQUE, OPERATOR_UNKNOWN, parsedStack, TYPE_operand, and TYPE_operator.
 {
     while (!parsedStack.empty())
     {
         printf("\tTYPE: %i\n", parsedStack.top().type);
         switch (parsedStack.top().type)
         {
         case TYPE_operator:
             printf("\n");
             int64_t arg;
             memcpy(&arg, &parsedStack.top().val[0], sizeof(arg));
             switch ((operatortypes_e)arg)
             {
             case OPERATOR_NONE:
                 printf("NOOP (anomaly) ");
                 break;
             case OPERATOR_CONCATENATION:
                 printf("CONCATENATION ");
                 break;
             case OPERATOR_ADDITION:
                 printf("+ ");
                 break;
             case OPERATOR_SUBTRACTION:
                 printf("- ");
                 break;
             case OPERATOR_MULTIPLICATION:
                 printf("* ");
                 break;
             case OPERATOR_DIVISION:
                 printf("/ ");
                 break;
             case OPERATOR_NEGATION:
                 printf("NEGATE -");
                 break;
             case OPERATOR_AND:
                 printf("AND ");
                 break;
             case OPERATOR_OR:
                 printf("OR ");
                 break;
             case OPERATOR_NOT:
                 printf("NOT ");
                 break;
             case OPERATOR_TRUE:
                 printf("TRUE ");
                 break;
             case OPERATOR_FALSE:
                 printf("FALSE ");
                 break;
             case OPERATOR_UNKNOWN:
                 printf("UNKNOWN ");
                 break;
             case OPERATOR_EQ:
                 printf("= ");
                 break;
             case OPERATOR_NE:
                 printf("<> ");
                 break;
             case OPERATOR_LT:
                 printf("< ");
                 break;
             case OPERATOR_GT:
                 printf("> ");
                 break;
             case OPERATOR_LTE:
                 printf("<= ");
                 break;
             case OPERATOR_GTE:
                 printf(">= ");
                 break;
             case OPERATOR_BETWEEN:
                 printf("BETWEEN ");
                 break;
             case OPERATOR_ISNULL:
                 printf("ISNULL ");
                 break;
             case OPERATOR_IN:
                 printf("IN ");
                 break;
             case OPERATOR_LIKE:
                 printf("LIKE ");
                 break;
             case OPERATOR_EXISTS:
                 printf("EXISTS ");
                 break;
             case OPERATOR_UNIQUE:
                 printf("UNIQUE ");
                 break;
             case OPERATOR_BETWEENAND:
                 printf("BETWEENAND ");
                 break;
             default:
                 ;
             }
             break;
         case TYPE_operand:
             switch (parsedStack.top().val[0])
             {
             case OPERAND_STRING:
                 printf("%s ", parsedStack.top().val.c_str()+1);
                 break;
             case OPERAND_IDENTIFIER:
                 printf("%s ", parsedStack.top().val.c_str()+1);
                 break;
             case OPERAND_PARAMETER:
             {
                 int64_t a;
                 memcpy(&a, &parsedStack.top().val[1], sizeof(a));
                 printf("$%li ", a);
             }
             break;
             case OPERAND_SUBQUERY:
                 printf("subquery, ");
                 break;
             case OPERAND_INTEGER:
             {
                 int64_t a;
                 memcpy(&a, &parsedStack.top().val[1], sizeof(a));
                 printf("%li ", a);
             }
             break;
             case OPERAND_BOOLEAN:
                 if (parsedStack.top().val[1]=='t')
                 {
                     printf("boolean true\n");
                 }
                 else
                 {
                     printf("boolean false\n");
                 }
                 break;
             case OPERAND_FLOAT:
             {
                 long double a;
                 memcpy(&a, &parsedStack.top().val[1], sizeof(a));
                 printf("$%Lf ", a);
             }
             break;
             default:
                 ;
             }
             break;
         default:
             ;
         }
         parsedStack.pop();
     }
     printf("\n");
 }
void Larxer::pushaggregate (char aggregatetype, const char * val)
push aggregate and associated field onto stack
Parameters
aggregatetype type of aggregate
val associated field
Definition at line 124 of file Larxer.cc.
References OPERAND_AGGREGATE, pushstack(), and TYPE_operand.
 {
     string str(2 + strlen(val), char(0));
     str[0] = OPERAND_AGGREGATE;
     str[1] = aggregatetype;
     memcpy(&str[2], val, strlen(val));
     pushstack(Larxer::TYPE_operand, str);
 }
void Larxer::pushoperand (char operandtype)
push operand onto stack
Parameters
operandtype type of operand
Definition at line 94 of file Larxer.cc.
References pushstack(), and TYPE_operand.
 {
     string str(&operandtype, 1);
     pushstack(Larxer::TYPE_operand, str);
 }
void Larxer::pushoperand (char operandtype, int64_t val)
push operand onto stack
Parameters
operandtype type of operand
val associated value
Definition at line 100 of file Larxer.cc.
References pushstack(), and TYPE_operand.
 {
     string str(1 + sizeof(val), char(0));
     str[0] = operandtype;
     memcpy(&str[1], &val, sizeof(val));
     pushstack(Larxer::TYPE_operand, str);
 }
void Larxer::pushoperand (char operandtype, long double val)
push operand onto stack
Parameters
operandtype type of operand
val associated value
Definition at line 108 of file Larxer.cc.
References pushstack(), and TYPE_operand.
 {
     string str(1 + sizeof(val), char(0));
     str[0] = operandtype;
     memcpy(&str[1], &val, sizeof(val));
     pushstack(Larxer::TYPE_operand, str);
 }
void Larxer::pushoperand (char operandtype, const char * val)
push operand onto stack
Parameters
operandtype type of operand
val associated value
Definition at line 116 of file Larxer.cc.
References pushstack(), and TYPE_operand.
 {
     string str(1 + strlen(val), char(0));
     str[0] = operandtype;
     memcpy(&str[1], val, strlen(val));
     pushstack(Larxer::TYPE_operand, str);
 }
void Larxer::pushstack (stacktypes_e type)
put item on stack
stack is intermediary between parsing and Statement object
Parameters
type stack entry
Definition at line 63 of file Larxer.cc.
References parsedStack.
Referenced by pushaggregate(), and pushoperand().
 {
     stackmember_s m = {type, string()};
     parsedStack.push(m);
 }
void Larxer::pushstack (stacktypes_e type, int64_t val)
put item on stack
stack is intermediary between parsing and Statement object
Parameters
type stack entry
val value associated with entry
Definition at line 69 of file Larxer.cc.
References parsedStack.
 {
     string stackstr(sizeof(val), '0');
     memcpy(&stackstr[0], &val, sizeof(val));
     parsedStack.push({type, stackstr});
 }
void Larxer::pushstack (stacktypes_e type, long double val)
put item on stack
stack is intermediary between parsing and Statement object
Parameters
type stack entry
val value associated with entry
Definition at line 76 of file Larxer.cc.
References parsedStack.
 {
     printf("%s %i pushstack float %Lf\n", __FILE__, __LINE__, val);
     string stackstr(sizeof(val), '0');
     memcpy(&stackstr[0], &val, sizeof(val));
     parsedStack.push({type, stackstr});
 }
void Larxer::pushstack (stacktypes_e type, const char * val)
put item on stack
stack is intermediary between parsing and Statement object
Parameters
type stack entry
val value associated with entry
Definition at line 84 of file Larxer.cc.
References parsedStack.
 {
     parsedStack.push({type, string(val)});
 }
void Larxer::pushstack (stacktypes_e type, string & val)
put item on stack
stack is intermediary between parsing and Statement object
Parameters
type stack entry
val value associated with entry
Definition at line 89 of file Larxer.cc.
References parsedStack.
 {
     parsedStack.push({type, val});
 }
Member Data Documentation
class Statement::query_s* Larxer::currentQuery
Definition at line 345 of file Larxer.h.
Referenced by consumeColumns(), consumeDelete(), consumeFrom(), consumeGroupby(), consumeHaving(), consumeInobject(), consumeInsert(), consumeOrderby(), consumeSelect(), consumeStoredProcedure(), consumeSubquery(), consumeUpdate(), consumeWhere(), and eatstack().
std::stack<stackmember_s> Larxer::parsedStack
Definition at line 344 of file Larxer.h.
Referenced by consumeColumns(), consumeDelete(), consumeExpression(), consumeFrom(), consumeGroupby(), consumeHaving(), consumeInobject(), consumeInsert(), consumeOrderby(), consumeSelect(), consumeStoredProcedure(), consumeUpdate(), consumeWhere(), eatstack(), Larxer(), popstack(), printstack(), and pushstack().
class Statement* Larxer::statementPtr
Definition at line 346 of file Larxer.h.
Referenced by TransactionAgent::compile(), consumeSubquery(), Pg::cont(), eatstack(), Pg::executeStatement(), Larxer(), and TransactionAgent::newstatement().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Larxer.h
/home/infinisql/build/infinisql/infinisqld/Larxer.cc