InfiniSQL: MessageAckApply Class Reference
MessageAckApply Class Reference
Message variant for acknowledging Applier activities.
#include <Message.h>
Classes
struct ackapply_s
MessageAckApply POD (serializable by memcpy) data members.
Public Member Functions
MessageAckApply ()
MessageAckApply (int64_t subtransactionidarg, int64_t applieridarg, int64_t partitionidarg, int statusarg)
Message variant for acknowledging Applier activities.
virtual ~MessageAckApply ()
size_t size ()
get Message size
string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
size_t size ()
get Message size
std::string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
string * sermsg ()
return serialized Message variant string
void setEnvelope (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
put addresses in Message variant envelope
Public Attributes
ackapply_s ackapplyStruct
Public Attributes inherited from Message
__int128 nextmsg
message_s messageStruct
Additional Inherited Members
Static Public Member Functions inherited from Message
static class Message * des (string *serstr)
deserialize entire message
Detailed Description
Message variant for acknowledging Applier activities.
Returns
Definition at line 785 of file Message.h.
Constructor & Destructor Documentation
MessageAckApply::MessageAckApply ()
Definition at line 733 of file Message.cc.
 {
 }
MessageAckApply::MessageAckApply (int64_t subtransactionidarg, int64_t applieridarg, int64_t partitionidarg, int statusarg)
Message variant for acknowledging Applier activities.
Parameters
subtransactionidarg subtransactionid
applieridarg applierid
partitionidarg partitionid
statusarg status
Returns
Definition at line 737 of file Message.cc.
                                                 :
     ackapplyStruct ({subtransactionidarg, applieridarg, partitionidarg,
                 statusarg})
MessageAckApply::~MessageAckApply () virtual
Definition at line 747 of file Message.cc.
 {
 }
Member Function Documentation
void MessageAckApply::clear ()
clear contents of this
Definition at line 780 of file Message.cc.
References ackapplyStruct, and Message::clear().
 {
     Message::clear();
     ackapplyStruct={};
 }
void MessageAckApply::package (class SerializedMessage & serobj)
serialize this
Parameters
serobj SerializedMessage
Definition at line 768 of file Message.cc.
References ackapplyStruct, Message::package(), and SerializedMessage::ser().
Referenced by ser().
 {
     Message::package(serobj);
     serobj.ser(ackapplyStruct);
 }
string * MessageAckApply::ser ()
create string with serialized message
Returns
serialized message string
Definition at line 756 of file Message.cc.
References SerializedMessage::data, SerializedMessage::getpayloadtype(), logfile, package(), and SerializedMessage::pos.
 {
     class SerializedMessage serobj(size());
     package(serobj);
     if (serobj.data->size() != serobj.pos)
     {
         fprintf(logfile, "%s %i ser %i size %lu pos %lu\n", __FILE__, __LINE__,
                 serobj.getpayloadtype(), serobj.data->size(), serobj.pos);
     }
     return serobj.data;
 }
size_t MessageAckApply::size ()
get Message size
Returns
size in bytes
Definition at line 751 of file Message.cc.
References ackapplyStruct, SerializedMessage::sersize(), and Message::size().
 {
     return Message::size() + SerializedMessage::sersize(ackapplyStruct);
 }
void MessageAckApply::unpack (SerializedMessage & serobj)
deserialize into this
Parameters
serobj SerializedMessage
Definition at line 774 of file Message.cc.
References ackapplyStruct, SerializedMessage::des(), and Message::unpack().
Referenced by Message::des().
 {
     Message::unpack(serobj);
     serobj.des(ackapplyStruct);
 }
Member Data Documentation
ackapply_s MessageAckApply::ackapplyStruct
Definition at line 844 of file Message.h.
Referenced by Applier::ackedApply(), clear(), package(), size(), TransactionAgent::TransactionAgent(), and unpack().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc