InfiniSQL: MessageTransaction Class Reference
MessageTransaction Class Reference
Message variant for transaction processing.
#include <Message.h>
Classes
struct transaction_s
MessageTransaction POD (serializable by memcpy) data members.
Public Member Functions
MessageTransaction ()
virtual ~MessageTransaction ()
size_t size ()
get Message size
string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
size_t size ()
get Message size
std::string * ser ()
create string with serialized message
void package (class SerializedMessage &serobj)
serialize this
void unpack (SerializedMessage &serobj)
deserialize into this
void clear ()
clear contents of this
string * sermsg ()
return serialized Message variant string
void setEnvelope (const Topology::addressStruct &source, const Topology::addressStruct &dest, class Message &msg)
put addresses in Message variant envelope
Public Attributes
transaction_s transactionStruct
Public Attributes inherited from Message
__int128 nextmsg
message_s messageStruct
Additional Inherited Members
Static Public Member Functions inherited from Message
static class Message * des (string *serstr)
deserialize entire message
Detailed Description
Message variant for transaction processing.
Returns
Definition at line 378 of file Message.h.
Constructor & Destructor Documentation
MessageTransaction::MessageTransaction ()
Definition at line 388 of file Message.cc.
                                        : transactionStruct()
 {
 }
MessageTransaction::~MessageTransaction () virtual
Definition at line 392 of file Message.cc.
 {
 }
Member Function Documentation
void MessageTransaction::clear ()
clear contents of this
Definition at line 426 of file Message.cc.
References Message::clear(), and transactionStruct.
Referenced by MessageSubtransactionCmd::clear(), and MessageCommitRollback::clear().
 {
     Message::clear();
     transactionStruct={};
 }
void MessageTransaction::package (class SerializedMessage & serobj)
serialize this
Parameters
serobj SerializedMessage
Definition at line 414 of file Message.cc.
References Message::package(), SerializedMessage::ser(), and transactionStruct.
Referenced by MessageSubtransactionCmd::package(), MessageCommitRollback::package(), and ser().
 {
     Message::package(serobj);
     serobj.ser(transactionStruct);
 }
string * MessageTransaction::ser ()
create string with serialized message
Returns
serialized message string
Definition at line 402 of file Message.cc.
References SerializedMessage::data, SerializedMessage::getpayloadtype(), logfile, package(), and SerializedMessage::pos.
 {
     class SerializedMessage serobj(size());
     package(serobj);
     if (serobj.data->size() != serobj.pos)
     {
         fprintf(logfile, "%s %i ser %i size %lu pos %lu\n", __FILE__, __LINE__,
                 serobj.getpayloadtype(), serobj.data->size(), serobj.pos);
     }
     return serobj.data;
 }
size_t MessageTransaction::size ()
get Message size
Returns
size in bytes
Definition at line 397 of file Message.cc.
References SerializedMessage::sersize(), Message::size(), and transactionStruct.
Referenced by MessageSubtransactionCmd::size(), and MessageCommitRollback::size().
 {
     return Message::size() + SerializedMessage::sersize(transactionStruct);
 }
void MessageTransaction::unpack (SerializedMessage & serobj)
deserialize into this
Parameters
serobj SerializedMessage
Definition at line 420 of file Message.cc.
References SerializedMessage::des(), transactionStruct, and Message::unpack().
Referenced by MessageSubtransactionCmd::unpack(), and MessageCommitRollback::unpack().
 {
     Message::unpack(serobj);
     serobj.des(transactionStruct);
 }
Member Data Documentation
transaction_s MessageTransaction::transactionStruct
Definition at line 430 of file Message.h.
Referenced by clear(), Transaction::continueCommitTransaction(), Transaction::continueSelectRows(), Transaction::continueSqlDelete(), Transaction::continueSqlPredicate(), SubTransaction::drainIndexLockQueue(), SubTransaction::drainRowLockQueue(), Engine::Engine(), package(), SubTransaction::processTransactionMessage(), Transaction::processTransactionMessage(), SubTransaction::replyTransaction(), Transaction::rollback(), SubTransaction::searchReturn1(), Transaction::sendTransaction(), size(), TransactionAgent::TransactionAgent(), SubTransaction::uniqueIndex(), and unpack().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/Message.h
/home/infinisql/build/infinisql/infinisqld/Message.cc