InfiniSQL: ApiInterface Class Reference
ApiInterface Class Reference abstract
Stored procedure API.
#include <infinisql.h>
Classes
struct results_s
results from SQL query
Public Member Functions
ApiInterface ()
virtual ~ApiInterface ()
virtual void doit ()=0
virtual void continueFunc1 (int64_t entrypoint, void *statePtr)=0
user-defined continuation function
virtual void continueFunc2 (int64_t entrypoint, void *statePtr)=0
second user-defined continuation function
virtual void continuePgFunc (int64_t entrypoint, void *statePtr)=0
after SQL activity is performed
virtual void continuePgCommitimplicit (int64_t entrypoint, void *statePtr)=0
continuation function after implicit commit
virtual void continuePgCommitexplicit (int64_t entrypoint, void *statePtr)=0
continuation function after explicit commit
virtual void continuePgRollbackimplicit (int64_t entrypoint, void *statePtr)=0
continuation function after implicit rollback
virtual void continuePgRollbackexplicit (int64_t entrypoint, void *statePtr)=0
continuation function after explicit rollback
void deserialize2Vector ()
orphan
void beginTransaction ()
start Transaction
void destruct ()
orphan
void bouncebackproxy ()
orphan
void insertRow (apifPtr re, int64_t recmd, void *reptr, int64_t tableid)
deprecated
void deleteRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
deprecated
void replaceRow (apifPtr re, int64_t recmd, void *reptr)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, int64_t input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, uint64_t input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, bool input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, long double input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, char input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, string *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< int64_t > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< uint64_t > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< bool > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< long double > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< char > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< string > *input)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, int64_t lower, int64_t upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, uint64_t lower, uint64_t upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, bool lower, bool upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, long double lower, long double upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, char lower, char upper)
deprecated
void selectRows (apifPtr re, int64_t recmd, void *reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, string *lower, string *upper)
deprecated
void fetchRows (apifPtr re, int64_t recmd, void *reptr)
deprecated
void unlock (apifPtr re, int64_t recmd, void *reptr, int64_t rowid, int64_t tableid, int64_t engineid)
unlock row
void rollback (apifPtr re, int64_t recmd, void *reptr)
rollback transaction
void rollback (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
rollback transaction
void commit (apifPtr re, int64_t recmd, void *reptr)
commit transaction
void revert (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur)
deprecated
void updateRowNullField (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, int64_t input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, uint64_t input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, bool input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, long double input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, char input)
deprecated
void updateRow (apifPtr re, int64_t recmd, void *reptr, uuRecord_s &uur, int64_t fieldid, string input)
deprecated
bool unmakerow (int64_t tableid, string *rowstring, vector< fieldValue_s > *resultFields)
deprecated
void prepareResponseVector (int64_t resultCode)
deprecated
void addFieldToRow ()
deprecated
void addFieldToRow (int64_t val)
deprecated
void addFieldToRow (uint64_t val)
deprecated
void addFieldToRow (bool val)
deprecated
void addFieldToRow (long double val)
deprecated
void addFieldToRow (char val)
deprecated
void addFieldToRow (string &val)
deprecated
void setReEntry (apifPtr re, int64_t recmd, void *reptr)
set continuation target back to ApiInterface object
void sendResponse (int64_t resultCode, vector< std::string > *v)
deprecated
bool execStatement (const char *stmtname, Statement *stmtPtr, apifPtr reentryfunction, int64_t reentrypoint, void *reentrydata)
execute SQL statement
bool execStatement (const char *stmtname, vector< std::string > &args, apifPtr reentryfunction, int64_t reentrypoint, void *reentrydata)
execute SQL statement
int64_t getResultCode ()
get resultCode from most recent transactional activity
void deleteTransaction ()
delete Transaction
void deleteStatement ()
delete Statement
void getStoredProcedureArgs (Statement *stmtPtr, std::vector< std::string > &argsRef)
put args from stored procedure Statement into vector of strings
Public Attributes
class TransactionAgent * taPtr
class ApiInterface * pgPtr
class Statement * statementPtr
std::vector< std::string > inputVector
class Transaction * transactionPtr
procedureResponse_s response
std::vector< std::string > responseVector
void * destroyerPtr
apifPtr continueFunc1Ptr
apifPtr continueFunc2Ptr
apifPtr continuePgFuncPtr
int sockfd
int64_t domainid
results_s results
Detailed Description
Stored procedure API.
Stored procedure programming is described in http://www.infinisql.org/docs/reference/
Definition at line 243 of file infinisql.h.
Constructor & Destructor Documentation
ApiInterface::ApiInterface () inline
Definition at line 261 of file infinisql.h.
     {
         ;
     }
virtual ApiInterface::~ApiInterface () inline virtual
Definition at line 265 of file infinisql.h.
     {
         ;
     }
Member Function Documentation
void ApiInterface::addFieldToRow ()
deprecated
Definition at line 762 of file api.cc.
References Transaction::addFieldToRow(), and transactionPtr.
 {
     transactionPtr->addFieldToRow();
 }
void ApiInterface::addFieldToRow (int64_t val)
deprecated
Definition at line 767 of file api.cc.
References Transaction::addFieldToRow(), and transactionPtr.
 {
     transactionPtr->addFieldToRow(val);
 }
void ApiInterface::addFieldToRow (uint64_t val)
deprecated
Definition at line 772 of file api.cc.
References Transaction::addFieldToRow(), and transactionPtr.
 {
     transactionPtr->addFieldToRow(val);
 }
void ApiInterface::addFieldToRow (bool val)
deprecated
Definition at line 777 of file api.cc.
References Transaction::addFieldToRow(), and transactionPtr.
 {
     transactionPtr->addFieldToRow(val);
 }
void ApiInterface::addFieldToRow (long double val)
deprecated
Definition at line 782 of file api.cc.
References Transaction::addFieldToRow(), and transactionPtr.
 {
     transactionPtr->addFieldToRow(val);
 }
void ApiInterface::addFieldToRow (char val)
deprecated
Definition at line 787 of file api.cc.
References Transaction::addFieldToRow(), and transactionPtr.
 {
     transactionPtr->addFieldToRow(val);
 }
void ApiInterface::addFieldToRow (string & val)
deprecated
Definition at line 792 of file api.cc.
References Transaction::addFieldToRow(), and transactionPtr.
 {
     transactionPtr->addFieldToRow(val);
 }
void ApiInterface::beginTransaction ()
start Transaction
Definition at line 44 of file api.cc.
References transactionPtr.
 {
     transactionPtr = new class Transaction(taPtr, domainid);
 }
void ApiInterface::bouncebackproxy ()
orphan
Definition at line 55 of file api.cc.
References Transaction::reenter(), and transactionPtr.
 {
     transactionPtr->reenter();
 }
void ApiInterface::commit (apifPtr re, int64_t recmd, void * reptr)
commit transaction
Definition at line 231 of file api.cc.
References APISTATUS_PENDING, Transaction::commit(), NOCOMMAND, Transaction::pendingcmd, Transaction::reenter(), setReEntry(), and transactionPtr.
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     transactionPtr->commit();
 }
virtual void ApiInterface::continueFunc1 (int64_t entrypoint, void * statePtr) pure virtual
user-defined continuation function
Parameters
entrypoint entrypoint for continuation
statePtr state data
Implemented in Pg.
virtual void ApiInterface::continueFunc2 (int64_t entrypoint, void * statePtr) pure virtual
second user-defined continuation function
Parameters
entrypoint entrypoint for continuation
statePtr state data
Implemented in Pg.
virtual void ApiInterface::continuePgCommitexplicit (int64_t entrypoint, void * statePtr) pure virtual
continuation function after explicit commit
explicit commit is sent as COMMIT or END at end of transaction
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implemented in Pg.
Referenced by Pg::sqlcommitexplicit().
virtual void ApiInterface::continuePgCommitimplicit (int64_t entrypoint, void * statePtr) pure virtual
continuation function after implicit commit
implicit commit done after a single statement is entered, not in a transaction already, and session_isautocommit is true
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implemented in Pg.
Referenced by Pg::closesocket(), and Pg::sqlcommitimplicit().
virtual void ApiInterface::continuePgFunc (int64_t entrypoint, void * statePtr) pure virtual
after SQL activity is performed
based on the statement type and transaction state, a variety of things if session_isautocommit==true, and is SELECT, INSERT, UPDATE, DELETE, then output If autocommit==false, and SELECT, INSERT, UPDATE, DELETE, then prepare output but don't output if COMMIT (END), then commit open transaction and output results already prepared if ROLLBACK, then rollback open transaction and output results CommandComplete at the end of everything returned If set, then set whatever
Parameters
entrypoint entry point to contiue
statePtr state data to continue with
Implemented in Pg.
Referenced by Pg::executeStatement().
virtual void ApiInterface::continuePgRollbackexplicit (int64_t entrypoint, void * statePtr) pure virtual
continuation function after explicit rollback
explicit commit is sent as ROLLBACK statement within transaction
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implemented in Pg.
Referenced by Pg::sqlrollbackexplicit().
virtual void ApiInterface::continuePgRollbackimplicit (int64_t entrypoint, void * statePtr) pure virtual
continuation function after implicit rollback
implicit rollback done generally after a failure of some kind which forces a rollback
Parameters
entrypoint entry point to continue
statePtr state data to continue with
Implemented in Pg.
Referenced by Pg::sqlrollbackimplicit().
void ApiInterface::deleteRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur)
deprecated
Parameters
re
recmd
reptr
uur
Definition at line 151 of file api.cc.
References APISTATUS_NOTOK, Transaction::currentCmdState, DELETE, DELETEROW, uuRecord_s::engineid, Transaction::getnextpendingcmdid(), NOCOMMAND, Transaction::cmdState_s::originaluur, PAYLOADSUBTRANSACTION, Transaction::pendingcmd, Transaction::pendingcmdid, Transaction::reenter(), uuRecord_s::rowid, MessageSubtransactionCmd::subtransaction_s::rowid, Transaction::sendTransaction(), setReEntry(), Transaction::stagedRows, MessageSubtransactionCmd::subtransactionStruct, uuRecord_s::tableid, MessageSubtransactionCmd::subtransaction_s::tableid, transactionPtr, WRITELOCK, and Transaction::zeroCurrentCmdState().
 {
     setReEntry(re, recmd, reptr);
     if (!transactionPtr->stagedRows.count(uur))
     {
         transactionPtr->reenter(APISTATUS_NOTOK);
         return;
     }
     if (transactionPtr->stagedRows[uur].locktype != WRITELOCK ||
         transactionPtr->stagedRows[uur].cmd != NOCOMMAND ||
         transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_NOTOK);
         return;
     }
     transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
     transactionPtr->pendingcmd = DELETE;
     transactionPtr->zeroCurrentCmdState();
     transactionPtr->currentCmdState.originaluur = uur;
     // tableid,rowid,DELETEROW,SUBTRANSACTIONCMDPAYLOAD, returns status
     class MessageSubtransactionCmd *msg = new class MessageSubtransactionCmd();
     class MessageSubtransactionCmd &msgref = *msg;
     msgref.subtransactionStruct.rowid =
         transactionPtr->currentCmdState.originaluur.rowid;
     msgref.subtransactionStruct.tableid =
         transactionPtr->currentCmdState.originaluur.tableid;
     transactionPtr->sendTransaction(DELETEROW, PAYLOADSUBTRANSACTION, 1,
                                     transactionPtr->currentCmdState.originaluur.engineid,
                                     (void *)msg);
 }
void ApiInterface::deleteStatement ()
delete Statement
Definition at line 830 of file api.cc.
References pgPtr, and statementPtr.
 {
     delete pgPtr->statementPtr;
 }
void ApiInterface::deleteTransaction ()
delete Transaction
Definition at line 825 of file api.cc.
References transactionPtr.
 {
     delete transactionPtr;
 }
void ApiInterface::deserialize2Vector ()
orphan
Definition at line 36 of file api.cc.
References TransactionAgent::args, TransactionAgent::argsize, inputVector, and taPtr.
 {
     msgpack::unpacked msg;
     msgpack::unpack(&msg, taPtr->args, taPtr->argsize);
     msgpack::object obj = msg.get();
     obj.convert(&inputVector);
 }
void ApiInterface::destruct ()
orphan
Definition at line 49 of file api.cc.
References destroyerPtr.
 {
     spclassdestroy d = (spclassdestroy)destroyerPtr;
     d(this);
 }
virtual void ApiInterface::doit () pure virtual
Implemented in Pg.
bool ApiInterface::execStatement (const char * stmtname, Statement * stmtPtr, apifPtr reentryfunction, int64_t reentrypoint, void * reentrydata)
execute SQL statement
Parameters
stmtname statement name
stmtPtr Statement
reentryfunction function to reenter to
reentrypoint continuation entry point
reentrydata continuation state
Returns
success or failure to execute statement
Definition at line 797 of file api.cc.
References Statement::queries.
 {
     return execStatement(stmtname, stmtPtr->queries[0].storedProcedureArgs,
                   reentryfunction, reentrypoint, reentrydata);
 }
bool ApiInterface::execStatement (const char * stmtname, vector< std::string > & args, apifPtr reentryfunction, int64_t reentrypoint, void * reentrydata)
execute SQL statement
Parameters
stmtname statement name
args statement parameters
reentryfunction function to reenter to
reentrypoint continuation entry point
reentrydata continuation state
Returns
success or failure to execute statement
Definition at line 805 of file api.cc.
References domainid, Statement::execute(), TransactionAgent::statements, taPtr, and transactionPtr.
 {
     if (!taPtr->statements[domainid].count(string(stmtname)))
     {
         return false;
     }
     class Statement *stmt = new class Statement;
     *stmt=taPtr->statements[domainid][string(stmtname)];
     stmt->execute(this, reentryfunction, reentrypoint, reentrydata,
                   transactionPtr, args);
     return true;
 }
void ApiInterface::fetchRows (apifPtr re, int64_t recmd, void * reptr)
deprecated
Definition at line 202 of file api.cc.
References APISTATUS_PENDING, FETCH, Transaction::getnextpendingcmdid(), NOCOMMAND, Transaction::pendingcmd, Transaction::pendingcmdid, Transaction::reenter(), setReEntry(), and transactionPtr.
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
     transactionPtr->pendingcmd = FETCH;
 }
int64_t ApiInterface::getResultCode ()
get resultCode from most recent transactional activity
Returns
resultCode
Definition at line 820 of file api.cc.
References Transaction::resultCode, and transactionPtr.
 {
     return transactionPtr->resultCode;
 }
void ApiInterface::getStoredProcedureArgs (Statement * stmtPtr, std::vector< std::string > & argsRef)
put args from stored procedure Statement into vector of strings
Parameters
stmtPtr Statement
argsRef resulting arguments
Definition at line 835 of file api.cc.
References Statement::queries.
 {
     argsRef=stmtPtr->queries[0].storedProcedureArgs;
 }
void ApiInterface::insertRow (apifPtr re, int64_t recmd, void * reptr, int64_t tableid)
deprecated
Parameters
re
recmd
reptr
tableid
Definition at line 61 of file api.cc.
References APISTATUS_FIELD, APISTATUS_NOTOK, APISTATUS_NULLCONSTRAINT, APISTATUS_PENDING, Transaction::checkNullConstraintOK(), Transaction::currentCmdState, Table::fields, Transaction::fieldValues, Transaction::getEngineid(), Transaction::getnextpendingcmdid(), Transaction::cmdState_s::indexEntries, INSERT, NEWROW, NOCOMMAND, NONE, PAYLOADSUBTRANSACTION, Transaction::pendingcmd, Transaction::pendingcmdid, Transaction::reenter(), Transaction::returnNewRow, Transaction::cmdState_s::row, MessageSubtransactionCmd::row, Transaction::cmdState_s::rowEngineid, Transaction::cmdState_s::rowidsEngineids, Transaction::schemaPtr, Transaction::sendTransaction(), setReEntry(), MessageSubtransactionCmd::subtransactionStruct, Transaction::cmdState_s::tableid, MessageSubtransactionCmd::subtransaction_s::tableid, Transaction::tableid, Transaction::cmdState_s::tablePtr, Schema::tables, transactionPtr, Table::unmakerow(), and Transaction::zeroCurrentCmdState().
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     uuRecord_s uur = { -1, -1, -1 };
     transactionPtr->returnNewRow = uur; // why this here?
     transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
     transactionPtr->pendingcmd = INSERT;
     transactionPtr->zeroCurrentCmdState();
     transactionPtr->currentCmdState.tableid = tableid;
     transactionPtr->currentCmdState.tablePtr =
         transactionPtr->schemaPtr->tables[tableid];
     indexInfo_s blankIdxInfo = {};
     transactionPtr->currentCmdState.indexEntries.resize
         (transactionPtr->currentCmdState.tablePtr->fields.size(), blankIdxInfo);
     indexEntry_s blankIdxEntry = {};
     transactionPtr->currentCmdState.rowidsEngineids.resize
         (transactionPtr->currentCmdState.tablePtr->fields.size(), blankIdxEntry);
     for (size_t n=0; n<transactionPtr->currentCmdState.tablePtr->fields.size();
          n++)
     {
         if (transactionPtr->checkNullConstraintOK(n)==false)
         {
             transactionPtr->reenter(APISTATUS_NULLCONSTRAINT);
             return;
         }
         if (transactionPtr->currentCmdState.tablePtr->fields[n].indextype != NONE)
         {
             transactionPtr->currentCmdState.indexEntries[n].engineid =
                 transactionPtr->getEngineid(transactionPtr->currentCmdState.tablePtr, n);
             transactionPtr->currentCmdState.indexEntries[n].fieldid = n;
             transactionPtr->currentCmdState.indexEntries[n].tableid =
                 transactionPtr->currentCmdState.tableid;
             transactionPtr->currentCmdState.indexEntries[n].fieldVal =
                 transactionPtr->fieldValues[n];
         }
         else
         {
             transactionPtr->currentCmdState.indexEntries[n].engineid = -1;
         }
         transactionPtr->currentCmdState.rowidsEngineids[n].engineid =
             transactionPtr->currentCmdState.indexEntries[n].engineid;
     }
     transactionPtr->currentCmdState.rowEngineid =
         transactionPtr->getEngineid(transactionPtr->currentCmdState.tablePtr, 0);
     if (transactionPtr->currentCmdState.rowEngineid == -1)
     {
         transactionPtr->reenter(APISTATUS_NOTOK);
         return;
     }
     // now, prepare message for Engine, which expects:
     // transaction_enginecmd NEWROW, transaction_messageStruct.payloadtype
     // SUBTRANSACTIONCMDPAYLOAD
     // reentrypoint 1
     // tableid, row
     // expects in return: rowid
     class MessageSubtransactionCmd *msg = new class MessageSubtransactionCmd();
     class MessageSubtransactionCmd &msgref = *msg;
     msgref.subtransactionStruct.tableid=tableid;
     if (transactionPtr->currentCmdState.tablePtr->
         makerow(&transactionPtr->fieldValues, &msgref.row)==false)
     {
         transactionPtr->reenter(APISTATUS_FIELD);
         delete msg;
         return;
     }
     vector<fieldValue_s> f;
     transactionPtr->currentCmdState.tablePtr->unmakerow(&msgref.row, &f);
     transactionPtr->currentCmdState.row = msgref.row;
     transactionPtr->sendTransaction(NEWROW, PAYLOADSUBTRANSACTION, 1,
                                     transactionPtr->currentCmdState.rowEngineid,
                                     (void *)msg);
 }
void ApiInterface::prepareResponseVector (int64_t resultCode)
deprecated
Definition at line 746 of file api.cc.
References response, responseVector, procedureResponse_s::resultCode, and procedureResponse_s::sbuf.
 {
     response.resultCode = resultCode;
     msgpack::sbuffer *sbuf = new msgpack::sbuffer;
     msgpack::pack(*sbuf, responseVector);
     response.sbuf = sbuf;
 }
void ApiInterface::replaceRow (apifPtr re, int64_t recmd, void * reptr)
deprecated
Parameters
re
recmd
reptr
Definition at line 188 of file api.cc.
References APISTATUS_PENDING, Transaction::getnextpendingcmdid(), NOCOMMAND, Transaction::pendingcmd, Transaction::pendingcmdid, Transaction::reenter(), REPLACE, setReEntry(), and transactionPtr.
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
     transactionPtr->pendingcmd = REPLACE;
 }
void ApiInterface::revert (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur)
deprecated
Definition at line 271 of file api.cc.
References APISTATUS_PENDING, NOCOMMAND, Transaction::pendingcmd, Transaction::reenter(), Transaction::revert(), setReEntry(), and transactionPtr.
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     transactionPtr->revert(uur);
 }
void ApiInterface::rollback (apifPtr re, int64_t recmd, void * reptr)
rollback transaction
Definition at line 244 of file api.cc.
References APISTATUS_PENDING, NOCOMMAND, Transaction::pendingcmd, Transaction::reenter(), Transaction::rollback(), setReEntry(), and transactionPtr.
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     transactionPtr->rollback();
 }
void ApiInterface::rollback (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur)
rollback transaction
Definition at line 257 of file api.cc.
References APISTATUS_PENDING, NOCOMMAND, Transaction::pendingcmd, Transaction::reenter(), Transaction::rollback(), setReEntry(), and transactionPtr.
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     transactionPtr->rollback(uur);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op)
deprecated
Definition at line 285 of file api.cc.
References APISTATUS_NOTOK, searchParams_s::op, OPERATOR_ISNOTNULL, OPERATOR_ISNULL, OPERATOR_SELECTALL, Transaction::reenter(), MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), and transactionPtr.
 {
     setReEntry(re, recmd, reptr);
     if ((op != OPERATOR_ISNULL) && (op != OPERATOR_ISNOTNULL) &&
         (op != OPERATOR_SELECTALL))
     {
         transactionPtr->reenter(APISTATUS_NOTOK);
         return;
     }
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, int64_t input)
deprecated
Definition at line 304 of file api.cc.
References MessageSubtransactionCmd::fieldVal, fieldInput_u::integer, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s fieldVal = {};
     fieldVal.value.integer = input;
     searchParameters.values.push_back(fieldVal);
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, uint64_t input)
deprecated
Definition at line 318 of file api.cc.
References MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldInput_u::uinteger, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s fieldVal = {};
     fieldVal.value.uinteger = input;
     searchParameters.values.push_back(fieldVal);
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, bool input)
deprecated
Definition at line 332 of file api.cc.
References fieldInput_u::boolean, MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s fieldVal = {};
     fieldVal.value.boolean = input;
     searchParameters.values.push_back(fieldVal);
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, long double input)
deprecated
Definition at line 346 of file api.cc.
References MessageSubtransactionCmd::fieldVal, fieldInput_u::floating, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s fieldVal = {};
     fieldVal.value.floating = input;
     searchParameters.values.push_back(fieldVal);
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, char input)
deprecated
Definition at line 360 of file api.cc.
References fieldInput_u::character, MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s fieldVal = {};
     fieldVal.value.character = input;
     searchParameters.values.push_back(fieldVal);
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, string * input)
deprecated
Definition at line 374 of file api.cc.
References MessageSubtransactionCmd::fieldVal, searchParams_s::op, OPERATOR_REGEX, searchParams_s::regexString, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), fieldValue_s::str, transactionPtr, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     if (op == OPERATOR_REGEX)
     {
         searchParameters.regexString = *input;
     }
     else
     {
         fieldValue_s fieldVal = {};
         fieldVal.str = *input;
         searchParameters.values.push_back(fieldVal);
     }
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< int64_t > * input)
deprecated
Definition at line 398 of file api.cc.
References MessageSubtransactionCmd::fieldVal, fieldInput_u::integer, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s blankFieldVal = {};
     fieldValue_s fieldVal;
     searchParameters.values.reserve(input->size());
     for (size_t n=0; n<input->size(); n++)
     {
         fieldVal = blankFieldVal;
         fieldVal.value.integer = input->at(n);
         searchParameters.values[n] = fieldVal;
     }
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< uint64_t > * input)
deprecated
Definition at line 421 of file api.cc.
References MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldInput_u::uinteger, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s blankFieldVal = {};
     fieldValue_s fieldVal;
     searchParameters.values.reserve(input->size());
     for (size_t n=0; n<input->size(); n++)
     {
         fieldVal = blankFieldVal;
         fieldVal.value.uinteger = input->at(n);
         searchParameters.values[n] = fieldVal;
     }
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< bool > * input)
deprecated
Definition at line 444 of file api.cc.
References fieldInput_u::boolean, MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s blankFieldVal = {};
     fieldValue_s fieldVal;
     searchParameters.values.reserve(input->size());
     for (size_t n=0; n<input->size(); n++)
     {
         fieldVal = blankFieldVal;
         fieldVal.value.boolean = input->at(n);
         searchParameters.values[n] = fieldVal;
     }
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< long double > * input)
deprecated
Definition at line 467 of file api.cc.
References MessageSubtransactionCmd::fieldVal, fieldInput_u::floating, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s blankFieldVal = {};
     fieldValue_s fieldVal;
     searchParameters.values.reserve(input->size());
     for (size_t n=0; n<input->size(); n++)
     {
         fieldVal = blankFieldVal;
         fieldVal.value.floating = input->at(n);
         searchParameters.values[n] = fieldVal;
     }
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< char > * input)
deprecated
Definition at line 490 of file api.cc.
References fieldInput_u::character, MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s blankFieldVal = {};
     fieldValue_s fieldVal;
     searchParameters.values.reserve(input->size());
     for (size_t n=0; n<input->size(); n++)
     {
         fieldVal = blankFieldVal;
         fieldVal.value.character = input->at(n);
         searchParameters.values[n] = fieldVal;
     }
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, vector< string > * input)
deprecated
Definition at line 513 of file api.cc.
References MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), fieldValue_s::str, transactionPtr, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     fieldValue_s blankFieldVal = {};
     fieldValue_s fieldVal;
     searchParameters.values.reserve(input->size());
     for (size_t n=0; n<input->size(); n++)
     {
         fieldVal = blankFieldVal;
         fieldVal.str = input->at(n);
         searchParameters.values[n] = fieldVal;
     }
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, int64_t lower, int64_t upper)
deprecated
Definition at line 537 of file api.cc.
References MessageSubtransactionCmd::fieldVal, fieldInput_u::integer, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     searchParameters.values.reserve(2);
     fieldValue_s fieldVal = {};
     fieldVal.value.integer = lower;
     searchParameters.values[0] = fieldVal;
     fieldVal.value.integer = upper;
     searchParameters.values[1] = fieldVal;
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, uint64_t lower, uint64_t upper)
deprecated
Definition at line 554 of file api.cc.
References MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldInput_u::uinteger, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     searchParameters.values.reserve(2);
     fieldValue_s fieldVal = {};
     fieldVal.value.uinteger = lower;
     searchParameters.values[0] = fieldVal;
     fieldVal.value.uinteger = upper;
     searchParameters.values[1] = fieldVal;
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, bool lower, bool upper)
deprecated
Definition at line 572 of file api.cc.
References fieldInput_u::boolean, MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     searchParameters.values.reserve(2);
     fieldValue_s fieldVal = {};
     fieldVal.value.boolean = lower;
     searchParameters.values[0] = fieldVal;
     fieldVal.value.boolean = upper;
     searchParameters.values[1] = fieldVal;
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, long double lower, long double upper)
deprecated
Definition at line 589 of file api.cc.
References MessageSubtransactionCmd::fieldVal, fieldInput_u::floating, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     searchParameters.values.reserve(2);
     fieldValue_s fieldVal = {};
     fieldVal.value.floating = lower;
     searchParameters.values[0] = fieldVal;
     fieldVal.value.floating = upper;
     searchParameters.values[1] = fieldVal;
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, char lower, char upper)
deprecated
Definition at line 606 of file api.cc.
References fieldInput_u::character, MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), transactionPtr, fieldValue_s::value, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     searchParameters.values.reserve(2);
     fieldValue_s fieldVal = {};
     fieldVal.value.character = lower;
     searchParameters.values[0] = fieldVal;
     fieldVal.value.character = upper;
     searchParameters.values[1] = fieldVal;
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::selectRows (apifPtr re, int64_t recmd, void * reptr, int64_t tableid, int64_t fieldid, locktype_e locktype, operatortypes_e op, string * lower, string * upper)
deprecated
Definition at line 623 of file api.cc.
References MessageSubtransactionCmd::fieldVal, searchParams_s::op, MessageSubtransactionCmd::searchParameters, Transaction::select(), setReEntry(), fieldValue_s::str, transactionPtr, and searchParams_s::values.
 {
     setReEntry(re, recmd, reptr);
     searchParams_s searchParameters = {};
     searchParameters.op = op;
     searchParameters.values.reserve(2);
     fieldValue_s fieldVal = {};
     fieldVal.str = *lower;
     searchParameters.values[0] = fieldVal;
     fieldVal.str = *upper;
     searchParameters.values[1] = fieldVal;
     transactionPtr->select(tableid, fieldid, locktype, &searchParameters);
 }
void ApiInterface::sendResponse (int64_t resultCode, vector< std::string > * v)
deprecated
Parameters
resultCode
v
Definition at line 640 of file api.cc.
References TransactionAgent::sendResponse(), TransactionAgent::sockfd, sockfd, and taPtr.
 {
     taPtr->sockfd = sockfd;
     taPtr->sendResponse(false, resultCode, v);
 }
void ApiInterface::setReEntry (apifPtr re, int64_t recmd, void * reptr)
set continuation target back to ApiInterface object
Parameters
re this
recmd entry point
reptr state data
Definition at line 754 of file api.cc.
References Transaction::reentryCmd, Transaction::reentryFuncPtr, Transaction::reentryObject, Transaction::reentryState, and transactionPtr.
Referenced by commit(), deleteRow(), fetchRows(), insertRow(), replaceRow(), revert(), rollback(), selectRows(), unlock(), updateRow(), and updateRowNullField().
 {
     transactionPtr->reentryObject = this;
     transactionPtr->reentryFuncPtr = re;
     transactionPtr->reentryCmd = recmd;
     transactionPtr->reentryState = reptr;
 }
void ApiInterface::unlock (apifPtr re, int64_t recmd, void * reptr, int64_t rowid, int64_t tableid, int64_t engineid)
unlock row
Definition at line 216 of file api.cc.
References APISTATUS_PENDING, Transaction::getnextpendingcmdid(), NOCOMMAND, Transaction::pendingcmd, Transaction::pendingcmdid, Transaction::reenter(), setReEntry(), transactionPtr, and UNLOCK.
 {
     setReEntry(re, recmd, reptr);
     if (transactionPtr->pendingcmd != NOCOMMAND)
     {
         transactionPtr->reenter(APISTATUS_PENDING);
         return;
     }
     transactionPtr->pendingcmdid = transactionPtr->getnextpendingcmdid();
     transactionPtr->pendingcmd = UNLOCK;
 }
bool ApiInterface::unmakerow (int64_t tableid, string * rowstring, vector< fieldValue_s > * resultFields)
deprecated
Definition at line 646 of file api.cc.
References Transaction::schemaPtr, Schema::tables, and transactionPtr.
 {
     return transactionPtr->schemaPtr->tables[tableid]->unmakerow(rowstring,
                                                                  resultFields);
 }
void ApiInterface::updateRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur)
deprecated
Definition at line 653 of file api.cc.
References Transaction::currentCmdState, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), transactionPtr, and Transaction::updateRow().
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = true; // look in
     // uses Transaction::fieldsToUpdate map
     transactionPtr->updateRow();
 }
void ApiInterface::updateRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur, int64_t fieldid, int64_t input)
deprecated
Definition at line 673 of file api.cc.
References Transaction::currentCmdState, Transaction::cmdState_s::fieldid, Transaction::cmdState_s::fieldVal, fieldInput_u::integer, fieldValue_s::isnull, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), transactionPtr, Transaction::updateRow(), and fieldValue_s::value.
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = false;
     transactionPtr->currentCmdState.fieldid = fieldid;
     transactionPtr->currentCmdState.fieldVal.isnull = false;
     transactionPtr->currentCmdState.fieldVal.value.integer = input;
     transactionPtr->updateRow();
 }
void ApiInterface::updateRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur, int64_t fieldid, uint64_t input)
deprecated
Definition at line 685 of file api.cc.
References Transaction::currentCmdState, Transaction::cmdState_s::fieldid, Transaction::cmdState_s::fieldVal, fieldValue_s::isnull, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), transactionPtr, fieldInput_u::uinteger, Transaction::updateRow(), and fieldValue_s::value.
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = false;
     transactionPtr->currentCmdState.fieldid = fieldid;
     transactionPtr->currentCmdState.fieldVal.isnull = false;
     transactionPtr->currentCmdState.fieldVal.value.uinteger = input;
     transactionPtr->updateRow();
 }
void ApiInterface::updateRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur, int64_t fieldid, bool input)
deprecated
Definition at line 697 of file api.cc.
References fieldInput_u::boolean, Transaction::currentCmdState, Transaction::cmdState_s::fieldid, Transaction::cmdState_s::fieldVal, fieldValue_s::isnull, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), transactionPtr, Transaction::updateRow(), and fieldValue_s::value.
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = false;
     transactionPtr->currentCmdState.fieldid = fieldid;
     transactionPtr->currentCmdState.fieldVal.isnull = false;
     transactionPtr->currentCmdState.fieldVal.value.boolean = input;
     transactionPtr->updateRow();
 }
void ApiInterface::updateRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur, int64_t fieldid, long double input)
deprecated
Definition at line 709 of file api.cc.
References Transaction::currentCmdState, Transaction::cmdState_s::fieldid, Transaction::cmdState_s::fieldVal, fieldInput_u::floating, fieldValue_s::isnull, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), transactionPtr, Transaction::updateRow(), and fieldValue_s::value.
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = false;
     transactionPtr->currentCmdState.fieldid = fieldid;
     transactionPtr->currentCmdState.fieldVal.isnull = false;
     transactionPtr->currentCmdState.fieldVal.value.floating = input;
     transactionPtr->updateRow();
 }
void ApiInterface::updateRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur, int64_t fieldid, char input)
deprecated
Definition at line 721 of file api.cc.
References fieldInput_u::character, Transaction::currentCmdState, Transaction::cmdState_s::fieldid, Transaction::cmdState_s::fieldVal, fieldValue_s::isnull, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), transactionPtr, Transaction::updateRow(), and fieldValue_s::value.
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = false;
     transactionPtr->currentCmdState.fieldid = fieldid;
     transactionPtr->currentCmdState.fieldVal.isnull = false;
     transactionPtr->currentCmdState.fieldVal.value.character = input;
     transactionPtr->updateRow();
 }
void ApiInterface::updateRow (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur, int64_t fieldid, string input)
deprecated
Definition at line 733 of file api.cc.
References Transaction::currentCmdState, Transaction::cmdState_s::fieldid, Transaction::cmdState_s::fieldVal, fieldValue_s::isnull, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), fieldValue_s::str, transactionPtr, and Transaction::updateRow().
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = false;
     transactionPtr->currentCmdState.fieldid = fieldid;
     transactionPtr->currentCmdState.fieldVal.isnull = false;
     transactionPtr->currentCmdState.fieldVal.str = input;
     transactionPtr->updateRow();
 }
void ApiInterface::updateRowNullField (apifPtr re, int64_t recmd, void * reptr, uuRecord_s & uur, int64_t fieldid)
deprecated
Definition at line 662 of file api.cc.
References Transaction::currentCmdState, Transaction::cmdState_s::fieldid, Transaction::cmdState_s::fieldVal, fieldValue_s::isnull, Transaction::cmdState_s::isupdatemultiplefields, Transaction::cmdState_s::originaluur, setReEntry(), transactionPtr, and Transaction::updateRow().
 {
     setReEntry(re, recmd, reptr);
     transactionPtr->currentCmdState.originaluur = uur;
     transactionPtr->currentCmdState.isupdatemultiplefields = false;
     transactionPtr->currentCmdState.fieldid = fieldid;
     transactionPtr->currentCmdState.fieldVal.isnull = true;
     transactionPtr->updateRow();
 }
Member Data Documentation
apifPtr ApiInterface::continueFunc1Ptr
Definition at line 736 of file infinisql.h.
apifPtr ApiInterface::continueFunc2Ptr
Definition at line 737 of file infinisql.h.
apifPtr ApiInterface::continuePgFuncPtr
Definition at line 738 of file infinisql.h.
void* ApiInterface::destroyerPtr
Definition at line 735 of file infinisql.h.
Referenced by destruct().
int64_t ApiInterface::domainid
Definition at line 740 of file infinisql.h.
Referenced by Pg::continueLogin(), execStatement(), and Pg::Pg().
std::vector<std::string> ApiInterface::inputVector
Definition at line 731 of file infinisql.h.
Referenced by deserialize2Vector().
class ApiInterface* ApiInterface::pgPtr
Definition at line 729 of file infinisql.h.
Referenced by deleteStatement().
procedureResponse_s ApiInterface::response
Definition at line 733 of file infinisql.h.
Referenced by prepareResponseVector().
std::vector<std::string> ApiInterface::responseVector
Definition at line 734 of file infinisql.h.
Referenced by prepareResponseVector().
results_s ApiInterface::results
Definition at line 742 of file infinisql.h.
Referenced by Statement::branchtotype(), Pg::continuePgFunc(), Statement::execute(), Pg::executeStatement(), Pg::putDataRows(), Pg::putRowDescription(), Statement::reenter(), and Statement::startQuery().
int ApiInterface::sockfd
Definition at line 739 of file infinisql.h.
Referenced by sendResponse().
class Statement* ApiInterface::statementPtr
Definition at line 730 of file infinisql.h.
Referenced by Pg::closesocket(), Pg::cont(), Pg::continuePgCommitexplicit(), Pg::continuePgCommitimplicit(), Pg::continuePgRollbackexplicit(), Pg::continuePgRollbackimplicit(), deleteStatement(), Pg::executeStatement(), Pg::Pg(), and Statement::reenter().
class TransactionAgent* ApiInterface::taPtr
Definition at line 728 of file infinisql.h.
Referenced by Pg::cont(), Pg::continueLogin(), Pg::continuePgCommitexplicit(), Pg::continuePgCommitimplicit(), Pg::continuePgFunc(), Pg::continuePgRollbackexplicit(), deserialize2Vector(), execStatement(), Pg::executeStatement(), Pg::Pg(), Pg::putAuthenticationOk(), Pg::putErrorResponse(), Pg::rewritesocket(), sendResponse(), and Pg::writesocket().
class Transaction* ApiInterface::transactionPtr
Definition at line 732 of file infinisql.h.
Referenced by addFieldToRow(), beginTransaction(), bouncebackproxy(), Pg::closesocket(), commit(), Pg::continuePgCommitexplicit(), Pg::continuePgCommitimplicit(), Pg::continuePgFunc(), Pg::continuePgRollbackexplicit(), Pg::continuePgRollbackimplicit(), deleteRow(), deleteTransaction(), execStatement(), Pg::executeStatement(), fetchRows(), getResultCode(), insertRow(), Pg::Pg(), replaceRow(), revert(), rollback(), selectRows(), setReEntry(), Pg::sqlbegin(), Pg::sqlcommitexplicit(), Pg::sqlcommitimplicit(), Pg::sqlrollbackexplicit(), Pg::sqlrollbackimplicit(), unlock(), unmakerow(), updateRow(), updateRowNullField(), and Pg::writesocket().
The documentation for this class was generated from the following files:
/home/infinisql/build/infinisql/infinisqld/infinisql.h
/home/infinisql/build/infinisql/infinisqld/api.cc