InfiniSQL: /home/infinisql/build/infinisql/infinisqld/larx.h File Reference
larx.h File Reference
Function declarations so flex and bison can work together.
#include <stdint.h>
#include "parser.h"
#include <string.h>
#include <stdio.h>
Classes
struct perlarxer
data for flex and bison to cooperate
Functions
int yyparse (struct perlarxer *)
parser function declaration
void flexinit (struct perlarxer *)
probably initializes state object for reentrent tokenizer
void flexbuffer (char *, size_t, void *)
or this could intialize state object for reentrant tokenizer
void flexdestroy (void *)
destroy state object for reentrant tokenizer
Detailed Description
Function declarations so flex and bison can work together.
Author
Mark Travis mtrav.nosp@m.is15.nosp@m.432+s.nosp@m.rc@g.nosp@m.mail..nosp@m.com
Date
Tue Dec 17 13:26:16 2013
Definition in file larx.h.
Function Documentation
void flexbuffer (char * , size_t , void *)
or this could intialize state object for reentrant tokenizer
does anybody actually know what flex and bison do?
Referenced by Larxer::Larxer().
void flexdestroy (void *)
destroy state object for reentrant tokenizer
Referenced by Larxer::Larxer().
void flexinit (struct perlarxer *)
probably initializes state object for reentrent tokenizer
Referenced by Larxer::Larxer().
int yyparse (struct perlarxer *)
parser function declaration
Returns
some bison result
Referenced by Larxer::Larxer().